### ISSUE TITLE
新增“鼠标操作”动作类型

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#10]
有些程序的部分功能无法通过简单的键盘模拟输入来操作，只能用鼠标来进行点击，故希望能加上“鼠标操作”动作类型，支持鼠标移动，单击，双击，滚轮滚动（貌似可以加入单击滚轮以实现自唤醒启动器？）
现阶段的替代方案只有用外部程序来模拟这一行为。
值得一提的是，这想法貌似让Quicker更像是一款类似AutoHotKey的产品而不是简单的启动器了。

**Comment by LonelySteve** [comment]
想法来自于——

期望Quicker能够自动关闭首次打开非Pro版时即会弹出的窗口提示：

![image](https://user-images.githubusercontent.com/34429322/48602091-f3e02580-e9ac-11e8-94db-c60df5990554.png)

这个窗口按啥键都不好使，只有用鼠标单击“继续”才能关闭该弹窗。

**Comment by cuiliang** [comment]
计划加入。鼠标有几个问题：1. 分辨率依赖；2. 会打乱手操作鼠标的指针位置；  有没有什么建议？ 单击滚轮自动唤醒启动器，这个是否就是中键单击唤醒Quicker了？
由于AHK的协议，不能直接嵌入AHK的组件。 我在考虑增加脚本类型，运行动作的时候把脚本写入临时文件，然后执行文件，类似于双击ahk文件的效果。 这样只要用户电脑安装了ahk软件，就可以共享动作了。 这样怎么样？ ahk毕竟写脚本毕竟灵活

**Comment by LonelySteve** [comment]
这个问题的确很复杂呢，我也没有太深入的思考。

- 对于分辨率依赖的问题，很麻烦，可能这是阻碍加入这一动作的一大理由
- 对于打乱手操作鼠标的指针位置的问题，可以考虑提供一个选项让动作制定者决定是否确保鼠标指针在执行完成所有动作后回到初始位置

“单击滚轮自动唤醒启动器”这句话意思就是在说，对于Quicker自己模拟中键单击应当会唤醒自己（激活面板），其实如果没有Quicker的话，因为Listary的缘故，在桌面中间单击会打开它的菜单，但是Quicker对中间单击这一事件的响应好像比任何程序都高，那自己模拟中键单击就应当会唤醒自己（激活面板）。

最后，如果能用上ahk，那当然很让人开心啦。

**Comment by cuiliang** [comment]
好的
