### ISSUE TITLE
中键激活覆盖了Chrome鼠标放在标签上中键关闭标签的功能

### ISSUE THREAD

**Issue by soulless-c** [cuiliang/Quicker#100]

**Comment by WildSaCk** [comment]
+1 刚想上来提个issue就看到了

**Comment by cuiliang** [comment]
请在配置窗口中设置使用其他激活方式，比如长按右键等 @WildSaCk @soulless-c

**Comment by WildSaCk** [comment]
> 请在配置窗口中设置使用其他激活方式，比如长按右键等 @WildSaCk @soulless-c

能否加个双击中键的方式？

**Comment by cuiliang** [comment]
双击中键前会同时触发两次单击，可能也会造成混淆的。 昨天有个朋友提示按ctrl+中键发送原有中键功能，不知道是不是好使。
