### ISSUE TITLE
高级动作：http返回内容更多的信息提取方式

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#107]
XML 内容提取；
HTML 内容提取；

**Comment by i5151** [comment]
Quicker自己创建窗口显示浏览器的内容？

**Comment by cuiliang** [comment]
不是，是调用API的时候，处理API的返回内容。 也可以用来提取网页的内容。 比如给个网址生成markdown的链接

**Comment by i5151** [comment]
能像CopyTranslator那样，直接显示运行结果吗？

可能某些需要打开浏览器的动作按钮，也直接显示结果了。

**Comment by cuiliang** [comment]
嗯，未来会有这样的，已经有朋友搞了查词典了，不过需要用到收费API。

**Comment by cuiliang** [comment]
@i5151 刚发了个版本，可以更新一下。

**Comment by i5151** [comment]
更新完了，没有看到什么变化，也没有看到文档。

**Comment by i5151** [comment]
> 嗯，未来会有这样的，已经有朋友搞了查词典了，不过需要用到收费API。

这样非常好，Quicker就像个工具软件，而不只是启动器了。

显示的结果也更方便、快速、灵活，比直接打开浏览器效率高。
