### ISSUE TITLE
支持从资源管理器中直接拖放文件或文件夹到Quicker？

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#11]
- 考虑新增一个置顶按钮，置顶后面板即使失去焦点也不会自动关闭。以便从资源管理器中拖动文件或目录（或是超链接）到面板，快捷创建动作
- 动作编辑窗口的路径编辑框不接受拖动的文件或文件夹
![demo](https://user-images.githubusercontent.com/34429322/48618036-0cfbcd00-e9d3-11e8-8749-acee1ff472ab.gif)

**Comment by cuiliang** [comment]
本来是能做到的，最初也有。可以直接把文件拖到面板上建立快捷方式。

听我说说原因:
Quicker需要提权运行，有点类似于“以管理员身份运行”，但是不需要每次运行的时候弹框请求。这样才能和各种进程交互。

因为Windows的安全策略，低权限的窗口是不能拖动对象到高权限的窗口里的，所以，这里的拖动被Windows禁止了。

可以通过这几个方式设置图标：
1. 在资源管理器里右键复制图标文件，然后在按钮上右键，选择“粘贴图标”。
2. 复制图片（比如用截图工具或画图中选中区域后复制）,然后在按钮上右键粘贴图标。
3. 在网页里图片上点右键，复制图片，然后在按钮上粘贴图标。
3. 直接选择图标。

未来考虑提供不需要提权的版本，这样可以方便的拖动。

**Comment by cuiliang** [comment]
找到了一个手工降权的方法，就是把quicker目录复制到桌面上一份运行。这时候是普通权限，可以接受拖动。 我等再把拖放处理加回去。

**Comment by cuiliang** [comment]
已完成，下次版本更新0.7.x提供。因为Windows权限机制，只能从以管理员身份运行的资源管理器中拖动文件和目录到Quicker面板。
![20181128_](https://user-images.githubusercontent.com/1972649/49287299-eb710a00-f4d7-11e8-81f6-07ed572ea75e.gif)

**Comment by Sdator** [comment]
> 已完成，下次版本更新0.7.x提供。因为Windows权限机制，只能从以管理员身份运行的资源管理器中拖动文件和目录到Quicker面板。
> ![20181128_](https://user-images.githubusercontent.com/1972649/49287299-eb710a00-f4d7-11e8-81f6-07ed572ea75e.gif)

请问这个是付费版功能吗?  我目前使用的版本是1.5.6.0 免费版，没有拖放真的很不方便。
系统版本是 Microsoft Windows 10 企业版 LTSC 10.0.17763

**Comment by cuiliang** [comment]
> > 已完成，下次版本更新0.7.x提供。因为Windows权限机制，只能从以管理员身份运行的资源管理器中拖动文件和目录到Quicker面板。
> > ![20181128_](https://user-images.githubusercontent.com/1972649/49287299-eb710a00-f4d7-11e8-81f6-07ed572ea75e.gif)
> 
> 请问这个是付费版功能吗? 我目前使用的版本是1.5.6.0 免费版，没有拖放真的很不方便。
> 系统版本是 Microsoft Windows 10 企业版 LTSC 10.0.17763

付费版也没有这个功能的，是权限问题不是功能问题。如果你使用第三方文件管理器，可以用管理员身份启动它之后拖放到面板上。

**Comment by Sdator** [comment]
> > > 已完成，下次版本更新0.7.x提供。因为Windows权限机制，只能从以管理员身份运行的资源管理器中拖动文件和目录到Quicker面板。
> > > ![20181128_](https://user-images.githubusercontent.com/1972649/49287299-eb710a00-f4d7-11e8-81f6-07ed572ea75e.gif)
> > 
> > 
> > 请问这个是付费版功能吗? 我目前使用的版本是1.5.6.0 免费版，没有拖放真的很不方便。
> > 系统版本是 Microsoft Windows 10 企业版 LTSC 10.0.17763
> 
> 付费版也没有这个功能的，是权限问题不是功能问题。如果你使用第三方文件管理器，可以用管理员身份启动它之后拖放到面板上。

我从你的演示图中看到quicker的工具箱有打开资源管理器的功能但在我这边并没有看到。我尝试了用管理员身份运行资源管理器还是一样无法拖放

**Comment by cuiliang** [comment]
@Sdator Sdator  这个方法曾经可以，后来可能windows更新就不行了，所以去掉了。第三方的应该是可以的。

**Comment by Sdator** [comment]
@cuiliang 好的 目前我尝试把程序目录移动到桌面运行 确实可以临时解决拖放问题。
