### ISSUE TITLE
高级组合动作中【程序流程】步骤显示不完全

### ISSUE THREAD

**Issue by mifenfeifen** [cuiliang/Quicker#116]
暂时只测试了【如果】：
（win10 + 0.7.22版）
1. 若【如果】流程里的步骤很多，超过第一屏→不会出现滚动条，无法查看超过第一屏的步骤
2. 在流程之外添加步骤，此时会出现滚动条，但【如果】流程里能显示出来的步骤依然有限→只能显示一屏的流程
3. 改变编辑窗口的高度，【如果】流程里显示的步骤更多

总结：
【如果】流程只能显示一屏的步骤→若步骤过多，则显示不完全
![snipaste_2018-12-24_10-08-29](https://user-images.githubusercontent.com/16129288/50389326-f845ee00-0763-11e9-9f54-e808d5108670.png)

**Comment by cuiliang** [comment]
谢谢，已了解此问题，可能是wpf的bug，暂时还没有找到很好的办法，我再继续研究下。

**Comment by cuiliang** [comment]
@mifenfeifen 请尝试一下0.7.23版本 https://getquicker.net/Forum/ViewTopic?id=37

**Comment by mifenfeifen** [comment]
@cuiliang 已试用，效果显著
