### ISSUE TITLE
Privacy Terms

### ISSUE THREAD

**Issue by Riajyuu** [cuiliang/Quicker#12]
Ever since you introduce a mandatory login to public sever, you have to clarify infos to be collected in a Privacy Terms.
Or, allow users to use without login

**Comment by cuiliang** [comment]
关于对话框里有隐私声明，这样可行不？ 不是很懂这块，方便提供个模版么？

**Comment by Riajyuu** [comment]
@cuiliang 
From Google Translate:
Is it alright to use About dialog? Any templates?
-------
it shall be provided upon login window as a clickable link or display during installation. Or you should allow to use without login.
As far as template, there is no necessity to be professional as lawyer. Simply clarify datas to be collected wil be just fine.

**Comment by cuiliang** [comment]
归档
