### ISSUE TITLE
为各种「获取」类的动作增加“是否成功”的判定，以及“失败后停止动作”的选项

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#120]
![image](https://user-images.githubusercontent.com/4013062/50392541-5259aa00-078a-11e9-96d5-78970d5b9952.png)

如图，现在“获取文件列表”还只有最基础的内容，而“获取文本”则增加了“失败后是否停止”的选项。
为了方便各种情况的对应处理，希望这类动作都能增加「成功/失败」的布尔输出，并且让用户自行勾选失败后是否停止。

**Comment by cuiliang** [comment]
- [ ] 获取剪贴板文本
- [ ] 获取剪贴板文件列表
- [ ] 找图定位
- [ ] 获取剪贴板图片
- [ ] 获取选择的文件列表

**Comment by xqhjay** [comment]
已经有人提了。复议！

**Comment by cuiliang** [comment]
fixed： 0.7.25
