### ISSUE TITLE
支持代理设置

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#129]
有的用户需要设置代理上网，增加选项支持系统代理设置。

**Comment by yyoung97** [comment]
通过浏览器设备代理。

**Comment by cuiliang** [comment]
发现代理无法对WPF本身的图片加载等功能生效。 所以暂时不做了，需用户自己调整Quicker.exe.config里的代理设置。
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

**Comment by woaer** [comment]
非常有用
