### ISSUE TITLE
为“打开网址”动作类型支持更多协议

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#13]
使用添加了HTTPS协议的网址的动作出现以下提示：

![image](https://user-images.githubusercontent.com/34429322/48662736-40b52080-eac1-11e8-8e73-9f9e33af80e7.png)

对于大多数支持HTTPS协议的网站来说，这不是问题，因为这些网站基本都会强制使用HTTPS协议。

此问题的发现来自于我想添加一个最简单的功能：以选中的文本当作网址，使用浏览器访问该网址，但当我在网址编辑框中填入“{context}”（无http:\/\/前缀），即会报错（同上）。

可能这不构成问题，那么再举一个需求：

使用Quicker快捷打开Chrome的小恐龙彩蛋游戏，那么使用“打开网址”动作类型的话，你可能就会填入“chrome://dino/”，有趣的是，现在不会弹窗报错，而是弹出打开方式选择面板：

![image](https://user-images.githubusercontent.com/34429322/48662851-02206580-eac3-11e8-8a98-3197a7828b90.png)

**Comment by cuiliang** [comment]
> 使用添加了HTTPS协议的网址的动作出现以下提示
这段不是很明白，  我试了一下  https的网址直接运行是可以打开浏览器的。
不带http(s) 协议的网址是不能运行的，目前还没做内容判断，只是调用系统的启动进程来执行。 回头尝试增加一点判断。

chrome://dino/  这个是一个uri的格式，windows会认为chrome:是一种协议。  windows10 有一个配置“按协议指定默认应用” 。 它没找到chrome:协议所对应的应用。
我测试了一下，通过参数也传不到chrome里。 只能在chrome里发送按键实现了。
https://getquicker.net/sharedaction?code=ad9804cd-dcca-49b1-93ca-08d64cf149bb

**Comment by LonelySteve** [comment]
@cuiliang https协议的确可以正常识别，可能是我输入协议时打错字了 :< 

另外：

1. 请问第一个需求有简单一点的实现方案吗？

2. 这里的错误提示为啥是一个简陋的MessageBox？不支持的协议（无协议）链接是否应当报错？

**Comment by cuiliang** [comment]
第一个需求是哪个？ 有点乱：）
命令是发送给Windows执行的，这个对话框是windows执行命令的时候显示的，Quicker的处理之前已经结束了。 Quicker事先并不能知道哪些可以执行。

**Comment by LonelySteve** [comment]
>以选中的文本当作网址，使用浏览器访问该网址，但当我在网址编辑框中填入“{context}”（无http:\/\/前缀），即会报错。

这个。

**Comment by cuiliang** [comment]
如果增加一个专门的“用浏览器”打开的动作，是不是就可以解决了？

**Comment by LonelySteve** [comment]
应该是可以的，虽然感觉这会让新用户混乱，“用浏览器”和“打开网址”有啥区别？

**Comment by cuiliang** [comment]
后来的版本组合动作里增加了打开网址模块
