### ISSUE TITLE
？搜索已安装的动作

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#141]
> 支持声调的那种  百度搜索（bdss） 或者输入b 自动排列b开头的动作，按使用频率排列
> 在动作越来越多的情况下方便查找。
> 

感觉这个是另一种不同的使用方式了。有点像wox listray?
是否有必要？是否不符合quicker的方向？

**Comment by Death-** [comment]
似乎可关

**Comment by cuiliang** [comment]
done
