### ISSUE TITLE
变量插值在【检查程序已启动】中无效

### ISSUE THREAD

**Issue by mifenfeifen** [cuiliang/Quicker#147]
变量插值在文本性动作中是有效的，如【消息提示】，但在【检查程序已启动】中无效

复现动作链接：https://getquicker.net/sharedaction?code=76ca3d33-fdba-4836-9da1-08d66d2ef230

可通过修改program的默认值和第二个【检查程序已启动】中的值去检查其他程序。
已测试chrome，notepad

**Comment by cuiliang** [comment]
嗯嗯，此处有bug。

**Comment by cuiliang** [comment]
另外激活进程主窗口步骤也无效。 已处理待下次版本更新。

**Comment by cuiliang** [comment]
fixed 0.7.27
