### ISSUE TITLE
工具箱页码的建议。。。

### ISSUE THREAD

**Issue by i5151** [cuiliang/Quicker#151]
能不能显示（页数/总页数）这样格式，比如：4/20。

**Comment by cuiliang** [comment]
总页数的获取需要额外的一次数据库查询，为了减少服务器压力，所以简化了一下。后期根据情况再优化了

**Comment by i5151** [comment]
原来如此，现在翻页总有种深不见底的感觉，想看有没有新的动作总不知道是继续翻下去还停止。不像以前，从头拉到尾，有什么新动作一目了然。

**Comment by cuiliang** [comment]
现在增加了排序，更方便依据时间或其他条件查找一些。 另外，在网页里看更好一些，有一些动作会有动图演示，在网页里可以直接看。
![image](https://user-images.githubusercontent.com/1972649/50548010-86e4ce80-0c80-11e9-94d8-098b08df0b99.png)

**Comment by i5151** [comment]
我一般都是单击托盘图标，呼出主窗口，然后点击工具箱查看，感觉比网页方便一点，想用直接就拖过来了，而且绝大多数动作看名字就知道是干什么的了。

**Comment by i5151** [comment]
![FhzYxx.png](https://s1.ax1x.com/2018/12/31/FhzYxx.png)
不明白每页底部留那么大的空白是什么意思？

**Comment by cuiliang** [comment]
每页固定20条，可能和分辨率有关系，或者如果左边面板上显示了“为XXX创建面板的文字”，面板也会比平时高一些，工具箱高度和面板对齐，就会造成这里空大一些。回头我再研究下能不能自适应一下。

**Comment by i5151** [comment]
每页固定显示肯定不行，如果调整按钮大小、边框大小之后，工具箱能显示的长度肯定会不同。我还是用Quicker最初的界面，没做任何调整，固定显示都不合适。

自适应肯定是最科学的，无论怎么调整界面，无论什么分辨率，每页都会满页显示。

**Comment by cuiliang** [comment]
归档
