### ISSUE TITLE
quicker自启动后右键菜单无法激活

### ISSUE THREAD

**Issue by huhongyun** [cuiliang/Quicker#155]
Win10系统，quicker自启动后右键菜单无法激活，需要手动关闭quicker，重新启动方可激活右键菜单

**Comment by cuiliang** [comment]
通常是和手势软件冲突。 如果手势软件也是使用右键，那么它会拦截右键事件，quicker无法获取。

**Comment by cuiliang** [comment]
系统挂钩会有先后次序。可能是后启动的，会先捕捉并拦截事件。
quicker对右键的处理是，右键按下后如果移动了，就会识别到不是要激活quicker，从而还原右键点击和移动事件。所以不会影响手势软件的处理。 但是手势软件拦截的比较彻底，所以quicker没法识别到右键长按了。

**Comment by huhongyun** [comment]
明白了，多谢！

**Comment by huhongyun** [comment]
我发现与wgestures冲突了，那么WIN10自启动可以设置先后顺序吗？让wgestures先，Quicker后

**Comment by cuiliang** [comment]
好像不能直接设置。 可以用计划任务延时启动quicker，具体方法可能需要谷歌一下。
