### ISSUE TITLE
可以让多个应用程序共用一套面板吗

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#162]
应用场景：我有一系列动作适用于各种代码编辑器（Sublime/VSC/Spyder 等等），但是给每个都建单独面板的话，每次新增和修改都得重复好几次操作
或者换个思路…【全局动作】？
不管这个动作在几个面板里，只要有改动就在所有面板都更新，这样可以吗
![image](https://user-images.githubusercontent.com/1972649/50635901-0e875180-0f8f-11e9-8431-46261047fed7.png)

**Comment by kts168** [comment]
以一个动作面板为基础面板 , 其他应用继承这个基础面板

**Comment by kts168** [comment]
只有基础面板可以编辑 , 其他继承面板不让编辑

**Comment by cuiliang** [comment]
@kts168 我也是这样考虑。等后续实现。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/multi-profile
使用链接面板
