### ISSUE TITLE
代码编辑窗口不能记忆自动换行状态

### ISSUE THREAD

**Issue by GHsdsb** [cuiliang/Quicker#1639]
**描述BUG**
代码编辑器中的自动换行不能取消

**重现步骤**
1.取消代码编辑器中的自动换行
2.点击关闭
3.点击保存
4.进入代码编辑器，发现自动换行又勾上了

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![2022-04-17_014757](https://user-images.githubusercontent.com/103849445/163686435-ba2a0144-c65b-4972-a8df-b1b6fbad3861.png)

**环境信息:**
 - Windows 10 专业工作站版 21H2 19044.1586：
 - [1.32.8](https://getquicker.net/Help/Versions/Version?version=1.32.8.0)：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不好意思，这里没有记忆功能。
