### ISSUE TITLE
Win10系统使用quicker后鼠标左键偶发无法点击

### ISSUE THREAD

**Issue by Sean-Xiaoming** [cuiliang/Quicker#164]
Win10.1809.64bit系统，使用quicker一段时间了，发现一个小问题。
就是quicker在运行时（后台，并没有唤起菜单的情况下），会出现鼠标左键点击无效情况，每天会出现几次，没有规律，出现时就像鼠标左键坏了一样，点击系统中任何位置均无效，而右键是好的。
已经测试过几天，只要退出quicker，就不再出现这种情况。
quicker一直用的是最新版。
补充：我设置启动quicker面板的快捷键是，长按鼠标右键200ms或单击键盘Ctrl

**Comment by Sean-Xiaoming** [comment]
> 收到，这里应该是有一个bug，和使用长按右键有关系，我再分析分析。

谢谢！

**Comment by cuiliang** [comment]
出现的时候，ctrl+alt+delete 打开任务管理器之后可能能临时性修复故障，可以试试，不用重启quicker。

**Comment by Sean-Xiaoming** [comment]
> 出现的时候，ctrl+alt+delete 打开任务管理器之后可能能临时性修复故障，可以试试，不用重启quicker。

我之前就是这么解决的

**Comment by cuiliang** [comment]
有试过后来版本还有这个问题么？没有的话我把这个case关掉

**Comment by Sean-Xiaoming** [comment]
目前没重现，应该好了，谢谢

**Comment by Ounan1224** [comment]
> Win10.1809.64bit系统，使用更快的一段时间了，发现一个小问题。
> 就是更快在运行时（后台，并没有唤起菜单的情况下），会出现鼠标左键点击无效情况，每天会出现几次，没有规律，出现时就像鼠标左键坏了一样，点击系统中任何位置均无效，而右键是好的。
> 已经测试过几天，只要退出更快，就不再出现这种情况.quicker 
> 一直用的是最新版。
> 补充：我设置启动更快面板的快捷键是，长按鼠标右键为200ms或单击键盘Ctrl键

我也出现这样的问题 ，2019年4月14日  （已经更新了最新版quicker）还是会有这样的情况，偶尔出现

**Comment by cuiliang** [comment]
@Ounan1224 请确认一下版本是否是0.10.7

**Comment by Ounan1224** [comment]
是的 0.10.7.0 ，偶尔会出现这样的问题，左键点击不灵

**Comment by cuiliang** [comment]
> 是的 0.10.7.0 ，偶尔会出现这样的问题，左键点击不灵

是左键点击不灵（比如再点一次就能点上了），还是彻底没反应了呢？左键点哪里都不生效那种？  鼠标品牌型号是啥？

**Comment by Ounan1224** [comment]
刚才仔细测试了一下，具体情况如下：1、 比如我正在窗口化看视频，我想全屏，于是双击左键，可是没有全屏成功，却变成了暂停（因为单击视频是暂停，双击是全屏），于是我就要尝试很多次，才能成功让视频全屏， 2、比如我想双击打开文件夹，却发现整个桌面文件都不能点了，就像左键坏了一样，然后关掉quicker就好了。

**Comment by cuiliang** [comment]
归档
