### ISSUE TITLE
new feature request: Parse the 2D code on the screen

### ISSUE THREAD

**Issue by Dongguage** [cuiliang/Quicker#166]
new feature request: Parse the 2D code on the screen

**Comment by Dongguage** [comment]
ok, but if can encapsulate these two steps into one feature, that's great. Thanks!

**Comment by cuiliang** [comment]
嗯，不过目前模块比较多了，太多了反而不好找，需要控制一下模块的数量。所以这个暂时就不加单独模块了，以后如果有更好的组织方式的时候再考虑。
