### ISSUE TITLE
更新0.7.34.0后运行.bat 脚本后，cmd窗口不会自动关闭（原来可以自动关闭）

### ISSUE THREAD

**Issue by zj1123581321** [cuiliang/Quicker#167]
@echo off
powershell (Add-Type '[DllImport(\"user32.dll\")]^public static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2)

实现息屏操作，更新前是可以自动关闭的，更新后不能自动关闭。或者有什么变通的解决方式么？没搜索到。

**Comment by cuiliang** [comment]
用的哪个类型的动作？ @zj1123581321 
我直接在cmd窗口里执行，出现这个错误 ：
```
Add-Type : e:\TEMP\kvzmeht2.0.cs(8) : 当前上下文中不存在名称“user32”
e:\TEMP\kvzmeht2.0.cs(7) :     {
e:\TEMP\kvzmeht2.0.cs(8) : >>>     [DllImport(user32.dll)]public static extern int SendMessage(int hWnd, int hMsg, int
wParam, int lParam);
e:\TEMP\kvzmeht2.0.cs(9) :
所在位置 行:1 字符: 2
+ (Add-Type '[DllImport(user32.dll)]public static extern int SendMessag ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type]，Excepti
    on
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : 无法添加类型。出现编译错误。
所在位置 行:1 字符: 2
+ (Add-Type '[DllImport(user32.dll)]public static extern int SendMessag ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type]，InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by cuiliang** [comment]
可能和文件编码有关系。 新版本增加了文件编码支持，我测试下试试

**Comment by cuiliang** [comment]
@zj1123581321 确实是编码问题。 没有指定的情况下，按utf8带bom的格式写入，windows执行的时候会有些不太正常。 原来是utf8不带bom的格式。 可以修改一下动作，指定脚本格式为gb2312。

 脚本执行的时候，会在temp目录中写入脚本文件，如果已存在就不会再写了。
所以如果执行不对，需要先删除一下temp里的以quicker- 开始的临时文件再执行。

**Comment by cuiliang** [comment]
@zj1123581321 编码和窗口保留不是一个问题；试过改成其他编码，也会保留一个这样的窗口。我卸载重装0.7.28版本，运行 https://getquicker.net/sharedaction?code=26922dd8-16fc-4714-3879-08d6636f8814 也会有一个这样的窗口。
![image](https://user-images.githubusercontent.com/1972649/50766915-ed3ba380-12b5-11e9-9e06-7648de42a993.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/50767843-5d97f400-12b9-11e9-92f1-77f425910dd4.png)

直接在cmd窗口里执行，也不会结束。

**Comment by cuiliang** [comment]
测试应该没问题，先关闭了。如果还有再打开
