### ISSUE TITLE
chrome tab 右键关闭与 quicker 冲突

### ISSUE THREAD

**Issue by Zeroto521** [cuiliang/Quicker#17]
耍下的 [GreenChrome](https://shuax.com/project/greenchrome/) 与 Quicker 起冲突了。

利用 GreenChrome 设置了 Chrome tab 页右键关闭，但右键关闭 tab 时，quicker 会启动。

quicker 不是中键启动的吗？

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/48691695-6bf95600-ec0e-11e8-9c60-c5dba8af7a3f.png)
看下这里有木有启动ctrl+右键呢。

**Comment by Zeroto521** [comment]
![image](https://user-images.githubusercontent.com/25895405/48694830-6d2f8080-ec18-11e8-8438-220b84ad015a.png)

没

**Comment by cuiliang** [comment]
是不是  GreenChrome 内部发送按键了

**Comment by cuiliang** [comment]
chrome应该是中键关闭，可能是它这个功能是通过发送按键来实现的。

**Comment by Zeroto521** [comment]
那看来只能在 chrome 里设置其他快捷键了

**Comment by cuiliang** [comment]
新版本已增加右键长按，滚轮左推等激活方式，可以尝试一下。
