### ISSUE TITLE
设置里的外观大小有时候会自动变化

### ISSUE THREAD

**Issue by 18178416912** [cuiliang/Quicker#1730]
设置里的外观大小有时候会自动变化，比如默认按钮（这里指悬浮按钮）大小是72，然后我调整大小为100后**悬浮**一个按钮（此刻为100）。然后我调整大小回到72，这时候那个100大小的按钮是确切为100的，待我**重启或者久了不点那个按钮**之后，会自动回调大小为72。
我想要的是让它一直保持为100大小，而不会自己回调我后面更改的大小72。

**Comment by cuiliang** [comment]
没太懂，截图看下哪里？

**Comment by 18178416912** [comment]
> 没太懂，截图看下哪里？

![image](https://user-images.githubusercontent.com/101691575/182142454-278e917a-93e6-42ea-997f-ade9de599135.png)

**Comment by 18178416912** [comment]
> 没太懂，截图看下哪里？

![image](https://user-images.githubusercontent.com/101691575/182142612-444f607a-dd65-4a85-a136-b45030dc00e1.png)

**Comment by 18178416912** [comment]
简单来说，右边这么大的按钮，重启（或者其它操作触发）之后会变成左边这么小

**Comment by cuiliang** [comment]
你是说这里会从72自动变成100？ 目前还没有遇到过这种情况。 
你有几个电脑同时开启了quicker？数据同步正常么？

**Comment by 18178416912** [comment]
> 你是说这里会从72自动变成100？ 目前还没有遇到过这种情况。 你有几个电脑同时开启了quicker？数据同步正常么？

是的，等我复现之后再回馈
就一个电脑，没有同步异常

**Comment by 18178416912** [comment]
> 你是说这里会从72自动变成100？ 目前还没有遇到过这种情况。 你有几个电脑同时开启了quicker？数据同步正常么？

复现了，是重启还有同步的问题。能不能在我调100之前让之前的按钮保持72，这跟着变化大小就不好用了。

**Comment by cuiliang** [comment]
正常都会记住的。 你的账号email是多少？另外请截图看一下同步历史记录。

**Comment by 18178416912** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 上午7:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiliang/Quicker] 设置里的外观大小有时候会自动变化 (Issue #1730)




 
正常都会记住的。 你的账号email是多少？另外请截图看一下同步历史记录。

**Comment by cuiliang** [comment]
看不到Email也看不到截图。

**Comment by 18178416912** [comment]
> 看不到Email也看不到截图。

226475545@qq.com
![IMG_20220802_100646](https://user-images.githubusercontent.com/101691575/182284305-e2b27abc-dcd4-4b5f-b7b5-c520db346206.jpg)
![IMG_20220802_100708](https://user-images.githubusercontent.com/101691575/182284320-5d822c18-f609-4df2-82eb-9badf5adcf64.jpg)

**Comment by 18178416912** [comment]
> 看不到电子邮件也看不到截图。

有解决办法吗

**Comment by cuiliang** [comment]
看起来没有什么问题。 有设置自动运行的动作么？ 每次同步完就会这样么？
试一下退出账号重新登录一下
![image](https://user-images.githubusercontent.com/1972649/182365205-5cb4a313-6b15-4534-a9df-907dac7392a0.png)

**Comment by 18178416912** [comment]
> 看起来没有什么问题。 有设置自动运行的动作么？ 每次同步完就会这样么？ 试一下升级quicker到最新版，然后退出账号重新登录一下 ![image](https://user-images.githubusercontent.com/1972649/182365205-5cb4a313-6b15-4534-a9df-907dac7392a0.png)

单纯同步是不会变化的，我重登账号之后重启是会变化的，所以问题出在重启quicker上

**Comment by cuiliang** [comment]
再确认一下，变化的是面板窗口的按钮大小，还是悬浮动作页的按钮大小，还是两个都会变呢？

**Comment by 18178416912** [comment]
> 再确认一下，变化的是面板窗口的按钮大小，还是悬浮动作页的按钮大小，还是两个都会变呢？

悬浮动作页和面板都变
