### ISSUE TITLE
悬浮动作页容易误操作

### ISSUE THREAD

**Issue by 18178416912** [cuiliang/Quicker#1738]
**需求描述**
悬浮动作页容易误操作，如容易点到“关闭悬浮窗”。

**描述你想要的解决方案**
增加双击关闭，又或者隐藏“关闭按钮”。

**Comment by 18178416912** [comment]
需求描述
悬浮动作页容易误操作，如容易点到“关闭悬浮窗”。

描述你想要的解决方案
增加双击关闭，又或者隐藏“关闭按钮”。

**Comment by 18178416912** [comment]
作者理一下

**Comment by cuiliang** [comment]
不是很理解。 那个关闭不是在右上角么？也很小，为什么会容易误触呢？ 方便的话发个录屏看看操作过程。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
