### ISSUE TITLE
建议增加触屏适配

### ISSUE THREAD

**Issue by wherebubugs** [cuiliang/Quicker#176]
surface等触屏设备有可能既不用键盘也不用鼠标
建议触发方式增加 长触屏，此时“回到鼠标”的坐标记录为 触屏按下的坐标
不知道可不可以实现？

**Comment by cuiliang** [comment]
之前有考虑，不过现在还没时间做。 不知道现在市场上有没有什么触屏手势软件，如果有的话，可以设置手势来发送能激活quicker的快捷键组合。这样比如几个手指同时按下，就可以出发quicker。

**Comment by wherebubugs** [comment]
这在目前是一个非常有效的建议：TouchMe，非常感谢！

**Comment by cuiliang** [comment]
@wherebubugs 我还没有在触屏上使用过quicker。 你有什么体会，欢迎在这里留言。谢谢！

**Comment by wherebubugs** [comment]
刚刚试过了，Gesturesign会比TouchMe好用。
在触摸屏下存在这个问题，需要用手势来识别是否解析为鼠标或键盘
单指在很多触摸软件下会是移动操作，所以必须多指解析
多指滑动确实能激活鼠标再激活quicker，但由于手势是移动的线条，激活的鼠标坐标点有点莫名其妙

**Comment by cuiliang** [comment]
如果通过快捷键激活的话，quicker是显示在屏幕中间的。位置比较确定一点。手势软件应该可以模拟发送快捷键。

**Comment by wherebubugs** [comment]
基本能用了~ 周末我就写个知乎详细描述一下 quicker在surface的小操作

**Comment by wherebubugs** [comment]
写完啦，欢迎阅读：https://www.zhihu.com/question/26541545/answer/571807176  
Gesturesign下面可以选择第一个手指的落点为点击点，位置就很确定了！

**Comment by cuiliang** [comment]
看到了，谢谢啦~  
你的面板数已经改成不限了，重启一下就可以了。

**Comment by wherebubugs** [comment]
YES，I SEE！谢谢！
