### ISSUE TITLE
Suggestion：关于收费方式的一点建议

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#18]
个人很不喜欢这种强制传播才能解锁的方式，希望能直接购买面板或者用 Donate 的方式来解锁。
（虽然软件初期用这种方式也不是不能理解啦）

总之，请给一个直接氪金的机会！

**Comment by cuiliang** [comment]
理解。主要是希望能建立一套动作配置分享系统，这样用的人越多，分享的人越多，软件的价值就越大。可以直接Q我一下

**Comment by Moyf** [comment]
嗯，这个确实，用户自定义的这种「共享库」的潜力是无限的，也能有效提升用户自己的体验。
对于这套体系个人是非常欣赏的~  (￣▽￣)ノ

其实今天中午同事推荐给我的时候，第一个反应就是打开官网查看 Price 信息，然而并没有找到，哈哈。
目前有考虑过收费相关的形式吗？
（个人比较推崇 Listary 和 Snipaste 这样基础免费+升级Pro 的方案）

顺便一提，现在网站上的「用户」页面没有“注册”按钮，目前看来是只有软件内能注册，这是特意设置的吗？

**Comment by cuiliang** [comment]
目前还未确定如何商业化，不过商业化是肯定的。免费增值的这种方式最有可能。等软件功能基本达到目标以后再考虑。目前网站是不能注册的，必须用软件注册。

**Comment by cuiliang** [comment]
整理issues
