### ISSUE TITLE
激活方式：右键按下后滑动

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#183]
相对于右键长按，操作更流畅一些，不需要等待和停顿。

**Comment by i5151** [comment]
试了一下，居然和Opera浏览器鼠标手势一样，以后肯定会有冲突。

**Comment by chengqsz** [comment]
双击右键呢 感觉没什么需要用到双击右键的应用吧

**Comment by cuiliang** [comment]
@chengqsz 双击右键会触发两次单击，会造成右键菜单闪烁。

**Comment by i5151** [comment]
@cuiliang 
现在的激活方式已经很丰富了。

不显示登录窗口很好，因为支持本地登录了。显示登录提示完全没必要，为什么Quicker总是在启动时制造点动静呢？就不能安安静静地做个美男子😂😂😂

还有，我选择了配置存本地，还会上传到服务器吗？

**Comment by cuiliang** [comment]
@i5151 😂 后面再加个选项要不要提示。 目前加这个是因为经常需要等它启动后去执行动作。
本地之后也会同步到服务器，只是不实时同步了，断网也可以正常使用和做配置修改。

**Comment by i5151** [comment]
开机启动那两秒钟谁等不了，非要急着这一会儿启动Quicker，而且托盘图标就是最好的提示。
我托盘图标一长串，包括从古至今用过的所有其他软件，Quicker是唯一一个我已经看到加载的托盘图标了，还要告诉我一声：自己启动了😂，看来你在小学是个爱表现总给老师打报告的好学生。😂😂😂

我在第一次选择了，配置存本地，什么时候会再次上传服务器？如果不选存本地，是不是还和之前一样，实时上传到服务器？我选择了之后，如何修改，能不能在设置中加上选项？

**Comment by cuiliang** [comment]
@i5151 是配置修改后延时几十秒同步的，然后启动之后、网络断开再连接之后都会检查一下。在菜单里关闭并退出当前帐号，可以清理本地数据，下次打开会出现登录界面。 不能和原来完全一样了，因为现在不再保存密码，只保存了帐号，选项和原来不一样了。 主要考虑是2种场景，一种是自己的电脑，就存储配置，一种是临时性使用，就不存储配置，这样密码也不会保存。

**Comment by i5151** [comment]
就是说选择存本地，只是延时上传。但如果没有网络能会不会报错？

同步的时候，以时间为准？

**Comment by cuiliang** [comment]
是的

**Comment by i5151** [comment]
我不选存本地，配置还是会实时上传，只是密码不上传了？

**Comment by cuiliang** [comment]
密码要上传才能验证登陆。 密码是不在当前电脑保存了，原来是保存到电脑里，下次开启的时候自动填到登录窗口里去登录。

**Comment by cuiliang** [comment]
@i5151 是的

**Comment by i5151** [comment]
我没有选择配置存本地，每次都让我输入密码可不行啊。

**Comment by cuiliang** [comment]
@i5151 理论上来讲，存储密码是不太安全的，虽然经过加密。 所以，如果在不安全的环境（公共电脑），还是每次输入密码比较好；如果在一个安全的环境（自己的电脑），把配置保存到本地更合理一些的。

**Comment by i5151** [comment]
这个思路有点矫枉过正了，也就是想的太多了。用公共电脑不安全是可能的，但短时间使用是不可能安装Quicker的；长时间使用，必有自己专用的账户，安全问题是微软的事。而且只想到了，公共电脑的不安全，没有想到在自己电脑安全的环境下想实时上传怎么办？比如我在有网并且频繁改动Quicker的情况下，想直接上传配置到服务器，每次都是输入密码就太折腾了。

**Comment by cuiliang** [comment]
保存在本地只是有一点延时（目前大概20s），这样也是为了避免向服务器传的太频繁。因为用户调整按钮的时候经常会在很短的时间内调整很多次，之前每次都传，本身也容易失败，造成数据保存不成功，关闭quicker之后配置就丢了。再一个服务器压力也会比较大。

**Comment by cuiliang** [comment]
done
