### ISSUE TITLE
FR：希望能提供自定义用户界面的功能（AKA 皮肤设置）

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#19]
![snipaste_2018-11-19_16-03-10](https://user-images.githubusercontent.com/4013062/48693529-ad8cff80-ec14-11e8-88d1-409a54fe6490.png)
如图，当前的界面在一些复杂背景下显示状况非常糟糕。

希望能提供基础的用户界面设置，例如选择背景底色的「颜色」和「不透明度」。
当前的显示效果相当于是“不透明度=0”——即完全透明。

顺便，目前这种效果可以加个磨砂玻璃化的模糊效果，这样也能显著提升观感。

以上，感谢开发！

**Comment by cuiliang** [comment]
正常不应该这个效果:(   是什么操作系统版本？

**Comment by Moyf** [comment]
咦……难怪了
用的系统是 Windows 10 
![image](https://user-images.githubusercontent.com/4013062/48693907-d06be380-ec15-11e8-8a63-50d3f15c6139.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/48693941-ea0d2b00-ec15-11e8-8212-7ed0fb032902.png)
这个是正常界面（忽略上面的黑条，调试状态）

**Comment by Moyf** [comment]
那么可能是我系统配置上的原因……稍等，我先自测一波

**Comment by cuiliang** [comment]
![-1](https://user-images.githubusercontent.com/1972649/48696040-c0ef9900-ec1b-11e8-9002-2c1d2198d081.png)
目前正常显示是这种玻璃效果的。 应该还是你电脑上的什么配置造成的，可以再查下看看:)

**Comment by Moyf** [comment]
> 目前正常显示是这种玻璃效果的。 应该还是你电脑上的什么配置造成的，可以再查下看看:)

对了，虽然原 issue 中的情况是由于系统异常，但是还是希望能添加更多**自定义界面**的支持。

![image](https://user-images.githubusercontent.com/4013062/48906153-95301580-ee9e-11e8-8786-2f340eab360c.png)

例如自定义界面主色调（Like Snipaste）和不透明度。
甚至对于某部分用户来说，他们甚至希望能自定义图片作为背景（笑）
