### ISSUE TITLE
chrome标签页双击左键会弹出, 占用了我的双击关闭, 设置里面还没法设置

### ISSUE THREAD

**Issue by lin962648** [cuiliang/Quicker#193]
已删除所有面板内容，还会在chrome标签页双击左键弹出, 占用了我的双击关闭, 设置里面还没法设置。因为已删除所有面板内容，不应该是其他快捷设置引发的吧。如何解决呢

**Comment by cuiliang** [comment]
弹出和面板设置没有关系。 请在设置窗口中，打开“激活面板”标签页，把chrome加入黑名单。
![image](https://user-images.githubusercontent.com/1972649/51290391-b0eb0e80-1a3e-11e9-85af-0158715a133f.png)

**Comment by lin962648** [comment]
原来在设置中把激活方式的鼠标gun滚轮的勾去掉即可！！！
我现在只保留了长按右键方式。不会双击激活面板了。好开心。
![image](https://user-images.githubusercontent.com/7478530/51290431-cd874680-1a3e-11e9-88ac-d738d9705fbf.png)

**Comment by cuiliang** [comment]
好的：）
