### ISSUE TITLE
神器求出Mac版

### ISSUE THREAD

**Issue by bikmanwei** [cuiliang/Quicker#20]
我目前为了解决效率问题，€159购买了一款叫Stream Deck的桌面设备，这个设备本来是用来直播的，每一个按钮都可以自定义功能和背景图。肌肉记忆果然非常高效。但如今见到Quicker此等神器，手里退居二线的安卓手机都开始自行震动了！求出Mac版。

**Comment by cuiliang** [comment]
哈哈，我也买了做快捷键用，但是感觉有时候不是很方便，所以才开发的quicker。mac开发不是很懂，但是应该是能实现类似的效果。待我把windows搞定再说。

**Comment by Moyf** [comment]
感谢楼上两位！发现了个新的酷炫产品。

顺便路过推荐一下 Logitech G13 单手键盘，纯物理按键，配一个LED显示器，支持 20+ 个自定义按键配置以及3套方案。
不过这款产品国内现在没啥货源，正在苦恼替代品 Orz

**Comment by cuiliang** [comment]
如果不需要显示器，淘宝有很多卖自定义小键盘的，100左右，也是可以自定义按键，宏什么的。

**Comment by bikmanwei** [comment]
> 哈哈，我也买了做快捷键用，但是感觉有时候不是很方便，所以才开发的quicker。mac开发不是很懂，但是应该是能实现类似的效果。待我把windows搞定再说。

感谢Owner回复。
我UI设计，坐标阿姆斯特丹。如果需要画个图标啊界面啥的请告诉我。

**Comment by cuiliang** [comment]
提前先谢过啦~ 说不定真的会需要：）

**Comment by Moyf** [comment]
> 如果不需要显示器，淘宝有很多卖自定义小键盘的，100左右，也是可以自定义按键，宏什么的。

嗯嗯，感谢告知！去搜了一下，确实发现一些类似产品。
不过我对于这类外设的主要需求是这几点：
1. 可以随当前程序自动切换配置
2. 除了按键分配和宏之外，还支持打开指定程序/文件
3. 每个程序支持多套方案

所以其实核心还是在驱动/配套程序上，但目前看到的似乎只是简单地分配按键和操作宏（比如这个[键位多到酷炫的键盘](https://item.taobao.com/item.htm?spm=a230r.1.14.1.3fc453c8CI21rV&id=43429852858&ns=1&abbucket=14#detail)）
如果满足第二点，就可以结合 AHK 和 bat 来实现更多的功能了 √

目前找下来，罗技的 Logitech Game Software 是满足需求的（甚至支持脚本，虽然脚本语法很奇怪）；雷蛇那边的雷云看介绍也可以，但还没实操过。
Stream Deck 刚才看了下宣传视频，似乎也能满足上面3点需求，可以请两位帮忙求证一下吗？

**Comment by bikmanwei** [comment]
> > 如果不需要显示器，淘宝有很多卖自定义小键盘的，100左右，也是可以自定义按键，宏什么的。
> 
> 嗯嗯，感谢告知！去搜了一下，确实发现一些类似产品。
> 不过我对于这类外设的主要需求是这几点：
> 
> 1. 可以随当前程序自动切换配置
> 2. 除了按键分配和宏之外，还支持打开指定程序/文件
> 3. 每个程序支持多套方案
> 
> 所以其实核心还是在驱动/配套程序上，但目前看到的似乎只是简单地分配按键和操作宏（比如这个[键位多到酷炫的键盘](https://item.taobao.com/item.htm?spm=a230r.1.14.1.3fc453c8CI21rV&id=43429852858&ns=1&abbucket=14#detail)）
> 如果满足第二点，就可以结合 AHK 和 bat 来实现更多的功能了 √
> 
> 目前找下来，罗技的 Logitech Game Software 是满足需求的（甚至支持脚本，虽然脚本语法很奇怪）；雷蛇那边的雷云看介绍也可以，但还没实操过。
> Stream Deck 刚才看了下宣传视频，似乎也能满足上面3点需求，可以请两位帮忙求证一下吗？

以上要求均符合。老好用了

**Comment by Moyf** [comment]
> 以上要求均符合。老好用了

猴的，谢谢！
另，抱歉在 Issue 里歪了个楼 _(:з」∠)_

**Comment by cuiliang** [comment]
整理issues
