### ISSUE TITLE
站内沟通机制

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#202]
- [ ] 动作的反馈可以及时获知；
- [ ] 内部互相交流；
- [ ] 关注某类动作、某个exe的动作分享；
- [ ] 关注某个动作；
- [ ] 关注某人（分享的动作）；
- [ ] 动作投票；
- [ ] 动作更新通知；

...

**Comment by kanglade** [comment]
希望能收到客户端推送
