### ISSUE TITLE
BUG - Quicker.x86.0.8.5.0

### ISSUE THREAD

**Issue by jacaowei** [cuiliang/Quicker#207]
![image](https://user-images.githubusercontent.com/34974176/51724277-8da40d00-2097-11e9-9328-0d418eefe73e.png)

**Comment by cuiliang** [comment]
是什么情况下出现的呢？ 系统是Win7 32位么？

**Comment by cuiliang** [comment]
@jacaowei  请重新下载一下版本安装试试，32位版已更新至0.8.6.

**Comment by cuiliang** [comment]
先关了，如果还有问题再reopen吧。
