### ISSUE TITLE
全屏游戏状态取消激活

### ISSUE THREAD

**Issue by LucYang2017** [cuiliang/Quicker#208]
在打游戏的时候，比如FPS游戏，按右键开镜会出现鼠标，希望取消

**Comment by cuiliang** [comment]
0.8.5 已增加全屏禁用选项。可以试一下有没有问题。
![image](https://user-images.githubusercontent.com/1972649/51784811-9d038300-2189-11e9-9d0b-d6dc92b945d2.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题再reopen吧。

**Comment by smdx023** [comment]
很nice，就因为玩游戏的时候老是弹出来。然后我把这软件关了。今天想起反馈一下，没想到看到这个选项，这个选项藏得深了点，不注意还找不到。不过问题解决了还是很棒的
