### ISSUE TITLE
为按钮增加快捷键

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#21]
键盘党用户，可以直接用按键选择执行快捷动作。
面板弹出后可用

**Comment by komazhou** [comment]
恩，可以参考一下Google扩展surfinger，自动分配快捷键，分布在左手区域，增加左右手切换选项，这样可以兼顾键盘党，鼠标党，左右手，不知道可以实现不

**Comment by ll905518294** [comment]
墙裂建议为按钮增加全局快捷键，例如鼠标右键设置全局快捷键，默认不设置，避免冲突。高频使用的用户自己设置。（参考autohotkey的全局快捷键的效率）

**Comment by cuiliang** [comment]
已增加弹出后使用单键触发功能。0.7.28
