### ISSUE TITLE
【获取窗口标题】工作不正常

### ISSUE THREAD

**Issue by mifenfeifen** [cuiliang/Quicker#214]
> 版本：0.8.5
在资源管理器中，无法获得窗口标题（但是在桌面可以）
以下是【获取进程信息】+【获取窗口标题】两个动作的输出信息：

在资源管理器：
> Process：explorer
> Path：C:\Windows\Explorer.EXE
> Win：

在桌面：
> Process：explorer
> Path：C:\Windows\Explorer.EXE
> Win：FolderView 

其他程序：
> Process：powershell
> Path：C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
> Win：选择Windows PowerShell

**Comment by mifenfeifen** [comment]
在该版本下，发现【提示消息】动作根本没有反应

**Comment by cuiliang** [comment]
> 在该版本下，发现【提示消息】动作根本没有反应

试试重启一下Quicker看看能不能正常。 这个提示消息的组件似乎有一个bug，很早以前我也遇到过一次不显示的情况。

资源管理器这类好像是多个窗口组成，点不同的位置，结果会不同。 点标题栏或工具栏区域，可以得到标题，点下面文件列表那里，就会得不到。

**Comment by cuiliang** [comment]
@mifenfeifen  或许可以优化一下，找到根窗口再获取标题。待我有时间测试一下看看。 这个先开着吧。

**Comment by cuiliang** [comment]
新版增强了获取窗口标题动作。可选 前台窗口（根窗口）或指针位置窗口（可能是子窗口）。
![image](https://user-images.githubusercontent.com/1972649/52542211-817ab800-2dd8-11e9-903f-29ac0ae2353c.png)
