### ISSUE TITLE
Quicker与WGestures的右键冲突

### ISSUE THREAD

**Issue by PrimaryCoderX** [cuiliang/Quicker#220]
不得不说Quicker是一款相当不错的软件，在此由衷感谢作者的无私奉献，但是仍有一些问题：
WGestures：另外一款专注于鼠标手势操作的效率工具
Quicker的唤醒方式被我设置为按住右键原地不动200ms
在安装WGestures之前Quicker正常，在安装WGestures后Quicker的唤醒失效
但在以下情况下Quicker仍正常：
①在禁用WGestures的程序界面按住右键200ms可以唤醒
②完全退出WGestures
③在两款软件完全退出后先打开WGestures再打开Quicker可以全局正常
希望可以排查问题，提出Quicker唤醒失败的解决方案。

**Comment by cuiliang** [comment]
这个是正常的，两个软件都依赖于拦截右键按下事件。
如果需要同时使用这两个软件，建议在WGuestures里增加一个手势，发送激活Quicker的快捷键，取消quicker的右键激活选项。

**Comment by PrimaryCoderX** [comment]
Ok，已解决，谢谢，曲线救国ヽ(￣▽￣)ﾉ
根据第三条，取消Quicker开机自启，设置手势打开Quicker
同时保留了两款软件的使用习惯(～￣▽￣)～

**Comment by cuiliang** [comment]
> Ok，已解决，谢谢，曲线救国ヽ(￣▽￣)ﾉ
> 根据第三条，取消Quicker开机自启，设置手势打开Quicker
> 同时保留了两款软件的使用习惯(～￣▽￣)～

不是取消开机自启，是取消右键激活的选项哦。
