### ISSUE TITLE
功能完善

### ISSUE THREAD

**Issue by gerhardtpeng** [cuiliang/Quicker#226]
希望在文本处理中添加删除回车的操作

**Comment by cuiliang** [comment]
可以直接用替换文本模块
被旧值里敲一个回车，新值留空，后面参数可以不选。

**Comment by vixiaobai** [comment]
希望可以加入多选操作,第一次使用设置会删除添加很多东西

**Comment by cuiliang** [comment]
> 希望可以加入多选操作,第一次使用设置会删除添加很多东西

@vixiaobai 后期将不再预置太多示例动作，让用户根据需求添加。
