### ISSUE TITLE
长按右键会激活面板

### ISSUE THREAD

**Issue by happyblank** [cuiliang/Quicker#230]
mindjet中长按右键会激活面板，设置中已关闭长按右键激活
![default](https://user-images.githubusercontent.com/14332247/52829318-4396d000-3107-11e9-915a-1ec366b8f7de.png)

**Comment by cuiliang** [comment]
是每次还是偶尔？
请提供下Quicker版本、Windows版本、和配置窗口截图。 
另外，如果启用了右键移动激活，长按的时候如果鼠标移动超过5个像素，也会触发。

**Comment by happyblank** [comment]
> 
> 
> 是每次还是偶尔？
> 请提供下Quicker版本、Windows版本、和配置窗口截图。
> 另外，如果启用了右键移动激活，长按的时候如果鼠标移动超过5个像素，也会触发。

应该是我对『按右键移动』理解有误导致，的确是这个触发的

**Comment by cuiliang** [comment]
或许文字描述有歧义，需要改进。 你理解成啥样了？
