### ISSUE TITLE
其他的面板激活方式

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#234]
吸附在屏幕边缘。https://getquicker.net/Forum/ViewTopic/231

在屏幕上画圈？

**Comment by linyubin** [comment]
建议自定义鼠标动作来激活面板,工程绘图软件中很经常用到右键以及中键,很容易误触发激活面板

**Comment by cuiliang** [comment]
> 建议自定义鼠标动作来激活面板,工程绘图软件中很经常用到右键以及中键,很容易误触发激活面板

如果使用了手势软件，可以用手势软件发送激活Quicker的快捷键，应该可以解决冲突。
