### ISSUE TITLE
快捷键建议

### ISSUE THREAD

**Issue by komazhou** [cuiliang/Quicker#24]
建议增加翘板快捷键启动，按住左键点击右键或按住右键点击左键，这样可以避免在很多程序中冲突的问题，使用也比较方便顺手

**Comment by cuiliang** [comment]
已增加长按右键方式。 翘板方式在按完右键再按左键的时候，长按右键已经激活面板。所以这种方式相对于长按右键多了一次操作。 另外，许多手势软件也支持翘板方式，可以利用手势软件的翘板操作，发送快捷键来激活Quicker。
