### ISSUE TITLE
请增加鼠标侧键启动的激活方式，鼠标中键在浏览器上可以上滑下拉，也可关闭标签还是比较常用的页

### ISSUE THREAD

**Issue by gakaks** [cuiliang/Quicker#256]

**Comment by cuiliang** [comment]
侧键是硬件定义的，在软件中无法得到。 如果鼠标带驱动可以自定义侧键，可以将其转换为发送激活quicker的快捷键。 目前也支持长按右键或按右键滑动激活等方式，不必要用中键。

**Comment by gakaks** [comment]
好的吧，我设置组合键然后用鼠标自定义侧键解决了，感谢你制作了这么优秀方便的软件

**Comment by cuiliang** [comment]
> 好的吧，我设置组合键然后用鼠标自定义侧键解决了，感谢你制作了这么优秀方便的软件

😊
