### ISSUE TITLE
动作参数？ 将一些变量设置为“动作参数”，用户安装时设置。

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#263]
- [ ] 动作参数标记
- [ ] 变量排序
- [ ] 必填验证

**Comment by kanglade** [comment]
之前我想过这问题，当时觉得完全可以开发者通过状态来实现啊，找不到状态时提示用户输入。后来发现还是有缺点，那就是状态不能同步，换了电脑又得再操作一遍。不过这算是缺点么

**Comment by WilsonXuwx** [comment]
目前的话是在动作分享时说明改那个变量值来做到提醒设置"动作参数"。
那现在这样做是否是为了提升用户体验?以下建议:
1. 安装时请求设置“动作参数”可以作为一个模块，需要的话在设计动作时加入。
2. “动作参数”可以右键动作在弹出菜单中随时修改。

**Comment by kanglade** [comment]
与下面这个结合起来考虑怎么样：
[支持某些个人信息网络同步 #360](https://github.com/cuiliang/Quicker/issues/360)

- 实现云变量概念，值存在云端
- 必填验证可由开发者写在动作中，无须Quicker本身实现，就像状态

**Comment by cuiliang** [comment]
目前可以通过表单、变量作为状态、检测按键的结合实现配置。 不增加额外的处理了。
