### ISSUE TITLE
默认动作面板管理

### ISSUE THREAD

**Issue by zxj-gh** [cuiliang/Quicker#265]
能否把『默认』面板独立出来，转变成『设为默认』的功能？
这样可以方便在不同时期切换工作重点，流通、遍历，这样来配合其他小工具（如Everything、Taggedfrog、Excel）保证一些良性循环得以简洁、流畅地实现，也使得每个面板都不会被遗忘，从而增强库存功能的自我迭代、更新能力。

**Comment by cuiliang** [comment]
不是特别明白。 新的版本中增加了锁定面板切换的功能，可以试下是否能满足

**Comment by zxj-gh** [comment]
可以用，感谢～

CuiLiang <notifications@github.com> 于 2019年3月1日周五 上午10:38写道：
