### ISSUE TITLE
建议增加按键检测功能

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/Quicker#269]
像“获取剪贴板文本”一样，但又可以比它更高级，当检测到某个按键或者按键组合后，执行对应步骤（或步骤组，或完全独立的动作分支），检测按键可以是持续性检测，也可以运行到某个步骤时等待按键。

比如这个连续复制动作：https://getquicker.net/Sharedaction?code=f817b237-1072-4b99-d64b-08d69892fb0c
它复制完后需要等待10秒才能自动结束动作，若是可以检测按键，比如检测到按下Enter时则结束动作，将会带来极大的便利。

假如实现这个功能，Quicker的应用范围将更广泛，能实现更多更复杂更高级的动作。

**Comment by cuiliang** [comment]
暂时通过 “等待窗口模块” 实现。
https://getquicker.net/Forum/ViewTopic/348
