### ISSUE TITLE
当前程序已使用了Windows管理器对象的系统允许的所有句柄

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#274]
![image](https://user-images.githubusercontent.com/1972649/53683426-9ee9d480-3d3b-11e9-9f22-5e495316ceb0.png)

**Comment by cuiliang** [comment]
暂未重现了

**Comment by mingjinglyh** [comment]
此问题我的电脑多次重现

**Comment by cuiliang** [comment]
@mingjinglyh 目前反馈这个问题的比较少。请提供尽量多的信息以判断和什么有关。
