### ISSUE TITLE
复用一部分步骤

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#276]
- [x] 1.复制动作的一组步骤到另一个动作中
 减少重复劳动，一个关键的问题是变量怎么处理。
- [ ] 2. 像函数那样可以多次调用

**Comment by kanglade** [comment]
是否可以考虑引入「命名空间」，步骤组里面加个选项「□命名空间」，勾上后，里面的变量为步骤组特有。这样可以解决步骤复制后变量的处理。

**Comment by kanglade** [comment]
关于第2个问题，
是否可以给步骤组命名，就像变量一样，
然后加个模块：「调用步骤」

**Comment by cuiliang** [comment]
归档
