### ISSUE TITLE
FR：新增根据当前软件判定是否启用中键功能

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#29]
当前的 Quicker 已经可以根据不同的软件来自动切换面板，但是对某些软件（例如 3D 建模软件）来说，所有的中键相关组合（中键单击、Ctrl/Shift/Alt 等等修饰键）都是被占用的，这种情况下希望能屏蔽热键。

换句话说，希望能增加「设置某个软件中 Quicker 是否生效」的选项，来避免某些特定软件下的干扰。

REF：
![image](https://user-images.githubusercontent.com/4013062/48765670-9ec64b80-eced-11e8-952c-e1a9b8bcb705.png)

**Comment by cuiliang** [comment]
好的，考虑增加此设置。 和弹出面板改进统一考虑。 #5

**Comment by i5151** [comment]
现在不是可以换成其他键了吗？直接换成其他键就行了，不一定非得中键。

**Comment by Moyf** [comment]
> 现在不是可以换成其他键了吗？直接换成其他键就行了，不一定非得中键。

@i5151 你其实没 Get 到重点，这个需求的核心不是「换按键」而是「排除清单」。
中键（或者任意按键）没问题，但是「某些软件不需要 Quicker 进行响应」。


> 好的，考虑增加此设置。 和弹出面板改进统一考虑。 #5

@cuiliang 感谢！

**Comment by i5151** [comment]
> > 现在不是可以换成其他键了吗？直接换成其他键就行了，不一定非得中键。
> 
> @i5151 你其实没 Get 到重点，这个需求的核心不是「换按键」而是「排除清单」。
> 中键（或者任意按键）没问题，但是「某些软件不需要 Quicker 进行响应」。
> 
> > 好的，考虑增加此设置。 和弹出面板改进统一考虑。 #5
> 
> @cuiliang 感谢！
@Moyf 你同样没有 Get 到重点，用其他的按键本身就排除了Quicker对中键的响应，而且是永久的。

**Comment by cuiliang** [comment]
@i5151 
有一些情况确实需要黑名单处理，比如使用远程桌面的时候，本想给远程的窗口操作，结果本机弹出了。 这个最终分3种情况了：正常，特殊（按键冲突的）和彻底屏蔽的。

**Comment by Moyf** [comment]
> @Moyf 你同样没有 Get 到重点，用其他的按键本身就排除了Quicker对中键的响应，而且是永久的。

@i5151 这可能是你的“需求”和“解决方式”，但不是我这个 FR 的核心。

这么说吧，其实就是：
1. 我乐意用中键作为快捷键方式，并且在大部分软件中用这个方式很舒服。
2. 在小部分软件中用不到 Quicker，希望排除掉。

这样明白了吗？

**Comment by i5151** [comment]
> @i5151
> 有一些情况确实需要黑名单处理，比如使用远程桌面的时候，本想给远程的窗口操作，结果本机弹出了。 这个最终分3种情况了：正常，特殊（按键冲突的）和彻底屏蔽的。
其实，设置可以更灵活一些，可以让用户自由定义激活面板的按键组合。

**Comment by Moyf** [comment]
> @i5151
> 有一些情况确实需要黑名单处理，比如使用远程桌面的时候，本想给远程的窗口操作，结果本机弹出了。 这个最终分3种情况了：正常，特殊（按键冲突的）和彻底屏蔽的。

Yep，刚才另一位关注的是第二种情况，而这个 FR 讨论的是第三种情况。
Owner gets the point.

**Comment by i5151** [comment]
> > @Moyf 你同样没有 Get 到重点，用其他的按键本身就排除了Quicker对中键的响应，而且是永久的。
> 
> @i5151 这可能是你的“需求”和“解决方式”，但不是我这个 FR 的核心。
> 
> 这么说吧，其实就是：
> 
> 1. 我乐意用中键作为快捷键方式，并且在大部分软件中用这个方式很舒服。
> 2. 在小部分软件中用不到 Quicker，希望排除掉。
> 
> 这样明白了吗？

用不到的软件你用什么方式激活呢？换成其他的方式还是不使用了？

**Comment by Moyf** [comment]
> 用不到的软件你用什么方式激活呢？换成其他的方式还是不使用了？

工作时间啦，暂停探讨吧。
我相信 Owner 那边已经了解到咱们的需求了。

**Comment by i5151** [comment]
@cuiliang 
热键这个问题只能说你一开始就过于强调鼠标中键了，有些考虑欠妥，中键并不是一个闲置的按键。对一般人来说可能把中键做按键使用的不多，但很多软件并没有忘记它，很多软件都设置有中键的使用，而且它们对中键的设置还很花哨，能实现很多功能，在这些软件中使用中键作为激活热键必然有问题。不只是楼主说的软件，就是在一般的软件中，按中键都有快速浏览的常规作用，用中键做热键就必然限制了中键在这些软件中的作用。Quicker也不可能要求别人做出修改，如果排除了这些软件，那Quicker的使用体验就不统一、甚至不方便了，想在任何场景中都能维持相同的体验就显得很困难，最后还是得自己找到适用自己的独特热键，所以维持统一的全局热键对Quicker的使用体验非常重要。。

现在好多人看到宣传就把Quicker和中键绑定了，好像Quicker只能用中键、必须用中键，不用就不是Quicker了，先入为主地排斥了其他热键。其实，与维持全局统一的热键相比，具体用什么热键激活倒不是那么重要，找到自己用着方便就行，用几次之后就会习惯，Quicker的强大之处在于用适用自己的方式激活之后，它就变成了超级强大的可编程的鼠标快捷键，而不是激活它的热键本身。

还有就是罗技的一大波鼠标的中键是没有普通的按键功能的，总不能一开始就把他们排除在外吧？

现在可以更改已经很不错了，应该都能找到适合自己的，不过还应多加些组合，让用户自己选择，甚至让用户可以自由定义任意的快捷键，反正自己用着舒服，不与其他热键冲突就行了，Quicker没有必要限制得太严。

这点可以参考Snipaste，虽然它设置F1、F3的热键遭不少人诟病，但它更改热键的方式确实很简单灵活直观，只是它不支持鼠标热键。

**Comment by cuiliang** [comment]
@i5151 
谢谢，确实是这样的。 我主要是平时不怎么用中键，觉得这个挺好，可以用起来。 现在才知道用的还真是非常多。
我会妥善处理一下。

**Comment by i5151** [comment]
@cuiliang 
中键我也不用，因为不能用。😂

我想热键的设置困扰和你对Quicker的定位不准有关，你始终认为Quicker是启动器而不是鼠标右键的增强。诚然，你开机启动时，运行所有要打开的软件、文件，且不说这么做的人能有多少，但就是这么做了，也只有这时Quicker才像个启动器，其余所有的时间它都更像一个右键菜单。

试想，鼠标上的哪个按键能在系统和应用软件的所有地方都呼出菜单，并且是不同的菜单，只有右键。而且Quicker为不同的应用软件设置的动作菜单更是像极了右键菜单。如果想清楚这一层，就不会在中键上打转了，开始的热键就会定位在右键上。

右键单击，显然排除。右键双击、长按，这种反人类的设计也不在考虑之内，而且系统和软件都没有为右键做过过多的优化设计，右键基本只是接收单击，双击、长按也很难起作用。

剩下自然就会想到右键组合，Ctrl+右键是最先能想到的。Ctrl最容易按，此组合也极少会有冲突；不行还有Shift、Alt，Win+右键也应该没问题吧， 大不了它们还可以组合，肯定能找到适用的，实在不行就自己设定。

所以，把热键默认为Ctrl+右键，既符合软件的定位也极少冲突，不愿意用的自己可以修改成想要的，应该问题就不多了。

**Comment by Moyf** [comment]
干脆就放开多一些的【触发键】选项吧，我之前也有看到 Issue 是希望用键盘快捷键来呼出 Quicker 菜单的。

* 鼠标左键、中键、右键
* 4套修饰键（Ctrl、Win、Alt、Shift）
* 键盘上的基础按键

——正常来说这三个的搭配就足矣。

想继续拓展的话还可以加上：
* 连续按键触发（例如 Alt+Q+W）
* 同时按下触发（左键按下的同时，点击右键）

这些方案也都有软件做过，可行性上没问题。

**Comment by i5151** [comment]
> 干脆就放开多一些的【触发键】选项吧，我之前也有看到 Issue 是希望用键盘快捷键来呼出 Quicker 菜单的。
> 
> * 鼠标左键、中键、右键
> * 4套修饰键（Ctrl、Win、Alt、Shift）
> * 键盘上的基础按键
> 
> ——正常来说这三个的搭配就足矣。
> 
> 想继续拓展的话还可以加上：
> 
> * 连续按键触发（例如 Alt+Q+W）
> * 同时按下触发（左键按下的同时，点击右键）
> 
> 这些方案也都有软件做过，可行性上没问题。

没有禁忌地全放开，我也是这么和他提的，但也必须有个基本的默认热键，而且是和其他软件极少冲突的，使用简单方便的。
