### ISSUE TITLE
两个问题：1）安装后没有图标，只有文字标签；2）打开共享库的时候卡顿

### ISSUE THREAD

**Issue by aben1188** [cuiliang/Quicker#290]
今天第一次安装使用，目前有两个问题：
1）安装后，全部都没有图标，只有文字标签，难道要重新设置一遍图标吗？
2）打开共享库时，出现卡顿，鼠标无法操作，应该是在请求服务器，但难道不是异步请求吗？

**Comment by cuiliang** [comment]
请参考 https://getquicker.net/Forum/ViewTopic/315
