### ISSUE TITLE
自定义面板突然丢失！！

### ISSUE THREAD

**Issue by HgyHgyHgy** [cuiliang/Quicker#291]
开始突然不能自动弹出自定义面板，自定义面板并无丢失。

然后以为必须更新软件，才会变得正常。

结果下载后，安装，到了让退出quicker时，win10居然死机了。
重启，重新安装后，正常。

但自定义面板丢失了！面板名称依然在，但变成空白了！

这个quicker并无更新，就突然出现这种情况，也不清楚是quicker偷偷更新，还是win10的更新，导致专用面板不能用。但win10今天并无更新，早上还是正常。就算win10偷偷更新了，也并没重启电脑。

这个会丢失面板，十分不方便！

**Comment by cuiliang** [comment]
在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
一切都是默认设置。无其他杀毒软件，只有win10自带的。
升级时，导致win10死机，不得不重启。
重启后，重新安装，quicker清理之前 未完成的安装，清理完，安装好后，就丢失了面板配置了。

建议弄个，快速选择面板的方法吧，比如快捷键选择面板。自动识别失败的时候，依然能用。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
在更新quicker后，安装quicker时，会造成win10死机。
这个太奇怪。Win10一般不会死机的。
只能卸载了，除非卸载后，也重新出现win10死机的问题，证明不是quicker造成的。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
Quicker.x64.0.9.27.0.msi 会导致死机，在选择运行程序时，也会假死。

只能安装旧的Quicker.x64.0.8.2.0.msi。
在它们直接按好像还有其他好几个版本，在网上没有安装文件。


Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
旧的Quicker.x64.0.8.2.0.msi也不能用！虽然不会死机，但是调用程序不能执行。可能是win10的更新造成。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
卸载后，重启，重新安装旧的版本，好像能正常使用。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by HgyHgyHgy** [comment]
就刚设置面板的时候能用，重新点击中键，面板就丢失了。

Win10的更新和quicker不兼容呀啊！！！！


Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月6日 19:26
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

在本机存储配置了么？ 修改面板后，是否同步完成了呢？
有安装什么杀毒或安全软件么？
如果登录的时候选择了在本机保存配置，数据会存储在 C:\Users\用户名\AppData\Local\Quicker\data 下。建议先手工备份一下这个目录。
quicker没有自动更新功能。

**Comment by cuiliang** [comment]
不是很清楚具体什么情况。 建议录屏看一下。 目前还没有其他用户反应类似的问题，可能和您电脑上什么组件冲突。

**Comment by HgyHgyHgy** [comment]
主要是安装它的过程中，半路就死机了。之后，win10就有不明原因出现死机的毛病了！不能用了。不然，就算用不了那个特有面板，只用那个主面板，还是可以的。现只能改用maxlaunch。
这个能不能出个兼容性高点，稳定性高点，功能简单点的版本？
建议考虑把那个特有面板作为一个选项，这样特有面板不能用，也能用分页的面板代替，这个兼容性就会好很多。
还有就是去掉可能导致win10死机部分的功能去掉，或者作为可选项，默认情况不开启。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月7日 19:29
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

不是很清楚具体什么情况。 建议录屏看一下。 目前还没有其他用户反应类似的问题，可能和您电脑上什么组件冲突。

**Comment by cuiliang** [comment]
死机可能是别的原因，目前还没有其他用户反应安装时候死机现象的。

**Comment by HgyHgyHgy** [comment]
但是win10是很少会出现死机现象。
在安装的半路，它提示关闭运行的quicker,点确认后，它就突然画面一动不动，鼠标，键盘不能动，画面完全不改变，也没出错信息出现。
然后之后，就初心了突然死机的现象了。并且死机的现象，不是在使用quicker的过程中发生的。
但这个是在安装了那个最新版之后才出现这个死机现象。
这个影响还是很大的。譬如有工作没及时保存，它突然死机了，工作就全部丢失了。

Guiyang Huang

发件人: CuiLiang
发送时间: 2019年3月8日 9:23
收件人: cuiliang/Quicker
抄送: HgyHgyHgy; Author
主题: Re: [cuiliang/Quicker] 自定义面板突然丢失！！ (#291)

死机可能是别的原因，目前还没有其他用户反应安装时候死机现象的。
