### ISSUE TITLE
用户选择：快速选择选项

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#295]
![image](https://user-images.githubusercontent.com/1972649/53965249-cc63c300-412b-11e9-9a7c-0ca88bb0f800.png)

**Comment by cuiliang** [comment]
done

**Comment by mgdreamingstar** [comment]
启用筛选之后，能否在筛选出只有一个候选的情况下，回车键默认发送唯一的候选？

**Comment by cuiliang** [comment]
> 启用筛选之后，能否在筛选出只有一个候选的情况下，回车键默认发送唯一的候选？

 快速通道刚更新了1.5.3，可以试一下。

**Comment by mgdreamingstar** [comment]
神速添加功能，多谢了！
