### ISSUE TITLE
增加选项：面板弹出位置

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#30]
在屏幕中间弹出，或跟随鼠标，（或依据激活方式，键盘激活的在屏幕中间，鼠标激活的跟随鼠标位置）

**Comment by i5151** [comment]
怎么激活并不重要，重要的是激活之后都是要鼠标操作，键盘激活之后也是要鼠标操作，所以面板的弹出位置只应是跟随鼠标，这样能减少鼠标移动的距离、提高效率。

在屏幕中间弹出只有一种可能，就是鼠标单击托盘图标。

其实，这就是现在软件的设置，挺合理的，没必要再改了。

**Comment by i5151** [comment]
单击托盘图标还是修改成中间弹出更好。
