### ISSUE TITLE
滑动鼠标滚轮会调节声音大小问题

### ISSUE THREAD

**Issue by zhongjie10086** [cuiliang/Quicker#307]
启动quicker后在浏览器标签页滑动鼠标滚轮，会调节声音大小

**Comment by cuiliang** [comment]
可以在这里配置是否启用调节音量的辅助功能： 
![image](https://user-images.githubusercontent.com/1972649/54079591-58d3d880-431a-11e9-8ab9-c68f175b0935.png)

启用后，只有在最顶端Y坐标等于0的时候才会生效，向下移动一个像素就会是原有功能。

**Comment by zhongjie10086** [comment]
无法关闭这项功能，取消后保存会显示出错。
![TIM图片20190310132338](https://user-images.githubusercontent.com/48387208/54081048-a101f380-4338-11e9-97c2-f12d309e8010.png)

**Comment by cuiliang** [comment]
> 无法关闭这项功能，取消后保存会显示出错。
> ![TIM图片20190310132338](https://user-images.githubusercontent.com/48387208/54081048-a101f380-4338-11e9-97c2-f12d309e8010.png)

感谢反馈。 方便截图一下么？ 我把这4个选项取消，保存的时候没有报错。可能和别的选项有关，麻烦你把几个tab都截图一下，我试试用相同的参数保存一下。

**Comment by zhongjie10086** [comment]
![AVH0T0VO 6_6I_ BR8CQ7N7](https://user-images.githubusercontent.com/48387208/54084545-07a10480-436d-11e9-98e3-35f5747b6daf.png)
![TIM截图20190310194055](https://user-images.githubusercontent.com/48387208/54084557-230c0f80-436d-11e9-8a06-266ea007f031.png)
![TIM截图20190310194108](https://user-images.githubusercontent.com/48387208/54084558-23a4a600-436d-11e9-9120-572dbf9de29b.png)
![TIM截图20190310194130](https://user-images.githubusercontent.com/48387208/54084559-23a4a600-436d-11e9-94b3-5bfcf74f2e73.png)
![TIM截图20190310194144](https://user-images.githubusercontent.com/48387208/54084560-243d3c80-436d-11e9-92e8-0d4c768d0804.png)
![TIM截图20190310194234](https://user-images.githubusercontent.com/48387208/54084562-24d5d300-436d-11e9-8ae8-4e1a0c745a88.png)
![TIM截图20190310194346](https://user-images.githubusercontent.com/48387208/54084563-24d5d300-436d-11e9-97e0-e579e87beb3a.png)

**Comment by cuiliang** [comment]
@zhongjie10086 
使用相同的配置没有复现。
可以看下log里有没有错误消息：https://getquicker.net/Forum/ViewTopic/345
