### ISSUE TITLE
BUG：无法识别 UMP 的 Onenote

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#31]
在 Windows 10 的 Onenote 软件中，无法识别到当前所在的软件；手动指定 exe 后，也无法在激活软件自动切换。

![image](https://user-images.githubusercontent.com/4013062/48899427-89d2ef00-ee8a-11e8-9e8e-220f9c3dc1da.png)

**Comment by cuiliang** [comment]
收到。 UWP的进程有封装，不能直接得到exe，这个不知道是不是有什么特殊。 我等试下

**Comment by cuiliang** [comment]
测试可以识别。先关了，有问题再open :)
