### ISSUE TITLE
win10首次无法唤醒

### ISSUE THREAD

**Issue by zhangenming** [cuiliang/Quicker#311]
进系统后
长按右键快捷键无法唤醒
必须手动开启, 点击任务栏图标
之后快捷键才会生效

可稳定复现
OS 版本:          10.0.17763 暂缺 Build 17763

**Comment by cuiliang** [comment]
有同时使用手势软件或其他可能用到鼠标挂钩的软件么？

**Comment by zhangenming** [comment]
> 有同时使用手势软件或其他可能用到鼠标挂钩的软件么？

是的  有用WGestures

**Comment by cuiliang** [comment]
和两个软件挂钩的顺序（软件的启动顺序）有关系。 如果WG先拦截了右键，Quicker就没法触发了。因为这时候没有右键长按事件了，如果鼠标没有移动，WG会再右键抬起的时候再模拟发送一个右键点击的事件。

**Comment by cuiliang** [comment]
现在的版本可以打开和关闭一下配置窗口来重新挂钩一下，下个版本增加一个托盘菜单用来重新加载鼠标挂钩。

**Comment by zhangenming** [comment]
> 现在的版本可以打开和关闭一下配置窗口来重新挂钩一下，下个版本增加一个托盘菜单用来重新加载鼠标挂钩。

其实现在  只要手动双击任务栏图标打开一下就自动好了
添加菜单没什么意义吧 区别不大

**Comment by cuiliang** [comment]
好的。 这个case先关掉了，关一个是一个，open太多压力大啊😂

**Comment by cuiliang** [comment]
hi, 有使用Windows虚拟桌面么？ 我今天调试的时候第一次遇到了一个弹出的时候显示在其他虚拟桌面的现象。

**Comment by zhangenming** [comment]
是的 有使用dexpot

**Comment by zhangenming** [comment]
我两个显示器 分辨率不一样  两个显示器非第一次都可以正常激活
