### ISSUE TITLE
模块：调用其他动作

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#312]
通过组合其他动作，来实现更复杂的应用。
这类动作无法分享。

**Comment by kanglade** [comment]
可以考虑给动作增加输入和输出，使能够像函数那样调用。

**Comment by kanglade** [comment]
我觉得这里应该通过动作的名称而不是ID来调用

**Comment by kanglade** [comment]
是不是类似等待窗口配合等待时间，或者显示文本里的「等待关闭」来实现，
等待时间里面加个「等待调用动作完成时取消」又如何？
另外动作加上输入输出机制

**Comment by cuiliang** [comment]
使用子程序实现
