### ISSUE TITLE
很多HTTp或HTTPS的网站的图标获取不到

### ISSUE THREAD

**Issue by gjianbo** [cuiliang/Quicker#313]
如:
https://t.chanjet.com/tplus/view/login.html

**Comment by cuiliang** [comment]
这个网页里回传的内容是一个跳转，里面基本是空的，没有标题和图标信息，所以没办法得到图标的。

**Comment by cuiliang** [comment]
增加了一点处理，为空时取默认位置favicon.ico在这个网址测试成功了。
