### ISSUE TITLE
步骤：希望能拖拽调整步骤顺序，并自选「添加/移除常用步骤」

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#318]
![image](https://user-images.githubusercontent.com/4013062/54259242-0c013380-45a0-11e9-85eb-a5d4b854c365.png)

希望能给步骤也加上右键菜单：
* 添加进常用步骤（或者叫“收藏”？）
* 移出常用步骤

并且希望能自己调整步骤的顺序，每个人常用的动作都不同，这样自由度更大。

（这个属于易用性方面的提升，优先级挺低的哈）

**Comment by cuiliang** [comment]
嗯，这个主要是要同步服务器会困难一些，后期再优化

**Comment by cuiliang** [comment]
1.4.15 版本增加收藏夹和按使用次数排序。
