### ISSUE TITLE
FR：关于界面以及易用性的几条建议

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#32]
**List**
1. 自定义面板的按钮数量&大小
2. 给按钮添加快捷键选项
3. 移除 Quicker 主页的固定按钮
4. 将空白格子的单击添加调整为双击

---

**Description**
> 1. 自定义面板的按钮数量&大小

如下图，希望能选择面板中的按钮个数以及纵横布局，外加自定义调节按钮大小的选项。
![image](https://user-images.githubusercontent.com/4013062/48905492-a9731300-ee9c-11e8-9887-d4401f9f599c.png)

> 2. 给按钮添加快捷键选项

在添加按钮的同时，给用户*可自选*的快捷键设置选项，这样在打开面板的时候，直接敲击对应快捷键就可以执行对应按钮的操作。
这个提升可以配合`用键盘呼出 Quicker`的特性。

进一步的，可以在按钮角落提示它对应的触发快捷键。
（最好是让用户自己选择是否显示按键提示）

![image](https://user-images.githubusercontent.com/4013062/48905647-138bb800-ee9d-11e8-910f-99e4a1751f47.png)

相关Link：#21

> 3.移除 Quicker 主页的固定按钮

![image](https://user-images.githubusercontent.com/4013062/48905689-328a4a00-ee9d-11e8-8bec-18aaa5d2c622.png)
出于用户易用性的角度，这个按钮没有常驻在右上角的必要。
可以考虑放到上方菜单栏作为小图标显示。

另一种方案是作为付费点。
对轻度用户来说，被占一个格子无所谓；
但是重度用户就会希望能充分利用空间，并且愿意为此付费。

> 4. 将空白格子的单击添加调整为双击

某些面板可能会有较多的空位。
但鼠标左键比较容易误操作，点到一下就弹出选框，这个触发比较难受。

调整为双击添加新动作，则可以极大地避免误操作的情况。

——以上。

---

感谢崔亮大大的开发！

另外私心希望能放个支付宝收款码出来，方便捐款~
Quicker 本身也可以采取「前期Donate+后期增加Pro版本」的方式，据我所知 Seer 和 Snipaste 都是走的这样的路线。

**Comment by cuiliang** [comment]
收到，感谢你的建议，辛苦了！ 我会仔细考虑~

**Comment by i5151** [comment]
1、按钮的大小和单屏按钮的数量要和手机客户端相适应，现在的大小、单屏按钮的数量其实是手机客户端的最佳显示效果，更改了手机客户端就不好显示了，没有办法和电脑一一对应了。

按钮的数量，翻屏就增加了，要多少有多少。

2、本身Quicker应看做鼠标快捷键，比键盘快捷键更快，都用键盘快捷键的话，弹出面板就完全没必要了，Quicker只要常驻系统托盘就好，全部键盘快捷键解决了。

3、这倒是应该去掉，不过要是翻屏的话，不去也得去。

4、这个倒是无所谓，习惯它这个左右单击都有动作就行了。

**Comment by i5151** [comment]
> > 1、按钮的大小和单屏按钮的数量要和手机客户端相适应，现在的大小、单屏按钮的数量其实是手机客户端的最佳显示效果，更改了手机客户端就不好显示了，没有办法和电脑一一对应了。
> 
> 不要只考虑**自己**的用户体验好吗……我目前是纯 PC 用户。
> 虽然我也在等 iOS 版本，但我认为在我的工作场景中，更多的是纯 PC 端的操作。
> 
> 如果这种方案和当前的「手机远程操作」有冲突，咱们应该致力于想出更合理的解决方案，而不是直接否定，您觉得呢？
> 
> > 2、本身Quicker应看做鼠标快捷键……
> 
> 这种想法其实是把产品定位给限制住了。
> 「弹出菜单+快捷键触发」的方案，在 Alfred、Wox 这类 Launcher 软件中都是广泛应用的。
> 
> ![image](https://user-images.githubusercontent.com/4013062/48927580-f04f2000-ef11-11e8-8833-fa7c6c7fe35e.png)
> 如图，右侧的序号代表用对应的数字键来激活选项。这种情景下，面板提供的是「视觉信息」，可以让用户减少记忆负担，并且明确操作对象。
> 
> _“本身XX就应该如何……”_ 等于替用户做决定。
> 但对效率软件而言，每个人顺手的操作方式都不一样，也希望您能抱着更开放的心态。

1、不要只考虑**自己**的感受，OK？你是纯PC用户，我不是，Quicker也不是，它一开始就有手机客户端。以后推出IOS版的话，更要考虑界面的统一了。
起码把Quicker的产品都用到了，再提建议不迟。

2、并不是把Quicker定位限制了，而这就是Quicker的定位。
Quicker的里面动作就是模拟键盘输入快捷键，以鼠标点击代替，结果你让Quicker以一个快捷键代替另外一个快捷键，是不是多此一举？

应该保持开放心态的人是你，没人替你决定该用什么，我只是谈我的观点，就像你谈你的而不是我的一样。

**Comment by cuiliang** [comment]
哈哈，不要争论的太激烈了。你们提的都非常好，感谢你们~ 我会综合考虑。。。

**Comment by Moyf** [comment]
@i5151 ……首先你这个引用方式实在太难回复了。
我截取单句来吧。

> 不要只考虑**自己**的感受……
![image](https://user-images.githubusercontent.com/4013062/48927922-2c37b480-ef15-11e8-9630-9788166d1f9f.png)

所以我从来没有直接否定他人的需求——「这个功能我用不到，开不开发**无所谓**」。
我在求同存异，希望软件最后能整合不同用户的需求，你呢？


> 没人替你决定该用什么……
事实上，开发者对 Quicker 的塑造，就决定了我之后使用这个软件的方式。
我希望「增加」对键盘的支持，你觉得「Quicker 就是用鼠标代替键盘」所以不需要增加。
而你还觉得我不够开放 （笑）

---

Anyway，没人能阻止你在网上输出自己的观点，最终做决定的也是开发者自己。
祝好。

**Comment by Moyf** [comment]
> 哈哈，不要争论的太激烈了。你们提的都非常好，感谢你们~ 我会综合考虑。。。

嗯，我心态很稳。就探讨探讨，没必要吵。
归根结底，用户说再多毕竟是纸上谈兵，最后开发量和决策权还是落到你头上的。辛苦啦 ヾ(´･ω･｀)ﾉ

**Comment by i5151** [comment]
> @i5151 ……首先你这个引用方式实在太难回复了。
> 我截取单句来吧。
> 
> > 不要只考虑**自己**的感受……
> 
> ![image](https://user-images.githubusercontent.com/4013062/48927922-2c37b480-ef15-11e8-9630-9788166d1f9f.png)
> 
> 所以我从来没有直接否定他人的需求——「这个功能我用不到，开不开发**无所谓**」。
> 我在求同存异，希望软件最后能整合不同用户的需求，你呢？
> 
> > 没人替你决定该用什么……
> 
> 事实上，开发者对 Quicker 的塑造，就决定了我之后使用这个软件的方式。
> 我希望「增加」对键盘的支持，你觉得「Quicker 就是用鼠标代替键盘」所以不需要增加。
> 而你还觉得我不够开放 （笑）
> 
> Anyway，没人能阻止你在网上输出自己的观点，最终做决定的也是开发者自己。
> 祝好。

显然你还得多学学语文，你引用的“自己感受”的说法是针对你的说法的。

我提的建议，不管用什么说法都是我的观点，都是我认为的“应该”，难道我提建议应从你的角度说应该吗？你不也是提出和作者不同的观点吗？就像希望「增加」对键盘的支持，不是你认为的“应该”吗？

你本身就没有理解Quicker的意义，居然说美其名曰说自己是开放😂😂😂

PS：表情符号都是利用Quicker打出来的😎

**Comment by Moyf** [comment]
@i5151 真棒！说的太好了！
真希望有天我也能有你这样的语文水平和思想境界！向您学习！ (๑•̀ㅂ•́)و✧

**Comment by YsielX** [comment]
这里面的按钮数量现在是不是还没实现呢，想要面板里的数量更少更容易点到，希望能实现一下，感谢！
