### ISSUE TITLE
chrome app 模式 支持设置参数

### ISSUE THREAD

**Issue by gjianbo** [cuiliang/Quicker#326]
常用命令行参数介绍：
1. --incognito，设置浏览器直接从隐身模式启动功能，您在隐身模式中浏览网页不会保留浏览器记录、Cookie存储库或搜索记录，会保留下载的文件和已存的书签。
2. --start-maximized，启动时自动最大化窗口。
3. --lang=en_US，设置语言为英语_美国（这里可以写各种语言代码），快速切换显示语言，而免去在设置中点击数次并重启的麻烦。
4. --user-agent="thatis my user agent"（如果字符串不含空格则无需引号），设置伪造的用户代理字符串，可以验证网站对于不同浏览器采取的不同的行为。
5. --user-data-dir=D:\userdata，设置自定义用户数据位置，对于系统盘空间较小，希望把用户数据（包含缓存）放在其他位置的用户非常有用。
6. --disable-images，设置为禁止图像，对于流量有限制，或者其他不想看图的人群非常有用。
7. --no-sandbox，不使用沙箱，在和某些杀毒软件有冲突时，可以关闭沙箱。
8. --trusted-plugins，仅使用信任的插件。
9. --restore-last-session，启动时恢复最近的会话。

**Comment by cuiliang** [comment]
纠结了很久，感觉会用到这个的不是很多。如果需要可以直接用运行或打开模块在里面加命令行参数。 所以这个就先关了。
