### ISSUE TITLE
Suggestion：推广方面的途径

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#33]
Hey，这次是与软件本身无关的内容。
主要是关于偏向海外的一种宣传渠道。

先介绍一个网站：https://alternativeto.net/

这个站点通常是用来查找“同类软件”的，比如说 Mac 平台的 Alfred 很好用，就可以从 AlternativeTo 中关联检索到 PC 平台的 Listary、Wox 等等，又或者是某个软件需要付费，可以在这儿找免费的替代品。
——我自己很多效率软件都是按图索骥从这里查询到的。

刚才搜了一下，Quicker 暂时还没有被收录进 AlternativeTo，个人觉得有时间可以把相关信息放上去，同时 Link 到类似的效率软件中。
这样当很多其他用户查找类似的效率软件时，都可以看到 Quicker，算是比较针对性的投放了。

---

P.S. 顺便说几个我知道的软件站点吧，都是日后（或者现在已经）可以宣传 Quicker 的地方：
* 善用佳软
* 小众软件
* 异次元软件
* 数码荔枝（这是软件商城，之后商业化也可以考虑谈合作）

**Comment by cuiliang** [comment]
谢谢。 现在还只是中文界面，alternativeto还是等软件完善了，做个国际版再发了（好像还有一个https://www.producthunt.com/ 好像也比较闻名），要不老外都不知道干啥用：）

**Comment by Moyf** [comment]
啊哈，刚刚想到的，补充一个，知乎的各种”XX软件好用、XX软件良心“相关问题~
比如这个：https://www.zhihu.com/question/36847530/

不过我看到 Quicker 好像已经建了专栏了哈  (￣▽￣)ノ

**Comment by i5151** [comment]
还是先把软件完善了，起码收费通道完善了，再出国际版、各个语种的版本，之后再到国际上宣传。

另外你说的那几个网站别日后了，已经都宣传完了，我就是看了之后才知道的。

**Comment by i5151** [comment]
那天安装完了之后就推荐给了一个站长，刚到网站看了一下，居然还没加到网址导航中。不行，我得催他一下。

**Comment by i5151** [comment]
> > 还是先把软件完善了……
> 
> 同意。
> 
> > 另外你说的那几个网站别日后了，已经都宣传完了，我就是看了之后才知道的。
> 
> **（或者现在已经）** 这几个字就是用来防杠的。可惜防不胜防啊…… ┑(￣Д ￣)┍
> 每次这种「随便说个建议」的内容都要事先检索确认一遍信息，成本太高了。

只能说明你是杠精，并且对那几个网站并不熟悉，而且建议只是随便说的，那几个网站宣传好几波了，前几次我都没忘心里去，因为不能用中键，最近又看到才试了一下。

**Comment by Moyf** [comment]
> 只能说明你是杠精，并且对那几个网站并不熟悉，而且建议只是随便说的，那几个网站宣传好几波了，前几次我都没忘心里去，因为不能用中键，最近又看到才试了一下。

您说得有道理，祝您生活顺利 ：）

**Comment by cuiliang** [comment]
归档
