### ISSUE TITLE
是否可以增加配置一，配置二，避免两个不通地方使用时，出现冲突

### ISSUE THREAD

**Issue by oooopsr** [cuiliang/Quicker#333]
我希望我在公司是配置一，在家是配置二，两套不同的配置，避免冲突。期待增加此功能。谢谢！

**Comment by cuiliang** [comment]
直接用两个不同的帐号呢？

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/multi-profile
使用主机绑定
