### ISSUE TITLE
FR：键盘动作功能的优化

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#34]
**>> Outline**
我认为 Quicker 在「键盘动作」这个功能模块上优化下去，可以做到”按键精灵“类软件的大部分功能，很期待这部分的加强。
不过目前在设置上，有几个用着不太舒服的点，希望能得到优化。

---

**>> List**
- [ ] 复制粘贴动作序列
- [ ] 导出导入
- [ ] 增加”动作说明“（注释）
- [ ] 按键直接记录（#23 已记录）

---

**>> Details**

> 复制粘贴动作序列

![image](https://user-images.githubusercontent.com/4013062/48928127-e1b73780-ef16-11e8-8b8a-f99d0196cecd.png)

有的时候，动作B可能是在动作A的基础上**截取一部分动作序列**做调整得到的。
这种情况下，希望能直接**多选**并**复制**A中的某一部分动作，并**粘贴**到动作B中。
（Ctrl 单个多选，Shift 连续多选）

> 导出导入

这个其实是针对高阶用户的功能。
举个例子，AHK 和 按键精灵 的动作序列，都可以作为纯数据格式，方便在文本编辑器中做批量处理或更快捷的编辑。

![image](https://user-images.githubusercontent.com/4013062/48928166-3bb7fd00-ef17-11e8-83b7-b7afe992fadc.png)

如果能在动作序列界面提供导入/导出文本数据的功能，对于复杂动作的便携会有很大帮助。

> 按键直接记录（#23 已记录）

这个其实在另一个 Issue 中已经记录了，不再赘述。

> 增加”动作说明“（注释）的选项

这同样是针对比较复杂的动作序列，可以让用户在某一部分动作中插入注释，方便后期的维护和调整。

![image](https://user-images.githubusercontent.com/4013062/48928215-b254fa80-ef17-11e8-8274-e94205a8758d.png)
按键精灵中的注释块。

![image](https://user-images.githubusercontent.com/4013062/48928229-d57faa00-ef17-11e8-894f-b0f3890c68ac.png)
iOS 捷径中的注释。

**Comment by cuiliang** [comment]
done
