### ISSUE TITLE
存储配置出错。未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by yingpwu** [cuiliang/Quicker#350]
存储配置出错。未将对象引用设置到对象的实例。

**Comment by cuiliang** [comment]
版本号是多少？

备份此目录的文件后，清除掉，然后再启动Quicker 看看是否正常。
C:\Users\用户名\AppData\Local\Quicker\data

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
