### ISSUE TITLE
状态存取操作简化：像变量一样处理

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#355]
![image](https://user-images.githubusercontent.com/1972649/54879657-748cc200-4e76-11e9-87bb-5ea4a0f3c60e.png)

**Comment by kanglade** [comment]
还有，词典的操作是不是也可以简化呢，比如
$${词典.键}
是取对应的值呢

**Comment by kanglade** [comment]
还有，
$${clipboard}
是取剪贴板

这时就需要考虑变量的一些「保留字」了

**Comment by cuiliang** [comment]
已增加变量设置：作为状态使用。
