### ISSUE TITLE
导出动作为exe

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#359]
> 导出成独立小程序，发到没装Quicker的电脑上使用。很多人永远也不愿意花一点点时间去了解和使用Quicker这样能带来巨大好处的软件，但是如果能让他们体验到功能的强大，也许会有人去用。

**Comment by WilsonXuwx** [comment]
既然独立导出的能用了，为什么还要装quicker？

**Comment by cuiliang** [comment]
> 既然独立导出的能用了，为什么还要装quicker？

我目前的想法也是感觉一个技术上比较难，一个是不是有什么价值也存疑。 先记录一下，如果后续有什么人补充一些信息再说了，这个是非常远期的事情了。

**Comment by cuiliang** [comment]
估计不太可能了。close
