### ISSUE TITLE
目前每应用的动作数量为4x4,建议增加动作数量为5x5或者更多

### ISSUE THREAD

**Issue by kts168** [cuiliang/Quicker#36]
目前每应用的动作数量为4x4,建议增加动作数量为5x5或者更多

**Comment by i5151** [comment]
刚开始我也纳闷为什么这么设计，但你装上手机客户端之后，就会明白，现在的安排很合理。

至于按钮数量，翻屏比该每页增加数量好多了。界面始终是一致的，按钮数量能到无限。

**Comment by cuiliang** [comment]
整理issues
