### ISSUE TITLE
支持某些个人信息网络同步

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#360]
> 我想到设计一个动作，网络书签，就需要保存数据到服务器；
 还有就是我做的「速记」，是记录一些灵感
比如还有些配置文件，也可以作为同步

**Comment by WilsonXuwx** [comment]
类似网络书签的功能参见我的动作“零食盒子”，目前是利用google drive做跨设备同步。
干脆拓展为“云变量”概念，允许用户拥有一定云空间用于跨设备同步本地变量。

**Comment by kanglade** [comment]
还有比如「网搜」的搜索引擎列表，可以单独保存在「云」上，添加搜索资源只需修改该列表，而不需要更新该动作。

**Comment by cuiliang** [comment]
已增加云状态存取模块。[云状态存取 - Quicker](https://getquicker.net/KC/Help/Doc/clouddata '使用Quicker软件，为您的常用Windows操作建立捷径，更快、更简单的完成工作，让效率触手可及。')
