### ISSUE TITLE
开启毛玻璃效果会导致卡顿

### ISSUE THREAD

**Issue by BIFWIG** [cuiliang/Quicker#365]
体现在拖动任意软件的时候，能明显感觉到 _鼠标卡顿_ ，在亚克力效果没该问题。

**Comment by cuiliang** [comment]
请提供下详细操作系统版本和具体的硬件配置看下。

**Comment by BIFWIG** [comment]
CPU：i7-7700HQ
内存：24G
显卡：GTX-1060

操作系统：Win10专业版
版本号：1809
操作系统版本：17763.316

**Comment by cuiliang** [comment]
是在开启Quicker的毛玻璃效果后，即便不弹开Quicker，也会造成其他软件拖动慢么？ 这硬件配置看起来还挺好的

**Comment by BIFWIG** [comment]
对的，只要启用，即使只在后台运行。

**Comment by cuiliang** [comment]
我在本地两个电脑上测试没有发现这个问题。期待更多朋友反馈后再方便定位。

**Comment by greedyxing** [comment]
也遇到同样的问题，全新安装的quicker，拖动或者放大缩小其他任意窗口（例如chrome），电脑鼠标都会卡顿下。

**Comment by cuiliang** [comment]
@greedyxing 禁用一下透明效果吧，可能透明效果和某些系统不太兼容。

**Comment by cuiliang** [comment]
1903的API改变的后果。已去掉亚克力效果。
