### ISSUE TITLE
FR：Ctrl+左键拖拽快速复制动作

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#37]
![2018-11-26_09-56-45](https://user-images.githubusercontent.com/4013062/48988683-b5432b80-f161-11e8-9c41-99800b81dd40.gif)

如图，当前在拖拽时按住 Ctrl 会出现加号图标，我还以为已经做过这个功能了。
希望新增「默认左键拖拽是移动，Ctrl+左键拖拽是复制」的特性。

适合用在快速创建多个同类动作的时候，例如创建好「打开文件夹A」之后，快速复制粘贴出多份，并设置成打开文件夹B、C、D等等。
会比右键复制、右键粘贴要快一些些。

**Comment by cuiliang** [comment]
Done。
