### ISSUE TITLE
FR：为动作新增一种类型「下拉按钮」

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#38]
![image](https://user-images.githubusercontent.com/4013062/48989090-9d6ca700-f163-11e8-95e1-7e02a6c18256.png)

当前每个按钮都是对应「一个动作」，不知有没有可能新增一种“动作类型”，来打开一个下拉选框，并提供多个“子动作”供选择？
类似下图：
![image](https://user-images.githubusercontent.com/4013062/48989114-bffec000-f163-11e8-80d7-4d02802fc06d.png)

---

不过这样的拓展可能会和当前的思路冲突，或者增加大量的程序冗余性……所以只是尝试性提出建议，仅供参考。

**Comment by cuiliang** [comment]
这个配置起来不方便，执行操作效率也比较低。 其实最初做过这个功能，后来拿掉了。
