### ISSUE TITLE
希望尽快实现添加 crontab  类 schedule 模块

### ISSUE THREAD

**Issue by studyinhub** [cuiliang/Quicker#380]
能否添加 schedule 模块？
希望有些任务能够在后台定时去执行，如果能够参考 Linux 中的 crontab 实现最好了

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/quicker-starter
可以使用外部启动的方式，通过windows计划任务实现。 目前此版本可以在群共享中下载。

**Comment by cuiliang** [comment]
先关了哦，目前通过计划任务定时吧。
