### ISSUE TITLE
悬浮按钮功能改进

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#381]
- [x] 如果修改了原始动作，则更新悬浮按钮的动作定义。
- [x] 切换活动的软件后，自动隐藏和显示悬浮按钮。
- [x] 增加关闭悬浮按钮的托盘菜单；
- [x] 预设固定的大小尺寸
- [ ] 保存和还原悬浮按钮位置

**Comment by kanglade** [comment]
悬浮按钮右键能不能弄个编辑项呢？或者按住Shift点击编辑？这样就可以不用每次打开面板编辑了，很方便

**Comment by cuiliang** [comment]
编译动作的一个问题是编辑后要保存到原来的位置，这个位置目前只有在从面板上编辑的时候才能获得。
后面我再想办法试试看

**Comment by cuiliang** [comment]
归档
