### ISSUE TITLE
如果长时间不调用 , 后台内存泄露严重

### ISSUE THREAD

**Issue by kifast** [cuiliang/Quicker#385]
但只要窗口调用一次后, 内存马上就释放掉了

![image](https://user-images.githubusercontent.com/12144158/55395814-f5ce0e00-5574-11e9-990e-e7b470c5173d.png)

![image](https://user-images.githubusercontent.com/12144158/55395793-e8188880-5574-11e9-8b9a-826343a203eb.png)

**Comment by cuiliang** [comment]
有使用手势软件么？

**Comment by kifast** [comment]
没有手势软件
又测试了一下
应该是与浏览器的鼠标手势冲突
开着浏览器后 , 桌面的文件夹每打开关闭一次就会申请8M+的内存 (文件夹全部关闭后打开)

**Comment by cuiliang** [comment]
@kifast 好的，下一版整个重写了激活面板的模块，可以到时候测试一下是否有改善，之前版本里右键激活有一点问题。
