### ISSUE TITLE
执行AHK脚本会另外弹出窗口导致脚本运行失败

### ISSUE THREAD

**Issue by pysense** [cuiliang/Quicker#393]
我创建了一个执行脚本的动作，脚本类型选择AHK，脚本内容：

```
WinSet, AlwaysOnTop,, A
```

用于将当前活动窗口置顶和取消置顶，我在其中一台电脑上执行正常，脚本能正常工作。

后来在另一台电脑上执行一直不工作，我发现执行时会快速地弹出一个CMD界面，于是修改了脚本内容：

```
WinSet, AlwaysOnTop,, A
Sleep, 5000
```

看到CMD窗口显示的标题是 AutoHotkey 执行文件的路径，而此时处于置顶状态的正是这个CMD窗口，我不明白这个是我系统环境的问题，还是Quicker的问题，有人遇到过这种情况吗？

我的系统是 Windows 10，ahk 文件有关联，可以直接执行。

```
C:\Workspace\tmp>assoc .ahk
.ahk=AutoHotkey

C:\Workspace\tmp>ftype AutoHotkey
AutoHotkey=C:\ProgramData\scoop\apps\autohotkey\1.1.30.01\AutoHotkeyU64.exe "%1" %*
```

**Comment by cuiliang** [comment]
可以重新安装一下ahk试试。 对于未指定程序的脚本，quicker是给系统自己打开的。 类似于在Win+R打开的运行对话框里输入文件的完整路径的效果。

**Comment by pysense** [comment]
谢谢，虽然没搞懂，但确实是环境的问题，AutoHotkey 重装后可以了。
