### ISSUE TITLE
【调查】定时执行动作功能

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#395]
如果你也有这方面的需求，请在这条issue下留言：
大概需要什么样的功能，什么样的需求场景。

**Comment by kanglade** [comment]
**「Quicker 启动时」执行动作**

- 有些软件需要开机时启动，可以通过 Quicker 来控制，而不是系统本身，更易管理，比如 Listary。
- 有些动作需要开机时启动，这时只能在 Quicker 启动后进行，比如「天气预报」，Quicker 启动时即可运行该动作。

**Comment by kanglade** [comment]
**「每隔一定时间」执行动作**

- 适合每隔一段时间执行的动作，比如「备份」、「提醒喝水」、「休息」，方便调整管理，而不是写在动作中。

**Comment by kanglade** [comment]
**「准确时间」执行动作**

- Quicker 内「任务计划程序」，系统「任务计划程序」操作太麻烦，这个可以做简便些。
- 目前计时类动作可以通过倒计时的方式来实现，一来麻烦，二来受关机重启的影响。

**Comment by kanglade** [comment]
**「倒计时」执行动作**

- 可以用来设计「计时器」类动作。

**Comment by kanglade** [comment]
**日程类**

- 每天
- 每周
- 每月
- 每年

**Comment by kanglade** [comment]
- 定时管理最好有专门的界面来管理
- 最好能和动作模块衔接，能通过动作来制定定时任务

**Comment by cuiliang** [comment]
done
