### ISSUE TITLE
需求动作标记跳转功能

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/Quicker#396]
比如下面这样，简单实现鼠标在不同位置点击10次，点完后又能快速跳转到别的地方。

**标记此处为：$$rem**
　　移动到坐标X,Y点击1次
　　赋值 X=X+50
　　赋值 Y=Y+50
　　计数+1

如果计数＜10
　　则
　　　　**跳转到：$$rem**
　　否则    
　　　　**跳转到：$$remX**（跳转去做其他的事情）

**Comment by cuiliang** [comment]
类似于编程语言里的goto语句了，一般不建议使用这种的，会增加复杂度和出错率。 
另外在Quicker里好像也很难实现。
这个例子这样比较合适：

移动到初始位置
重复10次：
-- 相对移动50、50
-- 点击
做其他事情

**Comment by marcusxx** [comment]
对对对，好像是容易出错，暂时不考虑吧
