### ISSUE TITLE
【调查】热键功能支持

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#397]
除了运行动作，如果还希望执行其他功能操作，请在此贴评论。

**Comment by kanglade** [comment]
基本上功能操作都能做成动作，然后通过热键来执行，有些常用的可以考虑单独支持：
- 热键输出文本
- 热键打开文件
- 热键运行脚本
- 热键执行一些系统操作，比如「最小化到系统托盘」

**Comment by marcusxx** [comment]
检测到某个按键可以执行配置好的步骤组，比如说把等待窗口直接取消，换成按下Enter键结束等待，按下Esc键直接结束动作等等。

**Comment by cuiliang** [comment]
主要是考虑一些针对Quicker自身的操作。
其他操作可以先定义好动作再执行动作，这样比较统一，也不用单独开发在快捷键里定义动作的功能。
目前已考虑：
暂停Quicker弹出；
向APP发送启动语音输入指令；

**Comment by kanglade** [comment]
- 终止进行中的动作

**Comment by kanglade** [comment]
- 弹出面板也能设热键
