### ISSUE TITLE
FR：面板操作改善（手动调节排序、跨面板拖拽/复制动作）

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#40]
如题：
![image](https://user-images.githubusercontent.com/4013062/49133760-31816e80-f31c-11e8-8c88-bd6a0422617c.png)

①希望能在面板界面拖拽重新排序 ，或者提供【向上移动】、【向下移动】、【移到顶端】的选项
②希望能在拖拽一个图标到其他面板上时，自动切换到这个面板，方便跨面板进行操作（同时能支持拖拽复制 #37 就更好啦！）

**Comment by cuiliang** [comment]
1）目前是按名称排序的。 这个地方顺序并没有其他的作用，所以调整顺序也没有什么意义的。
2）研究下

**Comment by cuiliang** [comment]
✔
