### ISSUE TITLE
图片查看器改进

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#405]
- [x] 设置等待窗口关闭；
- [x] 初始缩放比例；
- [ ] 右键设置桌面；
- [x] 显示位置；

- 长截图滚动显示
支持图片列表，显示图片时支持滚动翻图
![image](https://user-images.githubusercontent.com/1972649/56181761-8ca0cd00-6041-11e9-8cfb-4b2678462d8f.png)

**Comment by kanglade** [comment]
- [ ] 右键OCR
