### ISSUE TITLE
搜索和执行动作

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#408]
- [ ] 快捷键打开
- [ ] 可以搜索id和标题
- [ ] 点击执行
- [ ] 查看所属面板和位置

**Comment by kanglade** [comment]
建议还可以给动作设置关键词。
想象这么个场景：快捷键激活输入框，键盘敲击「ws」，回车后运行动作「网搜」。十分方便~
类似Listary，可参考。

**Comment by cuiliang** [comment]
done
