### ISSUE TITLE
希望作者可以适配安卓4.x，利用淘汰的老手机做第二键盘

### ISSUE THREAD

**Issue by sml920505** [cuiliang/Quicker#41]
华为mate1 安卓4.4.4安装失败，无法安卓5.0以上系统
锤子安卓7.0运行正常
------------------------
每个人都有大量淘汰老手机，大多停留在4.x阶段，希望作者有余力可以适配，

**Comment by cuiliang** [comment]
暂时没有精力了。 安卓客户端已开源 https://github.com/cuiliang/QuickerAndroid
