### ISSUE TITLE
还原鼠标位置，有时会去到激活面板后动作按钮所在的位置。

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#416]

**Comment by Death-** [comment]
![image](https://user-images.githubusercontent.com/2096408/56087887-ee78ff80-5ea6-11e9-8474-2bd6cf92428e.png)

**Comment by cuiliang** [comment]
更新版本后还出现了么？

**Comment by Death-** [comment]
> 
> 
> 更新版本后还出现了么？

还没测评，录数据任务今天刚刚到手，还没开搞。
一会儿或者明天，看看时间试一下

**Comment by cuiliang** [comment]
> > 更新版本后还出现了么？
> 
> 还没测评，录数据任务今天刚刚到手，还没开搞。
> 一会儿或者明天，看看时间试一下
不急不急

**Comment by Death-** [comment]
> 
> 
> 更新版本后还出现了么？

测试40余次，没有再出现无法还原问题，哈哈
