### ISSUE TITLE
面板管理按钮居中导致误触的问题

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#42]
@cuiliang 

## 问题

当选择右键长按方式激活面板时，在某些应用上可能会导致误触面板管理按钮，并弹出动作面板管理及工具箱窗口。

![image](https://user-images.githubusercontent.com/34429322/49337500-71af5c80-f64e-11e8-9106-d12ef2a24a82.png)

## 原因

因为为了显示当前应用名而挪动了这个按钮，如果当前应用名比较长，那么它很有可能会处于鼠标指针处。令人奇怪的是，这个按钮在面板已激活的情况下是不会右键打开动作面板管理及工具箱窗口的，但是在右键激活面板的情况下可以做到。

## 建议

可以考虑仅显示当前应用的图标或对当前应用名显示长度做限制。

## 环境
Quicker v0.7.4.0
Windows 1809

另外就是面板被我调整了一下大小，不知道是不是有这部分的因素。

![image](https://user-images.githubusercontent.com/34429322/49337554-b4256900-f64f-11e8-8ec6-91572b349b54.png)

**Comment by LonelySteve** [comment]
>这个按钮在面板已激活的情况下是不会右键打开动作面板管理及工具箱窗口的，但是在右键激活面板的情况下可以做到。-

这个可以称为BUG的现象有几率在使用Quicker一段时间后自行消失，但是重启后可再现，非常奇怪。。

是不是可以考虑重新设计一下界面，，面板中部的这些按钮说实话不是能经常用到的

![demo](https://user-images.githubusercontent.com/34429322/49338704-4a618b00-f660-11e8-8274-25352140486a.gif)

**Comment by cuiliang** [comment]
@LonelySteve 
我来讲一下原因。
按钮调小以后，面板就窄了，导致那个面板管理的标正好在鼠标下面。文字宽度之前做了限制，但是面板变小后还是不够。

长按右键方式激活面板，在面板弹出后有2种操作方法：一种松开右键，移动到按钮上再左键单击；另一种是鼠标不松开，移动到一个动作按钮上松开，执行按钮的动作。

两个操作方式的判断依据是，在面板弹出以后，松开右键之前，鼠标是否有移动。 如果没有移动（或者移动少于5个像素），程序判断是第一种方式，这时候不会触发动作。 如果移动了，就会触发动作。

所以，如果弹出后鼠标移动了一些距离，这时候面板管理的按钮正好在指针下面，就会触发动作了。

这里我再想办法优化一下看看。 目前那个面板管理的按钮也没有其他比较合适的放置位置。 只能再缩短一下面板名称文字了。。。

**Comment by cuiliang** [comment]
鼠标不动也会触发。已找到问题，马上修改。

**Comment by cuiliang** [comment]
@LonelySteve 方便的时候可以再试下新的版本是否还会误触发。

**Comment by LonelySteve** [comment]
v7.5.0

**Comment by LonelySteve** [comment]
v7.5.0

现在误触发打开面板管理和工具箱的现象没有了，虽然极端情况（鼠标右键并移动）下还是有可能会触发。

**Comment by LonelySteve** [comment]
@cuiliang 

v7.6.0

![demo](https://user-images.githubusercontent.com/34429322/49413945-94578780-f7ac-11e8-87ef-480f29412afe.gif)

>右键不松开，移动到一个动作按钮上松开，执行按钮的动作。

建议去除这种特性，一般人的常识都是松开右键再点击左键

如果我右键长按的时候，鼠标不小心抖了一下，然后又松开了右键，不就又会误触嘛。。

**Comment by cuiliang** [comment]
嗯，这个地方后期再优化一下，避免触发面板管理。
长按方式不像单击，按完可以马上期待弹出。长按有一个惯性，等他弹出以后，需要一点时间才反应过来，再松开，再单击的话，感觉没用直接挪动到按钮上松开更连贯。你可以尝试几次，看看是否容易习惯 :)

**Comment by LonelySteve** [comment]
@cuiliang 
又捡起了不熟悉的ahk，，，为了演示花了点时间

右键打开窗口后松开右键，再对着面板上某个按钮点击右键会视作执行，而不是弹出上下文菜单

重启Quicker这个现象会消失，一段时间后可能会再现

![demo](https://user-images.githubusercontent.com/34429322/49427145-8b32de80-f7dd-11e8-8110-63972709fe15.gif)
