### ISSUE TITLE
web批量删除共享

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#422]
用于自己临时分享的一些测试动作的删除
![image](https://user-images.githubusercontent.com/2096408/56254957-7ce2c080-60f5-11e9-9106-82426c342e88.png)

**Comment by cuiliang** [comment]
或者过几天自动删除？

**Comment by Death-** [comment]
> 
> 
> 或者过几天自动删除？

有一些还是不想自动删的。比如说有人把公共分享根据新版本做了修改，变成了临时共享。
或者因为频频爆bug改为临时分享。
这些临时分享后续还是有可能再转公开

**Comment by cuiliang** [comment]
暂不考虑了。
