### ISSUE TITLE
动作按钮名称下方显示已设置的快捷键

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#425]
![image](https://user-images.githubusercontent.com/2096408/56356700-3469f680-620c-11e9-8c13-643b23252f65.png)
如图，字体可以设置稍小一点。
考虑到有些人喜欢简洁版本，可以再多考虑多一个设置，是否于面板显示按钮快捷键

**Comment by Death-** [comment]
或者图标右下角出现一个绿色点，表明设置了快捷键。
然后类似备注一样，鼠标移过去后显示具体快捷键名称。

**Comment by cuiliang** [comment]
考虑到全局快捷键绑定的动作比较少，开发起来又比较麻烦，所以不做了。
