### ISSUE TITLE
外部启动使用动作名称而不是id

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#426]
传递url scheme是这样的：shortcuts://run-shortcut?name=扫码
「捷径」通过URL Scheme调用动作是用的name属性，我记得之前id也可以的。我想它这样做是不是有一定的考虑，比较容易实现动作套动作？不用担心下载动作的id不一致问题？而且分享起来是不是也容易些呢，比如自行下载相关动作就行了，不用考虑id问题。

**Comment by Death-** [comment]
可是同名的问题如何解决呢

**Comment by cuiliang** [comment]
> 可是同名的问题如何解决呢

这样就不能重名了

**Comment by 1090197965** [comment]
不太科学, 因为这会让所有用户分享动作的时候不能同名, 这就很蛋疼, 而且有时候新建懒得起名咋办

**Comment by cuiliang** [comment]
1.4.17 支持。`quicker:runaction:记事本操作集`

**Comment by kanglade** [comment]
传参也顺道支持一下呗
