### ISSUE TITLE
处理大动作的共享问题

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#427]
一个1M有1000个人安装就会有1G的数据库占用，对性能和资源影响很大。

暂时停用此类分享；
限制分享动作的大小；
限制同步面板的文件大小；
使用只读方式共享存储：只在服务器保存一个实例，安装的人只能读取不能编辑动作；（按动作尺寸，1k以下的直接复制，超过尺寸的使用引用方式）

**Comment by kanglade** [comment]
1. 动作作者应该非只读吧
2. 全部用引用，统一起来会不会好些

**Comment by cuiliang** [comment]
使用引用模式保存安装的共享动作；大动作禁止本地编辑；其他动作编辑时自动更新为普通模式；禁止分享未修改的共享动作；
