### ISSUE TITLE
无法建立快捷打开onedrive中的文件夹

### ISSUE THREAD

**Issue by Holaplace** [cuiliang/Quicker#43]
下载OneDrive之后，将及时备份的文件拖入其中同步，但是发现不能建立快捷方式到onedrive中的同步文件夹，quicker显示系统找不到指定的文件夹

**Comment by Holaplace** [comment]
对的，是按照您的步骤。但还是出错
![gif](https://user-images.githubusercontent.com/45121260/49348042-f39a9680-f6dd-11e8-9f94-b5ac2b7b88eb.gif)

**Comment by cuiliang** [comment]
哦，知道了。 路径里有一些特殊字符，我调整一下处理方法试试。 目前的话，可以在路径两头上增加英文半角引号试一下。

**Comment by Holaplace** [comment]
添加英文单引号或双引号都还不行。
![gif](https://user-images.githubusercontent.com/45121260/49348229-3741d000-f6df-11e8-95d7-2105a462447f.gif)

**Comment by cuiliang** [comment]
好的，了解了，我这边处理一下。 谢谢~

**Comment by Holaplace** [comment]
希望Quicker越做越好，如果您处理好了，麻烦回复一下，谢谢了

**Comment by cuiliang** [comment]
没问题的

**Comment by cuiliang** [comment]
已修复好，过两天版本更新时一同发布。谢谢~

**Comment by Holaplace** [comment]
点赞，谢谢

**Comment by cuiliang** [comment]
@Holaplace 已发布0.7.6版本，可以下载测试一下。

**Comment by Holaplace** [comment]
已经下载最新版本，恢复正常了，谢谢
