### ISSUE TITLE
【FR】共享动作页面：更新历史位置调整

### ISSUE THREAD

**Issue by WilsonXuwx** [cuiliang/Quicker#433]
**需求描述**
更新历史目前再评论同级的tab页中，部分up主手动贴到正文。
放在正文方便用户确认更新内容选择是否更新。

**描述你想要的解决方案**
将更新历史放到正文最下方，如果太长，折叠到仅显示最近3次。

**描述您考虑过的替代方案**
页面右侧也不错。

 **其他上下文**
N/A。

**Comment by cuiliang** [comment]
正文中增加了最近3次的更新记录。

**Comment by WilsonXuwx** [comment]
nice
