### ISSUE TITLE
【FR】UI：面板管理按钮与工具箱按钮部分功能重复

### ISSUE THREAD

**Issue by WilsonXuwx** [cuiliang/Quicker#434]
**需求描述**
面板管理按钮按下同时弹出面板管理与工具箱，单独设置工具箱按钮是否有必要？

**描述你想要的解决方案**
建议可以用面板管理按钮替换掉工具箱按钮，给面板名称显示腾出一个字的位置。

**描述您考虑过的替代方案**
在设置中可以选择隐藏工具箱按钮（与复制粘贴按钮一样）

 **其他上下文**
<img src='https://i.loli.net/2019/04/28/5cc559247cefb.png' title='TIM.png' />

**Comment by cuiliang** [comment]
归档。现在的面板管理按钮已经取消了。点击文字实现相同功能。
