### ISSUE TITLE
【FR】添加隐藏托盘图标功能

### ISSUE THREAD

**Issue by DivinerHJF** [cuiliang/Quicker#437]
**需求描述**
反正是开机启动一直使用，所以想隐藏任务栏的托盘图标，图个清静

**描述你想要的解决方案**
在设置里添加隐藏托盘图标的选项

**Comment by cuiliang** [comment]
因为有些功能是在托盘图标里的，有时会用到。
建议使用这种方式隐藏。
![隐藏托盘图标](https://user-images.githubusercontent.com/1972649/56942498-a962f780-6b4d-11e9-81a2-185a6c98a652.gif)
