### ISSUE TITLE
【BUG】右键长按激活导致右键失灵

### ISSUE THREAD

**Issue by llconan** [cuiliang/Quicker#438]
**描述BUG**
对bug的清晰简洁描述。
更新版本之后，之前的右键长按激活200ms，在开关几次时会导致右键间歇失灵。

**重现步骤**
1.右键长按激活，200ms
2.打开，并关闭窗口
3.右键会暂时不能用，无法打开右键菜单，要移动一段距离鼠标，或者切换窗口才恢复

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 17763
 - Quicker版本：0.11.3.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
我这里没有能重现。右键长按激活面板后是通过什么方式关闭面板？

**Comment by llconan** [comment]
点击其他没有面板的地方。



李剑锐 博士研究生
上海交通大学 制冷与低温工程研究所
上海市闵行区东川路800号，上海，200240
Email：llconan@126.com
电话：15216712328
 
 
发件人： CuiLiang
发送时间： 2019-05-02 09:10
收件人： cuiliang/Quicker
抄送： llconan; Author
主题： Re: [cuiliang/Quicker] 【BUG】右键长按激活导致右键失灵 (#438)
我这里没有能重现。右键长按激活面板后是通过什么方式关闭面板？

**Comment by kanglade** [comment]
「长按右键」选项勾上时，弹出面板后（无论键盘弹出还是右键弹出），在面板范围之外点击右键就会失灵，必须得关闭面板才行，不知道算不算BUG。还有就是，在开机后的一小段时间内，鼠标右键失灵（此时Quicker面板没有打开），比如不能在桌面右键刷新，看是不是因为类似的原因。

**Comment by cuiliang** [comment]
> 「长按右键」选项勾上时，弹出面板后（无论键盘弹出还是右键弹出），在面板范围之外点击右键就会失灵，必须得关闭面板才行，不知道算不算BUG。还有就是，在开机后的一小段时间内，鼠标右键失灵（此时Quicker面板没有打开），比如不能在桌面右键刷新，看是不是因为类似的原因。

弹出时右键失效我也发现了。 其他时候右键这个还需要再调查一下看看什么情况出。

**Comment by cuiliang** [comment]
@llconan 方便把激活面板设置的创建截图一下么？

**Comment by llconan** [comment]
在 2019-05-04 19:51:28，"CuiLiang" <notifications@github.com> 写道：


@llconan 方便把激活面板设置的创建截图一下么？

**Comment by llconan** [comment]
https://s2.ax1x.com/2019/05/04/EdsYOH.png

> 在 2019-05-04 19:51:28，"CuiLiang" <notifications@github.com> 写道： @llconan 方便把激活面板设置的创建截图一下么？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

https://s2.ax1x.com/2019/05/04/EdsYOH.png

**Comment by cuiliang** [comment]
@llconan 请从群文件或 https://getquicker.net/Download 下载0.11.5版本测试看看

**Comment by cuiliang** [comment]
@llconan 更新版本后问题还复现么？

**Comment by llconan** [comment]
暂时没出现了

**Comment by cuiliang** [comment]
好的
