### ISSUE TITLE
【BUG】编辑已有动作时无法保存

### ISSUE THREAD

**Issue by AndyZhang88** [cuiliang/Quicker#439]
**描述BUG**
编辑已有动作后保存，但是实际动作没有变化，无法保存

**重现步骤**
1.在chrome网页中键点开quicker
2.编辑动作
3.保存
4.再次编辑，动作内容无变化

**相关截图**
有

**环境信息:**
 - 操作系统版本：windows 10 家庭中文版
 - Quicker版本：0.10.7.0

**附加信息**
编辑的动作：
https://getquicker.net/sharedaction?code=4af51de4-6e39-4747-fe7e-08d64e214827
编辑的内容：
把Ctrl+V改为Ctrl+C
![Snipaste_2019-04-30_23-26-11](https://user-images.githubusercontent.com/50144679/56973424-6893ce80-6b9f-11e9-8a86-31a2f3f230ee.jpg)

**Comment by Death-** [comment]
最新版本的更新中：
fix：旧版组合动作不能编辑的问题；

https://getquicker.net/Forum/ViewTopic/486

试着更新版本看看

**Comment by cuiliang** [comment]
0.11.3版本中已修复。 如果还有问题，请再reopen这条issue。

**Comment by AndyZhang88** [comment]
> 0.11.3版本中已修复。 如果还有问题，请再reopen这条issue。

已经升级到0.11.3.0版本，还是无法保存。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/57186408-3375dc00-6f11-11e9-950d-9e12bf19922e.png)

这里的文字需要手工改掉，是动作名称。再试下看看

**Comment by AndyZhang88** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/57186408-3375dc00-6f11-11e9-950d-9e12bf19922e.png)
> 
> 这里的文字需要手工改掉，是动作名称。再试下看看

感谢，和你说的是一样的。
