### ISSUE TITLE
【FR】用类似录制宏的方式新建动作

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#440]
**需求描述**
对于有简单编程需求者，或动作设计包含大量按键操作者，
用录制宏可能是个好的选择。

**描述你想要的解决方案**
记录键盘输入、记录鼠标输入、记录每两次鼠标操作间的位移、记录延时时间，
然后生成为组合动作。
然后可以批量改延时时间更好。

**描述您考虑过的替代方案**
暂无

 **其他上下文**
这样对新手其实挺友好的，容易上手。
但是设计这个估计需要大量工作量，可以在后期考虑设计，有利于软件上手和推广。

**Comment by cuiliang** [comment]
已支持录制。
