### ISSUE TITLE
【BUG】无法加入黑名单

### ISSUE THREAD

**Issue by shatuhi** [cuiliang/Quicker#441]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1. 无法使用拖拽窗口增加游戏程序至黑名单。
2. 手动添加后，无法生效。
3.  激活窗口后，第二部份快捷功能显示的是上一个软件的快捷功能。

**相关截图**
![20190503001538](https://user-images.githubusercontent.com/50195708/57090135-aed06580-6d38-11e9-908b-3d8fb85b4e94.png)

**环境信息:**
 - 操作系统版本：win10教育版1809
 - Quicker版本：0.11.3.0

**附加信息**
游戏安装包：http://cache.dl.fantasy-earth.com/fezero/client/FEZ_setup.zip

**Comment by cuiliang** [comment]
这个游戏在我电脑上无法安装，界面都显示乱码。是只有这一个无法添加么？ 别的软件正常么？ 游戏运行使用管理员身份了么？

**Comment by shatuhi** [comment]
> 这个游戏在我电脑上无法安装，界面都显示乱码。是只有这一个无法添加么？ 别的软件正常么？ 游戏运行使用管理员身份了么？

目前其他软件正常添加或使用。另外，这个游戏是日文的，所以需要系统支援日语或者用Locale转译。

**Comment by cuiliang** [comment]
抱歉哦，这个问题后来一直没有办法验证。 
据了解有不少软件会有特别的措施隐藏进程名。
先关了，如果还需处理，请再reopen
