### ISSUE TITLE
【FR】词典值的批量设置

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#442]
**需求描述**
目前要设置词典值相对比较麻烦，键与值必须一个个录入。比较麻烦。
同样的，在需要做批量修改的时候也比较痛苦，需要一个个点开来设置。

**描述你想要的解决方案**
是否可以和用户选择步骤中类似，以 | 符号间隔开来。然后实现批量输入。
如：
A|状态很好
B|状态一般
C|状态较差
D|状态很差
一次输入设置4个键值对，在需要修改的时候，也只需要点开一个步骤编辑就可以了。

**描述您考虑过的替代方案**
暂无

 **其他上下文**
![image](https://user-images.githubusercontent.com/2096408/57132129-27830080-6dd1-11e9-88c0-06731edfa2cd.png)

**Comment by cuiliang** [comment]
使用赋值模块应该可以批量的。试下看看。
词典变量默认值可以使用两种方式写：
A，简单模式：每行一个键值对， 格式为  Key:Value
B, Json数据：以  “json:” 开始，后面接着写json格式的内容。

**Comment by Death-** [comment]
> 使用赋值模块应该可以批量的。试下看看。
> 词典变量默认值可以使用两种方式写：
> A，简单模式：每行一个键值对， 格式为 Key:Value
> B, Json数据：以 “json:” 开始，后面接着写json格式的内容。

原来文档有，没好好看，thx
（好丢脸哈哈）
