### ISSUE TITLE
【BUG】动作反馈的文字输入区域不能输入

### ISSUE THREAD

**Issue by 0000zjn** [cuiliang/Quicker#443]
**描述BUG**
进行动作反馈，选择不正常时，会出现“请描述您的问题”的输入框，此输入框无法做任何输入包括粘贴文字。

**重现步骤**
1.首次运行某个操作后自动弹出动作反馈/右键某操作进入动作反馈
2.选择不正常
3.QQ拼音尝试输入，输入失败
4.英语-美式键盘输入，输入失败

**相关截图**
![image](https://user-images.githubusercontent.com/29851115/57177532-3502be00-6e97-11e9-9de2-136cee976277.png)

**环境信息:**
 - 操作系统版本：windows10 1809
 - Quicker版本：0.11.3.0

**附加信息**
无

**Comment by cuiliang** [comment]
感谢反馈！

**Comment by cuiliang** [comment]
已修复。 可以从下载页面 下载快速通道 0.11.5版本修复。
