### ISSUE TITLE
【FR】组合动作模块：捕获热键

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#444]
**需求描述**
在动作中捕获按键组合，并根据组合执行步骤（类似于“用户选择”模块）。适用于某些需要频繁使用键盘操作的情况。

**描述你想要的解决方案**
暂无

**描述您考虑过的替代方案**
AHK

 **其他上下文**

比如有这么个软件：NeatMouse
https://neatdecisions.com/products/neatmouse/
主要功能是用键盘来移动鼠标，可以让鼠标实现像素级的移动，搞设计的朋友可能会比较有用。
开启即可用方向键代替鼠标移动，关闭后释放热键。
如果Quicker有「捕获热键」模块的话，就完全可以替代这个软件了。
如果要实现类似的功能，恐怕只能用这个脑洞模块了。

比如连续复制那个，可以设置热键，粘贴是时候Ctrl+1粘贴第一个复制的内容，Ctrl+3粘贴第三个复制的内容

热键要动作一直运行，这对于动作来说，可能并不合适，因为一般动作都是临时性的

**Comment by kanglade** [comment]
可以做这么个动作「热键启动」，这个动作启动后常驻后台。然后，通过动作内热键的方式启动不同的操作，比如F1启动「动作1」，F2启动「动作2」，F3打开「某个网站」，F4打开记事本等等。有时又需要这些常用的热键，这时关闭该「热键启动」即可恢复正常的热键。

**Comment by marcusxx** [comment]
我感觉可以用多个流程、或者子动作的方式实现。
1、一个动作有N个流程，检测到某按键可以执行别的流程。
2、表面上看起来是一个动作，其实是多个动作的合集，检测到某按键时停止当前动作，运行另一个子动作。

**Comment by Death-** [comment]
如果可以捕获热键，那几个基于ahk的动作，都可以直接通过qk实现了
比如笔记本键盘中，对数字小键盘映射。

**Comment by 1090197965** [comment]
我觉得可以类似于 <等待剪贴板内容改变> 那个模块一样, 捕获热键也是类似

1. 设置默认等待时间, 在等待时间内会监控键盘录入, 也会返回值 [是否按下按键]
2. 在等待期间按下按键, 模块结束, 返回 [按下内容], 以及 [是否按下按键]
      (可以参考js, 有几个属性, 是否按下ctrl, 是否按下alt等)

这样只要写个循环, 然后再写一个switch, 按下不同按键就能执行不同动作, 达到目的

**Comment by kanglade** [comment]
场景：「添加成对符」动作运行后，使用不同热键来调用不同的成对符。

**Comment by kanglade** [comment]
在PS中使用，可以做一个针对PS捕获热键的动作，将复杂的热键简化，启动动作后生效，当PS使用完毕以后，中止该动作，对应的热键也会失效。

**Comment by kanglade** [comment]
感觉应该做成一个新动作类型：热键动作
编辑进入该动作后，就会有类似swich的结构。
运行该动作后，就会驻在后台监控按键。

**Comment by kanglade** [comment]
「征用热键执行动作步骤」这么理解可能比较合适

**Comment by kanglade** [comment]
「鼠标输入」里面虽然有「获取鼠标位置」的功能，但怎么取体验都不太好，如果能配合按键捕获，鼠标指向目标位置后，按下热键即可捕获到坐标，这样的解决方式才比较完美，并且动作结束后释放掉热键资源。

**Comment by cuiliang** [comment]
这个主要使用等待按键模块实现了。还有获取按键状态...
