### ISSUE TITLE
【FR】环形菜单操作方式

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#446]
**需求描述**
快速执行最常用的动作。
按下鼠标某个键后，朝某个方向快速移动即可。可以按角度分8个方向。
相对于手势软件的优点是不需要记忆。
主要问题是怎么和面板方式配合。

**描述你想要的解决方案**
暂无

**描述您考虑过的替代方案**
暂无

 **其他上下文**
参考：
https://getquicker.net/Forum/ViewTopic/188

https://jingyan.baidu.com/article/454316ab6a6a01f7a7c03aa5.html

![image](https://user-images.githubusercontent.com/1972649/57187167-d6ccee00-6f1d-11e9-9073-dcae78724258.png)

![image](https://user-images.githubusercontent.com/1972649/57187354-b56d0180-6f1f-11e9-82e5-588386832d61.png)

**Comment by kanglade** [comment]
想法：右键双击激活环形菜单，按方向滑动即可，不必很精确
