### ISSUE TITLE
【FR】支持自定义面板按钮的行列个数，隐藏全局面板等建议

### ISSUE THREAD

**Issue by pppscn** [cuiliang/Quicker#447]
**需求描述**
1、支持自定义面板按钮的行列个数
支持M*N定义面板的按钮个数

2、隐藏全局面板
目前已经有了强大的自动识别当前环境弹出不同的动过面板的功能，全局面板并不太需要，可以考虑允许用户隐藏（鉴于强制保留官网链接宣传的目的，建议此功能作为收费版功能）

3、隐藏系统托盘图标
同样是作为配置项，毕竟很少用到系统托盘的图标，可以在编辑模式下显示

4、编辑模式支持直接拖放，增加启动软件或目录等动作按钮
目前亮哥是说优先级的问题导致的，建议编辑时启动一个程序副本（或者编辑独立出来），优先级没那么高的

**Comment by 1090197965** [comment]
感觉吧, 需求1以后应该是会有的, 需求2可以和1合并, 全局面板可以设置行列数, 直接设置0行
需求3估计不会搞, 因为万一程序卡了或者其他情况, 可以用托盘关闭, 或者看托盘是否还在
需求4我也想要, 直接拖放链接,目录或者应用还是好用

**Comment by hewittchoi** [comment]
全局面板才是最需要的

**Comment by cuiliang** [comment]
归档

**Comment by kulkatt** [comment]
为什么还没有自定义面板动作数量这个功能？4x3的面板真不够用
