### ISSUE TITLE
【FR】web中，带文字反馈自动生成到回复中

### ISSUE THREAD

**Issue by Death-** [cuiliang/Quicker#448]
**需求描述**
当动作失败时，提交的反馈意见有的时候信息不足。

**描述你想要的解决方案**
脑洞一：把带文字反馈自动生成到回复中，可以方便动作作者与使用者沟通。
脑洞二：直接在反馈界面的网页中，特定留言后，有一个按钮是「引用反馈内容并回复」

**描述您考虑过的替代方案**
若有私信方式也可。

 **其他上下文**
暂无

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
