### ISSUE TITLE
【Bug】移动文件夹功能失效

### ISSUE THREAD

**Issue by NEPDream** [cuiliang/Quicker#449]
**描述BUG**
文件和目录操作功能中的移动或重命名文件（文件夹）功能在移动文件夹时候失效

**重现步骤**
1.尝试使用该功能移动任何文件夹都会出现文件夹已存在的错误提示

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10.pro
 - Quicker版本：0.11.3.0

**附加信息**
很好复现的问题，不需要过多描述了

**Comment by cuiliang** [comment]
测试正常，请分享一下动作我这里试试。

**Comment by NEPDream** [comment]
> 测试正常，请分享一下动作我这里试试。

就比如这个脚本，你看下脚本下面的评论和截图就明白了
https://getquicker.net/sharedaction?code=6aaceddc-6917-41cf-721a-08d697a27161
那个脚本失效，我测试就是那个功能的原因，所以我后来写了新的
https://getquicker.net/sharedaction?code=6e5c3712-74b0-45b7-53f4-08d6d1932d22
复现很容易，用“移动文件（或文件夹）”功能去移动一个文件夹就会提示出错了，就是评论里面的截图那样

**Comment by NEPDream** [comment]
我猜测可能跟win10的系统更新有关，你们可以尝试在最新的win10系统里面就能复现，我以为能很容易复现问题呢。

**Comment by cuiliang** [comment]
我查了一下，是因为多次复制到相同目录的问题。 在复制模块里有一个选项是“覆盖已有”，如果没有选择，下次复制到相同路径的时候，因为路径已经存在，就会报告这个错误。
可以选中一下这个选项试试。
![image](https://user-images.githubusercontent.com/1972649/57341010-1e948500-716b-11e9-89f5-c2b821fd24ce.png)

**Comment by NEPDream** [comment]
> 我查了一下，是因为多次复制到相同目录的问题。 在复制模块里有一个选项是“覆盖已有”，如果没有选择，下次复制到相同路径的时候，因为路径已经存在，就会报告这个错误。
> 可以选中一下这个选项试试。
> 可能需要调整一下，如果是文件夹的话，不判断目标是否存在。
> ![image](https://user-images.githubusercontent.com/1972649/57341010-1e948500-716b-11e9-89f5-c2b821fd24ce.png)

已经测试，确实是这个问题，但是说实话，这个逻辑和语言表达确实有点奇怪，希望可以在后续修改，避免其他人写脚本时候产生同样误解

**Comment by NEPDream** [comment]
> 我查了一下，是因为多次复制到相同目录的问题。 在复制模块里有一个选项是“覆盖已有”，如果没有选择，下次复制到相同路径的时候，因为路径已经存在，就会报告这个错误。
> 可以选中一下这个选项试试。
> 可能需要调整一下，如果是文件夹的话，不判断目标是否存在。
> ![image](https://user-images.githubusercontent.com/1972649/57341010-1e948500-716b-11e9-89f5-c2b821fd24ce.png)

还有个问题，他这个脚本用的是复制，所以勾上覆盖就解决了，但是我希望使用“移动”，会出现一样的问题，而且“移动文件夹”功能下没有覆盖选项，所以，移动模式下暂时出错无法解决

**Comment by cuiliang** [comment]
移动文件夹是不支持目录路径已经存在的情况的，存在就会报错中止。可以对源目录下的每个文件进行移动操作到目标文件夹下。

**Comment by NEPDream** [comment]
> 移动文件夹是不支持目录路径已经存在的情况的，存在就会报错中止。可以对源目录下的每个文件进行移动操作到目标文件夹下。

明白了，我总算弄懂这个逻辑了233333你们可以考虑优化一下说明，这也太难理解了

**Comment by cuiliang** [comment]
> > 移动文件夹是不支持目录路径已经存在的情况的，存在就会报错中止。可以对源目录下的每个文件进行移动操作到目标文件夹下。
> 
> 明白了，我总算弄懂这个逻辑了233333你们可以考虑优化一下说明，这也太难理解了

嗯嗯，还没时间写文档😂，后面会集中补一下
