### ISSUE TITLE
主窗口不能唤出

### ISSUE THREAD

**Issue by hewittchoi** [cuiliang/Quicker#450]
**描述BUG**
主窗口不能唤出

**重现步骤**
1.就是用着用着quicker突然不能唤出，更新到0.11.5.0才出现过的问题
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：0.11.5.0

**附加信息**

**Comment by cuiliang** [comment]
目前有一个bug，如果前一个动作没有执行完，后面的动作使用查看图片，在关闭图片的时候会死锁。 你有用使用查看图片操作的动作了么？

**Comment by cuiliang** [comment]
https://getquicker.net/Download  刚发了0.11.6版本，可以下载更新一下试试还会不会出。

**Comment by Forgetmyfairy** [comment]
同样遇到了这个问题，2019.5.9 检查版本更新为最新版本0.11.3.0

**Comment by cuiliang** [comment]
> 同样遇到了这个问题，2019.5.9 检查版本更新为最新版本0.11.3.0

下载页面里有0.11.6 快速通道版本可以试试

**Comment by cuiliang** [comment]
已更新0.11.7版本，请安装试试还会不会复现。 我先把这个case关掉了，如果还有问题再打开吧。
