### ISSUE TITLE
默认面板一直在重复创建，而且无法删除

### ISSUE THREAD

**Issue by checknao** [cuiliang/Quicker#451]
**描述BUG**
出现好多默认面板，而且设置之后第一个默认面板重启之后会还原

**重现步骤**
1.把其他面板的托到默认面板
2.重启电脑

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/11040904/57420369-df813500-7239-11e9-9890-d4c4c907508d.png)

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：0.11.3.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
退出帐号重新登录一下试试。 如果还不行，请把帐号和密码QQ或微博私信给我一下。https://weibo.com/cuiliang123

**Comment by checknao** [comment]
> 退出帐号重新登录一下试试。 如果还不行，请把帐号和密码QQ或微博私信给我一下。退出帐号：
> 在软件菜单里选择‘关闭并退出当前帐号’
> https://weibo.com/cuiliang123

重新登陆后正常啦
