### ISSUE TITLE
两台电脑下，无法提供不同的设置需求

### ISSUE THREAD

**Issue by 0000zjn** [cuiliang/Quicker#452]
**需求描述**
在两台电脑安装了Quicker，由于鼠标不同，我在一台电脑上设置了“弹出面板-激活方式”为滚轮左击，但另一台电脑的鼠标无此功能，所以我进行了不同的设置。但软件会在联网时自动同步，导致我不能同时使用不同的设置。

**描述你想要的解决方案**
提供自动/手动进行同步的选项，并提供手动上传/下载设置的按钮。

**描述您考虑过的替代方案**
部分与环境（包括硬件和工作环境）设置不进行同步，如弹出面板页。

**Comment by cuiliang** [comment]
使用一种两个电脑都能通用的方式，比如“画圈激活”等。
使用相同的方式在不同的电脑上工作，才是更高效的。
