### ISSUE TITLE
高鼠标回报率下拖拽窗口卡顿

### ISSUE THREAD

**Issue by z497519907** [cuiliang/Quicker#455]
**需求描述**
在4K屏幕,1000鼠标回报率下拖到节目会很卡
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以关掉窗口模糊选项试试。

**Comment by z497519907** [comment]
> 可以关掉窗口模糊选项试试。

完美解决,3Q
