### ISSUE TITLE
默认动作：新增一个打开Quicker帮助文档的动作

### ISSUE THREAD

**Issue by WilsonXuwx** [cuiliang/Quicker#456]
**需求描述**
用户找帮助文档不方便。

**描述你想要的解决方案**
新安装Quicker后，默认动作中新增一个打开Quciker帮助文档的动作。

**描述您考虑过的替代方案**
或者在主界面顶部新增一个按钮。

 **其他上下文**
https://getquicker.net/sharedaction?code=0e8f178b-03c5-4b71-d978-08d6d8115a6a

**Comment by cuiliang** [comment]
嗯，已经增加好了，忘了更新了😂
