### ISSUE TITLE
惯用手是右手时无法同步

### ISSUE THREAD

**Issue by LongSang01** [cuiliang/Quicker#457]
平板电脑设置为惯用右手时无法点击同步按钮

shell:::{80F3F1D5-FECA-45F3-BC32-752C152E456E}

![image](https://user-images.githubusercontent.com/49708391/57771884-a3246c00-7746-11e9-9eb8-3bd55a7d4336.png)

![image](https://user-images.githubusercontent.com/49708391/57771947-cea75680-7746-11e9-85cf-fdeb710a4d06.png)

必须改为惯用左手才能点击同步按钮

因为安装了数位板驱动所以默认手设置的是右手

**Comment by cuiliang** [comment]
本地测试正常， 不知道是不是和别的因素有关。 Win10 版本号是多少？ 我是1809的。
![image](https://user-images.githubusercontent.com/1972649/57894924-93f30a80-787b-11e9-8dff-e729c421347f.png)

**Comment by LongSang01** [comment]
我是win10 1903

**Comment by cuiliang** [comment]
> 我是win10 1903

1903还有问题么？ 刚刚测试也正常。

![image](https://user-images.githubusercontent.com/1972649/64528725-c9949580-d33b-11e9-88f0-d723990349ed.png)
