### ISSUE TITLE
电脑客户端连接到app是弹出no route to host 报错，尝试过添加端口，甚至关闭防火墙，依然无效。

### ISSUE THREAD

**Issue by richardfangf** [cuiliang/Quicker#459]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
确保在同一个网段里。有的wifi会限制设备互联。参考 https://www.yuque.com/quicker/help/mobile-app

**Comment by richardfangf** [comment]
试过了，但是还是没有用。手机和电脑都是连接在同一个无线网络下。

**Comment by cuiliang** [comment]
PC端已启动了吧？ 看一下电脑和手机的IP分别是多少，从电脑上ping一下手机ip看看是不是可以通。
参考：https://jingyan.baidu.com/article/154b463155c2b428ca8f4181.html

**Comment by richardfangf** [comment]
> PC端已启动了吧？ 看一下电脑和手机的IP分别是多少，从电脑上ping一下手机ip看看是不是可以通。
> 参考：https://jingyan.baidu.com/article/154b463155c2b428ca8f4181.html

手机的ip和电脑的ip是一样的，但是连接wifi的ip是不同的。用电脑ping手机wifi的ip显示超时，ping那个相同的ip显示无法访问主机，？？

**Comment by cuiliang** [comment]
同一个局域网的话，两个设备的IP肯定是不同的。 应该是网关相同，ip不同，但是ip的前3个数字通常是相同的。

**Comment by richardfangf** [comment]
> 同一个局域网的话，两个设备的IP肯定是不同的。 应该是网关相同，ip不同，但是ip的前3个数字通常是相同的。

那该怎么办呢

**Comment by richardfangf** [comment]
> 同一个局域网的话，两个设备的IP肯定是不同的。 应该是网关相同，ip不同，但是ip的前3个数字通常是相同的。

我使用电脑去ping手机的ip地址，但是显示无法访问目标主机

**Comment by cuiliang** [comment]
两个IP分别是多少？

**Comment by richardfangf** [comment]
电脑是192.168.31.231
手机是192.168.31.36

**Comment by cuiliang** [comment]
确认电脑防火墙关闭。PC端显示二维码的时候，如果有多个ip，选择使用这个31.231的ip，手机扫码连接试试。
如果还不行，有可能是wifi禁止设备互通了。

**Comment by richardfangf** [comment]
防火墙全部关闭后，pc端还是只显示31.231这个一个ip，没有多的ip。仍然失败。

**Comment by cuiliang** [comment]
那应该是网络的限制了。
