### ISSUE TITLE
右键菜单展开菜单无法使用

### ISSUE THREAD

**Issue by LeMonThELord** [cuiliang/Quicker#461]
**描述BUG**
右键菜单展开菜单无法使用

**重现步骤**
1. 软件右键出现一级菜单
2. 鼠标移至可展开处
3. 展开菜单出现在左侧
4. 鼠标移出展开处时展开菜单消失

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/39843121/57819734-0b1d9580-77cd-11e9-9a51-4046f375c73e.png)
![image](https://user-images.githubusercontent.com/39843121/57819803-5b94f300-77cd-11e9-91d5-853ba85c5d1d.png)

**环境信息:**
 - 操作系统版本：Win10 64bit
 - Quicker版本：0.11.7.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Windows10哪个版本？ 我这里测试正常，win10 1809。

**Comment by cuiliang** [comment]
另外，是否鼠标左右键倒换了？像这个一样 #457

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
