### ISSUE TITLE
无法获取选中的文本

### ISSUE THREAD

**Issue by Aincvy** [cuiliang/Quicker#463]
**描述BUG**
在任何情况都下都提示 无法获取选中的文本
使用的是最新版本的

**重现步骤**
1. 就选择文本然后用个功能就提示了。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/8110347/57832914-5646a100-77eb-11e9-880b-cea0826c7728.png)

**环境信息:**
 - 操作系统版本： WIN10
 - Quicker版本：0.11.7.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
卸载360，或加入白名单并且关闭驱动防护。

**Comment by Aincvy** [comment]
并没有安装360，  只有win10的  de什么的，这个有影响吗


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: CuiLiang <notifications@github.com>
发送时间: 2019年5月17日 07:39
收件人: cuiliang/Quicker <Quicker@noreply.github.com>
抄送: The World <474551869@qq.com>, Author <author@noreply.github.com>
主题: 回复：[cuiliang/Quicker] 无法获取选中的文本 (#463)




卸载360，或加入白名单并且关闭驱动防护。

**Comment by cuiliang** [comment]
> 并没有安装360， 只有win10的 de什么的，这个有影响吗 发自我的iPhone
Win10的应该没有影响。 这个获文本的方式是发送ctrl+c后读取剪贴板。 在记事本或别的软件里能获取到么？

**Comment by Aincvy** [comment]
不在家，我过几天回家后试试看


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: CuiLiang <notifications@github.com>
发送时间: 2019年5月17日 07:53
收件人: cuiliang/Quicker <Quicker@noreply.github.com>
抄送: The World <474551869@qq.com>, Author <author@noreply.github.com>
主题: 回复：[cuiliang/Quicker] 无法获取选中的文本 (#463)




并没有安装360， 只有win10的 de什么的，这个有影响吗 发自我的iPhone
Win10的应该没有影响。 这个获文本的方式是发送ctrl+c后读取剪贴板。 在记事本或别的软件里能获取到么？

**Comment by Aincvy** [comment]
记事本OK的  
XYplorer OK的
Notepad++ OK的 
VS OK 的

Chrome 浏览器 不OK

OneNote 部分OK  部分失败
 
![image](https://user-images.githubusercontent.com/8110347/58134540-ba3cef80-7c59-11e9-9613-7ff3a2cdc1cb.png)

**Comment by cuiliang** [comment]
chrome部分网页会有限制，比如百度文库之类的，会禁止copy。另外，是否使用其他监控剪贴板的软件？这类软件也会互相干扰。

**Comment by Aincvy** [comment]
百度文库之类的 我知道， 并没有在上面

似乎任何页面都不行,  把部分应用退出了，  也还是不行

下图是正在运行的程序
![image](https://user-images.githubusercontent.com/8110347/58138303-1dce1980-7c68-11e9-9a20-4fc5856f21ff.png)

WIN10 系统信息
![image](https://user-images.githubusercontent.com/8110347/58138331-376f6100-7c68-11e9-9c47-4dfacfbeb1de.png)

Chrome 版本信息
![image](https://user-images.githubusercontent.com/8110347/58138392-7bfafc80-7c68-11e9-9dd4-8142a8a12d1c.png)

Chrome 扩展信息
![image](https://user-images.githubusercontent.com/8110347/58138415-946b1700-7c68-11e9-816e-34dea2d0ca1a.png)


PS  有没有可能我的浏览器本身有问题？

**Comment by Aincvy** [comment]
另外， 我呼出面板是用的快捷键  ALT+Q  不是鼠标， 不知道有没有影响？

刚刚又试了试 Firefox 
出现了一个情况。

1. 我在firefox 里面选好文本
2. 我切到谷歌 对消息进行编辑
3. 我用 alt+tab 切换到 firefox 
4. 我用 alt+q 呼出面板， 点击百度搜索/谷歌搜索/百度翻译 中的一个任何一个按钮， 提示 无法获取文本
5. 我再次点击该按钮， 功能 生效了。
6. 又测试了下，  再次点击的时候 点击其他按钮也会生效

**Comment by cuiliang** [comment]
> 另外， 我呼出面板是用的快捷键 ALT+Q 不是鼠标， 不知道有没有影响？
> 
> 刚刚又试了试 Firefox
> 出现了一个情况。
> 
> 1. 我在firefox 里面选好文本
> 2. 我切到谷歌 对消息进行编辑
> 3. 我用 alt+tab 切换到 firefox
> 4. 我用 alt+q 呼出面板， 点击百度搜索/谷歌搜索/百度翻译 中的一个任何一个按钮， 提示 无法获取文本
> 5. 我再次点击该按钮， 功能 生效了。
> 6. 又测试了下，  再次点击的时候 点击其他按钮也会生效
> 7. 该操作在Chrome 上无效

Alt不能用啊，Alt键会激活各个软件的菜单，让焦点丢失。用ctrl单击或鼠标激活。

**Comment by Aincvy** [comment]
嗯， 可以了。。  

但是你们并没有说 不能使用 alt 键。。。

**Comment by cuiliang** [comment]
> 嗯， 可以了。。
> 
> 但是你们并没有说 不能使用 alt 键。。。

嗯，这里忽视了。我在文档里加一个。Alt基本是被所有软件都用来激活菜单的。

**Comment by Aincvy** [comment]
嗯， 还有个小问题是   使用这类功能的时候， 会把粘贴板给改掉， 这样有时候会不方便

**Comment by cuiliang** [comment]
> 嗯， 还有个小问题是 使用这类功能的时候， 会把粘贴板给改掉， 这样有时候会不方便

这个问题暂时没有更好的办法解决。 因为各进程之间目前只有剪贴板一个桥梁来交互数据。

**Comment by Aincvy** [comment]
我的想法是，  能不能先把粘贴板的数据暂存， 获取文本后再 还原回去？

**Comment by cuiliang** [comment]
> 我的想法是， 能不能先把粘贴板的数据暂存， 获取文本后再 还原回去？

之前加过。 有几个因素，一个是除了单纯的文本，不能很好的保存和恢复剪贴板。 另一个是，不能确保多久后，目标软件可以把剪贴板里的数据读取出来，恢复的快了会导致目前软件读取到恢复的剪贴板内容。 所以后来就拿掉了。

**Comment by Aincvy** [comment]
OK， 了解
