### ISSUE TITLE
Alt+TAB最小化后还会有窗口

### ISSUE THREAD

**Issue by Mxililove** [cuiliang/Quicker#465]
系统是win10 1903系统，当我的quicker最小化到任务栏之后，ALT+TAB切换程序的时候会有一个程序框，当我关闭这个程序框之后再对Quicker操作，Quicker会闪退。
![image](https://user-images.githubusercontent.com/33249249/57963310-fe2bae00-7954-11e9-9fb8-67ce3a12caf2.png)

**Comment by Huelse** [comment]
I met the same problem.
win10 v1809
![](https://i.bmp.ovh/imgs/2019/05/7961f9d8949586b1.jpg)

**Comment by cuiliang** [comment]
0.11.8 中已去除，可以从下载下载快速通道版本。
https://getquicker.net/Download
