### ISSUE TITLE
quicker和动态壁纸软件upupco有冲突，在开启动态壁纸的时候quicker面板无法弹出，经查upupco没有快捷键冲突

### ISSUE THREAD

**Issue by FIRpy** [cuiliang/Quicker#472]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
什么激活面板的方式？其他方式能否激活？ 有没有加黑名单？ 有没有设置全屏禁用选项？

**Comment by FIRpy** [comment]
就是单击鼠标中键没有反应，没有设置其他的激活面板方式，没有设置全屏禁用和黑名单，您可以测试一下


 
---原始邮件---
发件人: "CuiLiang"<notifications@github.com>
发送时间: 2019年5月26日(星期日) 晚上8:49
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"FIRpy"<457627575@qq.com>;
主题: Re: [cuiliang/Quicker] quicker和动态壁纸软件upupco有冲突，在开启动态壁纸的时候quicker面板无法弹出，经查upupco没有快捷键冲突 (#472)



什么激活面板的方式？其他方式能否激活？ 有没有加黑名单？ 有没有设置全屏禁用选项？

**Comment by cuiliang** [comment]
upupco的问题，它拦截中键了。 请向upupco反馈问题哦。
