### ISSUE TITLE
关闭设置中的“信息提示”-->“启动完成提示”，仍旧提示

### ISSUE THREAD

**Issue by Holaplace** [cuiliang/Quicker#473]
**描述BUG**
关闭设置中的“信息提示”-->“启动完成提示”，仍旧提示。
P.S. 并且提示两次

**重现步骤**
1.开机自启动
2.两次提示“程序启动完成”

**环境信息:**
 - 操作系统版本：最新win10
 - Quicker版本：0.11.7

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
提示的内容是？

**Comment by Holaplace** [comment]
程序启动完成

**Comment by Holaplace** [comment]
![Snipaste_2019-05-27_12-22-13](https://user-images.githubusercontent.com/45121260/58395324-22386f00-807a-11e9-93e4-5875a28ae307.png)
此时软件已经启动一分钟，才弹出提示，且两次，间隔约20s。之前我已在设置中取消提示选项

**Comment by cuiliang** [comment]
这个提示是因为多次启动quicker造成的。在第二次启动后，会检查是否已经启动了，如果已经启动了，就会提示这个信息然后退出。你看下是不是设置了多个自动启动项，或通过别的什么方式又启动了quicker。
