### ISSUE TITLE
UI：导出/载入外观设置配置文件

### ISSUE THREAD

**Issue by WilsonXuwx** [cuiliang/Quicker#474]
**需求描述**
设置好外观后能导出配置文件，这样多种配置可以切换。

**描述你想要的解决方案**
外观设置界面增加“载入/导出配置文件”。

**描述您考虑过的替代方案**
N/A。

 **其他上下文**
记录一下想法，感觉并不是很重要。
<img src='https://i.loli.net/2019/05/27/5cebd1c26d1b721155.png' title='Snipaste_2019-05-27_19-53-31.png' />

**Comment by cuiliang** [comment]
归档
已增加皮肤分享
