### ISSUE TITLE
开放自定义动作图标

### ISSUE THREAD

**Issue by shugaofeng** [cuiliang/Quicker#475]
**自定义动作图标**
为保证整个面板的美观性和协调性，希望能自定义动作图标，不要有30K的限制。

**Comment by cuiliang** [comment]
减小一下图标尺寸。 一般32*32即可，保存为png文件通常不会超过2k。

**Comment by shugaofeng** [comment]
> 减小一下图标尺寸。 一般32*32即可，保存为png文件通常不会超过2k。

不好意思，我表述有问题。目前大于 30K 的动作不能编辑，但是我只是想更换图标，不是说图标超过 30K。我想更换大于 30K 的动作的图标，以使得整个面板图标更加协调。

**Comment by cuiliang** [comment]
可以下载0.11.8版本，暂时取消了这个限制。 后续如何处理待定。

**Comment by shugaofeng** [comment]
> 可以下载0.11.8版本，暂时取消了这个限制。 后续如何处理待定。

嗯嗯，已更新，谢谢大佬
