### ISSUE TITLE
在腾讯桌面整理  打不开 quicker  

### ISSUE THREAD

**Issue by zhangran1033** [cuiliang/Quicker#476]
在腾讯桌面整理  打不开 quicker

**Comment by cuiliang** [comment]
有没有启用全屏禁用Quicker的选项？
![image](https://user-images.githubusercontent.com/1972649/58598477-2b5e5180-82af-11e9-8d3e-cfb65ed3ce7e.png)

**Comment by zhangran1033** [comment]
谢谢
