### ISSUE TITLE
Win10更新1903版后，部分界面空白，不显示任何控件

### ISSUE THREAD

**Issue by zhouqiaor** [cuiliang/Quicker#477]
**描述BUG**
Win10更新1903版后面板管理界面空白，无法操作，部分脚本（比如定时关机增强版）界面空白；
退出后登录界面也是空白的；
拖动主面板有严重延迟；

**重现步骤**
1.更新Win系统至1903（五月最新版）
2.激活主面板->面板管理->界面空白不显示任何

**相关截图**
截图稍后提交
![登录](https://user-images.githubusercontent.com/35691310/58570921-69398680-826b-11e9-864c-a8469bfdd399.PNG)
![image](https://user-images.githubusercontent.com/35691310/58572595-8cb20080-826e-11e9-9422-7ee921eaeabd.png)
![image](https://user-images.githubusercontent.com/35691310/58572698-c420ad00-826e-11e9-8fdb-a5ff66e33dbd.png)
![image](https://user-images.githubusercontent.com/35691310/58572849-0d70fc80-826f-11e9-88fd-d1216e78714d.png)

**环境信息:**
 - 操作系统版本：Win10, 1903版
 - Quicker版本：0.11.7.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
是全新安装的1903还是1809上更新的？ 我的电脑目前还刷不出更新，暂时无法调试

**Comment by zhouqiaor** [comment]
> 是全新安装的1903还是1809上更新的？我的电脑目前还刷不出更新，暂时无法调试

在1803上用[Windows10易升]工具更新的，更新前使用正常。重新安装后还有问题。
[Windows10易升]https://www.microsoft.com/zh-cn/software-download/windows10

**Comment by zhouqiaor** [comment]
> 是全新安装的1903还是1809上更新的？我的电脑目前还刷不出更新，暂时无法调试

你好，我是在1803上用[Windows10易升]工具更新的；
#更新前使用正常。重新安装后问题没有解决。
#登录界面虽然不显示文本和控件，但是凭感觉找到输入栏后还可以登录使用；
[Windows10易升] https://www.microsoft.com/zh-cn/software-download/windows10

**Comment by cuiliang** [comment]
可以试试重装一下显卡驱动看看能不能解决

**Comment by cuiliang** [comment]
参考：https://getquicker.net/Forum/ViewTopic/672

**Comment by zhouqiaor** [comment]
> 参考：[https](https://getquicker.net/Forum/ViewTopic/672)：[//getquicker.net/Forum/ViewTopic/672](https://getquicker.net/Forum/ViewTopic/672)

1. 卸载NVIDIA后重新安装，在设备管理器中关闭Intel显卡驱动后，窗体显示回复正常；
#猜测是升级安装1903后NVIDIA显卡驱动损坏了，直接切换显卡电脑崩溃；
2. 但是拖动主面板依然还有严重延滞；

**Comment by zhouqiaor** [comment]
> 参考：[https](https://getquicker.net/Forum/ViewTopic/672)：[//getquicker.net/Forum/ViewTopic/672](https://getquicker.net/Forum/ViewTopic/672)

多谢回复，窗体显示已解决
1. 卸载NVIDIA后重新安装，在设备管理器中关闭Intel显卡驱动后，窗体显示回复正常; 
＃猜测是升级安装1903后NVIDIA显卡驱动损坏了，直接切换显卡电脑崩溃;
2. 但是拖动主面板依然还有严重延滞;

**Comment by cuiliang** [comment]
> > 参考：[https](https://getquicker.net/Forum/ViewTopic/672)：[//getquicker.net/Forum/ViewTopic/672](https://getquicker.net/Forum/ViewTopic/672)
> 
> 多谢回复，窗体显示已解决
> 
> 1. 卸载NVIDIA后重新安装，在设备管理器中关闭Intel显卡驱动后，窗体显示回复正常;
>    ＃猜测是升级安装1903后NVIDIA显卡驱动损坏了，直接切换显卡电脑崩溃;
> 2. 但是拖动主面板依然还有严重延滞;

好的。
另外，什么情况下需要拖动面板？

**Comment by zhouqiaor** [comment]
> > > 参考：[https](https://getquicker.net/Forum/ViewTopic/672)：[//getquicker.net/Forum/ViewTopic/672](https://getquicker.net/Forum/ViewTopic/672)
> > 
> > 
> > 多谢回复，窗体显示已解决
> > 
> > 1. 卸载NVIDIA后重新安装，在设备管理器中关闭英特尔显卡驱动后，窗体显示回复正常; 
> >    ＃猜测是升级安装1903后NVIDIA显卡驱动损坏了，直接切换显卡电脑崩溃;
> > 2. 但是拖动主面板依然还有严重延滞;
> 
> 好的。
> 另外，什么情况下需要拖动面板？

面板遮住其它窗口（印象笔记、Word等）正在处理的文字；

升级1903后集显和独显驱动都有异常（禁用集显后，NVIDIA独显下无法调节屏幕亮度，不能切回集显），已恢复原系统；

**Comment by cuiliang** [comment]
> 面板遮住其它窗口（印象笔记、Word等）正在处理的文字；

是什么样的操作流程呢？ 正常是需要的时候激活面板，选动作以后面板就自动隐藏了，应该不会遮盖。 是使用了“钉住”么？

**Comment by zhouqiaor** [comment]
> > 面板遮住其它窗口（印象笔记、Word等）正在处理的文字；
> 
> 是什么样的操作流程呢？ 正常是需要的时候激活面板，选动作以后面板就自动隐藏了，应该不会遮盖。 是使用了“钉住”么？
____________________________________
场景： 在使用其它软件时添加动作（该场景发生刚为某软件新建面板添加动作时，其实不经常发生）
流程： 激活面板->工具箱->共享库中添加新动作时
由于主面板靠近屏幕右边界，导致共享库面板没有完全显示，（工具窗口不能关闭）会拖动面板；
![image](https://user-images.githubusercontent.com/35691310/59276631-478bc680-8c91-11e9-84a3-12e47cbb7837.png)
____________________________________
其它：有时在加载动作面板管理、工具箱界面时，（可能因为网络、电脑性能）会出现加载过慢，拖动面板也会出现（鼠标、动画）延滞；
