### ISSUE TITLE
windows 1903 有严重的拖拽延迟

### ISSUE THREAD

**Issue by Starcraft86** [cuiliang/Quicker#478]
BUG
在开启模糊效果后，拖拽框体，有严重的延迟效果。

重现步骤
1.重复几次没有很好的改观。
2.关闭模糊效果后，问题解决。

**Comment by cuiliang** [comment]
已知此问题，待我这里收到1903更新后调试下看看。

**Comment by maggiedot** [comment]
@cuiliang 可以手动更新到1903：https://www.microsoft.com/en-us/software-download/windows10

**Comment by cuiliang** [comment]
Windows API改变导致亚克力效果不可用了。 下个版本中将会移除，目前可以禁用模糊会修改为毛玻璃效果。
参考：
http://sourcechord.hatenablog.com/entry/2019/05/17/235928 
https://github.com/sourcechord/FluentWPF/issues/42
