### ISSUE TITLE
组合动作插入“提取文件路径信息”时，程序崩溃

### ISSUE THREAD

**Issue by luanmingyi** [cuiliang/Quicker#48]
组合动作插入“提取文件路径信息”时，出现卡顿直到崩溃，或直接崩溃

**Comment by luanmingyi** [comment]
在设计界面中，使得整个程序崩溃

**Comment by cuiliang** [comment]
@luanmingyi  我这边测了几次没有重现。 你那边现在做那个操作还是一样的么？版本是多少？ 崩溃的时候，麻烦那个异常提交的对话框点一下提交，我这里看一下异常信息。

**Comment by luanmingyi** [comment]
![q](https://user-images.githubusercontent.com/8343681/49498502-39a25680-f8a6-11e8-919f-58a5b32808bb.gif)
0.7.6.0
直接卡掉了，没有异常提交的对话框

**Comment by cuiliang** [comment]
好的，重现了，谢谢你的录屏

**Comment by cuiliang** [comment]
点错了

**Comment by cuiliang** [comment]
今天的0.7.11版本已修复此问题。
