### ISSUE TITLE
最近用起来总感觉全局面板不够用了

### ISSUE THREAD

**Issue by armymenrts** [cuiliang/Quicker#480]
**需求描述**
请问能不能鼠标放置在面板上半部分时可以使用鼠标滑轮向下翻页，也就是全局面板多几个

**描述你想要的解决方案**
希望可以新建多个全局面板，鼠标在全局面板范围时可以使用鼠标滑轮在多个面板种翻页

**描述您考虑过的替代方案**
虽然可以使用在主面板新建面板的方式调用，但是总感觉有些不方便。多谢Quicker！

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/multi-profile

**Comment by armymenrts** [comment]
肥肠抱歉没有仔细看教程，多谢回复
