### ISSUE TITLE
突然卡顿，鼠标延迟移动

### ISSUE THREAD

**Issue by princehanhan** [cuiliang/Quicker#481]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.使用过程中会出现卡顿，鼠标延迟
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 1809
 - Quicker版本：最新版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请更新到0.11.9版本试试会不会发生

**Comment by sunnyadams** [comment]
0.11.9也有拖动会卡顿情况

**Comment by cuiliang** [comment]
> 0.11.9也有拖动会卡顿情况

如果是WIN10 1903，不能使用亚克力模糊效果，要改成毛玻璃或取消模糊。

**Comment by cuiliang** [comment]
done。
后续版本取消了亚克力效果。
