### ISSUE TITLE
某个步骤运行出错时不要停止动作

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/Quicker#482]
如HTTP请求、正则提取等模块，受使用环境影响比较大容易出错，但并不影响整体动作的使用。

特别是某些需要列表循环的场景，如果因其中一个运行出错直接停止动作，会导致后面的循环无法继续进行。

还有比如同时展示多个网站的翻译结果时，如果其中一个错误，停止动作后其他翻译也无法显示。

可以加一个“失败后停止动作”的单独模块，由开发者决定是否在某个步骤失败后停止动作，否则一律忽略失败步骤，继续运行。

**Comment by cuiliang** [comment]
已在步骤组中增加忽略错误选项。
