### ISSUE TITLE
无法点击系统的任何按钮

### ISSUE THREAD

**Issue by asdzxc234** [cuiliang/Quicker#486]
**描述BUG**
鼠标中键调出面板，偶然卡一下后，无法点击系统任何按钮，就好像鼠标左键坏掉一样。
ctrl+alt+delete 打开任务管理器，可恢复点击，但是仍有失灵的情况，例如QQ聊天窗口，右键无法调出二级菜单（无法对图片另存为）。退出软件也不可以，只能重启电脑才能彻底解决。

**重现步骤**
1.鼠标中键调出面板
2.偶然卡一下后出现，5个小时已出现两次。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：WIN7
 - Quicker版本：0.11.9.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
执行的动作有用到鼠标的么？是执行某个动作之后卡一下，还是任何动作都会卡一下？ 有没有什么规律？
如果退出软件也不可以正常点击，就会比较奇怪。

**Comment by asdzxc234** [comment]
你好！第1次出现时，执行的动作没有鼠标动作，只是键盘；第2次，是鼠标中键调出面板，还没有去点击动作就出现问题，值得注意的是，当时可以看到鼠标中键的十字箭头图标与面板同时存在（以前使用是不会出现这个图标的）。
卡一下后就不卡了。没找到复现的规律，是偶然出现。
没有使用手势软件，当时也没用浏览器，不存在手势。
今天下午没出现了，像以往那样正常，我会继续使用，有问题再反馈。

**Comment by cuiliang** [comment]
是用的哪种浏览器？ 这个现象似乎是鼠标事件不匹配了（按下和抬起不配对）。 中间键激活的话，Quicker是会拦截按下和抬起事件，这时候浏览器应该不会有十字。

**Comment by asdzxc234** [comment]
你好，现在约隔两天会出现这种现象。
都是出现在开机后第一次调出Quicker（鼠标中键），有概率出现。拍照分享到网盘。
ctrl+alt+delete 打开任务管理器，可恢复点击，但存在失灵的现象。视频分享到网盘。

链接: https://pan.baidu.com/s/1Zd-lIhjWT4gIlRK6iKRbWA 提取码: jhie

PS：由于不会在回复时发图片和视频，你看看能不能看到现象吧。

**Comment by cuiliang** [comment]
用的是什么鼠标？ 有安装额外的鼠标驱动软件么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
