### ISSUE TITLE
在鼠标左手模式情况下，点击右键（鼠标左键）会屏蔽掉系统右键菜单

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#487]
**描述BUG**
https://getquicker.net/Forum/ViewTopic/718

标题好像有点儿绕，其实是这样子的，

我设置为右键350ms长按弹出，在正常的鼠标设置下，右击弹出系统菜单，右键长按弹出quicker，完美。

但是我由于工作需要，一般都是左手用鼠标，所以我调转了鼠标左右键，在左手鼠标模式下，右击动作无法弹出系统菜单，只有但是长按弹出quicker正常。

**环境信息:**
quicker版本 0.11.9.0

电脑win7 sp1和win10 18362.175

**Comment by cuiliang** [comment]
done

**Comment by zandlme** [comment]
> done

完美解决，开发者太赞了
