### ISSUE TITLE
动作-组合成文本-格式化字符串 如果包含大括号会报错

### ISSUE THREAD

**Issue by nir311** [cuiliang/Quicker#488]
**描述BUG**
动作-组合成文本-格式化字符串 如果包含大括号会报错

版本号：0.11.9.0

**附加信息**
使用 {0} {1} 分别替换{ },然后 使用参数0、1替换功能绕过报错

**Comment by cuiliang** [comment]
大括号在c#的FormatString里是用来标识要组合到文本里的变量的。这个是正常行为了。
参考：https://www.cnblogs.com/gongth-12/archive/2012/11/26/2791642.html
https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.8

**Comment by nir311** [comment]
@cuiliang 多谢。 将{ 和 }换成{{  }}后正常
