### ISSUE TITLE
强烈建议增加键盘选择

### ISSUE THREAD

**Issue by yixuan10000** [cuiliang/Quicker#49]
![image](https://user-images.githubusercontent.com/20551341/49447465-9acc1a80-f811-11e8-8d60-8f29f76ee6e2.png)
如图，在一个操作的盘的合适位置加入一个键盘选择，方便键盘党使用，应该能有更多人喜欢。

感谢开发者！！！

**Comment by cuiliang** [comment]
感谢反馈，后期会加入此功能。

**Comment by Moyf** [comment]
相关Issue：#32 第二点

**Comment by cuiliang** [comment]
0.7.28加入
