### ISSUE TITLE
软件启动时出现错误提示“绑定网络状态变更时间异常：依赖服务或组无法启动。（异常来自HRESULT:0X8007042C）”

### ISSUE THREAD

**Issue by 1578198226** [cuiliang/Quicker#490]
软件启动时出现错误提示“绑定网络状态变更时间异常：依赖服务或组无法启动。（异常来自HRESULT:0X8007042C）”

**Comment by cuiliang** [comment]
请按模版提供更详细的信息以便判断。

**Comment by 1578198226** [comment]
网络正常 但是同步软件 提示网络无法连接

**Comment by cuiliang** [comment]
windows版本？ 可能缺少或损坏了什么windows组件。

**Comment by 1578198226** [comment]
![image](https://user-images.githubusercontent.com/51977521/59730598-86171780-9275-11e9-8356-8ff5ca4e623b.png)

**Comment by cuiliang** [comment]
https://support.microsoft.com/en-us/help/2530126/0x8007042c-error-message-when-you-try-to-start-windows-firewall

**Comment by 1578198226** [comment]
![image](https://user-images.githubusercontent.com/51977521/59732934-ac8d8080-927e-11e9-875c-fe4a8913f1f7.png)

**Comment by 1578198226** [comment]
还是不行

**Comment by 1578198226** [comment]
每次启动都出现。。。

**Comment by cuiliang** [comment]
建议修复一下windows看看。另外如果优化关闭了什么服务，也还原一下。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by VergilChin** [comment]
我也是这个问题，绑定网络状态异常，不知道哪里出了问题

**Comment by cuiliang** [comment]
> 我也是这个问题，绑定网络状态异常，不知道哪里出了问题

这个可能是某个依赖的windows服务被停用了。windows有做过什么优化么？

**Comment by VergilChin** [comment]
> 软件启动时出现错误提示“绑定网络状态变更时间异常：依赖服务或组无法启动。（异常来自HRESULT:0X8007042C）”

找到原因了，网络和共享中心没开启。如果所依存的服务没有启动，就启动相关服务。event log服务也是要启动的。
