### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by cizixiu** [cuiliang/Quicker#491]
**描述BUG**
鼠标按住界面拖拽时，界面无法跟随鼠标一起运动，而是严重滞后。像慢动作。

**重现步骤**
1.设置外观为亚克力效果
2.拖拽界面，会出现上述bug

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win 10  1903
 - Quicker版本：0.11.9

**附加信息**
外观如果设置成毛玻璃，则没有上述bug

**Comment by cuiliang** [comment]
已知问题，1903的API更改导致毛玻璃不可用，下一个版本中将去除。

**Comment by cuiliang** [comment]
#478
