### ISSUE TITLE
增加判断路径是文件还是文件夹

### ISSUE THREAD

**Issue by youjianglong** [cuiliang/Quicker#493]
**需求描述**
当前无法判断从系统文件管理器拿到的路径是文件还是文件夹

**描述你想要的解决方案**
增加判断路径是文件还是文件夹的动作

**Comment by youjianglong** [comment]
这个应该比较容易实现，而且还是有必要的

**Comment by cuiliang** [comment]
这个是什么用途？ 一般得到的路径应该都是已经明确文件或文件夹的。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/checkpathexists
