### ISSUE TITLE
建议在屏幕边缘支持更多像滑动音量一样的快捷操作

### ISSUE THREAD

**Issue by Aidelank** [cuiliang/Quicker#494]
Quicker不应当局限于滑动滚轮来调整音量，“屏幕边缘”这一快捷键还有更多的潜在功能。

个人建议Quicker增加如同在屏幕底部滑动滚轮来调整，创建，删除虚拟桌面等功能；屏幕左右边单击便可翻页等。

目前本人还在使用One Quick来达到这一功能，但希望Quicker的开发者可以采用这一功能，毕竟虚拟桌面也是许多办公人士常用的效率提升办法。

One Quick参见知乎：https://www.zhihu.com/question/36847530/answer/92868539

**Comment by cuiliang** [comment]
切换虚拟桌面可能比较有用，创建和删除应该很少用到吧？ 一般是弄几个虚拟桌面以后就不会再更改数量了，所以感觉没有必要。 可以考虑增加切换。

**Comment by Aidelank** [comment]
@cuiliang 
嗯没错。创建和删除其实可以直接新建基本动作就可以达到。
另外，我很期待这个切换虚拟桌面的功能，您可以预估一下更新日期吗？谢谢！

**Comment by cuiliang** [comment]
> @cuiliang
> 嗯没错。创建和删除其实可以直接新建基本动作就可以达到。
> 另外，我很期待这个切换虚拟桌面的功能，您可以预估一下更新日期吗？谢谢！

暂无具体的时间安排。 我希望能做成由用户自定义的，这样会比较通用一些。

**Comment by Aidelank** [comment]
> > @cuiliang
> > 嗯没错。创建和删除其实可以直接新建基本动作就可以达到。
> > 另外，我很期待这个切换虚拟桌面的功能，您可以预估一下更新日期吗？谢谢！
> 
> 暂无具体的时间安排。 我希望能做成由用户自定义的，这样会比较通用一些。

好的，祝愿Quicker日益强大

**Comment by cuiliang** [comment]
自定义功能做了但是感觉太复杂，不适合直接开放，后期再研究了。
