### ISSUE TITLE
  屏蔽掉了系统右键BUG!!!bug!!!  好多界面用右键确弹出来qucker

### ISSUE THREAD

**Issue by lzzv** [cuiliang/Quicker#495]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.  屏蔽掉了系统右键BUG!!!bug!!!  好多界面用右键确弹出来qucker
2.  屏蔽掉了系统右键BUG!!!bug!!!  好多界面用右键确弹出来qucker

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/24580480/61016279-ac862980-a3c1-11e9-9967-d90403a388ee.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
版本多少？ 之前版本有一个相关的bug。
另外可以修改配置，取消右键激活的选项。

![image](https://user-images.githubusercontent.com/1972649/61016349-e5260300-a3c1-11e9-9ac0-12ab03ca1292.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
