### ISSUE TITLE
动态更改获取文本的渠道

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#50]
我有一个idea，目前Quicker许多动作都是依靠选中文字执行的，但是有相当一部分情景下希望动作还能通过其他手段获取到文字（比如提供输入框以直接手动输入，使用剪切板内的文字内容等），在执行动作前，通过配合其他键位（比如Ctrl，Shift，Alt等）改变这一行为，如果能提供一个子程序封装上述功能，将会使Quicker的使用场景更加广泛，望采纳！

**Comment by cuiliang** [comment]
考虑实现获取是否选中文字

**Comment by linyubin** [comment]
如果我想在一个组合动作中获得一个文件的路径,应该如何实现?

**Comment by cuiliang** [comment]
> 如果我想在一个组合动作中获得一个文件的路径,应该如何实现?

在组合动作中使用“获取选中的文件”模块。会输出列表类型的变量，然后使用“每个”模块，对列表里的每个值（一个文件路径）进行相应从操作。

**Comment by cuiliang** [comment]
不考虑动态切换了，可以根据需要在动作里按 选中文本-剪贴板-输入的流程获取内容后处理。
