### ISSUE TITLE
上传图标时可剪裁尺寸，能对列表中的图标进行分类与重命名

### ISSUE THREAD

**Issue by fwzuw** [cuiliang/Quicker#500]
**需求描述与解决方案**
如果添加了很多动作以及很多图标，甚至干脆加了个表情包（的缩略图）进来，图标列表会变得非常臃肿，最好能通过分类来管理图标列表，以及对列表中的图标进行重命名（美观）。

**描述您考虑过的替代方案**
对于不需要反复使用的图标，添加到动作里后可以立刻从列表删掉。但这样似乎并不会删掉服务器（以及本地数据）里的图标，如果下次还要使用，需要再上传一次，反而更加浪费资源。

另外图标上传似乎还有尺寸上的限制，2.2kb 130x106 的图标被限制，5.8kb 72x72 的图标却没有被限制，我打开 ps 把 130x106 图像缩小到 32x32 才上传成功。所以希望干脆上传图标时能直接剪裁尺寸，不用再去使用其他的工具剪裁。

**Comment by cuiliang** [comment]
在服务器端是不删除的，因为动作的分享机制，如果删除了，可能别的动作就会加载不了图标。
目前图标尺寸主要是按分辨率限制，最大分辨率72*72。
裁剪工具短期估计安排不了，等有时间再研究一下。
推荐在 https://www.iconfont.cn/ 下载图标。

**Comment by cuiliang** [comment]
剪裁暂不考虑了。
