### ISSUE TITLE
快捷面板屏幕左侧贴边打开“动作面板管理”的BUG

### ISSUE THREAD

**Issue by zingplus** [cuiliang/Quicker#502]
在屏幕左侧启动Quicker，快捷面板会贴边显示，此时打开“动作面板管理”则在屏幕外显示且无法关闭快捷面板，此时只能再次点击“≡”按钮或将快捷面板右拖。

**Comment by cuiliang** [comment]
https://getquicker.net/Download 请下载快速通道版本0.13.4 已更改设计。现在是显示在屏幕中间了。

https://www.yuque.com/quicker/help/profiles
