### ISSUE TITLE
快捷切换“上下文面板”和开启“动作面板管理”的建议

### ISSUE THREAD

**Issue by zingplus** [cuiliang/Quicker#503]
因随时可能调用其他面板的动作，建议设置TAB键快速切换“上下文面板”，建议设置SHIFT键快速开启“动作面板管理”。

**Comment by cuiliang** [comment]
已更改设计，可以将通用动作页挂在其他软件下面。
可以试一下。
![image](https://user-images.githubusercontent.com/1972649/61171011-10684800-a5a4-11e9-9935-8841695fb395.png)

**Comment by cuiliang** [comment]
可能没太理解原题。
使用滚轮切换面板是最快速的方法。 键盘激活时可以用方向键切换动作页。
先关了，如果还有问题，请再reopen
