### ISSUE TITLE
鼠标中建误触发quicker

### ISSUE THREAD

**Issue by flyingicedragon** [cuiliang/Quicker#504]
**描述BUG**
未将鼠标中建设置为激活quicker的按键，但是有时单击鼠标中键会激活quicker。
鼠标中键被我设置为了eudic快捷查单词的按键。

**环境信息**
 - 操作系统版本：Windows10 1803
 - Quicker版本：0.11.9.0

**附加信息**
关闭eudic后，未发现会激活quicker。但是也有可能是因为关闭eudic后很少单击鼠标中键。

**Comment by cuiliang** [comment]
有可能某个软件做了按键转换，它在收到中键之后，转换成了另一个能触发Quicker的事件。

**Comment by flyingicedragon** [comment]
> 
> 
> 有可能某个软件做了按键转换，它在收到中键之后，转换成了另一个能触发Quicker的事件。

那估计就是eudic导致的，我试着找找解决办法。
