### ISSUE TITLE
13位时间戳（毫秒）计算成时间，并转换成文本

### ISSUE THREAD

**Issue by GithubFeed** [cuiliang/Quicker#505]
现有的功能只能计算10位时间戳，希望可以精确到13位毫秒；

 用户可以通过格式控制功能来选择输出到秒，或者输出到毫秒。谢谢！

https://getquicker.net/Docs/Show?articleId=41

**Comment by cuiliang** [comment]
在1.0.1里加上了，编辑器工具箱里搜索“获取时间”模块。请到下载页面里下载快速通道版本。
