### ISSUE TITLE
单击ctrl键激活的问题

### ISSUE THREAD

**Issue by zingplus** [cuiliang/Quicker#507]
单击ctrl键只能激活最前端软件，无法激活软件界面外对应的程序。

**Comment by cuiliang** [comment]
不是很明白，请截图示意一下。

**Comment by zingplus** [comment]
比如网易云音乐在最前端，鼠标悬浮于任务栏，单击ctrl键，激活的是网易云音乐面板而不是任务栏面板。
<img width="960" alt="Snipaste_2019-07-24_00-07-32" src="https://user-images.githubusercontent.com/52854447/61728698-4da0b700-ada8-11e9-8d03-f9de141c235a.png">

**Comment by cuiliang** [comment]
加载的动作页是根据“前台窗口”判断的，而不是鼠标所在位置。
使用鼠标方式激活的时候，比如中键点击了某个位置，会尝试把这个位置的窗口设置为“前台窗口”。所以用鼠标中键点击任务栏，任务栏会变成前台窗口。
用键盘激活的时候，是不能更改前台窗口的。 所以这时候哪个软件是前台窗口，就会加载哪个软件的动作页。
要想用键盘让任务栏获得焦点，可以试试Win+B。

**Comment by zingplus** [comment]
哦
