### ISSUE TITLE
使用鼠标侧键时，会经常误触软件

### ISSUE THREAD

**Issue by zxjrainbow** [cuiliang/Quicker#509]
我使用鼠标的侧键进行弹出界面。
当我的鼠标位置正好在屏幕的底部时，当按下侧键（未放开）在弹出界面时，在鼠标下会可能正好是某个动作按键，然后我这时放开侧键，就是触发了该动作。
建议：
触发前判断鼠标位置是不是已经离开原按下位置超过一定位置了。如果是，则不触发动作。

**Comment by cuiliang** [comment]
目前是判断是不是移动了的。 如果按下之后没有移动，就不会弹出。大概是10个像素的标准。

**Comment by zxjrainbow** [comment]
不对，我按侧键，是按下就弹出了，还没到松开就已经弹出了。

**Comment by cuiliang** [comment]
哦，想错了😂。 弹出是立即的，是不是执行动作，根据在弹出后是不是移动鼠标超过10个像素来判断。

**Comment by zxjrainbow** [comment]
根椐我测试的结果，应该是根椐键松开时的位置去触发动作的。并没有判断是不是与起始位置超过10个像素。

**Comment by cuiliang** [comment]
是的，松开的时候，判断移动有没有超过10个像素（从弹出面板的位置开始）。如果没超过就不执行。

**Comment by zxjrainbow** [comment]
你试了侧键了吗？并没有判断的。

**Comment by zxjrainbow** [comment]
![d](https://user-images.githubusercontent.com/29429838/61770753-98f6ac00-ae20-11e9-812e-89bb83315c84.gif)

**Comment by cuiliang** [comment]
> 你试了侧键了吗？并没有判断的。
刚测试之后才回复的。 
侧键和中键是同一段代码。

>这个动画就是显示，我按下侧键就弹出了，然后我移动到别的动作上了再松开，一样会触发。
就是这个逻辑。按侧键弹出，然后这时候如果没有移动鼠标，松开侧键，就不会执行鼠标指向位置的动作。 如果这时候移动了鼠标超过10个像素，就会执行动作。

**Comment by cuiliang** [comment]
这个是设计的两种操作方式。
方式1：点击侧键后松开，移动鼠标，执行动作。
方式2：按下侧键，移动到动作上，松开，执行动作。这种方式少一次点击。

**Comment by zxjrainbow** [comment]
> > 就是这个逻辑。按侧键弹出，然后这时候如果没有移动鼠标，松开侧键，就不会执行鼠标指向位置的动作。 如果这时候移动了鼠标超过10个像素，就会执行动作。

但这样的逻辑实际是有问题的。不应该在弹出时还去执行触发的动作。应该是在完成一次按下松开按键事件后，再一次的按下松开的事件才是触发动作。

**Comment by zxjrainbow** [comment]
> 这个是设计的两种操作方式。
> 方式1：点击侧键后松开，移动鼠标，执行动作。
> 方式2：按下侧键，移动到动作上，松开，执行动作。这种方式少一次点击。

你这个想法我理解了。但正常都是按了就松开了，并不会移动到想要的动作上。因为鼠标点击习惯是松开了再点一次。当然，手机类可以这样处理。

**Comment by cuiliang** [comment]
所以支持两种操作方式的。 只是要注意，如果不想执行动作，就要马上松开。
