### ISSUE TITLE
动作需求：在“等待时间”动作中添加弹窗检测功能

### ISSUE THREAD

**Issue by jrconfucius** [cuiliang/Quicker#510]
**需求描述**
存在场景：quicker启用动作，系统后台运行，运行后弹窗（如需要用户填写密码等类似情景），quicker在弹窗上继续后续动作。

**描述你想要的解决方案**
在“等待时间”动作中添加弹窗检测功能，出现弹窗则停止等待，前台窗口切换至弹窗界面，继续执行后续动作。

**描述您考虑过的替代方案**
现有方案：将等待时间设长，并使用鼠标输入动作确保前台切换至弹窗，然后执行后续动作。
缺点：等待时间过短则动作失效，过长则浪费时间。

 **可能出现的问题**
等待系统后台运行期间出现其他干扰弹窗被误识别，可以根据识别进程名称进行弹窗甄别。

**Comment by cuiliang** [comment]
这个请使用“等待窗口”模块。https://www.yuque.com/quicker/help/showwaitwin
操作类型可选“显示窗口并等待用户关闭”

**Comment by jrconfucius** [comment]
不是要让quicker弹窗，是检测运行中的其他软件的弹窗，例如我的流程里有一步是打开一个文件，这个文件是加密的，需要输入密码，密码已经存在一个变量里了，我需要等待文件打开，在输入密码的弹窗出现的时候再进行后续操作，也就是将变量进行输出。
我现在设置等待时间过短，输入密码无效，过程失败；等待时间过长，有浪费时间。文件如果是本地的还好，可以通过平时的运行速度去估算，有时文件是通过smartview和服务器连接的，启动速度受网络环境的影响。
我现在需要打开文件，等待，检测弹窗后停止等待，将变量输出（输入密码），然后再进行后续操作。

**Comment by cuiliang** [comment]
等待有2个实现的策略，一个是做完其他事情后，让quicker等待用户手动去完成某个操作，用户完成后告诉quicker可以继续。第二个是在quicker里循环判断目标窗口是否打开。 可以参考https://getquicker.net/sharedaction?code=2a59718b-523b-4e7e-a4a8-08d70bf0ab12
