### ISSUE TITLE
鼠标右键完全失效

### ISSUE THREAD

**Issue by zeshanhu** [cuiliang/Quicker#511]
**描述BUG**
更新了软件到最新版以后，整个电脑的右键完全失效，退出quicker才重新可以使用鼠标右键

**重现步骤**
1.打开quicker
2.鼠标右键失效

**相关截图**
无

**环境信息:**
 - 操作系统版本：Microsoft windows10专业版 10.0.18362版本18362
 - Quicker版本：1.0.4.0

**附加信息**
这是一个非常严重的BUG，我完全无法使用quicker了

**Comment by cuiliang** [comment]
通常是360造成的，360添加到信任列表，关闭驱动防护后使用。
360有严重的bug造成信任列表无效，并且每次更新quicker都需要加一次信任列表。

**Comment by qq496380235** [comment]
![image](https://user-images.githubusercontent.com/34149367/62262661-19826180-b44c-11e9-8a87-d535a9cbebc8.png)
在设置--弹出面板--激活方式  把长按右键选项取消掉，可以正常使用了

**Comment by cuiliang** [comment]
> ![image](https://user-images.githubusercontent.com/34149367/62262661-19826180-b44c-11e9-8a87-d535a9cbebc8.png)
> 在设置--弹出面板--激活方式 把长按右键选项取消掉，可以正常使用了

360 的问题，参考：https://getquicker.net/Forum/ViewTopic/816

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
