### ISSUE TITLE
希望能更改昵称或删除账户

### ISSUE THREAD

**Issue by Wo1framalpha** [cuiliang/Quicker#514]
**需求描述**
希望能更改昵称

**描述你想要的解决方案**
会员中心中提供更改昵称的功能

**描述您考虑过的替代方案**
提供删除账户的功能，通过这种方式实现曲线更改昵称

 **其他上下文**
我在注册的时候不小心输入错误还顺带按到了回车键，结果直接注册了一个乱七八糟的昵称，但我这次注册使用的邮箱是我的常用邮箱，个人来说不太想再用一个不常用的邮箱注册一个新账号，所以希望能给像我这样的少数群体提供一个挽回自己错误的机会。

**Comment by cuiliang** [comment]
ok

**Comment by cuiliang** [comment]
现在可以修改昵称了。 在修改密码链接下面。
https://getquicker.net/Member/Home
