### ISSUE TITLE
建议在用户选择模块增加n秒后关闭的选项

### ISSUE THREAD

**Issue by yixuan10000** [cuiliang/Quicker#515]
**需求描述**
比如一个划词翻译动作，我就翻译出来看一看，就继续我其他操作，这时候还需要手动关闭翻译结果的用户选择框。再比如截图后弹出一个用户选择框可搜图、贴图。但是我就想截图就不管了并不是每次都需要点击选择框。所以建议在用户选择模块增加n秒后关闭的选项

**描述你想要的解决方案**
建议在用户选择模块增加n秒后关闭的选项。比如增加一个选项，在xx秒后自动关闭。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
如图所示
![image](https://user-images.githubusercontent.com/20551341/62304653-00f86280-b4b1-11e9-97ce-08636c3495ed.png)

**Comment by cuiliang** [comment]
1.1.2 已增加
https://www.yuque.com/quicker/versions/1.1.x
