### ISSUE TITLE
每次使用复制粘贴动作之后，得到的文本都是新建的文件

### ISSUE THREAD

**Issue by HAPPY-AMY** [cuiliang/Quicker#516]
**需求描述**
目前使用的是quicker1.0.4.0版本，结合畅邮这个软件一起使用的。

具体是这样操作的 https://www.yuque.com/changyou/cysysm/erfa3o

目前使用这个功能是将网页上抓取的邮箱都一键复制，碰到的困扰是所有抓取的邮箱都保存在同一个文件里面。这样没有办法做区分保存。
**描述你想要的解决方案**
希望每次复制粘贴的动作的结果，都另存为一个新的文件，最好是能以日期-时间来命名。例如：20190805-120101/20190805-130524...

**描述您考虑过的替代方案**
加入日期时间变量作为文本档案名

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏

**Comment by cuiliang** [comment]
不好意思，刚刚能访问github来处理消息。
因为这个动作不是我做的，不是很了解。可以尝试联系动作的作者看看（可以考虑给作者发个红包-）。
你也可以自己修改一下动作，在保存的时候生成一个新的文件名来存储。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
