### ISSUE TITLE
建议新增动作的列表展示方式

### ISSUE THREAD

**Issue by GoNerddy** [cuiliang/Quicker#517]
**需求描述**
弹出动作面板后，可以选择像右键菜单一样按照列表展示

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/24631294/62503607-76ed2880-b827-11e9-88a5-4002c0f27b64.png)
![image](https://user-images.githubusercontent.com/24631294/62503641-a308a980-b827-11e9-97e6-620c325132cb.png)

**Comment by cuiliang** [comment]
感谢建议。 后期可能会考虑此类布局。不过这种也会有一定的弊端，比如不易定位、菜单可能比较高等。

**Comment by cuiliang** [comment]
目前显示和触发方式比较多了，暂不考虑其他形式了。
