### ISSUE TITLE
在浅色背景下，应用名称和设置面板颜色相近，看不清

### ISSUE THREAD

**Issue by wenmin92** [cuiliang/Quicker#518]
**描述BUG**
如题

**重现步骤**
设置浅色背景，看截图

**相关截图**
![image](https://user-images.githubusercontent.com/6901815/62503630-92583380-b827-11e9-88c8-74c0678eb5c9.png)

**环境信息:**
 - 操作系统版本：Win10 1903
 - Quicker版本：1.0.4.0

**Comment by cuiliang** [comment]
谢谢反馈。
已了解此问题，后续可能会增加一个字体颜色参数解决。

**Comment by cuiliang** [comment]
done  1.1.13里改成和按钮一样颜色了。
