### ISSUE TITLE
蓝牙鼠标卡顿

### ISSUE THREAD

**Issue by LeuJue** [cuiliang/Quicker#519]
**描述BUG**
对bug的清晰简洁描述。
鼠标是微软sculpt舒适滑控鼠标，Windows版本1903，实测在滚轮失效后关闭quicker就恢复正常
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：18362.10005
 - Quicker版本：1.0.4.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不好意思，刚刚能访问github来处理消息。
滚轮失效具体是什么样的现象？
