### ISSUE TITLE
离线使用的功能考虑

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#52]
最低目标：
- 可离线使用。比如断网的情况、在外出等暂时不能联网的地方使用的情况、网络情况比较差的情况
2级目标：
- 可轻度调整配置：创建和编辑、删除动作等。

目前可以想到的困难：
图标是不能离线存储的。 因为动作里要保存图标的统一位置，这个位置是图标保存到服务器后生成的，所以在离线情况下修改配置的时候，是不能修改图标的。

如果多个电脑使用同一个账号同时离线修改，存在同步冲突问题。

增加考虑配置同步问题：
目前的情况：当一台 PC 上进行更改时，另一台 PC 不能及时收到更改。需要关闭账户，重新登录才能同步更改。

**Comment by 804260247** [comment]
离线修改配置时用本地的图标可以吗

**Comment by cuiliang** [comment]
@804260247 本地图标的话，程序逻辑上有些问题。 图标可能变得不存在了，换一个机器就没有图标了，也不能分享动作了。

**Comment by 804260247** [comment]
@cuiliang 能否加一个判断呢？离线时添加的图标先放在本地，等账号登录后将图标上传到服务器

**Comment by cuiliang** [comment]
@804260247 理论上也是有可能的，开发的时候尝试看看

**Comment by i5151** [comment]
本地也存放一份完整的配置文件，和云中的相同。

平时先存本地，再同步到云。没网的时候用本地的配置，如有配置变更，联网的时候再同步，以时间为准，都是新的覆盖老的。

**Comment by 804260247** [comment]
@cuiliang 恩恩\(^o^)/

**Comment by Moyf** [comment]
「可轻度调整配置：创建和编辑、删除动作等。」这个很需要！

**Comment by feiian** [comment]
期待大神尽快实现离线功能

**Comment by matengxiao** [comment]
大神目前有进展么？

**Comment by cuiliang** [comment]
@matengxiao 除了更新和设置图标，其他功能目前的版本0.8.5基本上可以离线使用的，不需要实时联网。 不过最初登录的时候还是要联网的。

**Comment by i5151** [comment]
你不说新版本我都不知道有更新了，Quicker为什么检测不到新版本了？

**Comment by cuiliang** [comment]
@i5151  0.8.2 版本的bug，参考 https://getquicker.net/Forum/ViewTopic/159 
可以订阅一下公众号。

**Comment by i5151** [comment]
![Snipaste_2019-01-27_10-28-21.png](https://z4a.net/images/2019/01/27/Snipaste_2019-01-27_10-28-21.png)
1、新版在点击托盘图标之后，最明显的感觉就是下巴变长了，底边处理得还不好。
2、右键图标，能不能不要延时显示，正常显示就行了，现在点了右键之后半天不消失，点击其他地方也不消失，非得等到时间消失。这个设计很怪异，也没有什么功能的右键菜单，完全没有必要这样设计。
3、提示、提示、提示，有托盘图标了，为什么还要提示？

**Comment by i5151** [comment]
公众号我订阅了，而且订阅了很多公众号，没时间看了，之前看公众号的时间都被头条占用了。

你还不如申请个头条号，看的人可能更多，而且互动性更强，比公众号好多了。

**Comment by i5151** [comment]
还有更新还是没有改进，不能自动安装，你们自己的程序还要用户自己手动关闭。

自启的程序，有托盘图标还不够，非得在桌面建个图标，还不能设置不建。

**Comment by cuiliang** [comment]
@i5151 
1. 下巴变长这个我这也没出现，什么样的操作会出现？
2. 右键图标这个不是很明白，可能是bug，截图看下？
3. 启动的时候提示可以在配置窗口里关掉。 其他还有什么提示么？
4. 自动安装新版已经可以，参见刚才的更新说明；
5. 桌面图标等以后有时间学习怎么做安装包了再说喽。

**Comment by i5151** [comment]
1、在没有建过动作菜单的软件上呼出界面，感觉很明显。
2、不是右键图标，是托盘图标的右键菜单。
3、还有就是断网重新连接之后。
4、新版可以了？那只能等新新版的时候再试了。
5、增加可以，起码在安装的过程中有个设置选项，让用户自己决定建不建桌面图标。

**Comment by i5151** [comment]
没注意看更新说明，是能自动安装了。

但看到提示很怪异，用户都自己选择下载并安装，为什么在安装的时候还要询问？

只是想要个顺畅的下载安装过程，怎么这么难呢？非得生硬地加入询问打断。

**Comment by cuiliang** [comment]
@i5151 好的。 新版断网提示应该已经没有了。

**Comment by i5151** [comment]
其实，就像我之前说的，要提示也可以。

很多软件做的就很好，就是在托盘图标上加上动画。启动完成了、准备好了之后，Quicker的托盘图标有白色亮条划过一下。或者重新联网之后，亮条再次划过一下，不但让人知道Quicker在运行，准备好了，而且还显得高大上，不会各种提示乱飞给用户添乱。

**Comment by i5151** [comment]
最新的版本，怎么频繁出现第一次点击按钮之后，没有拷贝选择文本的情况。

这些按钮之前都是好好的，前几次以为是其他软件的问题，现在不同的按钮都出现过这样的情况，才想到是Quicker的问题。

**Comment by i5151** [comment]
![Snipaste_2019-02-01_17-16-28.png](https://z4a.net/images/2019/02/01/Snipaste_2019-02-01_17-16-28.png)
没有更新就显示：当前版本为最新；现在显示得太复杂，还有错误。

**Comment by cuiliang** [comment]
> 最新的版本，怎么频繁出现第一次点击按钮之后，没有拷贝选择文本的情况。
> 
> 这些按钮之前都是好好的，前几次以为是其他软件的问题，现在不同的按钮都出现过这样的情况，才想到是Quicker的问题。

复制选择文本的操作是向窗口发送ctrl+v，然后等待读取剪贴板。 如果不成功，通常是和某个监听剪贴板的其他软件冲突了。可以依次关下托盘里的软件测试一下

**Comment by i5151** [comment]
> > 最新的版本，怎么频繁出现第一次点击按钮之后，没有拷贝选择文本的情况。
> > 这些按钮之前都是好好的，前几次以为是其他软件的问题，现在不同的按钮都出现过这样的情况，才想到是Quicker的问题。
> 
> 复制选择文本的操作是向窗口发送ctrl+v，然后等待读取剪贴板。 如果不成功，通常是和某个监听剪贴板的其他软件冲突了。可以依次关下托盘里的软件测试一下

没有其他的监控软件，而且只是第一次不行，再执行就没问题了。

**Comment by cuiliang** [comment]
> > > 最新的版本，怎么频繁出现第一次点击按钮之后，没有拷贝选择文本的情况。
> > > 这些按钮之前都是好好的，前几次以为是其他软件的问题，现在不同的按钮都出现过这样的情况，才想到是Quicker的问题。
> > 
> > 
> > 复制选择文本的操作是向窗口发送ctrl+v，然后等待读取剪贴板。 如果不成功，通常是和某个监听剪贴板的其他软件冲突了。可以依次关下托盘里的软件测试一下
> 
> 没有其他的监控软件，而且只是第一次不行，再执行就没问题了。

有一些翻译、下载软件也会监控剪贴板，比如迅雷、idm什么的。

**Comment by i5151** [comment]
> > > > 最新的版本，怎么频繁出现第一次点击按钮之后，没有拷贝选择文本的情况。
> > > > 这些按钮之前都是好好的，前几次以为是其他软件的问题，现在不同的按钮都出现过这样的情况，才想到是Quicker的问题。
> > > 
> > > 
> > > 复制选择文本的操作是向窗口发送ctrl+v，然后等待读取剪贴板。 如果不成功，通常是和某个监听剪贴板的其他软件冲突了。可以依次关下托盘里的软件测试一下
> > 
> > 
> > 没有其他的监控软件，而且只是第一次不行，再执行就没问题了。
> 
> 有一些翻译、下载软件也会监控剪贴板，比如迅雷、idm什么的。

一直都安装这些软件，但之前没有问题。

**Comment by cuiliang** [comment]
我电脑上之前会和IDM冲突，开着IDM会造成读写剪贴板都特别慢，可能有时候Windows会抽风，也可能和启动顺序有关，这个具体情况还搞不特别清楚。 目前的话，可以通过我说那个方法确认一下是不是软件之间相互影响。

**Comment by i5151** [comment]
因为之前的版本没有、而且IDM一直都在，大概率是Quicker新版的原因。
