### ISSUE TITLE
软件卡死

### ISSUE THREAD

**Issue by Meli55a** [cuiliang/Quicker#520]
**描述BUG**
软件随机卡死，任务栏图标右键也无效，只能杀进程重新运行

**重现步骤**
随机出现，大概一两个小时出现一次
**相关截图**
![bug图](https://i.loli.net/2019/08/11/DvMlqtsJruxUARQ.png)

**环境信息:**
 - 操作系统版本：Win10 1903, 18362.267
 - Quicker版本：1.0.10.0
- 杀软为火绒，没有装其它电脑管理工具

**附加信息**
- Quicker 外观选择的风格是 深色半透，现在已经关闭毛玻璃效果，看是否还会出现此问题，

**Comment by cuiliang** [comment]
不好意思，刚刚能访问github来处理消息。
是使用什么弹出面板的方式？ 下次出现的时候可以试试按ctrl+alt+delete打开任务管理器，看看能不能恢复。
另外，你使用的是什么鼠标？ 鼠标是否有安装驱动（或使用windows自带驱动）？

**Comment by Meli55a** [comment]
鼠标中键弹出面板
任务管理器恢复是啥意思？只能杀进程重开软件，鼠标用的是带自双飞燕血手幽灵，带宏编程的，近两天没有再出现此问题，出现此问题时，屏幕会闪一下，今天更新了显卡驱动，再观察观察
另外，按右键有时会弹出面板，不知道是不是我鼠标的问题

**Comment by cuiliang** [comment]
右键弹出在这里设置：
![image](https://user-images.githubusercontent.com/1972649/63392876-0d564800-c3eb-11e9-9113-25e88a5feb58.png)

**Comment by CaiJie0611** [comment]
这个情况跟我一模一样，同样卡死，弹出面板不显示任何内容，一片毛玻璃，任务栏右键无法弹出退出选项，只能杀进程，而且这个随机概率是特别高。一天要七八次以上。特别窝火，一直懒得反馈，以为新开发的软件会慢慢修复，无奈更新了几代版本这个问题没受到重视，看了这个题主发出的问题已经十几天了。。

**Comment by cuiliang** [comment]
@CaiJie0611 
抱歉哦，我还不了解是什么情况。
出现的时候方便截图看一下么？ 一片毛玻璃，是指的面板窗口上只显示一个背景么？
卡住之前有使用过什么动作或做过什么操作么？

**Comment by CaiJie0611** [comment]
> @CaiJie0611
> 抱歉哦，我还不了解是什么情况。
> 出现的时候方便截图看一下么？ 一片毛玻璃，是指的面板窗口上只显示一个背景么？
> 卡住之前有使用过什么动作或做过什么操作么？

等待复现，但是截图跟题主一样，我也是设置了毛玻璃。据我所知这个情况是随机出现，偶然且经常性，面板窗口没有任何图标，就是一块毛玻璃的效果。而且之前说过，出现这个问题后任务栏图标是无法右键关闭的，只能杀进程。
之前用稳定版本，出现问题后我用了测试版本（最新），都无法解决。

操作系统：win10 LSTC 1809
应用版本：1.0.15.0，稳定版也是一样问题
裸奔系统

顺便反馈下，虽然我的电脑是机械硬盘，但是电脑干净且给我处理优化的挺好，但是启动程序鼠标会卡顿1秒，包括启动“动作”也会卡顿。希望能够尽快优化。

感谢开发者的回复。

**Comment by cuiliang** [comment]
@CaiJie0611 
机械盘卡1s可能是读取动作数据造成的。quicker数据保存在sqlite里，可能读取的时候随机IO操作比较多。ssd没有影响，但是机械盘因为随机访问性能比较差。 卡死的情况，不知道会不会和这个也有关系。ssd的情况下，因为速度快基本不会冲突，机械硬盘可能操作慢会导致某种冲突造成死锁。
额，只是猜测了。 
有条件建议换ssd，现在也很便宜，体验会是质的飞跃。

**Comment by Meli55a** [comment]
我的本子是N卡，更新后，观察到现在，一个多月，再没出现过类似的问题，so,应该不是软件的bug
