### ISSUE TITLE
鼠标中键间歇性 触发音量降低操作

### ISSUE THREAD

**Issue by ASIjacket** [cuiliang/Quicker#522]
**描述BUG**
反复对比测试后确认 再chrome或poi使用时，单击鼠标中键间歇性会触发音量下降一格问题。。。(⓿_⓿)？？？？？？？

**重现步骤**
1.每经过几十秒钟点击的鼠标中键会触发音量减低
2.对比试验确定为quiicker运行时触发， 目前只测试再cherome和poi 确定会100% 间隔一定时间 并点击中键时 触发

**环境信息:**
 - 操作系统版本：win10 1903
 - Quicker版本：1.0.4

**Comment by cuiliang** [comment]
如果未使用鼠标调节音量功能，可以在配置窗口中关闭一下试试。
![image](https://user-images.githubusercontent.com/1972649/63226343-2a342500-c20b-11e9-98e6-e6d9097f1e01.png)

**Comment by ASIjacket** [comment]
> 如果未使用鼠标调节音量功能，可以在配置窗口中关闭一下试试。
> ![image](https://user-images.githubusercontent.com/1972649/63226343-2a342500-c20b-11e9-98e6-e6d9097f1e01.png)

实测可行 应该是关闭标签页时误触发了音量调节👍
