### ISSUE TITLE
截图动作劫持屏幕

### ISSUE THREAD

**Issue by zingplus** [cuiliang/Quicker#523]
翻译动作 https://getquicker.net/sharedaction?code=8445e9db-0949-4af5-0103-08d6ac716968 在使用这个动作时，第一次操作后，在未返回结果前进行第二次操作，若第二次操作截图未完成前第一次结果返回则出现截图劫持屏幕，无法再进行操作，已多次重现这种情况，只有按Win键才能调出任务栏，然后只能重启Quicker。因该动作使用了程序的截图功能，而程序截图Esc取消经常无效，是否有关？ 
<img width="960" alt="20190818_104532" src="https://user-images.githubusercontent.com/52854447/63219542-3f2a9d00-c1a6-11e9-9c08-6a06f5483748.png">

**Comment by cuiliang** [comment]
感谢反馈。
我研究下看看。因为截图也是一个窗口，可能窗口叠加导致消息无法正常传递了。
目前的截图模块功能不支持esc退出。（开始截图以后，在截图状态下才支持）

**Comment by cuiliang** [comment]
新版显示文本改为非模态的了，应该可以解决此问题。
