### ISSUE TITLE
通用工作页加不到动作页中

### ISSUE THREAD

**Issue by gangjiegou** [cuiliang/Quicker#524]
**描述BUG**
对bug的清晰简洁描述。
我的动作页上添加不了通用的动作页，通用动作页只有默认的选项
**重现步骤**
1.
点击默认

2.
没有出现一个链接或者动作在动作页上
**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
<img width="311" alt="2019-08-19_100021" src="https://user-images.githubusercontent.com/53616197/63234607-909b6080-c268-11e9-968f-8de73a50cb57.png">
<img width="232" alt="2019-08-19_100040" src="https://user-images.githubusercontent.com/53616197/63234610-92652400-c268-11e9-90a8-897ab3ac2594.png">

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.0.4.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
通用动作页是这个里的动作页，请检查这个里有几个：
![image](https://user-images.githubusercontent.com/1972649/63237567-1ae9c180-c275-11e9-815e-17176e5897c0.png)

**Comment by gangjiegou** [comment]
![image](https://user-images.githubusercontent.com/53616197/63239294-30fb8000-c27d-11e9-9224-ac86b349320d.png)
上面这张图片是我在语雀教程上看的，但是我这里通用动作页只有默认这一个的如下
![image](https://user-images.githubusercontent.com/53616197/63239417-a5362380-c27d-11e9-84b9-af5f31a9f4ca.png)
我重启了下电脑，在我设置默认的通用动作页显示出来了，通用工作页现在改版了吗啊？只有默认这一项

**Comment by gangjiegou** [comment]
我知道了，这个是自己加上去的，这么说是之前卡了，设置好默认后就想试试（鼠标一直滚动）都没有出现通用的动作页，重启电脑，现在OK了，谢谢

**Comment by cuiliang** [comment]
不客气的。
