### ISSUE TITLE
可否告知“获取选中文本”的原理

### ISSUE THREAD

**Issue by sou1x** [cuiliang/Quicker#525]
**需求描述**
使用wireshark时，想复制这些原本无法复制的文本
![image](https://user-images.githubusercontent.com/17092109/63261142-4ee4d700-c2b5-11e9-8913-cb9b10eb4f36.png)

可否告知“获取选中文本”的原理，目前可以一条一条获取，我希望能批量获取，感谢！

**Comment by cuiliang** [comment]
模拟ctrl+c 后读取剪贴板。如果原本没法复制，Quicker也会无法复制。 建议导出后处理。

**Comment by sou1x** [comment]
感谢！我还以为是调用win32的函数获取窗体的内容呢。哈哈

**Comment by cuiliang** [comment]
关于这个实现，探索了不少方法。 获取窗体内容无法只得到选中的部分，而且有时候得到是窗体的标题。目前也就ctrl+c方式还比较通用了。
