### ISSUE TITLE
右键弹出窗体导致右键失灵，退出软件才恢复

### ISSUE THREAD

**Issue by JESSE2008** [cuiliang/Quicker#526]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Quicker版本？有没有360？ 退出360试试。

**Comment by JESSE2008** [comment]
我今天更新后出现的，上个版本还是收费之前的版本。 出现这个问题的版本是1.0.15.0 谢谢~ 在2019年08月24日 21:07 ，CuiLiang写道： Quicker版本？有没有360？ 退出360试试。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cuiliang** [comment]
> 我今天更新后出现的，上个版本还是收费之前的版本。 出现这个问题的版本是1.0.15.0 谢谢~ 在2019年08月24日 21:07 ，CuiLiang写道： Quicker版本？有没有360？ 退出360试试。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

那到底有没有用360呢？ 如果安装了360，需要关闭驱动防护+白名单才能正常。因为360或拦截模拟的鼠标事件。

另外如果没有使用右键方式激活，可以在配置中取消选项。

**Comment by JESSE2008** [comment]
退出360后果然没问题，打开360后又会出现此问题， 二者不可兼得

**Comment by cuiliang** [comment]
闭驱动防护+白名单哦。
