### ISSUE TITLE
悬浮按钮后，在面板删除按钮，再右键悬浮按钮点删除，会导致软件崩溃

### ISSUE THREAD

**Issue by gitgeekmj** [cuiliang/Quicker#527]
**描述BUG**
如题

**重现步骤**
1.悬浮一个按钮
2.删除原面板按钮
3.再去删除悬浮的按钮

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
win10
 - Quicker版本：
1.0.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈。 这时候取源动作失败了，可能需要在删除的时候判断一下。

**Comment by cuiliang** [comment]
fixed in 1.1.9
