### ISSUE TITLE
今天更新后,电脑的右键就不能用了啊

### ISSUE THREAD

**Issue by zhengmingliang** [cuiliang/Quicker#528]
**描述BUG**
今天更新后,电脑的右键就不能用了，
但是通过Quicker的按钮测试，确定我的鼠标右键没有坏，结束Quicker的进程后，右键就可以用了，确定是这个版本更新 后的问题

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.0.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
360 要添加到信任列表并且关闭驱动防护才能正常使用Quicker，要不然会被拦截消息。
另外，如果没有使用右键方式激活，可以在配置里关掉。
参考：https://github.com/cuiliang/Quicker/issues/526

**Comment by zhengmingliang** [comment]
添加了白名单不起作用，先把右键设置去掉了，然后就可以了

**Comment by cuiliang** [comment]
关闭驱动防护 不能少，360的白名单不完全白

**Comment by zhengmingliang** [comment]
> 关闭驱动防护 不能少，360的白名单不完全白

好的，十分感谢
