### ISSUE TITLE
安装后无法启动软件 卸载重新安装后也是如此

### ISSUE THREAD

**Issue by taiyoohong** [cuiliang/Quicker#529]
**描述BUG**
刚开始能用，不知道是冲突还是什么原因，后来打开软件后，只有右下角的任务栏有个小图标，点击图标也无法启动，中键无反应

**环境信息:**
 - 操作系统版本：win7
 - Quicker版本：Quicker.x64.1.0.15.0 

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by taiyoohong** [comment]
打开软件后，右键失效，无法弹出，中键也失效

**Comment by cuiliang** [comment]
删除quicker.db文件，然后重启Quicker试试。

![image](https://user-images.githubusercontent.com/1972649/63829997-94805e80-c99d-11e9-8ffa-3f3f8b08510f.png)

**Comment by cuiliang** [comment]
可以了么？

**Comment by taiyoohong** [comment]
可以了，但是为什么用着这么卡呢，还要安装office助手，还有的动作没反应，是不是这个免费版的缘故，专业版流畅吗？

**Comment by taiyoohong** [comment]
启动好几遍才能输入账号和密码，还要关闭几个软件，要不然很卡

**Comment by taiyoohong** [comment]
有的软件显示找不到指定的文件夹，像是everything之类的

**Comment by cuiliang** [comment]
很多动作需要根据自己的电脑修改的。 会依赖具体的路径。 编辑动作，看看里面的定义。
如果很卡，可能电脑性能不太能满足。 .net软件对内存和显卡有一些需求的。性能比较低的电脑不太建议安装了。

**Comment by taiyoohong** [comment]
性能应该还可以，玩吃鸡没问题，我再学习一下

**Comment by majinhui9** [comment]
无法启动，卸载重装了，旧数据删了，都不行

**Comment by cuiliang** [comment]
> 无法启动，卸载重装了，旧数据删了，都不行

已经close的issue下面容易看不到。
建议从一下方面诊断：
具体什么现象？之前正常么？ 什么时候开始不行的，电脑有做过什么更改（安装卸载软件、更新、等）？windows事件查看器里有什么错误消息？

**Comment by majinhui9** [comment]
> > 无法启动，卸载重装了，旧数据删了，都不行
> 
> 已经close的issue下面容易看不到。
> 建议从一下方面诊断：
> 具体什么现象？之前正常么？ 什么时候开始不行的，电脑有做过什么更改（安装卸载软件、更新、等）？windows事件查看器里有什么错误消息？

之前是好的，就今天开机发现启动不了了，以下是日志
System.TypeInitializationException: “Quicker.Domain.Services.WebConnector”的类型初始值设定项引发异常。 ---> System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。 (C:\Users\xlys9\AppData\Local\北京立迩合讯科技有限公司\Quicker.exe_StrongName_5xtnc0jhhkxpwehn2evmk5hx5worisjs\1.4.25.0\user.config line 16) ---> System.Xml.XmlException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。

**Comment by cuiliang** [comment]
> > > 无法启动，卸载重装了，旧数据删了，都不行
> > 
> > 
> > 已经close的issue下面容易看不到。
> > 建议从一下方面诊断：
> > 具体什么现象？之前正常么？ 什么时候开始不行的，电脑有做过什么更改（安装卸载软件、更新、等）？windows事件查看器里有什么错误消息？
> 
> 之前是好的，就今天开机发现启动不了了，以下是日志
> System.TypeInitializationException: “Quicker.Domain.Services.WebConnector”的类型初始值设定项引发异常。 ---> System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。 (C:\Users\xlys9\AppData\Local\北京立迩合讯科技有限公司\Quicker.exe_StrongName_5xtnc0jhhkxpwehn2evmk5hx5worisjs\1.4.25.0\user.config line 16) ---> System.Xml.XmlException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。

哦，有文件损坏了。C:\Users\xlys9\AppData\Local\北京立迩合讯科技有限公司\Quicker.exe_StrongName_5xtnc0jhhkxpwehn2evmk5hx5worisjs\1.4.25.0\user.config  找到这个文件删掉应该就可以了。

**Comment by majinhui9** [comment]
> > > > 无法启动，卸载重装了，旧数据删了，都不行
> > > 
> > > 
> > > 已经close的issue下面容易看不到。
> > > 建议从一下方面诊断：
> > > 具体什么现象？之前正常么？ 什么时候开始不行的，电脑有做过什么更改（安装卸载软件、更新、等）？windows事件查看器里有什么错误消息？
> > 
> > 
> > 之前是好的，就今天开机发现启动不了了，以下是日志
> > System.TypeInitializationException: “Quicker.Domain.Services.WebConnector”的类型初始值设定项引发异常。 ---> System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。 (C:\Users\xlys9\AppData\Local\北京立迩合讯科技有限公司\Quicker.exe_StrongName_5xtnc0jhhkxpwehn2evmk5hx5worisjs\1.4.25.0\user.config line 16) ---> System.Xml.XmlException: “.”(十六进制值 0x00)是无效的字符。 第 16 行，位置 1。
> 
> 哦，有文件损坏了。C:\Users\xlys9\AppData\Local\北京立迩合讯科技有限公司\Quicker.exe_StrongName_5xtnc0jhhkxpwehn2evmk5hx5worisjs\1.4.25.0\user.config 找到这个文件删掉应该就可以了。

好了，多谢
