### ISSUE TITLE
Edge新版兼容

### ISSUE THREAD

**Issue by FormatToday** [cuiliang/Quicker#530]
**需求描述**
新版edge与Chrome建议兼容

**描述你想要的解决方案**
新版edge使用了chromium内核，基本操作和Chrome一致，而现在edge分区没用动作。

**描述您考虑过的替代方案**
1.可以在设置应用程序的时候，不仅仅指定一个exe文件。
2.Chrome分区可以识别edge的exe

 **其他上下文**
无

**Comment by cuiliang** [comment]
感谢建议。 后续研究一下

**Comment by cuiliang** [comment]
现在可以设置关联程序，让edge使用chrome的动作设置了。
https://getquicker.net/KC/Kb/Article/244
