### ISSUE TITLE
更简洁的显示和防止误操作

### ISSUE THREAD

**Issue by SwingBin** [cuiliang/Quicker#531]
**需求描述**
建议把空着的格子取消加号符号，有时会时不时点到空着的加号，我的意思是，既然他是空的，那就让它禁止执行一切
![Snipaste_2019-09-04_12-37-10](https://user-images.githubusercontent.com/38577078/64226136-baaf7c80-cf10-11e9-94e7-fa6a65b82703.png)

![Snipaste_2019-09-04_12-38-49](https://user-images.githubusercontent.com/38577078/64226191-f77b7380-cf10-11e9-9154-76abb090263e.png)

建议可以把增添格子的按钮集成起来放在1区域或者2区域（如下图）
![Snipaste_2019-09-04_12-41-19](https://user-images.githubusercontent.com/38577078/64226315-78d30600-cf11-11e9-8cbd-bf4f6f19590c.png)

**Comment by cuiliang** [comment]
已增加选项
![image](https://user-images.githubusercontent.com/1972649/72710754-b70c5180-3ba2-11ea-90a3-6af8f5b19d52.png)
