### ISSUE TITLE
画圈打开面板后，是否可继续画圈隐藏面板

### ISSUE THREAD

**Issue by JasonTrue2019** [cuiliang/Quicker#532]
**需求描述**
之前关闭一段时间的画圈打开面板，最近再次打开发现还挺好用的，尤其是使用触控板的时候。
但有的时候这个启动方式会出现误触发（只是想晃晃鼠标，并没有像打开面板），而要在面板外边点一下鼠标取消有时需要挪很远（虽然近处点击鼠标也可以取消，但是近处的鼠标点击可能会对我的操作界面有影响，不得不往远方挪）

**描述你想要的解决方案**
画圈打开面板后，再画一个圈隐藏面板

**描述您考虑过的替代方案**
暂无

 **其他上下文**
暂无

**Comment by cuiliang** [comment]
暂时可以用esc关闭一下

**Comment by JasonTrue2019** [comment]
好的




------------------&nbsp;Original&nbsp;------------------

**Comment by cuiliang** [comment]
1.1.29 已增加，快速通道下载。
