### ISSUE TITLE
开机启动设置未生效

### ISSUE THREAD

**Issue by soulans** [cuiliang/Quicker#533]
**描述BUG**
软件里设置了`开机自动启动`后，依然不自动启动。
已经尝试使用管理员执行Quicker后设置，依然无效。

**环境信息:**
 - 操作系统版本：Microsoft windows版本1903（OS内部版本18362.295）
 - Quicker版本：1.0.15.0

**Comment by cuiliang** [comment]
有安装和使用了什么管家、安全类软件么？ 通常是他们拦截了注册表操作。 请尝试卸载一下这些软件，然后再开启选项后重启电脑看看能否成功自启。
这样主要是确认和什么软件有关系。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
