### ISSUE TITLE
代理网络问题反馈

### ISSUE THREAD

**Issue by CaiJie0611** [cuiliang/Quicker#534]
您好，开发者
        反馈个网络问题，我平常会使用ShadowsocksR全局代理网络，使用截图ocr动作时，却无法连接输出内容，只有关闭了代理软件才正常，能否在开启全局代理时，也可以正常使用动作，或者是 quicker本身可以提供socks5设置？

**Comment by cuiliang** [comment]
全局代理不是会代理所有网络流量么？ Quicker即使设置也没用的吧。
可以参考这里https://www.yuque.com/quicker/help/install#9bxga 试一下看看。
