### ISSUE TITLE
不能登陆

### ISSUE THREAD

**Issue by tyc877** [cuiliang/Quicker#535]
**描述BUG**
不能登陆
显示用户名和密码错误
已排除用户名和密码错误的问题 还是显示用户名与密码错误

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：
![捕获](https://user-images.githubusercontent.com/16409725/64471958-25b7b800-d18a-11e9-852f-bc69c35cb2fb.PNG)

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Quicker是什么版本？

**Comment by tyc877** [comment]
登不进去怎么看？
    On Saturday, September 7, 2019, 4:18:43 PM GMT+8, CuiLiang <notifications@github.com> wrote:  
 
 
Quicker是什么版本？

**Comment by tyc877** [comment]
是0.6.12.0    On Saturday, September 7, 2019, 4:19:56 PM GMT+8, Tang Yucheng <tang_yucheng@yahoo.com> wrote:  
 
  登不进去怎么看？
    On Saturday, September 7, 2019, 4:18:43 PM GMT+8, CuiLiang <notifications@github.com> wrote:  
 
 
Quicker是什么版本？

**Comment by cuiliang** [comment]
卸载一下从主页下载新版安装试试吧。可能版本太旧了

**Comment by cuiliang** [comment]
0.6.12 ？ 这么古老的版本呢

**Comment by tyc877** [comment]
装新版本的话那这台电脑上设置的快捷方式啥的还要重新设置嘛？
    On Saturday, September 7, 2019, 4:21:49 PM GMT+8, CuiLiang <notifications@github.com> wrote:  
 
 
0.6.12 ？ 这么古老的版本呢

**Comment by cuiliang** [comment]
应该不用的。 
但是因为这个版本太老，中间数据结构也有过变化，不清楚会不会有什么奇怪的问题。
有版本更新还尽量不要落后太多，因为数据结构会不断更新，通常只能兼容最近一段时间的版本。

**Comment by tyc877** [comment]
好了 原来的快捷方式也还在谢谢
    On Saturday, September 7, 2019, 4:25:44 PM GMT+8, CuiLiang <notifications@github.com> wrote:  
 
 
应该不用的。
但是因为这个版本太老，中间数据结构也有过变化，不清楚会不会有什么奇怪的问题。
有版本更新还尽量不要落后太多，因为数据结构会不断更新，通常只能兼容最近一段时间的版本。
