### ISSUE TITLE
一个脚本中第一次之后的”获取选中的文本“会失败。

### ISSUE THREAD

**Issue by fqzhou** [cuiliang/Quicker#536]
**描述BUG**
对bug的清晰简洁描述。
连续的两次（或多次） “获取选中的文本”，第二次以及之后的获取不到。目前试过的环境，欧陆词典、onenote、chrome。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
这里是为了验证这个问题，自己编了一组动作，主要内容是选中一句话，第一次获取存入变量C1，第二次获取存入变量C2，结果显示C1成功，C2失败。
![image](https://user-images.githubusercontent.com/10046680/64475611-7b568980-d1b7-11e9-9447-5894e84acb9c.png)
第一次结果
![image](https://user-images.githubusercontent.com/10046680/64475804-e43f0100-d1b9-11e9-8633-60f437d4e754.png)

第二次结果
![image](https://user-images.githubusercontent.com/10046680/64475805-edc86900-d1b9-11e9-9efa-871447f6a970.png)

*环境信息:**
 - 操作系统版本：
![image](https://user-images.githubusercontent.com/10046680/64475740-2f0c4900-d1b9-11e9-9955-0a9a017fa8cd.png)

 - Quicker版本：
![image](https://user-images.githubusercontent.com/10046680/64475851-8828ac80-d1ba-11e9-8e0f-f7ea1c26934f.png)

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
弹窗里确认选中了恢复焦点窗口的选项，并且在弹窗后多等待一些时间，比如300-600ms，待目标窗口获得焦点后再获取文本试试。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by fqzhou** [comment]
@cuiliang 谢谢。
确实跟弹窗有关，我禁掉了第一个弹窗就正常了，时间可以比较短1ms也没问题。
但是弹窗里面没有看到”恢复焦点窗口“的选项，如下图。能否给我说一下这个选项的位置，我好编动作的时候调试用。 
![image](https://user-images.githubusercontent.com/10046680/64632473-b4972f80-d42b-11e9-999e-ec445c5cabef.png)

**Comment by cuiliang** [comment]
弹窗显示没有恢复焦点，用户选择有。 没有恢复焦点的，要多等一些时间等待windows自动恢复。 不行的话可以增加一个恢复焦点窗口的模块。
![image](https://user-images.githubusercontent.com/1972649/64759592-2bd2dd80-d56a-11e9-8480-40d836e87129.png)
