### ISSUE TITLE
弹出面板 选择长按右键  与coreldraw x7快捷键 按住鼠标左键 点击右键 复制有冲突

### ISSUE THREAD

**Issue by wanghaochong1** [cuiliang/Quicker#538]
**描述BUG**
弹出面板 选择长按右键  与coreldraw x7快捷键 按住鼠标左键 点击右键 复制有冲突
会导致 coreldraw 鼠标左键拖动同时点击右键 复制物体的操作无效

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈。 找了一个方案，等下版本试一下。

**Comment by cuiliang** [comment]
方便的时候试下新版看看有没有解决。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
