### ISSUE TITLE
需求描述：对于长期使用的用户，如果任由所有人使用quiker, 相当于把私人电脑大量信息暴露出去，这是相当糟糕的。  解决方案：每次退出登录后再次登录应输入独立密码，用户可选择是否需要设置 

### ISSUE THREAD

**Issue by ccysmd** [cuiliang/Quicker#541]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
如果是公共电脑，每次使用完通过这个退出帐号。
![image](https://user-images.githubusercontent.com/1972649/64596640-dc17d900-d3e6-11e9-8eb3-b0f3cf94552b.png)

**Comment by cuiliang** [comment]
Quicker设计主要是私人电脑使用的场景的，所以尽量简化操作。
另外，创建case的时候，标题只写简单的摘要不要太长，详细内容在详情里写哦。
