### ISSUE TITLE
局部快捷键

### ISSUE THREAD

**Issue by vikeue** [cuiliang/Quicker#548]
**需求描述**
既然有全局快捷键 就应该有局部快捷键

**描述你想要的解决方案**
我希望我设置的一些快捷键只对于某一个软件生效，即局部快捷键
当我打开qq时，我设置的一些快捷消息的快捷键就会生效。如按f1发送你好
但是当我打开微信时f1发送的又是其他内容。

**描述您考虑过的替代方案**
我不是专业的，没啥替代方案
用鼠标点就失去了快捷的意义

 **其他上下文**

**Comment by kanglade** [comment]
「获取前台进程信息」模块 + 「按键捕获」模块（尚未实现），应该可以实现该需求。

**Comment by cuiliang** [comment]
1.4.17版本已支持。
