### ISSUE TITLE
组合动作：添加 Debug 功能支持 + 易用性提升

### ISSUE THREAD

**Issue by Moyf** [cuiliang/Quicker#55]
![image](https://user-images.githubusercontent.com/4013062/49492191-4321c380-f892-11e8-8ec8-ef6f52c21229.png)
如图，希望能：
1. 右键选择某个动作，将其暂时禁用（有时候不确定内容是否正确，但有又不想删掉重新添加，因为参数都已经设置好了）
2. 增加“Debug 模式”的选项，在该模式下，运行一个动作时能显示各个参数的内容。

还有提升易用性相关的：

![image](https://user-images.githubusercontent.com/4013062/49492309-b592a380-f892-11e8-8ef7-6fb90b23477a.png)
1. 在参数输入框底部添加「新建参数」的选项

![image](https://user-images.githubusercontent.com/4013062/49492392-07d3c480-f893-11e8-92f1-74babb7a13c4.png)
2. 在动作列表支持拖动，以及右键「添加/移出常用动作列表」。

现在的组合动作已经能满足大部分需求了，非常好用！感谢崔大开发~~
这些都是可以慢慢做的内容，仅供参考哈~

**Comment by Moyf** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/49494239-eb875600-f899-11e8-9e9d-0afe04713579.png)
> 加一条： 比较多的时候，不好找。 增加序号或在步骤里增加备注文字。

嗯，希望增加序号；
不过嵌套结构的怎么办？是按照自然顺序排下去（12、13、14）还是嵌套显示（12、12.1、12.2）？


另外再加一条：
![image](https://user-images.githubusercontent.com/4013062/49494709-86ccfb00-f89b-11e8-905a-c74dd0c9d788.png)
针对比较长的备注，鼠标悬浮的时候显示完整备注内容。

**Comment by cuiliang** [comment]
归档
