### ISSUE TITLE
无法启动quicker

### ISSUE THREAD

**Issue by bluetoothlessra** [cuiliang/Quicker#550]
**描述BUG**
软件突然无法正常启动，修复与卸载重装均无效

**环境信息:**
 - 操作系统版本：win10 x64
 - Quicker版本： 1.0.15.0

**附加信息**
无

**Comment by cuiliang** [comment]
删除一下quicker.db试试？ https://www.yuque.com/quicker/help/cannot_open_panel
是启动后有进程但是不弹出界面，还是没有进程？

**Comment by bluetoothlessra** [comment]
> 删除一下quicker.db试试？[https:](https://www.yuque.com/quicker/help/cannot_open_panel) //www.yuque.com/quicker/help/cannot_open_panel
> 是启动后有进程但是不弹出界面，还是没有进程？

已删除quicker.db，仍然无法启动，启动后有进程但很快就没有了

**Comment by cuiliang** [comment]
是不是也是最近升级了windows呢？ 看下windows事件查看器里，出错时间前后是否有错误事件。
最近有几个朋友升级了win10 8月底累积更新后有这个现象。

**Comment by bluetoothlessra** [comment]
> 是不是也是最近升级了windows呢？ 看下windows事件查看器里，出错时间前后是否有错误事件。
> 最近有几个朋友升级了win10 8月底累积更新后有这个现象。

我安装过了win10 8月底累积更新，检查了一些，确实在报错，谢谢了

**Comment by cuiliang** [comment]
> > 是不是也是最近升级了windows呢？ 看下windows事件查看器里，出错时间前后是否有错误事件。
> > 最近有几个朋友升级了win10 8月底累积更新后有这个现象。
> 
> 我安装过了win10 8月底累积更新，检查了一些，确实在报错，谢谢了

报错信息可以截图看一下么？

**Comment by bluetoothlessra** [comment]
> 是不是也是最近升级了windows呢？ 看下windows事件查看器里，出错时间前后是否有错误事件。
> 最近有几个朋友升级了win10 8月底累积更新后有这个现象。
> 
> 我安装过了win10 8月底累积更新，检查了一些，确实在报错，谢谢了
> 
> 报错信息可以截图看一下么？

![image](https://user-images.githubusercontent.com/55338487/64922076-88016000-d7fd-11e9-8af4-332906fd4347.png)

**Comment by cuiliang** [comment]
没错，都是这个d3d9.dll了。这是一个directx的文件，不晓得什么原因。
你用的显卡和驱动版本是什么呢？
可以试下运行 DxDiag 命令检测一下。

**Comment by cuiliang** [comment]
https://www.prepar3d.com/forum/viewtopic.php?t=134918
https://reshade.me/forum/troubleshooting/5729-windows-10-1903-d3d9-dll-0xc0000005-solved
https://forum.affinity.serif.com/index.php?/topic/96993-crash-on-startup/

查到了几个帖子，应该是更新导致的没错了。有一些人受到影响。 

> I think, I solved the problem. I toke an older version of the d3d9.dll, that in the KB4512941 windows update, older than 10.0.18362.329, and I copied it into the main P3D installation folder. Now I can start the sim. Thank you the tip again Randy.
这个人说他找到一个旧版本的d3d9.dll，拷贝到了目录里之后就可以了。
估计只能等微软在后续更新里解决这个问题了。

**Comment by bluetoothlessra** [comment]
> [https://www.prepar3d.com/forum/viewtopic.php?t=134918 ](https://www.prepar3d.com/forum/viewtopic.php?t=134918)
> [https://reshade.me/forum/troubleshooting/5729-windows-10-1903-d3d9-dll-0xc0000005-solved ](https://reshade.me/forum/troubleshooting/5729-windows-10-1903-d3d9-dll-0xc0000005-solved)
> [https：// forum.affinity.serif.com/index.php?/topic/96993-crash-on-startup/](https://forum.affinity.serif.com/index.php?/topic/96993-crash-on-startup/)
> 
> https://forum.gamer.com.tw/C.php?bsn=60030&snA=532891&tnum=1
> 
> 查到了几个帖子，应该是更新导致的没错了。有一些人受到影响。
> 
> > 我想，我解决了这个问题。我找到了旧版本的d3d9.dll，在KB4512941 windows更新中，早于10.0.18362.329，我将其复制到主P3D安装文件夹中。现在我可以开始使用SIM卡了。再次感谢Randy的小费。
> 
> 这个人说他找到一个旧版本的d3d9.dll，拷贝到了目录里之后就可以了。
> 估计只能等微软在后续更新里解决这个问题了。

感谢大佬解答(┌・ω・)┌✧谢谢惹
