### ISSUE TITLE
外观间隙为0时效果不彻底

### ISSUE THREAD

**Issue by mifenfeifen** [cuiliang/Quicker#56]
在设置-外观中，将间隙调为0后，左右间的间隙效果很好，但上下间的间隙效果不彻底
![snipaste_2018-12-05_14-00-06](https://user-images.githubusercontent.com/16129288/49493337-b62d3900-f896-11e8-968c-2a6194e40b23.png)
放大效果：
（红框为标示）
![snipaste_2018-12-05_14-06-05](https://user-images.githubusercontent.com/16129288/49493396-f096d600-f896-11e8-98e2-f630c68e89f1.png)

**Comment by mifenfeifen** [comment]
实际截图中体现不明显，但在背景为白色的页面打开quicker面板，白线会更为显眼

**Comment by cuiliang** [comment]
收到，我也发现了这个现象。

**Comment by cuiliang** [comment]
经尝试似乎无法解决，暂时close了。
wpf的机制不是像素对齐的，设置成小的负值也无法调整成一样的颜色。但有时候又看不出来，先不管啦
