### ISSUE TITLE
在我用其他电脑打开软件使用时可以在应用里增加一个“是否同步其他设备的设置”这样的选项吗？

### ISSUE THREAD

**Issue by 1023550193** [cuiliang/Quicker#560]
我有三台电脑都安装了Quicker都是同一个账号，然后每次在不同的电脑上使用它的时候都会自动应用我在上一台电脑里的应用打开位置，但是这三台电脑的应用存放位置都是不一样的所以我每次都得自己手动修改回适用于我目前所操作的这台电脑的应用快捷地址，这太愚蠢了

**Comment by cuiliang** [comment]
1. 专业版支持动作页主机绑定，可以为不同的电脑定义独立的动作页。

2. 运行类动作可以设置备用路径。
![image](https://user-images.githubusercontent.com/1972649/65326361-d8a10080-dbe3-11e9-9ea7-7ab24f3e4bef.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
