### ISSUE TITLE
文本悬浮窗改进考虑

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#563]
讨论帖：https://getquicker.net/Forum/ViewTopic/1130
黑名单：对此名单中的应用不启用；
白名单：对此名单中的应用只要抬起鼠标就显示悬浮；
自动显示的几个动作，其他展开再显示

文本模式和点击模式？文本模式：当前的，按光标判断；点击模式：只要抬起鼠标就显示？相当于一直跟随鼠标的一个动作页。

**Comment by firestarman-james** [comment]
建议对悬浮窗增加**双击窗口标题**切换到完整窗口的功能。

**Comment by firestarman-james** [comment]
建议给悬浮标增加一个延时自动消失的功能，用户可自己设置时长，然后考虑增加外观可选项（大小、性状、配色等）。

**Comment by firestarman-james** [comment]
双击左键时悬浮标也会相应闪烁两次，建议增加淡入淡出动画。
鼠标点击不同位置时，希望悬浮标能有个平移动画。

**Comment by firestarman-james** [comment]
悬浮标拖到屏幕最右侧时（实际会跟屏幕右侧边缘有一定距离），如果在悬浮标所在横向位置的任意纵向点击鼠标，悬浮标就会直接出现在鼠标位置，很容易引发误操作。建议增加鼠标位置判断，确保悬浮标出现的位置一定避开鼠标位置。
