### ISSUE TITLE
使用Ctrl作为唤醒键会与Word粘贴选项按钮弹出功能冲突

### ISSUE THREAD

**Issue by EX-XD** [cuiliang/Quicker#565]
**描述BUG**
在Quicker开启了Ctrl键作为弹出面板激活辅助按钮时（具体设置为【Ctrl+右键】激活），在MS Office 365中粘贴后右下角不会出现带Ctrl提示的粘贴选项面板。

**重现步骤**
1.在Quicker设置中开启【Ctrl+右键】激活；
2.Word中正常使用粘贴命令，粘贴选项按钮不会弹出；
3.退出Quicker；
4.Word粘贴选项按钮恢复正常；
5.重启Quicker；
6.粘贴选项按钮失效；
7.在Quicker中关闭【Ctrl+右键】激活；
8.Word粘贴选项按钮正常。
（以上步骤可能涉及Quicker以及Word的重启才能复现）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 Pro/Home 1903（18362.356）64bit with MS Office 365（16.0.11929.20288）64bit
 - Quicker版本：1.1.20.0

**附加信息**
粘贴选项按钮就是每次粘贴后右下角弹出的那个显示着Ctrl和一个下拉箭头的按钮，此时点击Ctrl或者用鼠标点击按钮，会弹出选择性粘贴的面板，对于多文件间复制粘贴内容很有帮助。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/65396000-62172500-ddd4-11e9-8b72-79769dcd1e29.png)

是说这个位置么？
我测试了一下，是正常的，目前的配置为：
![image](https://user-images.githubusercontent.com/1972649/65396054-8ffc6980-ddd4-11e9-9e27-b7a75ef9555d.png)

粘贴选项是否出现是和粘贴的内容有关系的。 
如果是从记事本里复制的内容，粘贴的时候没有这个选项（剪贴板里只有纯文本），如果是在网页里复制，粘贴就会有（这时候剪贴板里有多个格式类型）。
Quicker启动的时候，有没有在运行什么和剪贴板有关的动作？

**Comment by EX-XD** [comment]
应该不是Quicker的问题，好像是Word本身的问题，或者其他某个软件冲突……
从其他源复制过来的内容粘贴后都会弹出选项，在Word内复制的内容就会在慢速粘贴时出问题，快速反复点击Ctrl+V的前一两次不弹出，后面连续弹出。
准确地说也不是不弹出，是一弹出就消失掉……
看来要去微软社区问问
