### ISSUE TITLE
建议增加更多的触发弹出选项或功能

### ISSUE THREAD

**Issue by firestarman-james** [cuiliang/Quicker#570]
**需求描述** 

**1. 建议增加双击ctrl触发弹出的选项。**因为ctrl作为常用组合键（比如ctrl+shift/c/v）的其中一个按键，很容易出现按下了ctrl但没实际按下其他键（按到其他键但没实际按下去）的情况（尤其是ctrl+shift这种耗时最短的组合按键），这种情况意外弹出窗口容易打乱思路。

**2. 建议增加类似于早期QQ的停靠在桌面边缘时自动隐藏功能**（可参考http://www.rjzxw.com/diannao/589.html 的描述），鼠标移到桌面边缘时弹出窗口，平时自动隐藏。

PS：有同好滴童鞋们请给点赞支持。

**Comment by cuiliang** [comment]
暂不增加额外的触发方式了。
