### ISSUE TITLE
分享动作页

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#571]
分享整页相关的动作，比如一个数字键盘、所有一些语雀相关的操作等。

**Comment by 222YEDONG** [comment]
这个动作页 我之前想提issues来着 还添加滴答清单任务了，有人提那就不用说了。

- 很想让一些动作大神 分享一下自己的动作页布局，在用哪些动作页，日常工作生活流程是什么样的，等等。

- 目前动作搞的稍微有点多，不知道怎么整理好，【包括以往实验功能模块时的各种动作，乱七八糟，谷歌浏览器已经有16页了，希望早点支持检测不同网页，根据网址切换设置面板，和应用程序一样】

- 动作多了，面板整理不太方便，有没有可能更加灵活一些 @cuiliang 比如同时显示两个面板，然后 动作全部悬浮起来，移动整理好之后 就关闭悬浮，就按之前的整理的位置设置【仪表盘窗口功能挺不错的，但好像移动不了动作，只能看4个固定的面板】
