### ISSUE TITLE
悬浮标在二次选中时可否更新位置

### ISSUE THREAD

**Issue by JasonTrue2019** [cuiliang/Quicker#576]
**需求描述**
有的时候选中了一段文字，没有用到动作按钮，比如只是在word中给它标了颜色。
然后我选中另一段文字，打算要触发动作了，结果悬浮标还在第一段文字那边飘着，
鼠标要挪比较远才够得着。

**描述你想要的解决方案**
选中第二段文字的时候，悬浮标位置更新到跟前来

**描述您考虑过的替代方案**
或者第一段文字选中后，过了几秒没有操作自动隐去悬浮标？
这样感觉不太好，有的时候就是犹豫了那么几秒又要重新选择还是麻烦一些。

 **其他上下文**
暂无

**Comment by cuiliang** [comment]
是说的这个功能不? https://www.yuque.com/quicker/help/text-select-float-panel
悬浮标应该会自动更新位置的。录屏看一下？

**Comment by JasonTrue2019** [comment]
是这个功能。
是说如果选中后没有触发动作。然后再次选中的时候，不会更新位置。


如果是选中后触发了动作，再次选中的时候，位置是会更新的。




------------------&nbsp;Original&nbsp;------------------
