### ISSUE TITLE
能否不要关闭已经加载的面板

### ISSUE THREAD

**Issue by hh23485** [cuiliang/Quicker#579]
**需求描述**
我对面板归了一些类在通用类型中，但在不同的app中打开的时候，默认不加载默认类别的面板，这就比较苦恼。

**描述你想要的解决方案**
希望，能够允许不自动关闭之前加载的面板。
也就是说，如果我手动点击了某个面板的加载，那么当我切换app，或者在接下来一段时间里，或者是直到退出，每次换出quicker时，手动加载的面板都一直在下方，可以通过滚轮直接切换到。

**描述您考虑过的替代方案**
Null

 **其他上下文**
Null

**Comment by cuiliang** [comment]
可以放在全局动动作页，或者在应用设置里附加一些通用动作页。
手动加载的动作页会在切换软件后消掉。
![image](https://user-images.githubusercontent.com/1972649/65669764-b80af780-e076-11e9-93e3-7afc600d88d7.png)
