### ISSUE TITLE
在一组连续的组合动作中设置一个暂停点

### ISSUE THREAD

**Issue by bigboybo** [cuiliang/Quicker#59]
在一组连续的组合动作中插入一个手动输入的动作，然后检测到这个键输入后再执行后续的动作。否则一直保持手动键入的按键之前的动作？？

**Comment by cuiliang** [comment]
0.9.44 增加“等待窗口” 模块可以实现此功能。详见：https://www.yuque.com/quicker/help/showwaitwin
