### ISSUE TITLE
为动作增加“配置”分支

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#602]
可以动作上右键启动配置分支操作，修改动作里的参数。

**Comment by kanglade** [comment]
其实可以自由一些，不一定是配置，还可以是其他步骤（分支）。可以设计一个特殊的步骤组（可以标为蓝色），当触发这个分支后（我想的触发方式有：①右键选择「配置」项；②Ctrl+点击动作；③双击动作），直接进入这个特殊步骤组执行步骤，这个步骤和普通步骤其实一样，只是会优先执行，然后再执行它后面的其他步骤。

**Comment by kanglade** [comment]
如果没触发，则不执行里面的步骤。

**Comment by cuiliang** [comment]
现在一般使用按ctrl触发动作进入配置。不再另行开发功能了。
