### ISSUE TITLE
安装完软件，鼠标很卡

### ISSUE THREAD

**Issue by wlbookwl** [cuiliang/Quicker#605]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.感觉鼠标很重，很迟钝，没有鼠标的手感。
2.鼠标在任务栏上的时候也很卡。
3.看到可以自定义这么多动作库，确实不错。想订阅，但装上这个软件 系统鼠标被拖慢很多，很容易鼠标的轨迹很容易跳动，是不是我设置的有问题？下面你看看截图。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
![image](https://user-images.githubusercontent.com/28977668/66715069-7eb1e600-edf1-11e9-8e45-3bca2497a842.png)

 - Quicker版本：
![image](https://user-images.githubusercontent.com/28977668/66715056-6e017000-edf1-11e9-917d-2796971e4cfe.png)

**附加信息**
在此添加有关此问题的任何其他上下文。
![image](https://user-images.githubusercontent.com/28977668/66715119-03046900-edf2-11e9-8a2d-c6af11f5c784.png)
![image](https://user-images.githubusercontent.com/28977668/66715125-29c29f80-edf2-11e9-9fa0-963acb47f122.png)
![image](https://user-images.githubusercontent.com/28977668/66715194-d270ff00-edf2-11e9-8d84-5e0c4efdad1f.png)

**Comment by cuiliang** [comment]
可能是机器的性能不太能满足WPF运行的需要了。 WPF对内存和显卡都有一定的要求。 另外可以测试一下把托盘里的其他运行的软件暂时退出一下看看有没有改善。

**Comment by wlbookwl** [comment]
装了一个rolan 并不卡。可能软件原理不一样？

**Comment by cuiliang** [comment]
不一样的。严格来说Quicker和rolan不是一类程序的。 Rolan只是一个启动器，Quicker是一个运行环境。
Quicker使用WPF渲染，对于一个10年前的2核cpu来说，可能压力是有点大了。

**Comment by wlbookwl** [comment]
嗯。确实Quicker比较强大。rolan有点太简单点了。我换个电脑看看。

**Comment by cuiliang** [comment]
后来的版本优化了鼠标移动的处理。 请尝试1.3.19版本。
