### ISSUE TITLE
用quicker贴图，贴出的图片会发虚

### ISSUE THREAD

**Issue by biack519** [cuiliang/Quicker#606]
**描述BUG**
贴同一张图，用quicker贴出的图片会发虚，透明度为100%。其他软件（天若OCR）贴就没有问题，和直接打开原图效果一样。
**相关截图**
![屏幕截图(4)](https://user-images.githubusercontent.com/43265287/66716473-a6f51100-ee00-11e9-81f4-2988298d4f48.png)

左边是图片管理器直接打开，右上是quicker贴图，右下是其他软件贴图，

**环境信息:**
 - 操作系统版本：win10 1903
 - Quicker版本：1.1.31.0

**Comment by cuiliang** [comment]
感谢反馈。
是从剪贴板还是文件里读取的文件？ 
屏幕dpi缩放比例是多少？
Quicker使用WPF渲染，WPF里面处理方式不是像素对像素，而是使用的设备无关的单位，如果屏幕dpi比例不是100%，某些情况可能会不完全匹配到像素上。
后续可能重写图片显示模块改成Winform的方式。

**Comment by biack519** [comment]
哦 这样啊  我就是直接从剪贴板读取  调回100%再试还是会有这个问题  分辨率会变低  用quicker贴出的图片会直接变小   
![Honeyview_2019-10-14_03_20_12](https://user-images.githubusercontent.com/43265287/66734577-3ac4ec80-ee96-11e9-9196-41a7d1e0ebc9.png)

暂时还是得用其他软件 期待改进

**Comment by cuiliang** [comment]
应该已经解决了。如果还有请再reopen
