### ISSUE TITLE
提供一个powershell模块, 可以读取和设置动作变量.

### ISSUE THREAD

**Issue by zhoujin7** [cuiliang/Quicker#608]
**需求描述**
提供一个powershell模块, 可以读取和设置动作变量.
类似"运行Javascript代码"和"运行C#代码片段".

**描述你想要的解决方案**
提供一个powershell模块, 可以读取和设置动作变量.

**描述您考虑过的替代方案**
**目前的解决办法:**
![232](https://user-images.githubusercontent.com/8288988/66843938-0c333880-efa0-11e9-937b-4a3ae200ec77.png)

 **其他上下文**
![20191015225903](https://user-images.githubusercontent.com/8288988/66843896-fc1b5900-ef9f-11e9-878e-a42bdc571167.png)

**Comment by cuiliang** [comment]
Shell是独立的进程，没法直接传递参数。 要通过组装脚本或使用剪贴板传递信息。
