### ISSUE TITLE
同时显示多个通知消息的时候，有时候消息框不会自动消失

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#61]
![image](https://user-images.githubusercontent.com/1972649/49737253-5506ca80-fcc7-11e8-94c0-d35901f6ad1f.png)

**Comment by i5151** [comment]
这个问题从最开始用的时候就有，关注其他的问题把它忽略了。

**Comment by cuiliang** [comment]
好像没有再出现了，先关为净😂
