### ISSUE TITLE
"显示文本" 支持自定义字体

### ISSUE THREAD

**Issue by zhoujin7** [cuiliang/Quicker#610]
**需求描述**
"显示文本" 支持自定义字体. 
使用场景: 比如用来显示生成的代码, 需要使用等宽字体.
https://www.yuque.com/quicker/help/showtext

**描述你想要的解决方案**
![image](https://user-images.githubusercontent.com/8288988/66885082-c8731a00-f005-11e9-89f6-793d4989f857.png)

**描述您考虑过的替代方案**
无

 **其他上下文**
无

**Comment by cuiliang** [comment]
已增加，等后续版本更新。
![image](https://user-images.githubusercontent.com/1972649/67013748-344ca400-f126-11e9-8cba-fb9c288a901e.png)
