### ISSUE TITLE
CTRL+右键启动

### ISSUE THREAD

**Issue by nashtian** [cuiliang/Quicker#62]
当鼠标在屏幕偏上，或偏下时，CTRL+右键启动，QUICKER会相应右键事件，弹出QUICKER的上下文菜单。
这样会增加一次无意义的左键，来取消这个菜单。

QUICKER是否考虑增加一个判断，当启动方式是CTRL+右键时，就不要响应CTRL+右键的事件了。

**Comment by cuiliang** [comment]
收到，谢谢反馈

**Comment by i5151** [comment]
上一版已经解决这个问题了，而且解决得很好。7.14版上午装的，你这么一说，我刚试了一下，果然又重现这个问题了。

还包括任务栏，系统的右键菜单又重新出来了，就是Ctrl+右键 之后，有个右键点击动作没有处理干净。

建议在左上右三个边（尤其是不足界面半个宽度的）呼出主界面的时候，把鼠标指针也同样移动界面中点，为下步的动作按钮点击做准备，放在中点（中框中点）是到各个按钮最方便的位置。

**Comment by i5151** [comment]
@cuiliang 
鼠标在边缘呼出主菜单的时候，最好也把鼠标指针移动中点。就是没有右键菜单打开，也会显示按钮提示，界面显得乱、点击距离远不说，还容易误点击其他按钮。

**Comment by i5151** [comment]
还有一个小问题：动作按钮面板，我按住一个按钮放到另一个按钮上，总是显示让我检查网络。我再呼出主界面，按钮其实已经调整好了，但有时，重启电脑之后，按钮又回到了原来的位置。

**Comment by cuiliang** [comment]
@i5151  在用户没有指示的情况下，移动鼠标我感觉是不太合适的。 另外有一些动作要要点动作按钮以后把鼠标指针还原到弹出面板之前的位置去模拟点击，如果移动了鼠标指针，位置就变化了。 可以等以后有时间做一版体验一下试试。   网络存储是异步过程，提示失败的话，说明没有保存到服务器，下次重启肯定会丢掉之前的修改。 这个等以后做了后台同步应该可以缓解一下。

**Comment by i5151** [comment]
@cuiliang 
你说的也有道理，指针不移动也没关系，只是得把多余的右键处理掉。

![FtpaLj.png](https://s1.ax1x.com/2018/12/12/FtpaLj.png)
现在调整按钮位置经常就是弹出这个窗口，再打开主界面，按钮位置还调整好了。

但恢复系统之后，位置又回到之前的状态。我恢复系统并没有改变对云上的设置，这是为什么？

**Comment by cuiliang** [comment]
@i5151 说明没有成功保存到服务器，下次登录的时候重新下载了服务器的配置。可能是上传网速太慢的缘故，可以试试改用手机热点连接看看有没有改善。你用的哪个运营商的网络？ 等以后做好后台同步，应该可以解决这个问题，那时候本地会存一份配置，这样不会被云端覆盖掉了。

**Comment by i5151** [comment]
北京联通 光纤500M，上传刚升级到50M。

那样还可以离线操作，一定要考虑同步的准则问题。比如：平时存配置到本地，之后同步到云，这没有问题；但我配置改变也同步到云了，之后恢复系统了，备份的是改变之前配置，怎么办？是继续同步老配置到云，还是从云中下载新配置？

这就需要一个冲突解决的准则，可以以时间为准：时间最新的就是最正确的配置，就用新的覆盖老的。
可以以一端为主：产生冲突之后，以一端覆盖另一端，但这么做的缺点就是可能会出现老配置覆盖新配置，使之前的修改前功尽弃，如果改的多且复杂，是很麻烦的。

我一直在用的Goodsync，同步就必须解决冲突的最终准则问题才不会出错误。

以时间为准是最好的，最不可能出错的。但时间为准时，必须设定一个配置的总体时间，不要看每个具体配置的时间。因为有的配置上传之后，再恢复系统，老的配置可能没有这个配置信息，软件就无法判断新老而无所适从产生错误，设置一个配置改变的总体时间就不会产生这个问题。

Goodsync就有这个问题，老配置没有问题，它无法判断时间，产生错误，我只能用一端覆盖另一端，但这样做，我恢复系统之后，有时就会丢掉之前的设置。

**Comment by i5151** [comment]
@cuiliang 
我退回到7.11版了，这个版本的任务栏和边缘点击就处理得很好，按照你的设想应该是最理想的状态了。而且识别应用程序很准确，还没有出过错误。

**Comment by cuiliang** [comment]
更新了。 重启一下软件会有提示

**Comment by i5151** [comment]
好，我试一下。

**Comment by i5151** [comment]
随便再提个建议：我点击下载最新版的按钮之后，升级提示的窗口最好应该关闭了。

**Comment by i5151** [comment]
再提个建议：鼠标右键的按钮信息提示，能不能在设置中加个选项可以开关。因为按钮具体的作用都知道，而且就是名称（如果显示的话），提示有添乱之嫌，尤其在边缘呼出界面的时候。

**Comment by i5151** [comment]
![FaUsWd.jpg](https://s1.ax1x.com/2018/12/15/FaUsWd.jpg)

**Comment by cuiliang** [comment]
@i5151 可能用户还需要看一下更新内容，所以直接关闭掉不太好的。
“鼠标右键的按钮信息提示” 指的是哪个？是鼠标悬浮的时候显示的tooltip么？

**Comment by i5151** [comment]
不是先看完更新内容才下载的吗？其实要不是今天在看游泳世锦赛的时候登录网站看了下文档，发现你刚刚增加的新版文档，我一般都不看更新内容，反正有新版更新就得了，肯定没错。

你说的对，我被鼠标右键带偏了，是鼠标悬浮提示😂😂😂

**Comment by cuiliang** [comment]
tooltip并不是马上显示的，悬浮一段时间才会显示，鼠标移动的快的话就不会看到的。 有时候动作多了，比较容易忘记，有个提示还是挺好的。

**Comment by i5151** [comment]
但在边缘呼出界面的时候，鼠标正好在按钮上边，呼出界面之后立刻就有提示，显得很乱，总以为自己按错了按钮。

有提示是挺好，但也有不喜欢提示的。不如加个选项，让不需要提示的人可以关掉。

**Comment by i5151** [comment]
我刚试了一下，鼠标悬浮提示的速度，是立刻提示，没有延迟。

要不在右键菜单中加个属性选项，其中就有按键的说明。而且还可以设置按键的固定位置属性：比如固定，不能轻易移动删除，防止误删除误移动；或是能给按钮加密码，增加专用的性质，等等。
