### ISSUE TITLE
如何在不用quicker的时候默认不显示

### ISSUE THREAD

**Issue by whitmansir** [cuiliang/Quicker#624]
只想在鼠标按下滚轮的时候需要它，不需要的时候不想显示它

**Comment by cuiliang** [comment]
正常情况下都是不显示的呀，需要的时候通过配置的触发方式弹出。
如果你的关不掉，看看是不是钉住了。
![image](https://user-images.githubusercontent.com/1972649/67569093-7b5b1a80-f760-11e9-8bd5-8b47d51d9524.png)

**Comment by whitmansir** [comment]
没有被定住，但是我的是弹出以后就一直显示了，怎么设置用完以后自动消失，谢谢

**Comment by whitmansir** [comment]
[
![image](https://user-images.githubusercontent.com/43739375/67569287-0c31f600-f761-11e9-9e01-d767a2f79ec6.png)
](url)
比如这个，截图后就一直存在了。

**Comment by cuiliang** [comment]
录个动画看看？ 是什么方式弹出的？点击动作之后动作执行了么？ 
quicker版本是多少？

**Comment by whitmansir** [comment]
动作有执行，版本是1.1.31.0。就是执行完动作以后界面还是存在的，他不能在执行完后自动消失吗？

**Comment by cuiliang** [comment]
正常是消失的， 我也不是很清楚在你电脑上发生了什么。 有试过重启一下电脑么？ 另外你的电脑有没有安装什么手势软件、桌面增强软件之类的？

**Comment by whitmansir** [comment]
你好。我重启了一下好了。感谢您耐心的回复。谢谢

**Comment by cuiliang** [comment]
不客气的，这个现象确实比较奇怪，第一次碰到。
