### ISSUE TITLE
不显示图标

### ISSUE THREAD

**Issue by zrs-ipe** [cuiliang/Quicker#627]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
请参考 https://getquicker.net/Forum/ViewTopic/315

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
