### ISSUE TITLE
鼠标中键覆盖其他 软件操作

### ISSUE THREAD

**Issue by yws112358** [cuiliang/Quicker#629]
**描述BUG**
用着SSR，中键任务栏图标是服务器统计界面，方便控制开关和流量统计。但是设置中键（个人使用较方便，双击中键感觉很别扭）后无法开启ssr该功能
添加黑名单只能添加explorer进程，这样也不是合适的解决方法。

**重现步骤**
1.中键单击ssr图标弹出主界面

**环境信息:**
 - 操作系统版本：win10企业版 1903
 - Quicker版本：1.1.31

**Comment by cuiliang** [comment]
目前只能改成其他没有冲突的激活面板方式，
托盘区是没法用黑名单控制的。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
