### ISSUE TITLE
鼠标侧键触发软件问题

### ISSUE THREAD

**Issue by 1situzj** [cuiliang/Quicker#630]
**需求描述**
    当按下鼠标侧键 ( 例如 X2 )触发软件时, 移动鼠标到某个选项, 此时松开触发键就会直接触发该选 
    项, 导致有时会误触发

**描述你想要的解决方案**
    提供 "触发键按下就触发软件" 和 "触发键按下再松开才触发软件" 的设置选项

**Comment by cuiliang** [comment]
这个方式和中间等方式下，如果触发后松开前没有移动鼠标，松开的时候不会触发动作。如果移动了鼠标一段距离再松开，就会触发动作。 
为的是减少一次鼠标点击。
如果不希望执行动作，在弹出面板后先松开按键再移动鼠标试一下。

**Comment by 1situzj** [comment]
因为使用侧键需要拇指用力, 导致鼠标受力不均而移动, 有时候这种情况比较难避免. 可以添加 "触发键按下再松开才触发" 的选项吗?

**Comment by cuiliang** [comment]
侧键确实是比较容易位移，我考虑一下。

**Comment by 1situzj** [comment]
好的, 感谢

**Comment by cuiliang** [comment]
增加了判断，移动小于10像素的时候不触发动作。
