### ISSUE TITLE
把有选择状态和无选择状态可以区分开来？

### ISSUE THREAD

**Issue by rushpixy** [cuiliang/Quicker#637]
比如桌面 有选择文件 和 没选择时 弹出的 不一样.
浏览器 有选择文本和没选择文本时  弹出的 不一样.

**Comment by cuiliang** [comment]
Quicker实现判断这些内容对电脑来说会是一个额外的负担，会影响剪贴板里的内容，减慢面板的弹出速度。
而且要执行的动作也不一定是对选中内容进行操作的。
