### ISSUE TITLE
任务栏图标上的中键

### ISSUE THREAD

**Issue by iPerfectman** [cuiliang/Quicker#643]
任务栏上的图标原本中键的含义是创建新的窗口，可不可做到中键点击任务栏空白区域还是现在的这种情况，但是右键任务栏中的活动窗口或者已经打开的窗口的图标上边时，还是任务栏原本的操作

**Comment by cuiliang** [comment]
窗口结构在这里没法进一步划分了，任务栏上面整个是一个窗口，所以好像没法判断是在图标上点还是在空白区域点的。
