### ISSUE TITLE
鼠标滚轮无法切换动作页

### ISSUE THREAD

**Issue by windxiang** [cuiliang/Quicker#644]
**描述BUG**
使用鼠标滚轮无法切换动作页，非常不方便

**重现步骤**
1.用鼠标中间弹出窗口
2.在页面上使用鼠标滚轮
3.无法切换动作页

**环境信息:**
 - 操作系统版本：Windows
 - Quicker版本：1.1.41

**Comment by cuiliang** [comment]
确保已经创建了多个动作页。
关闭所有的手势有关的软件，然后测试一下看看。 
请截图协助确认。

**Comment by windxiang** [comment]
已经确认，存在多个动作页。

**Comment by windxiang** [comment]
![image](https://user-images.githubusercontent.com/3348349/68536955-8a63de80-0396-11ea-9370-67d8be05db4d.png)

**Comment by windxiang** [comment]
和StrokesPlus_x64软件冲突

**Comment by cuiliang** [comment]
StrokesPlus 软件里有滚轮操作的话可以关闭一下试试。

**Comment by windxiang** [comment]
修改StrokesPlus 配置后运行正常了。

**Comment by cuiliang** [comment]
> 修改StrokesPlus 配置后运行正常了。

修改的哪个地方，方便截个图么？ 我等写到文档里

**Comment by windxiang** [comment]
![image](https://user-images.githubusercontent.com/3348349/68537013-eaa75000-0397-11ea-98f7-37b8dd892fb4.png)

**Comment by windxiang** [comment]
截图已上传

**Comment by cuiliang** [comment]
> 截图已上传

谢谢
