### ISSUE TITLE
反馈运行动作导致软件出现问题

### ISSUE THREAD

**Issue by CaiJie0611** [cuiliang/Quicker#645]
**描述BUG**
动作链接
[天若OCR截图_增强](https://getquicker.net/Sharedaction?code=d1809cb3-16b8-4cac-13a3-08d667563b50)
[天若文字识别](https://getquicker.net/Sharedaction?code=fd9424df-8a93-49c2-0385-08d66ec50dc9)
描述：1.使用动作，自动运行软件并且自动运行快捷键截图，弹出的OCR识别窗口是空白且无法关闭，需要在任务托盘右键关闭天若。
             2.不使用动作，正常。
             3.删除动作中的自动运行程序的模块，只启用运行程序中的快捷键模块，保存，先打开天若OCR，然后再使用动作，OCR程序弹出的窗口是正常的。
     
**相关截图**
1.正常弹出
![20191110_061832](https://user-images.githubusercontent.com/31266850/68542325-8bbcf780-03e6-11ea-8726-7ead8ceaab87.png)

2.不正常弹出
![20191110_054616](https://user-images.githubusercontent.com/31266850/68542333-a1322180-03e6-11ea-8d5f-19fa469d68d8.png)

**环境信息:**
 - 操作系统版本：win 10 1909 
 - Quicker版本：1.1.41.0

**附加信息**
天若ocr（老版） 程序文件
链接: https://pan.baidu.com/s/1SSEDPuZt9nEmdcPdvQsu3Q 提取码: q3rg

**Comment by cuiliang** [comment]
具体动作的设计我没有详细了解过。 
可以右键编辑一下动作步骤，看一下实际实现的方式是否和当前要操作的天若版本匹配。 
有可能会因为要操作的软件版本更新导致某些步骤失效。

**Comment by CaiJie0611** [comment]
天若ocr（老版） 程序文件
链接: https://pan.baidu.com/s/1SSEDPuZt9nEmdcPdvQsu3Q 提取码: q3rg


![20191110_063208](https://user-images.githubusercontent.com/31266850/68542538-72b54600-03e8-11ea-9283-53e2d15734d3.png)

**Comment by CaiJie0611** [comment]
不修改动作，提前打开“天若ocr”，再运行动作，正常。
是动作脚本有问题还是？

**Comment by cuiliang** [comment]
这个动作看起来很简单，如果没有运行天若就先启动起来。具体它为什么表现不一样，可能需要天若来解释了。 
另外可以试下单独创建一个动作打开这个程序看看是不是正常。

**Comment by CaiJie0611** [comment]
创建了直接打开程序的基础动作后，使用快捷键或者用组合动作，弹出的窗口都不正常了。
这样意味着天若程序的问题了？

**Comment by cuiliang** [comment]
> 创建了直接打开程序的基础动作后，使用快捷键或者用组合动作，弹出的窗口都不正常了。
> 这样意味着天若程序的问题了？

是的，Quicker只是调用Windows的Process.Start接口启动进程。可能你使用的版本对启动环境有什么要求。
另外你可以试试在模块里设置一下“工作目录”参数，设置成exe文件所在的文件夹，看看有没有什么变化。
