### ISSUE TITLE
再次打开搜索的时候清除搜索框的内容

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#646]
From A.B

> 大佬不好意思又打扰你了，我想问下搜索框这个功能可否增加一个选项，就是再次唤出搜索框时默认为空呢？现在的情况是如果搜索框搜索过内容，再次唤出搜索框时保留了上一次搜索的关键词，但个人觉得大多情况下，如果上一次搜索过一个关键词，下次必定会在搜索框的历史记录里面首位，如果需要选择已经非常方便，而现在保留了上一次搜索的关键词，所以要查看最近使用过的动作历史记录必须按一次退格键。

**Comment by kanglade** [comment]
我也这么觉得，甚至觉得不需要增加选项，直接为空。
