### ISSUE TITLE
用户输入模块增加指定弹出位置功能

### ISSUE THREAD

**Issue by wwbrave** [cuiliang/Quicker#647]
**需求描述**
有的动作需要照屏幕上抄点内容（比如验证码，不好识别的那种，要“人工”智能），这个时候弹出的用户输入窗口刚好挡住验证码就很尴尬，每次都要手动挪一下……如果能指定弹出位置，应该方便很多。

**描述你想要的解决方案**
默认居中弹出，可以设定X和Y轴偏移量即可。

**描述您考虑过的替代方案**
如果麻烦的话也可以做几个选项，如居中、左下角、左上角、右下角、右上角这样。

 **其他上下文**
无。

**Comment by cuiliang** [comment]
1.4.4 加入。
