### ISSUE TITLE
高DPI下的鼠标点击错位问题

### ISSUE THREAD

**Issue by snomiao** [cuiliang/Quicker#649]
环境：4k屏，125%放大
目标软件：PanDownlaod

动作：
https://getquicker.net/Sharedaction?code=1c35a172-1969-4703-20f3-08d742f11f76

故障描述：
点击错位，无法完成功能

**Comment by cuiliang** [comment]
具体动作的问题请在问题下留言。
不过对于这类根据坐标定位的动作，在不同的分辨率下通常都会失效。 请根据自己的情况修改一下坐标，或者看看能不能改成使用键盘操作的方式实现。
