### ISSUE TITLE
Windows10 安装提示错误

### ISSUE THREAD

**Issue by MarvelTexas** [cuiliang/Quicker#650]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.安装错误提示
2.The system cannot open the device or file specified

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![Untitled](https://user-images.githubusercontent.com/44906007/68854213-39f3c600-06a1-11ea-8009-63df8f1db864.png)

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.1.14.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
之前有安装过么？ 如果有安装过，先卸载旧版试试。 如果有360等，先关闭试试。

**Comment by MarvelTexas** [comment]
没有安装过 没有任何杀毒软件 朋友推荐的 本来想下来试试 可安装都安装不了T.T

**Comment by cuiliang** [comment]
哦，可以试试重新下载一下安装包看看，不知道是不是不完整的缘故。
另外可以看看windows事件查看器里有没有什么相关的消息。
google搜索后，看到还有一些可能：
所在磁盘有没有加密？
安装程序没有权限访问Temp目录。。。
The location of the installer is on an encrypted directory.  
Place the installer in a non-encrypted directory and re-run the installer.
There is a corrupted version of Windows Installer engine on the machine. 
Re-install the Windows Installer Engine. Contact Microsoft to obtain a new copy of the Windows Installer.
The installation does not have access to the Temp directory, the default Temp directory of the machine is not clean or the Temp directory does not have enough space to run the setup.
The installation is being run over a Terminal Server or mapped network drive. 
Running the installer from a local location will address this
