### ISSUE TITLE
app连接失败

### ISSUE THREAD

**Issue by PascalZh** [cuiliang/Quicker#652]
**在同一局域网的情况下，出现app连接失败的情况**
刚开始可以正常连接app，某个时间点后无法连接（中途只是在看视频，没有什么特殊的操作）
通过手机app扫描的方式进行连接结果失败，尝试过更改ip，重启软件等方式均未成功连接
app端显示：未连接-Connection timed out

电脑端系统：win8.1
手机端：红米
路由器：小米路由器

**Comment by cuiliang** [comment]
电脑防火墙关下试试

**Comment by PascalZh** [comment]
> 
> 
> 电脑防火墙关下试试


试了，还是不行
![Snipaste_2019-11-15_21-47-41](https://user-images.githubusercontent.com/32212800/68947918-9fef6300-07f1-11ea-8322-dfeb1935ebc2.png)

**Comment by PascalZh** [comment]
> 
> 
> 电脑防火墙关下试试

这个信息可能有帮助
![Snipaste_2019-11-15_21-54-18](https://user-images.githubusercontent.com/32212800/68948338-a205f180-07f2-11ea-865a-dcdf66432eee.png)

**Comment by cuiliang** [comment]
可能网络不通。 你手机上有什么telnet工具么？ 可以试试能不能telnet到pc的666端口。

**Comment by PascalZh** [comment]
> 
> 
> 电脑防火墙关下试试

刚刚用别的同一局域网

> 
> 
> 可能网络不通。 你手机上有什么telnet工具么？ 可以试试能不能telnet到pc的666端口。

不好意思了，我这个可能是我自己网络设置的问题，我在别的机子上ping这台主机显示：无法访问目标主机

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/68949430-f7430280-07f4-11ea-80e1-edf5c75491d3.png)
不知道和这个专有网络有没有关系。
