### ISSUE TITLE
建议增加Quicker意外终止时的编辑器内容恢复

### ISSUE THREAD

**Issue by EX-XD** [cuiliang/Quicker#654]
**需求描述**
编辑动作时遇到死机、断电等意外情况，未保存的动作内容就会全部丢失，建议增加编辑器内容的恢复。

**描述你想要的解决方案**
增加对编辑中的动作每固定间隔保存快照的功能，用户自行选择快照数量和时间间隔，遇到意外情况重启软件后提醒恢复编辑状态。

**描述您考虑过的替代方案**
频繁直接保存动作也可以临时解决，但对于已经成型的动作，在一次性写好之前不太想破坏原有动作。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/69316869-a9a31b80-0c74-11ea-883f-c125f2739bfd.png)
专业版可以随时使用这个按钮保存当前版本

**Comment by EX-XD** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/69316869-a9a31b80-0c74-11ea-883f-c125f2739bfd.png)
> 专业版可以随时使用这个按钮保存当前版本

保存版本总觉得是应该在功能完整时使用，而且手动保存的习惯现在已经被各种自动保存惯的快没了……今天改到一半离开办事，回来发现死机，所有改动都没保存，才想起这个需求

**Comment by cuiliang** [comment]
死机的时候Quicker也没有机会再保存的。 一般这种情况需要定期自动保存，对Quicker目前的情况来说有点复杂了，后期再考虑。
