### ISSUE TITLE
分享动作，分类的【下拉菜单】被挡在后面了……

### ISSUE THREAD

**Issue by snomiao** [cuiliang/Quicker#656]
**描述BUG**
故障描述：分享动作窗口中，分类的下拉菜单被挡在后面了……

**重现步骤**
1. 右击一个自建动作，点击分享
2. 点击分类下拉菜单

**相关截图**
![image](https://user-images.githubusercontent.com/7323030/69486760-1cd1ab00-0e8a-11ea-8d92-f45538d75b41.png)

**环境信息:**
 - 操作系统版本：Windows 10 Pro  （1809 Build 17763.864）
 - Quicker版本：1.1.41 专业版

**附加信息**
无

**Comment by cuiliang** [comment]
这个是wpf的bug，一般再打开一次窗口就好了。暂时无法彻底解决。
