### ISSUE TITLE
动作更新提示

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#66]
安装的已分享动作有更新信息时，提示给已安装的人。
有动作更新时 , 客户端动作上能不能增加个红点提示 , 右键里面增加个更新动作。

**Comment by kts168** [comment]
还要考虑这种情况 , 如果动作被用户编辑过 , 如何更新 ? 覆盖 or 备份

**Comment by cuiliang** [comment]
另外一考虑：如果用户使用没什么问题，是不是不更新更好些，这样不打扰用户。 可以考虑和“点赞”功能结合，点赞过的，表示用户比较喜欢这个动作，只接收这些动作的更新通知。

**Comment by kanglade** [comment]
想到个比较好的办法：
如果动作有更新的话，在该动作的右键菜单里显示「有更新」，点击即可更新。
一来不打扰用户。
二来对该动作感兴趣的用户自然会主动去查看是否有更新，也不麻烦。

**Comment by kanglade** [comment]
还可以考虑加个「订阅」，订阅过的动作可以红点提示更新，甚至可以自动更新。

**Comment by WilsonXuwx** [comment]
1. 统一一个信息推送的入口。
2. 安装动作后，自动关注该动作。
3. 动作更新以信息（动作名/更新内容/链接）方式推送到用户。
4. 可随时取消动作订阅。

**Comment by cuiliang** [comment]
done
