### ISSUE TITLE
建议增加实时网速、cpu、内存显示

### ISSUE THREAD

**Issue by nocease** [cuiliang/Quicker#663]
弄个悬浮窗或者在面板一个地方显示
![image](https://user-images.githubusercontent.com/35341659/69839952-ac18fd00-1294-11ea-949c-c7306b60963f.png)

**Comment by nocease** [comment]
留个开关设置

**Comment by cuiliang** [comment]
这个需求和quicker的定位没有太大的关系了。quicker主要是希望提升操作的效率。 而且这类小工具比较多，没有再开发的必要了。
