### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by yufengerdai** [cuiliang/Quicker#676]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1. 点击 翻译，有时候会出现，获取失败。而且是连续获取失败。
2. 然后 翻译成中国

**相关截图**
![image](https://user-images.githubusercontent.com/7857370/70585596-a3fb7e80-1bff-11ea-9753-1df0daa33e8b.png)
![image](https://user-images.githubusercontent.com/7857370/70585607-aa89f600-1bff-11ea-930a-c767d8b03ae3.png)

如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
win10
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
使用的哪个动作？ 用什么方式弹出的面板？ 在什么软件里选择文本？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
