### ISSUE TITLE
建议：stringBuffer动作

### ISSUE THREAD

**Issue by nocease** [cuiliang/Quicker#677]
功能描述：
选中一个字符串，例如：
String str="你好，"+name+"。欢迎你"+sonmething;
执行动作后，字符串变为：
String str=new StringBuffer().append("你好，").append(name).append("。欢迎你").append(sonmething).toString();

**Comment by cuiliang** [comment]
IDE的重构工具应该更合适一些。
用Quicker的话，大概思路是用正则提取变量名和等号后面的部分。 
等号后面的部分再通过文本拆分成列表操作，根据+将内容分开。 再循环组装起来。
问题是文本内容中有＋的话就会出错。
