### ISSUE TITLE
动作的历史版本增强

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#678]
安装后保存初始版本；
发布到共享库时保存版本并标记。
远期考虑支持同步到服务器端。

**Comment by kanglade** [comment]
近期的话，有个想法：动作版本不同步到服务器端，但是版本日志可以进行同步，同时，加一个机器名的字段，这样动作历史版本的字段就有：保存时间、类型、备注、机器名。如果选择不是本机器名保存的版本进行恢复，那么就弹出提示。
