### ISSUE TITLE
轮盘建议

### ISSUE THREAD

**Issue by L-XiaoWei** [cuiliang/Quicker#679]
**需求描述**
轮盘设置了通用/全局动作，能不能有个设置开关按钮，关闭要不要在其他各个软件中显示默认的动作。

**Comment by cuiliang** [comment]
默认动作那里不设置留空就可以了。默认的目的主要是想给一些位置作为全局动作使用。

**Comment by Chilled-ops** [comment]
是为方便拖拽到全局动作吗？
