### ISSUE TITLE
建议：文本指令增加导入/导出和自定义分类功能

### ISSUE THREAD

**Issue by amperexia** [cuiliang/Quicker#683]
建议文本指令增加导入/导出功能，便于批量导入和修改缩写。
建议增加自定义分类功能，条目多了后有些混乱，不便于查找。

**Comment by cuiliang** [comment]
嗯，目前只是初步功能，后期再改进。

**Comment by cuiliang** [comment]
已增加扩展热键的分享。https://www.yuque.com/quicker/help/textcommand#8UEMb
