### ISSUE TITLE
在浏览器中无法进行按住左键点右键复制粘贴

### ISSUE THREAD

**Issue by libiewuxin** [cuiliang/Quicker#684]
**描述BUG**
在浏览器中无法进行按住左键点右键复制粘贴

**重现步骤**
1.在浏览器中选中要复制的文本
2.按着左键不动点右键出现浏览器右键菜单
3.不响应quick复制服务
4.粘贴同理，一样效果，希望可以尽早优化

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![微信图片_20191218122422](https://user-images.githubusercontent.com/59004234/71055628-5946ad00-2191-11ea-94aa-d20a31e9ed3f.png)

**环境信息:**
 - 操作系统版本：Windows1909教育版
 - Quicker版本：1.2.22.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
快速通道发布1.2.24版，可以试下。 如果有手势软件，可能需要重新加载一下鼠标挂钩，保证Quicker先截获鼠标事件。

**Comment by libiewuxin** [comment]
鼠标挂钩怎样重新加载？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CuiLiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 中午12:39
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"一壶清酒化流年"<1404685187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 在浏览器中无法进行按住左键点右键复制粘贴 (#684)




快速通道发布1.2.24版，可以试下。 如果有手势软件，可能需要重新加载一下鼠标挂钩，保证Quicker先截获鼠标事件。

**Comment by cuiliang** [comment]
如果Quicker后启动，就不需要了。 如果先启动，可以在托盘菜单上点右键，有重新加载挂钩的菜单项。
用1.2.24版本操作。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/71056439-3a95e580-2194-11ea-9286-a9d8e253718f.png)

**Comment by libiewuxin** [comment]
已收到，非常感谢！我找到问题所在了，是我的wgestures和quick冲突了，quick是个好软件，希望你们可以越做越好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CuiLiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 中午12:45
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"一壶清酒化流年"<1404685187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 在浏览器中无法进行按住左键点右键复制粘贴 (#684)

**Comment by libiewuxin** [comment]
托盘菜单在哪里，可以给我截个图吗，我不知道是哪里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CuiLiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 中午12:43
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"一壶清酒化流年"<1404685187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 在浏览器中无法进行按住左键点右键复制粘贴 (#684)




如果Quicker后启动，就不需要了。 如果先启动，可以在托盘菜单上点右键，有重新加载挂钩的菜单项。
 用1.2.24版本操作。

**Comment by cuiliang** [comment]
> 已收到，非常感谢！我找到问题所在了，是我的wgestures和quick冲突了，quick是个好软件，希望你们可以越做越好。

1.2.24应该可以和WG兼容了，需要Quicker比WG后启动。

**Comment by libiewuxin** [comment]
试了一下，确实是可以的，非常棒，给你们点赞。希望quick可以越做越好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CuiLiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 中午12:58
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"一壶清酒化流年"<1404685187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 在浏览器中无法进行按住左键点右键复制粘贴 (#684)



 
已收到，非常感谢！我找到问题所在了，是我的wgestures和quick冲突了，quick是个好软件，希望你们可以越做越好。
  
1.2.24应该可以和WG兼容了，需要Quicker比WG后启动。

**Comment by cuiliang** [comment]
不客气的。
