### ISSUE TITLE
怎么能设置成以前的样子，轮盘用不习惯

### ISSUE THREAD

**Issue by 1578198226** [cuiliang/Quicker#685]

**Comment by cuiliang** [comment]
如需禁用轮盘菜单，请在轮盘菜单触发键选项中选择“-无-”即可。
![image](https://user-images.githubusercontent.com/1972649/71069140-172e6300-21b3-11ea-8f02-c177b2f2ae43.png)
如需右键滑动激活面板选中这里：
![image](https://user-images.githubusercontent.com/1972649/71069182-2a413300-21b3-11ea-8f3e-53d58b99f0bc.png)

**Comment by 1578198226** [comment]
谢谢
