### ISSUE TITLE
隐藏任务栏时，无法弹出面板

### ISSUE THREAD

**Issue by Yaklo** [cuiliang/Quicker#686]
**描述BUG**
全屏软件误识别，无法长按鼠标打开
只能关闭

**重现步骤**
无

**相关截图**
无

**环境信息:**
 - 操作系统版本：win10 1809
 - Quicker版本：1.2.24.0

**附加信息**
无

**Comment by cuiliang** [comment]
看不懂，请详细描述。

**Comment by Yaklo** [comment]
1.2.24.0不关闭在全屏软件中禁用无法使用鼠标打开

**Comment by cuiliang** [comment]
> 1.2.24.0不关闭在全屏软件中禁用无法使用鼠标打开

是不是有多个屏幕，在副屏幕上？

**Comment by Yaklo** [comment]
有隐藏任务栏

**Comment by cuiliang** [comment]
是不是全屏目前的判断方法是根据屏幕大小是不是等于工作区大小，所以隐藏任务栏会被认为全屏状态。

**Comment by Yaklo** [comment]
以前的版本好像还可以正常使用来着，是改了吗

**Comment by cuiliang** [comment]
以前也是相同的判断方法的

**Comment by Yaklo** [comment]
![(T9ND5LLK(~3J}{E%J%FFC4](https://user-images.githubusercontent.com/50908861/71070177-30381380-21b5-11ea-8ff3-999167311a90.jpg)

**Comment by cuiliang** [comment]
发现了，是有个问题，不好意思

**Comment by Yaklo** [comment]
辛苦力

**Comment by cuiliang** [comment]
快速通道已更新1.2.25版本，请测试看看。
