### ISSUE TITLE
在其他软件内获取不到文本

### ISSUE THREAD

**Issue by lsjj15** [cuiliang/Quicker#687]
**描述BUG**
在其他软件内获取不到文本，跳转到浏览器在，搜索的内容一直是“[选中文本]”

**重现步骤**
1.总是出现，现在已经无法正常使用文字获取功能
2.

**相关截图**
![image](https://user-images.githubusercontent.com/59036154/71135153-d0388000-223b-11ea-86e8-8fc1f8844ffd.png)

**环境信息:**
 - 操作系统版本：WIN7
 - Quicker版本：1.2.26.0

**Comment by cuiliang** [comment]
请参考这个文档  https://getquicker.net/kc/help/doc/cannot_get_selected_text

**Comment by lsjj15** [comment]
看了文档。。是我描述得不够清楚。
WIN7系统下，只安装了一个火绒，在设置里面找了一下没有看到关于信任软件的选项。试过退出了也不行
文字窗口是微信手动CTRL+C可以使用，
呼出方式是长按右键或CTRL，两种方法都试过不行
后台也没有什么软件。
![image](https://user-images.githubusercontent.com/59036154/71155083-f845d480-2277-11ea-9408-6577bcad196a.png)
还有其他的可能吗

**Comment by cuiliang** [comment]
在记事本里可以获得文本么？试一下这个动作https://getquicker.net/sharedaction?code=06bc3199-955a-41f7-138f-08d738459453

**Comment by lsjj15** [comment]
哦哦 这个动作可以 ，在其他软件里也可以获得文本。那就是我要更新旧的动作？新旧的获取方式有什么不一样吗

**Comment by lsjj15** [comment]
感谢 可以了。才发现原来是那个搜索模块的变量变了，重新设置一下就好了。因为之前也间歇性的有过这个问题，所以没有注意到。抱歉
