### ISSUE TITLE
建议：修改辅助功能复制和粘贴的快捷键

### ISSUE THREAD

**Issue by 1situzj** [cuiliang/Quicker#690]
**需求描述**
辅助功能中的复制，粘贴使用的是 Ctrl + c 和 Ctrl + v ，但在部分程序上不兼容（如 Xshell 等 ssh 工具等）

**描述你想要的解决方案**
修改复制，粘贴的快捷键

**描述您考虑过的替代方案**
经试验，复制使用 Ctrl + Insert，粘贴使用 Shift + Insert 能最大程度兼容各种程序

**Comment by cuiliang** [comment]
感谢建议。 第一次看到这个快捷键😂

**Comment by cuiliang** [comment]
快速通道1.3.0版本已修改成这个键。谢谢。

**Comment by cuiliang** [comment]
还是有问题。ctrl+insert在腾讯桌面、一些文件管理器里不能使用，还不清楚会有哪些情况不行，要在下一版增加参数了。

**Comment by 1situzj** [comment]
这样的话只能让用户去选择使用哪种快捷键了

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/71436683-7b0fd900-2729-11ea-9060-12041ef7644d.png)
