### ISSUE TITLE
辅助功能-滚轮调音量不起作用

### ISSUE THREAD

**Issue by MLFH2019** [cuiliang/Quicker#691]
辅助功能-滚轮调音量不起作用。
有时候直接在程序界面，唤不出主界面。

**Comment by cuiliang** [comment]
hi，版本号多少？
滚轮调节音量需要在屏幕的顶边或底边（根据设置）操作。另外如果是副屏幕，在dpi不同的情况下，只能在顶边触发。
程序界面里呼不出，请看下有没有开启“全屏禁用”选项的时候隐藏桌面任务栏。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
