### ISSUE TITLE
中键弹出菜单失效

### ISSUE THREAD

**Issue by pythonlouvre** [cuiliang/Quicker#699]
**描述BUG**
中键弹出菜单失效

**环境信息:**
 - 操作系统版本： Win10专业版1909
 - Quicker版本：1.2.27.0

**Comment by cuiliang** [comment]
使用的哪种鼠标？是否有使用手势软件？
如果有同时使用手势软件，请避开相同的按键。
https://getquicker.net/KC/Kb/Article/225

**Comment by cuiliang** [comment]
后来可以了么？

**Comment by janima** [comment]
家里win7突然右键失效了，楼主有解决吗？没有其他手势软件，chrome有，不过之前也没有这个问题。

**Comment by cuiliang** [comment]
> 家里win7突然右键失效了，楼主有解决吗？没有其他手势软件，chrome有，不过之前也没有这个问题。
请详细描述一下问题。
windows版本、quicker版本，用什么激活方法，右键什么失效了，右键菜单有没有显示。。。尽量多的信息好判断。

**Comment by pythonlouvre** [comment]
解决了，确实跟手势软件有冲突，我这边是跟StrokesPlus.net有冲突，将设置中的次要鼠标手势键改成其他的就可以了。

**Comment by cuiliang** [comment]
> 解决了，确实跟手势软件有冲突，我这边是跟StrokesPlus.net有冲突，将设置中的次要鼠标手势键改成其他的就可以了。

感谢反馈~
