### ISSUE TITLE
注册失败的问题

### ISSUE THREAD

**Issue by Tomotoes** [cuiliang/Quicker#7]
![image](https://user-images.githubusercontent.com/32236122/48414721-6fac5900-e786-11e8-9f3d-83ce2180e3cc.png)

如图.
是因为我没有安装 `.Net` 框架吗? 

建议来个全局报错日志服务 , 每次软件一报错就会将信息存到您的服务器 , 然后再做个 ip 筛选, 统计 , 针对错误最多的情况 去解决.
个人想法 😄

**Comment by Tomotoes** [comment]
![image](https://user-images.githubusercontent.com/32236122/48415104-7091ba80-e787-11e8-8636-cfbdd887281e.png)
前几天重装了下系统, 看来系统自带了 .Net 框架 , 应该不是我上图提出的假设.
环境 : Win10 1803

**Comment by cuiliang** [comment]
网络情况好么？ 试试ping一下 getquicker.net 。 另外，电脑有没有用代理什么的？ 这个现象似乎是连不上服务器造成的。

**Comment by Tomotoes** [comment]
![image](https://user-images.githubusercontent.com/32236122/48415815-6ec8f680-e789-11e8-9c7f-b5cc17a94631.png)

![image](https://user-images.githubusercontent.com/32236122/48415886-a9cb2a00-e789-11e8-907c-f6fa4386243c.png)

嗯 , 再然后我关掉了 VPN ... 就好了...
