### ISSUE TITLE
全屏模式下滚轮调节音量失效

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/Quicker#701]
**描述BUG**
未更新之前全屏模式下在屏幕上部可以正常使用滚轮调节音量，更新后失效。

PS：全屏模式是指游戏或者浏览器视频全屏等类似情况

**重现步骤**
1.打开某一B站视频，全屏
2.鼠标移动到屏幕边缘（上部），滑动滚轮，音量未变化
3.退出全屏执行同样操作，音量变化

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 1903
 - Quicker版本：1.3.0.0

**附加信息**
具体从哪个版本开始失效忘记了。

**Comment by cuiliang** [comment]
是的，新的版本调解音量也会受到“全屏禁用”选项的控制。 
这里有点矛盾，是应该允许作为全屏禁用的例外还是也受控制？
因为新版还增加了触发角，如果调解音量可以例外，触发角是不是也应该例外呢？
我再想想。。。

**Comment by cesaryuan** [comment]
@cuiliang 我觉得单独搞个开关比较好。
对我个人来说，看视频的时候屏幕边缘调节音量很方便。

**Comment by cuiliang** [comment]
已改为全屏生效。请下载快速通道版本测试。
