### ISSUE TITLE
启动quicker鼠标卡顿

### ISSUE THREAD

**Issue by THEZIPPER** [cuiliang/Quicker#702]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.启动quicker
2.鼠标卡顿十秒左右，期间软件无反应
3.十秒过后鼠标恢复正常，软件可以正常使用

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：

![操作系统版本](https://user-images.githubusercontent.com/59190882/71498193-4ff6c800-2896-11ea-8dcf-d1a76a2e4645.PNG)
版本号1809

 - Quickner版本：
1.2.27.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
有没有设置自动启动动作？
![image](https://user-images.githubusercontent.com/1972649/71498298-c1367b00-2896-11ea-9a04-376cfd9ca77e.png)

**Comment by THEZIPPER** [comment]
![发](https://user-images.githubusercontent.com/59190882/71498458-6ea98e80-2897-11ea-8547-44a23b83871a.PNG)
没有这个选项

**Comment by cuiliang** [comment]
之前版本有这个现象不？ 试下退出帐号重新登录一下。
![image](https://user-images.githubusercontent.com/1972649/71498598-f55e6b80-2897-11ea-8261-ecaab49ab355.png)
另外这时候能看到任务管理器里的情况不？cpu、内存占用的情况

**Comment by THEZIPPER** [comment]
哦哦哦，账号重新登录一下就好了。谢谢。
之前版本没试过。
启动quicker时cpu，内存只是一瞬间升上去了，之后恢复正常。

**Comment by cuiliang** [comment]
好的。可能是本地数据文件有点问题，重新登录帐号会重建一下。
