### ISSUE TITLE
win10 64位 占用cpu达96%，机器经常卡死

### ISSUE THREAD

**Issue by helloo2020** [cuiliang/Quicker#703]
最新官网下载的版本

**Comment by cuiliang** [comment]
有在运行什么动作么？ 
Windows详细版本号和Quicker详细版本号是多少呢？ 有没有同时使用手势软件？
能不能复现，有没有什么规律，比如在做什么操作之后会上涨？

**Comment by huweiATgithub** [comment]
出现类似的情况，我的情况是quicker会在后台占用CPU，浮动在0-6%这样。
因为是笔记本，还是比较在乎这个的。Power usage显示moderate
重启quicker后问题依旧，未执行任何动作，应该跟动作无关。
不在前台时，quicker在后台有什么服务？是不是有什么关系？
不知道大家是不是也有同样的情况？

**Comment by cuiliang** [comment]
CPU是什么？Quicker版本多少？
如果有启用的话，取消这个选项。如果有开启画圈激活的话，关闭测试。
![image](https://user-images.githubusercontent.com/1972649/71609948-7898fd80-2bc7-11ea-87a7-e8b8e4533718.png)

如果有同时使用手势软件，关闭手势软件测试。
Quicker主要是在切换进程的时候加载动作页，其他就是键盘和鼠标挂钩，开销应该很小。


> 出现类似的情况，我的情况是quicker会在后台占用CPU，浮动在0-6%这样。
> 因为是笔记本，还是比较在乎这个的。Power usage显示moderate
> 重启quicker后问题依旧，未执行任何动作，应该跟动作无关。
> 不在前台时，quicker在后台有什么服务？是不是有什么关系？
> 不知道大家是不是也有同样的情况？

**Comment by cuiliang** [comment]
> 出现类似的情况，我的情况是quicker会在后台占用CPU，浮动在0-6%这样。
> 因为是笔记本，还是比较在乎这个的。Power usage显示moderate
> 重启quicker后问题依旧，未执行任何动作，应该跟动作无关。
> 不在前台时，quicker在后台有什么服务？是不是有什么关系？
> 不知道大家是不是也有同样的情况？

另外请试一下鼠标静止不动的时候和鼠标移动的时候，CPU有没有什么变化。

**Comment by huweiATgithub** [comment]
> > 出现类似的情况，我的情况是quicker会在后台占用CPU，浮动在0-6%这样。
> > 因为是笔记本，还是比较在乎这个的。Power usage显示moderate
> > 重启quicker后问题依旧，未执行任何动作，应该跟动作无关。
> > 不在前台时，quicker在后台有什么服务？是不是有什么关系？
> > 不知道大家是不是也有同样的情况？
> 
> 另外请试一下鼠标静止不动的时候和鼠标移动的时候，CPU有没有什么变化。

嗯嗯 确实是鼠标移动会导致变化 鼠标静止时会慢慢变成0% 鼠标一移动 cpu使用率就起来了
CPU是9750H

**Comment by huweiATgithub** [comment]
> 嗯嗯 确实是鼠标移动会导致变化 鼠标静止时会慢慢变成0% 鼠标一移动 cpu使用率就起来了
> CPU是9750H

另外，自动优化内存是没有开启的。我的设置里面，应该是没有需要追踪鼠标移动触发的功能的。
![image](https://user-images.githubusercontent.com/37072526/71612522-efd88c80-2bdb-11ea-9e6a-f1d4efe60a01.png)
轮盘菜单没有开启，app没有开启。快捷键，触发按键，自动运行，辅助这四个sections里面全部没有勾选，全是空白的。

**Comment by cuiliang** [comment]
> > 嗯嗯 确实是鼠标移动会导致变化 鼠标静止时会慢慢变成0% 鼠标一移动 cpu使用率就起来了
> > CPU是9750H
> 
> 另外，自动优化内存是没有开启的。我的设置里面，应该是没有需要追踪鼠标移动触发的功能的。
> ![image](https://user-images.githubusercontent.com/37072526/71612522-efd88c80-2bdb-11ea-9e6a-f1d4efe60a01.png)
> 轮盘菜单没有开启，app没有开启。快捷键，触发按键，自动运行，辅助这四个sections里面全部没有勾选，全是空白的。

好的，我试试优化一下这里。

**Comment by cuiliang** [comment]
@helloo2020 @huweiATgithub 快速通道已发布1.3.5版本，请测试一下有没有改善。谢谢。

**Comment by huweiATgithub** [comment]
> @helloo2020 @huweiATgithub 快速通道已发布1.3.8版本，请测试一下有没有改善。谢谢。

问题已经解决了！移动鼠标不再导致CPU使用率上升了
