### ISSUE TITLE
xshell 6 轮盘菜单空白

### ISSUE THREAD

**Issue by hentaiFly** [cuiliang/Quicker#705]
**描述BUG**
使用xshell 6 时，当鼠标在console中呼出轮盘菜单空白，在状态栏等地方呼出轮盘菜单则正常

**重现步骤**
1. 使用右键作为快捷键，在xshell console中呼出轮盘菜单

**相关截图**
图1为console中呼出，图2为导航栏呼出
![image](https://user-images.githubusercontent.com/14855943/71702434-72df2a00-2e0a-11ea-9c1f-f404457c771d.png)
![image](https://user-images.githubusercontent.com/14855943/71702441-84c0cd00-2e0a-11ea-8aea-828cc7b8b208.png)

**环境信息:**
 - 操作系统版本：win10 1903 18362.239
 - Quicker版本：1.3.8.0 专业版

**Comment by cuiliang** [comment]
应该是识别到了不同的进程。 标题栏和内容区可能是多个进程。 可以在内容区弹出面板，看一下面板窗口最下面显示的“为XXXX创建动作页”的提示，是不是显示了新的进程信息？

**Comment by hentaiFly** [comment]
> 应该是识别到了不同的进程。 标题栏和内容区可能是多个进程。 可以在内容区弹出面板，看一下面板窗口最下面显示的“为XXXX创建动作页”的提示，是不是显示了新的进程信息？

没有显示创建动作页，呼出面板的话显示的是正常的面板，有我为xshell定义的所有动作

**Comment by cuiliang** [comment]
快速通道已发布1.3.17版本，增加了关联应用程序设置。请测试是否可以解决。
https://www.yuque.com/quicker/help/profiles#0Og5g

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
