### ISSUE TITLE
无法弹出面板、触发文字指令功能

### ISSUE THREAD

**Issue by BushJiang** [cuiliang/Quicker#706]
**描述BUG**
设置长按右键弹出quicker面板，但quicker运行一段时间后，无法通过长按右键弹出面板，文字指令的功能也无法触发，不能通过缩略词发送文字。
关闭重启后恢复正常。

**重现步骤**
quicker运行一定时间后出现该bug。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.3.8.0

**Comment by cuiliang** [comment]
电脑CPU和内存资源紧张么？ 之前有一个用户有类似现象，电脑配置比较低，鼠标键盘挂钩可能被windows回收导致无法触发。

**Comment by cuiliang** [comment]
请观察一下有没有什么规律，比如在做什么操作之后容易出现这个现象。

**Comment by cuiliang** [comment]
你好，请https://getquicker.net/Download 下载快速通道1.3.14版本测试看看还会不会出现。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
