### ISSUE TITLE
提交新动作时，下拉框元素被遮挡

### ISSUE THREAD

**Issue by HumblerCoderX** [cuiliang/Quicker#708]
**描述BUG**
提交新动作时，下拉框元素被遮挡
**重现步骤**
1.看图说话

**相关截图**
![Snipaste_2020-01-04_16-20-04.png](https://upload-images.jianshu.io/upload_images/18280274-04fbc78ab98faf30.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**环境信息:**
 - 操作系统版本：版本Windows10 10.0.18362 版本 18362

 - Quicker版本：1.3.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个可能是wpf的bug，一般重新开一下窗口就会正常

**Comment by HumblerCoderX** [comment]
果然，现在正常了

> 这个可能是wpf的bug，一般重新开一下窗口就会正常
