### ISSUE TITLE
与vmware player的兼容性

### ISSUE THREAD

**Issue by z-xlong** [cuiliang/Quicker#71]
我设置的是“长按右键200ms”激活方式，
在vmware player中右键点击，ubuntu的右键菜单显示后立刻消失。虚拟机里的右键功能无法使用。
设置了屏蔽列表(vmware player.exe)后，之后在vmware player.exe上可以屏蔽，在虚拟机中，依然能够触发quicker。

**Comment by cuiliang** [comment]
虚拟机窗口是不是单独的exe，而不是vmware player.exe ？

**Comment by z-xlong** [comment]
> 虚拟机窗口是不是单独的exe，而不是vmware player.exe ？

我尝试屏蔽了vmware的很多exe，不能解决次问题。
您可以装一个虚拟机试试。
vmware player + ubuntu16.04

谢谢。

**Comment by cuiliang** [comment]
@z-xlong 
试试这个版本 https://pan.baidu.com/s/1_Ty6rN8UtOJB96M3uQ1qXw
player虚拟机的程序应该是vmware-vmx.exe 可以直接按“选择窗口”按钮添加。
![image](https://user-images.githubusercontent.com/1972649/50497267-fd12e680-0a70-11e9-8471-e60f1f82f651.png)
