### ISSUE TITLE
鼠标手势锁屏不起作用

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#711]
**描述BUG**
不管是轮盘还是鼠标手势，设置了锁屏（windows+L），但是不起作用啊！不知道是为什么？

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：window10
 - Quicker版本：1.3.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个可能是windows的限制，原来就有， 需要用脚本锁屏。请在动作库搜索一下，有不少动作可以参考。
