### ISSUE TITLE
【辅助】复制粘贴 在vscode中不能进行粘贴

### ISSUE THREAD

**Issue by CxistHans** [cuiliang/Quicker#712]
**描述BUG**
按住鼠标左键点右键可以正常复制，但是在Visual Studio Code中不能粘贴

**环境信息:**
 - 操作系统版本：win10 1909
 - Quicker版本：1.3.8.0
 - vscode：1.41.1

**Comment by cuiliang** [comment]
该功能的原理是先发送Ctrl+C，如果剪贴板内容变化了，说明是选择了文字，判断为用户的目的是复制操作。如果剪贴板没有变化，说明没有选择内容，这时候判断为要粘贴，发送Ctrl+V。
有一些软件，不管是不是选择了文字，发送ctrl+c都会引起剪贴板变化，这些软件将不支持粘贴操作。
比如在VisualStudio里，没有选中的时候是复制整行；vscode估计也是这种情况。Excel里也会更新剪贴板。
如果有侧键，可以考虑设置左键+侧键用于粘贴，左键+右键只用来复制。

**Comment by CxistHans** [comment]
@cuiliang 好的，理解了，谢谢，就是没有侧键很尴尬！！！
