### ISSUE TITLE
右键呼出主界面有时候不起作用

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#714]
**描述BUG**
问题如标题所述，有时候右键呼出主界面是不起作用的。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.3.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
你好，请https://getquicker.net/Download 下载快速通道1.3.14版本测试看看还会不会出现。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
