### ISSUE TITLE
钉住取消后不好使

### ISSUE THREAD

**Issue by lxh90101** [cuiliang/Quicker#715]
**描述BUG**
设置钉住后，取消后，再按中键窗口不自动隐藏

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
版本？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
