### ISSUE TITLE
win10系统下最新稳定版无法开机自启

### ISSUE THREAD

**Issue by Cavendisher** [cuiliang/Quicker#717]
如题，已打开win系统自启选项和quicker软件自启选项，仍无法开机自启。
望解决

**Comment by cuiliang** [comment]
开机启动无法正常，通常是各类管家搞的。如果安装并且不知道怎么设置的情况下，可以先卸载管家软件后开启一下测试。

**Comment by cuiliang** [comment]
另外也可以在windows的 启动菜单里创建快捷方式实现自启，就不需要开启那个选项了。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
