### ISSUE TITLE
希望可以开通永久专业版通道

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#719]
**需求描述**
感觉是不是开通专业版永久通道好些呢？因为现在这只能连续的买，感觉不爽啊！还是希望开发者大大可以开通一下，或者在节假日开通几天也无妨啊！！！！

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
永久授权虽然很爽能一下收不少钱，但不利于软件的持久运营。 
我之前在这篇里也有说明可以参考。 https://getquicker.net/kc/help/doc/versions  
目前也有一些获赠永久授权的方式，主要是对产品的开发或推广有比较大的贡献的情况。
