### ISSUE TITLE
防止截图功能导致隐私泄露

### ISSUE THREAD

**Issue by xiaopangju** [cuiliang/Quicker#721]
**需求描述**
http://bbs.huorong.cn/thread-65157-1-1.html

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
感谢反馈，可能是topmost标记导致的，我处理一下。

**Comment by cuiliang** [comment]
已处理，待下个版本更新。  目前在锁屏后如果有多余的窗口需要手动关闭一下。

**Comment by cuiliang** [comment]
1.3.19版本已解决并发布到快速通道了。
