### ISSUE TITLE
1.3.17.0更新后鼠标按键无法弹出面板

### ISSUE THREAD

**Issue by lianzhai** [cuiliang/Quicker#724]
**描述BUG**
鼠标按键弹出动作界面失败。
设置弹出面板界面正常，键盘热键可以正常弹出动作界面，鼠标热键失去所有效用。

**重现步骤**
1.开机自启动
2.鼠标热键无效
3.键盘热键有效
4.弹出界面无法用鼠标滚轮切换动作面板
5.重启无效

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10家庭版18363.535
 - Quicker版本：1.3.17.0免费版

**附加信息**

**Comment by cuiliang** [comment]
截图看一下弹出设置。 
在托盘图标上右键，重新加载挂钩是否正常？
另外有无使用其他手势软件？ 如有使用退出测试。

**Comment by lianzhai** [comment]
已解决。 感谢您的帮助。------------------ 原始邮件 ------------------
发件人: "CuiLiang"<notifications@github.com>
发送时间: 2020年1月16日(星期四) 上午10:31
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com>;
抄送: "lianzhai"<2858104869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cuiliang/Quicker] 1.3.17.0更新后鼠标按键无法弹出面板 (#724)



截图看一下弹出设置。
 在托盘图标上右键，重新加载挂钩是否正常？
 另外有无使用其他手势软&#x4EF6;？ 如有使用退出测试。
 
&mdash;

**Comment by CPCer** [comment]
@cuiliang 您好，我也是同样问题。我在调试中将原先使用的 `Ctrl + 右键` 改为了 `长按右键`，现在 `长按右键` 是正常的，但是找不回前者了。
![image](https://user-images.githubusercontent.com/8787958/72662037-b5b11c80-3a1c-11ea-8126-9f8d9dc76ed6.png)
上图是现在的设置，好像跟 `[用户手册](https://getquicker.net/kc/help/doc/activate)` 里也不一样了。请问能否恢复原按键
