### ISSUE TITLE
“弹出面板”-“长按右键”与WGestures冲突

### ISSUE THREAD

**Issue by The-Last-Straw** [cuiliang/Quicker#727]
**描述BUG**
先启动Quicker，后启动WGestures，则长按右键无法弹出面板；
先启动WGestures，后启动Quicker，则长按右键可以正常弹出面板。
两个软件我都是设置的开机自启动，但Quicker总是先于WGestures启动，以致于需要退出Quicker再重新打开才能用“长按右键”来弹出面板，比较麻烦。辛苦程序员研究一下解决方案。

**环境信息:**
 - 操作系统版本：Windows10专业版
 - Quicker版本：1.3.17.0、1.3.19.0（两个版本都试过）

**Comment by The-Last-Straw** [comment]
利用Startup Delayer这个软件延迟Quicker的启动可解决上述问题。
多装一个软件来解决问题让人难受，所以……

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Kb/Article/225  本质上都要拦截消息，冲突不可避免，请参考这个文档。

**Comment by The-Last-Straw** [comment]
> https://getquicker.net/KC/Kb/Article/225 本质上都要拦截消息，冲突冲突，请参考这个文档。

那好吧，谢谢哈。
