### ISSUE TITLE
希望能为动作页增加一个暂停的按钮.

### ISSUE THREAD

**Issue by litao188** [cuiliang/Quicker#729]
**需求描述**

设置了几个模拟按键的动作,并单独放在一页.
有时候需要暂停这些模拟按键只能一个一个点进去关闭. 
希望能在动作页增加一个暂停所有动作的按钮.
![image](https://user-images.githubusercontent.com/60057830/72678665-130fa100-3ae3-11ea-8472-5c26a03b1797.png)

**Comment by JasonTrue2019** [comment]
![image](https://user-images.githubusercontent.com/54923442/72681416-50355c80-3afe-11ea-8512-639b329435f1.png)
目前可以试试看，托盘右键→中止动作。
这个也可以设置快捷键的。

**Comment by litao188** [comment]
> ![image](https://user-images.githubusercontent.com/54923442/72681416-50355c80-3afe-11ea-8512-639b329435f1.png)
> 目前可以试试看，托盘右键→中止动作。
> 这个也可以设置快捷键的。

我的中止动作是灰色的,点不了,咋回事? 另外这个按钮的含义是什么? 使所有动作无效吗? 但是我只要特定动作页的动作无效, 这个有解吗.

**Comment by cuiliang** [comment]
设置快捷键或使用托盘菜单可以停止所有动作。灰掉表示没有在运行中的动作。
没法单独停止一个动作。
