### ISSUE TITLE
优化动作按钮的tooltip显示

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#73]
希望不要在不需要的时候出现。
目前在鼠标靠近屏幕边缘用长按右键等方式激活的时候，因为鼠标会在按钮上比较长的时间，容易激活tooltip。
？增加关闭tooltip选项？
？增加延时？

**Comment by i5151** [comment]
建议增加关闭选项。

同时增加按钮右键属性菜单，能设置按钮属性，能固定按钮，防止误删误移动。
可以设置按钮密码等等，谁还想到什么可以补充。

**Comment by i5151** [comment]
刚刚恢复了系统，又重装了一次Quicker。

小建议：安装程序中加上“在桌面建立图标的选项”，随机启动、常住内存软件的桌面图标我都会删掉，因为托盘一直有图标，点击随时能启动，完全没有必要在桌面留着图标。
