### ISSUE TITLE
选中字符少于3个时文本悬浮窗无效.希望解决.

### ISSUE THREAD

**Issue by litao188** [cuiliang/Quicker#730]
选中字符少于3个时文本悬浮窗无效.希望解决.
有时候只需要选中一位数或者两位数的数字, 但是这个时候文本悬浮窗并不起作用, 希望能解决这个问题.

**Comment by cuiliang** [comment]
之前有15个像素的距离判断，少于这个认为不是选择文字而是手抖。等改成5试试。

**Comment by litao188** [comment]
> 之前有15个像素的距离判断，少于这个认为不是选择文字而是手抖。等改成5试试。

这个能自己改吗, 还是得等版本更新.

**Comment by cuiliang** [comment]
> > 之前有15个像素的距离判断，少于这个认为不是选择文字而是手抖。等改成5试试。
> 
> 这个能自己改吗, 还是得等版本更新.

已更新到快速通道，更新版本即可。没有加参数，参数太多了也不好。
