### ISSUE TITLE
希望增加一个 是否使用系统代理的设置选项

### ISSUE THREAD

**Issue by Aincvy** [cuiliang/Quicker#734]
当 quicker 比代理 软件先启动的时候 会出现 一段时间的 同步失败情况。 
然后我的皮肤 好像就 挂了。 

可以修改配置文件的那个方法， 我看过了。 

我希望能在设置面板里面 直接选择

**Comment by cuiliang** [comment]
动作图标的下载这些wpf框架层面的，还没找到通过代码控制的方法。

**Comment by Aincvy** [comment]
> 动作图标的下载这些wpf框架层面的，还没找到通过代码控制的方法。

啥意思， 加一个 check box  不就好了吗。。
在 基本 -> 其他选项之类的地方里面。。

**Comment by cuiliang** [comment]
界面上当然好加，难的是看不见的功能实现部分。

**Comment by Aincvy** [comment]
你是说 下载这个功能，是不可见的， 而且没找到怎么样设置 代理？

不过 既然配置文件 都可以生效的话，  直接在代码里 设置 那个 defaultProxy 不行吗

**Comment by cuiliang** [comment]
可能也是可以的，等有空再详细研究下看看

**Comment by cuiliang** [comment]
done,待后续版本更新。
