### ISSUE TITLE
创建编辑动作时对照提示与检测动作重复的机制

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#735]
**一种检测与提示的机制**
对需求的描述。如需求的场景、解决的问题等。
😨编辑的时候没注意把模板改坏了，GitHub的预览看起来有点糟糕
场景：提交动作的时候 会根据名称 功能说明 图标等维度 _自动_检索🔍匹配库， 匹配度高的【也就是很可能在重复劳动】【类似于知网查重 https://www.cnki.cn/】 _进行提示；_ 
问题：
 1. 在天若OCR的那个区间的库里创建提交这个图床动作的时候我完全不知道群主你已经写过这个动作了，动作太多实在了解不过来，库里动作少一点还好很快就可以发现重复 但是多了的 翻不过来；我那个太简单了就一个打开网页的动作根本没必要写
 2. 感觉有时候我参照别人的动作编写我自己的非常不方便
 3. 一些提交的动作的标题字数太多很不克制，我有点强迫症
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
- 希望网页端还有客户端的动作库能够有一定的改进，增加展示效果或者 视图 以便更快的浏览动作 相关的内容，目前quicker的逻辑有点像印象笔记，3个级：程序，通用，全部=笔记，笔记本，笔记本组，分类类似于标签
- 使用GitHub没多久,但是那个branches对照的功能非常好，假如编辑两个动作选中启动branch对照，windows系统自动分屏把两个窗口分到两边进行对比，不同处颜色突出
- 是否应该强制限制标题的字数？虽然鼠标悬浮的时候会显示出来，我自己的笔记本电脑屏幕上标题超过12字看起来就有点不舒服，不知道其他的电脑屏幕是多少
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
或许可供参考：为知笔记的插件，notion【view视图等功能 创意】 听说notion 是浏览器套壳应用 展示效果非常好；可用这个链接注册体验：
https://www.notion.so/?r=d1d5583702a34387a1e2d098a71c4374
- GitHub上的项目：https://github.com/search?q=notion；
- 插件为知助手：标签云
 插件：http://www.wiz.cn/plugin-download.html
 百度百科关于标签云的内容：https://baike.baidu.com/item/%E6%A0%87%E7%AD%BE%E4%BA%91；
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
1.一时不慎重复造轮子：![image](https://user-images.githubusercontent.com/44609485/73119461-2fa55080-3f9d-11ea-9f3a-da3830e0dae5.png)
---
2. ![image](https://user-images.githubusercontent.com/44609485/73119668-384b5600-3fa0-11ea-88a6-191c3b03fd8e.png)
---
2.![image](https://user-images.githubusercontent.com/44609485/73119677-5022da00-3fa0-11ea-820e-19dfc2df032b.png)
---
3. ![image](https://user-images.githubusercontent.com/44609485/73120013-1fdd3a80-3fa4-11ea-8183-f47548081790.png)
![image](https://user-images.githubusercontent.com/44609485/73120123-48b1ff80-3fa5-11ea-87bc-1fdb1641e2d3.png)

**Comment by cuiliang** [comment]
可能比较难实现。
动作内容不像编程的代码可以方便的diff比较，所以很难实现对比的，也很难猜测动作的目的，以及用户要编写的动作的目的，从而去判断是不是有重复。
后续可能优化一下搜索，另外增加一个动作单功能方便用户整理动作库吧，再考虑。

**Comment by 222YEDONG** [comment]
@cuiliang 那 。。。![image](https://user-images.githubusercontent.com/44609485/73817732-a7d60680-4826-11ea-80ec-2dadaeb02010.png) 小修改【可能意思是在别人工作的基础上优化 小修改了一下】
我说的那个限制动作的标题字数。。。强制少于多少字，可实现吗？原谅强迫症【非常不规整+难看】，真的太难受了【目前对于提交的动作 只有群主一个人在审核，搞不过来】提交与审核批准都太过于随意

**Comment by cuiliang** [comment]
这个，没法限制别人分享动作的标题名称的。 你可以在安装以后编辑一下。另外可以在外观里设置不自动缩小字体。

**Comment by 222YEDONG** [comment]
好的，这个还真没注意到！感谢提醒
