### ISSUE TITLE
同一帐号能否在不同电脑之间设置不同的动作？

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#736]
**需求描述**
同一帐号能否在不同电脑之间设置不同的动作？因为现在这个是在一台电脑上面设置了动作，在另外一台电脑上面登陆，还是同步的动作，现在不想同步，就想同一帐号在不同电脑上面设置不同的动作。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
如果完全不同，请使用单独帐号。
如果部分不同，专业版支持动作页绑定功能，为不同的电脑单独创建动作页，具体说明请参考文档。
