### ISSUE TITLE
手机语音输入不能用

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#737]
**描述BUG**
手机上下载了quicker，扫码连接了电脑，点击语音输入，说是要安装Google语音搜索软件，就安装了，是老手机，新手机这个软件好像不能安装，而且我用的华为手机，应用商店也搜索不到这个软件。然后再点击语音输入，提示还是让安装Google语音搜索，然后就不知道怎样搞了！

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可以试试安装讯飞语记，也是可以用的。
