### ISSUE TITLE
在快捷面板窗口添加阴影

### ISSUE THREAD

**Issue by XHZMC** [cuiliang/Quicker#738]
需求描述
我觉得现在的快捷面板窗口没有阴影，挺别扭的。能不能添加个开关，以控制快捷面板窗口是否显示阴影？

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/73541822-5d433b80-446e-11ea-8026-0bb1c0e4382b.png)
有阴影的啊

**Comment by XHZMC** [comment]
好吧
