### ISSUE TITLE
手机端和电脑端复制粘贴

### ISSUE THREAD

**Issue by baileichao** [cuiliang/Quicker#740]
**需求描述**
将手机和电脑连接以后，能否增加这样的功能，就是我在手机上复制文字，然后电脑上直接粘贴就可以把手机上复制的文字粘贴了，或者在电脑端复制了，在手机上就可以直接粘贴了。感谢！！！

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
pc-手机，如果是苹果，可以使用https://getquicker.net/sharedaction?code=e927d844-d212-4428-758d-08d69de12a3b
互传需要Quicker实时连到服务器，对我个人来说成本太高短期没法实现的。
有很多第三方软件有这个功能，可以找一下。

**Comment by cuiliang** [comment]
https://clipber.com/index.html?style=orange
