### ISSUE TITLE
卡住用户 鼠标右键

### ISSUE THREAD

**Issue by Ridiculer** [cuiliang/Quicker#741]
**描述BUG**
卡住用户鼠标右键，导致鼠标右键直接失灵，无法在其他程序里使用鼠标右键，如桌面，任务栏，浏览器其他软件等，但是能够在quicker面板及设置里面被察觉和使用。

**重现步骤**（此重现步骤只适用于https://www.lanzous.com/i8uorji 这个软件）
1.运行该软件。
2.在其上弹出quicker面板，对，只是弹出了面板，此时除quicker外的鼠标右键已失效，怎么尝试也无用。
3.关闭该软件，一定要关闭了才可以，再次打开quicker面板，任意点击一次鼠标左右键，此时鼠标右键恢复正常。

**相关截图**
![image](https://www.privacypic.com/images/2020/02/07/Snipaste_2020-02-07_12-05-513ff5f23e27605c5e.png)
![image](https://www.privacypic.com/images/2020/02/07/Snipaste_2020-02-07_12-06-2696d75edf5a23ed7e.png)

**环境信息:**
 - 操作系统版本：win10 x64 ltsc2019 版本号1809
 - Quicker版本：1.4.9.0 开发版

**附加信息**
弹出quicker面板仅设置了鼠标x1键，关闭了所有的轮盘。

我自己也觉得可能是只存在于该软件的错误。但后来在多个使用场景中仍会 多次（一天可能得有几次吧） 的出现上述的问题，只是到底是其他哪些软件及出错步骤还未查知（比如我的浏览器右键手势，用着用着突然失灵）。
不过问题确实存在，可能还很普遍。在大多数情况下，上述步骤3也无法修复，此时只好无奈地ctrl+alt+del启动（任务栏右键已经失效）任务管理关闭quicker才能重新使用鼠标右键。
小白不是很懂电脑，但是也能感觉到可能是quicker在监测鼠标右键的时候，某个循环条件出错或者不对卡死，从而把所有的鼠标右键信号全堵在quicker里面了。

**Comment by cuiliang** [comment]
有安装360么？ 有的话需要加白名单并且关闭驱动防护才能正常使用Quicker。

**Comment by Ridiculer** [comment]
没有装360，只装了火绒，吧火绒关闭，用火绒剑把能关的进程都关了之后，仍然出现了这个问题，百思不得其解，后来进了带网络的安全模式，这个模式下没有错误，但是开机后有些进程确实杀不掉，有些是没有权限，有些杀掉后又自己重启，搞着搞着电脑都死机了几次，实在是搞不懂是和那个进程起冲突了.......

**Comment by Ridiculer** [comment]
用另一台刚装好系统只装了驱动的电脑实验，结果一致，只能在带网络的安全模式这个模式下没有错误

**Comment by cuiliang** [comment]
那个软件我本地运行报错，没法测试。
是只要在那个软件里点一下就会失效么？ 在别的地方点比较正常？
原贴里截图都显示不出来。

**Comment by Ridiculer** [comment]
我换了一个图床应该可以了。然后那个软件是个下载器，打开时会自动联网识别版本，抱歉，我觉得可能麻烦到你了。
