### ISSUE TITLE
关于大数据发布和一些动作改进的期望

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#742]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
- 希望以后大数据发布**不搞斜体**，我添加关注名单不方便；
![image](https://user-images.githubusercontent.com/44609485/73813988-b1f30780-481c-11ea-8f35-7ab2a5a6cdf4.png)
- 有没有考虑过可以有_更多的付费方案_，例如付费之后可以**看统计数据**，很希望能够获取安装后动作**点击次数数据**【除了安装次数 点赞 更多的维度】，有这个数据之后怎么显示方便查看？【帮助我断舍离，排列(哪些在1面板好？)、选择、删除】太不克制 很乱
【之前没有子程序功能，没重点，我探索动作库 感觉这也不错，那好像也可以学习一下，安装太多】，全局面板都到13
![image](https://user-images.githubusercontent.com/44609485/73816838-91c74680-4824-11ea-89dc-65af42b99d18.png)
我常用的工具如：滴答清单 inoreader【magic功能】，或许可供参考：【我记得有往这个方向努力过，统计使用时间这个功能，虽然我不需要，有另外的时间监控软件 rescutime，后来不知道哪次更新就没了，过去太久 记不清具体了】
![image](https://user-images.githubusercontent.com/44609485/73815032-b240d200-481f-11ea-9c04-139380622de0.png)
https://blog.inoreader.com/2019/11/new-feature-sort-by-magic-and-article-popularity-indicators.html 
![image](https://user-images.githubusercontent.com/44609485/73815090-e0261680-481f-11ea-8761-630d1dbf18e5.png)
- 搜索动作库 quicker后选择性安装的动作如下几个【检查与整合杂乱动作 没有好的头绪 这些总行】，能否深度整合他们【最好变成1个动作，目前4、5个太多了】；感觉群里群主当客服回答的很多的问题，真的很浅的，只需要群成员有耐心看文档多花个十几分钟就能够自己解决了
![image](https://user-images.githubusercontent.com/44609485/73814642-a274be00-481e-11ea-95c4-34063e4a2890.png)
这个面板上的动作**整合成1个**之后【不知道怎么形容好，但是目前的感觉就是不够完美】，有问题可以很方便的就去文档或库，很方便搜索直达，主要是没有人关注这个，Ever,还有群主等，我的实力又不足。。。把ever智搜 智识 搞明白后 估计应该差不多。。。。
- 文档和语雀进度不同步，希望有朝一日能够解决，语雀更新落后了，【我之前群里询问过群主 语雀订阅】白订阅到inoreader了【汇总了一些在用的软件，查看更新消息，选择性更新，只能电脑，手机还搞不了，rsshub上这个不太行  https://docs.rsshub.app/program-update.html#apkpure】
![image](https://user-images.githubusercontent.com/44609485/73815631-7e66ac00-4821-11ea-8c4d-96ba0c019026.png)
- 希望quicker在手机电脑联动方面 有所作为。。。【之前有不少人提到过的quicker悬浮球方案 个人认为不太靠谱，本人关掉小米自带的悬浮球，只保留一个FV悬浮球， 除非碾压否则不换，二选一我选FV，疫情这些天家里网络故障，电脑在用手机热点。。手机quicker 居然这都连不上，局域网要求高了点，感觉有人提到过 我重复了】USB？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
场景如下：我直接用OCR识别一下，添加到印象笔记里面然后用动作搜索，搜这个几个人写的动作进行学习。。。。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
_再次碎碎念：_
是否融资？多雇几个人【我也挺穷的 帮不了你】感觉群主真的忙不过来【根据我发的反馈消息，群主的回应可以看出】。。。又当开发者，又当客服。。。。我真没说要开发OCR去啊。。。
![image](https://user-images.githubusercontent.com/44609485/73814343-be2b9480-481d-11ea-835a-77b4a06bdd3a.png)
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
之前的一些人名单如下，有类似场景，有需要的人可以复制去，免得自己手打一回：
无法关注太多人物，目前暂时只能按照点赞数量来，根据他们发布的动作，安装与实践来学习：
Marcus
CL
云之轩
治钧
乐坛话事人
i_orange
极客【另外两个字打不了】
VernonLin
KBC
WlsonXuwx
zzzzls
JasonTrue
Ever
geek
龙少

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/92318212-75e68600-f03b-11ea-8b07-7283b22b3cf1.png)
这里可以看到点击次数。 
合并动作可以用用户选择的方式。
