### ISSUE TITLE
是否可为调用 利用API数据 提供更多便利

### ISSUE THREAD

**Issue by 222YEDONG** [cuiliang/Quicker#743]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
希望能够处理和调用更多的API，**或者提供便利**；目前已经可以调用文字识别的API。。。未来又会支持调用哪些API呢？
灵感来源于这个动作：天气预报动作：https://getquicker.net/sharedaction?code=7684df0e-83f8-40b7-c99b-08d66e1c5f1c
之前也使用过IFTTT 或者zapier之类的服务。。。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
核心逻辑：调用+显示的越少，速度越快
我调用rescutime 的API 他的文档：
https://www.rescuetime.com/anapi/setup/documentation#analytic-api-reference
一部分内容，打开网址之后  大致是这样的：
![image](https://user-images.githubusercontent.com/44609485/73836748-eed5f300-484a-11ea-8773-4a4b56418d60.png)
![image](https://user-images.githubusercontent.com/44609485/73837329-327d2c80-484c-11ea-991c-b271adbfcc96.png)
希望的场景：每小时整点，quicker提示消息的方式来显示过去一小时脉动 数值【目前rescutime网页打开 还是显得有些迟钝 因为调用的数值很多 还要可视化渲染】，自动提取出productivity_pulse【也就是生产率脉动，最好还是不要打开网页，每小时自动浏览器弹窗会打断掉学习流程】
![image](https://user-images.githubusercontent.com/44609485/73837538-a4ee0c80-484c-11ea-912a-702096e7a2e2.png)
![image](https://user-images.githubusercontent.com/44609485/73837789-2cd41680-484d-11ea-8add-0bc667fa97ce.png)
目前的都 实在太复杂了，完全看不懂。。。。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
格式一般都是['csv'| 'json']，是否能够从文本模块部分这方面入手处理。。。全选之后 ，提取出某段信息，可以比这个简略的多，一个小弹窗或者提示消息来显示数据类似于这样，可供参考：
![image](https://user-images.githubusercontent.com/44609485/73838011-ab30b880-484d-11ea-80b5-ecfa5d4183c4.png)
【点击rescutime谷歌浏览器插件后会以上的内容】
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
API可以使用http模块调用。

**Comment by 222YEDONG** [comment]
@cuiliang  感谢群主。。。。我之前看过这个部分的。。。包括文档，还有类似的动作，但是不知道怎么回事，我编辑API动作的时候就是没想起来，可能是因为之前那个模块的部分完全没有看懂，目前根据那个图传示例学习中。。

**Comment by 222YEDONG** [comment]
之前看过几回 ，那个部分，现在还是看不懂。。。

**Comment by 222YEDONG** [comment]
@cuiliang quicker能否优化 编辑窗口 我会双开编辑窗口，无法分屏到两边 有点不方便【使用场景：一边参照别人的动作 一遍写自己的动作】，希望有一天可以支持分屏。随便举例一下啊，目前是这样的：
![image](https://user-images.githubusercontent.com/44609485/73922703-8f3c1e00-4904-11ea-9f11-62a753851581.png)
希望可以变成这样的：
![image](https://user-images.githubusercontent.com/44609485/73922878-d7f3d700-4904-11ea-86cf-2c643049cbe8.png)
目前窗口变不了。。。
【是使用评论还是。。需要提issue吗？】

**Comment by cuiliang** [comment]
分屏windows自己就支持的。 按住标题栏拖放到屏幕的一边松开。

**Comment by 222YEDONG** [comment]
那个分屏 怎么分我知道 是系统支持的，我的意思是说 quicker 编辑两个动作的时候实现类似于图里的效果 @cuiliang

**Comment by cuiliang** [comment]
quicker提供这个没有必要了，一个是用的少，一个是windows本身有，花费很多成本开发不值得。
