### ISSUE TITLE
Quicker的文本输入窗口，输入法的候选窗不显示。

### ISSUE THREAD

**Issue by zghk** [cuiliang/Quicker#744]
**描述BUG**
我使用小小五笔输入法，在Qruicker软件中，需要输入文字的界面，输入法的候选窗不显示。

**重现步骤**
1.
2.

**相关截图**

**环境信息:**
 - 操作系统版本：Win10 18363.592
 - Quicker版本：1.4.13.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个通常是输入法的问题。
我这里使用QQ输入法和windows自带的，没有出现这个问题。
Quicker的窗口会有比较高的权限，另外有一些topmost的窗口，如果输入法处理不好，会有这个现象。
![image](https://user-images.githubusercontent.com/1972649/74094691-4365c080-4b20-11ea-8e05-b9a130bd2713.png)
