### ISSUE TITLE
关于文件管理

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#745]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
![image](https://user-images.githubusercontent.com/44609485/74079654-7010ce00-4a75-11ea-8670-50f1e78b9410.png)
1. @CL-北京  为什么非得鼠标点击的方式,quicker不能打开此电脑 【场景如下：下东西 之前看看各个盘 有多大空间 防止 下载东西 半途装不下 得终止】
2. 实践下面原则时遇到问题，假如可以增加一个文件夹判断或者获取文件夹里面的**文件大小的模块**就好了；
![image](https://user-images.githubusercontent.com/44609485/74079737-620f7d00-4a76-11ea-9fbd-ceedfbf278e3.png)之前文件管理没做好，往印象笔记里面放太多书的PDF，导致现在印象笔记用着时不时转圈，卡顿
2.1是否可以吸收一部分文件管理软件的优点部分，**增加模块**，现在的这些还不太够
![image](https://user-images.githubusercontent.com/44609485/74079760-cdf1e580-4a76-11ea-860f-d7dc5e9dc360.png)
详细信息里面有很多的属性，目前quicker利用到的只有那么一点，我把文件夹部分的动作 都大致看了一遍，大多是在搞文件名，或者文件夹结构【子文件夹似乎只能通过修改变量 +1个】
![image](https://user-images.githubusercontent.com/44609485/74079825-b6ffc300-4a77-11ea-8188-8b0118717ca9.png)
买了xyplorer很久了，精力没放到上面，没有咋调教过，那个区的动作太少【就只有我和其他几个寥寥无几的传了动作】，xyplorer+quicker不深入，所以也没有办法说出很具体的quicker可以吸收的优点。【突然想到文件夹部分有些动作 复制到xyplorer 失效】
- ![image](https://user-images.githubusercontent.com/44609485/74079969-7a34cb80-4a79-11ea-9b94-6311fd1f01b3.png)蛮不错
- ![image](https://user-images.githubusercontent.com/44609485/74080000-f0d1c900-4a79-11ea-8318-1c5af5933213.png)
3.构建**多对多关系**方面，是否需要更努力一点？**效法RSSHub项目的diygod**，统一 一下反馈的地方！上回发布大数据，几万人在用quicker,群里的只有几千。是否在群里发公告【或者干算**搬到telegram** 不用TIM了，bot发送issues消息】**号召更多人来GitHub提功能需求**
![image](https://user-images.githubusercontent.com/44609485/74080344-13fe7780-4a7e-11ea-9701-3bcfe2109a73.png)
他就叫我提issues【看置顶公告，路由问题，@一概不回】，这个是另外的人回我的
![image](https://user-images.githubusercontent.com/44609485/74080234-d1886b00-4a7c-11ea-9841-80b022d514f4.png)
太多人在@你，你也回不过来，处理这些，写代码的时间会少很多
![image](https://user-images.githubusercontent.com/44609485/74080239-e664fe80-4a7c-11ea-97e3-e3a6e060faf0.png)
---
![image](https://user-images.githubusercontent.com/44609485/74080381-73f51e00-4a7e-11ea-9714-0763be1458ef.png)
他解答了，如何减少这种现象：不同的人，在不同时间 问一样的问题？
![image](https://user-images.githubusercontent.com/44609485/74080376-693a8900-4a7e-11ea-9352-74e7c8ab87b4.png)
**描述你想要的解决方案**
1. 对你想要发生的事情进行清晰简洁的描述。
选中文件点击动作，文件夹大小判断模块起作用，根据判断条件：小于100MB,100-1GB，>1GB,发送到印象笔记，上传到坚果云，百度云。
如上**又带来一个问题**，来自同一个系列的文件自百度云下载之后 按照这一原则传到3个平台，太分散，调用不方便。这个onenote Gem系列工具，**链接不同平台**做的蛮不错的
OneNote插件：OneNote GEM 自动工具：http://cn.onenotegem.com/a/addins/auto-onenote.html
以前用OneNote，那些插件差不多都买了，后来被同步劝退，之前写过几个动作，因为要安装某插件才起效，quicker 怎么处理这个问题，包括现在在用的anki 要用到插件，调用某快捷键使用某个插件的功能【我上传过几个动作，动作里面**用注释，用相同的格式**写好了插件代码，以及安装和说明的地址】，有点**类似于之前**同软件不同版本的问题【我记得是steam的，目前解决了，但是这个呢？】
2.搬到telegram？
3.现在动作的消息互动还不多，通过邮件通知，以后多了呢？所有消息telegram？
![image](https://user-images.githubusercontent.com/44609485/74080547-fe8a4d00-4a7f-11ea-81e1-5b3d5a18d570.png)
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by 222YEDONG** [comment]
这个动作失效了
![image](https://user-images.githubusercontent.com/44609485/74097900-b422d200-4b4c-11ea-921e-37fd00b0a13c.png)
我在自创模版文件夹动作上+印象笔记笔记本名字创建的：![image](https://user-images.githubusercontent.com/44609485/74097906-c8ff6580-4b4c-11ea-9cfa-90205a5760cd.png)

**Comment by cuiliang** [comment]
好多，看不太懂，不太懂...
获取当前路径只在资源管理器里有效。

**Comment by 222YEDONG** [comment]
完全随缘。。。 @cuiliang ，正在实践GTD，把各种乱七八糟，划过脑海的想法都收集起来，然后行动实践，没有表达清楚，非常抱歉，慢慢应该会变好的，精简后如下：
1.希望搞个**telegram quicker 群**，目前只有QQ群。各种消息用机器人发到群里，包括更新 或者issues 啥的，类似于RSSHub的群聊。地址在此：https://t.me/rsshub。
![image](https://user-images.githubusercontent.com/44609485/74218530-4231c080-4ce5-11ea-81c9-62e5cf0f88e6.png)
2.文件管理部分模块能增强，更充分的利用xyplorer，或者说 有人会多创建点动作吗？在xyplorer 没动作用，好些个动作复制到xyplorer失效了。【因为explorer很多动作 有部分步骤看不动 所以我目前没法儿创建很适合我的版本，(＃￣～￣＃)】
3.希望能有个动作，帮助我按照如下的标准来实践文件管理，使得我管理文件更加方便，目前是搞的一团糟。
![image](https://user-images.githubusercontent.com/44609485/74217929-d3079c80-4ce3-11ea-9c09-a753e1d23933.png)
没有想法，不知道怎么搞的话 或许可以参考OneNote插件，有不少插件：OneNote GEM 自动工具：http://cn.onenotegem.com/a/addins/auto-onenote.html

**Comment by cuiliang** [comment]
归档
