### ISSUE TITLE
扩展热键支持导入配置

### ISSUE THREAD

**Issue by Sharpe-x** [cuiliang/Quicker#746]
**扩展热键导入别人分享的配置**
1.可以方便的把自己的配置分享给别人。
2.希望能将特殊控制键A的配置复制到控制键B,便于调整合适的控制键
![image](https://user-images.githubusercontent.com/21981767/74214194-65ee0a00-4cd7-11ea-9788-1a0176ff0411.png)

**Comment by cuiliang** [comment]
已计划添加分享功能。

**Comment by cuiliang** [comment]
已支持
