### ISSUE TITLE
windows 从睡眠模式启动后，quicker 点鼠标中键呼叫不出来

### ISSUE THREAD

**Issue by delphuy** [cuiliang/Quicker#747]
**描述BUG**
windows 从睡眠模式启动后，quicker 点鼠标中键呼叫不出来；需要从托盘区在图标上点右键，显示主界面才行；
OS重启后，正常；

**Comment by cuiliang** [comment]
版本多少？

**Comment by delphuy** [comment]
> 版本多少？

windows版本：win10专业版 1909 
Quicker版本：普通通道版本 1.3.17.0

**Comment by cuiliang** [comment]
开始睡眠后，马上开机，可以正常激活么？在托盘菜单里重新加载一下挂钩之后有效么？

**Comment by delphuy** [comment]
> 开始睡眠后，马上开机，可以正常激活么？在托盘菜单里重新加载一下挂钩之后有效么？

睡眠之后，马上启动，能正常激活；
托盘重新加载挂钩还没试过，我之前一般是晚上合起笔记本开启睡眠，早上启动，不清楚多久能重现，明天早上试试看。

**Comment by cuiliang** [comment]
1.7版本已增加自动检测挂钩功能，请更新测试。如果还有问题请reopen。
