### ISSUE TITLE
quicker语雀用户手册inoreader订阅出现问题。

### ISSUE THREAD

**Issue by 222YEDONG** [cuiliang/Quicker#748]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
![image](https://user-images.githubusercontent.com/44609485/74537729-9fdc3c00-4f75-11ea-99e8-becbb5d9f577.png)
1. 订阅错误，如图，全是错误：
![image](https://user-images.githubusercontent.com/44609485/74537792-be423780-4f75-11ea-9fb2-a1163ebb459e.png)
其他的知乎源还有tinyRSS上的网易 起点等都没问题的。是否需要我去rsshub提issues，我估计是修复不了
![image](https://user-images.githubusercontent.com/44609485/74537955-0eb99500-4f76-11ea-9111-0789ec067712.png)
2. RSS订阅源更新以及图片xian显示问题，希望语雀能够增加对于会员用户的快速通道版本更新的RSS订阅，之前好像说过这个问题，官网文档上的更新比语雀快很多，两个不同步，这个都是7天之前的了，应该是普通通道版本的吧
![image](https://user-images.githubusercontent.com/44609485/74538403-204f6c80-4f77-11ea-9de3-4614c54e9876.png)
去看了一下Pixiv的，图片显示没问题，应该不是inoreader的原因
![image](https://user-images.githubusercontent.com/44609485/74538614-8e942f00-4f77-11ea-895f-3ef87e13925d.png)
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
这个_随缘吧，我只报告有这个情况_
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/74597409-0eb2b580-509a-11ea-9ac5-bb1117510335.png)
你的网址可能搞错了。 我打开https://rsshub.app/yuque/doc/222449 看都是正常的。
