### ISSUE TITLE
chrome 双击左键也会弹出, 占用了我的双击关闭, 设置里面还没法设置.

### ISSUE THREAD

**Issue by rushpixy** [cuiliang/Quicker#75]
chrome 双击左键也会弹出, 占用了我的双击关闭, 设置里面还没法设置.

**Comment by cuiliang** [comment]
截图看下当前的弹出设置。 
如果通过双击模拟了其他操作，而这个操作又会激活Quicker的话，会有这个现象。需要更改激活方式到别的方式。

**Comment by cuiliang** [comment]
Quicker本身并没有识别双击左键的功能。
