### ISSUE TITLE
运行带命令行的程序，命令行参数中有空格的问题

### ISSUE THREAD

**Issue by sunshine2609** [cuiliang/Quicker#751]
**描述BUG**
例如，运行TotalCommand，打开某路径时，如果路径中带空格（比如“C:\Program Files (x86)”），则路径会被截团，无法对正确路径操作。
这不是一个Quick的问题，但是最好能提供一种简易的解决方案，多谢！

**重现步骤**
不需要重现了，应该很明白了吧。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
截图一下是在什么地方运行？

**Comment by sunshine2609** [comment]
你好，我发现应该可以搞的定，就是要在参数两侧加引号，否则就有问题。
看看这个地方能否加一个说明或者小提示，要不像我这种菜鸟可能会一直莫名其妙的出错。。

![1](https://user-images.githubusercontent.com/22074357/75088137-44690a00-5584-11ea-8f64-ae8b3dcae21b.png)

**Comment by cuiliang** [comment]
哦，这个确实和Quicker没有关系，是所调用的软件自身的处理决定的。
参数里路径加双引号应该算是一种常见的处理方式。我等在文档里增加一下。
