### ISSUE TITLE
动作的全局快捷键绑定进程无效

### ISSUE THREAD

**Issue by Smile117** [cuiliang/Quicker#752]
**描述BUG**
动作的全局快捷键绑定进程无效

**重现步骤**
1. 设置动作为模拟按键，例如方向键下
2. 设置全局快捷键，例如：设置k 为动作的快捷键
3. 绑定进程到福昕阅读器窗口
4. 改动作仍在所有程序内都有效，导致k键在其他程序无法使用(例如word)

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win 10 18363.657
 - Quicker版本：1.3.17.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by Smile117** [comment]
> **描述BUG**
> 动作的全局快捷键绑定进程无效
> 
> **重现步骤**
> Steps to reproduce the behavior:
> 
> 1. 设置动作为模拟按键，例如方向键下
> 2. 设置全局快捷键，例如：设置k 为动作的快捷键
> 3. 绑定进程到福昕阅读器窗口
> 4. 该动作仍在所有程序内都有效，导致k键在其他程序无法使用(例如word)
> 
> **相关截图**
> 如果适用，请添加屏幕截图以帮助解释您的问题。
> 
> **环境信息:**
> 
> * 操作系统版本：win 10 18363.657
> * Quicker版本：1.3.17.0
> 
> **附加信息**
> 在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请安装快速通道1.4.25版本解决。
