### ISSUE TITLE
选中word文字并启动quicker智识或翻译组建后，选中的文字自动被删除

### ISSUE THREAD

**Issue by lukegao1990** [cuiliang/Quicker#754]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.选中word中的某段文字
2.鼠标中键启动quicker
3.点击Ever智识或翻译组建
4.选中的文字自动被删除

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
尝试退出系统托盘区域中的所有软件。然后再测试看看。
在其他软件中会删除文字么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
