### ISSUE TITLE
有想过开通赞助渠道嘛？除了会员，差异化的付费

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#755]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
突然想到这个，是因为anki插件还有rsshub autohotkey脚本等的启发，为什么目前要限制只能买3年的会员，大概准备什么时候涨价？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
https://docs.rsshub.app/support/#zhou-qi-xing-zan-zhu
![image](https://user-images.githubusercontent.com/44609485/75223752-184ac480-57e2-11ea-9cb6-272c10d97ae7.png)
群主以后会接受付费赞助帮忙写动作吗？【虽然感觉不太能行，太忙了】或者为这个提供便利？
目前似乎已经有一些动作开始搞账号，付费用了，之前安装过，面板没整理好，不知道放哪里去了。
有没有想过效法一下苹果，苹果为开发者提供便利，苹果收取平台分成费，例如微信打赏要抽成，俗称苹果税。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
归档
