### ISSUE TITLE
quicker边沿触发功能

### ISSUE THREAD

**Issue by Hliyh** [cuiliang/Quicker#760]
**需求描述**
屏幕边缘触发，做热键。上下左右屏幕边沿触发不同的热键，配合鼠标实体按键和键盘实体按键触发功能。（例如：鼠标移到屏幕左边沿触发热键+点击鼠标左键实现设定快捷键返回上一桌面，点击右键又能实现其他不同的功能。）

**Comment by cuiliang** [comment]
配置和实现比较复杂，感觉实际实用性不是很高，还需要鼠标移动较远的距离，不如直接用面板触发动作的。
确实需要的话可以结合手势软件来实现了。
