### ISSUE TITLE
扩展热键/文本指令 添加变量支持（变量内容仅限来自剪切板/当前选中/预设）

### ISSUE THREAD

**Issue by 804260247** [cuiliang/Quicker#761]
有这方面的需求是不想为太简单的动作占用面板空间，比如对选中文字快速添加双引号之类的没必要通过动作来完成

**Comment by cuiliang** [comment]
增加了一下{selection}表示选中的文本。 {cliptext}原来就有，可以代替剪贴板文本。
不过获取选中文本会发送ctrl+c，如果在扩展热键中，可能会因为正在按扩展热键而导致失败。需要后续观察。
