### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by hh-first** [cuiliang/Quicker#762]
**描述BUG**
quicker不稳定，会挂掉

**重现步骤**
1.我设置的中建时间长了会失效得重新启动，而且有时滚轮无法切换动作框
2.点击任务栏弹出界面会出现界面在任务栏底下（我的任务栏是不用会自动收缩的，但正常情况下没问题的）
3.还有就是不同界面(eg:任务栏、chrome等)中间打开弹窗时，有时会出现仍在上一个界面的结果---但左键让其消失后再在新的界面上打开就可以了

**相关截图**
没想起来截图，但问题已经表述出来了，望见谅，以后会记得截图的，谢谢！

**环境信息:**
 - 操作系统版本：win10 1909

 - Quicker版本：普通通道1.4.25.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Quicker是直接运行在默认的安装位置的吧？
感觉像是被什么软件影响了。 可以尝试退出托盘区域中的其他软件，测试一下看看会不会好。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
