### ISSUE TITLE
是否可以用于自动安装软件，能否实现随缘，想到了就提一下。

### ISSUE THREAD

**Issue by 222YEDONG** [cuiliang/Quicker#763]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
由已知的scoop等【少数派可查】、chacolatey，输入代码就可以安装软件，输入代码自动更新全部软件，联想：quicker能否根据应用程序-添加的应用程序设置 的相关信息来安装软件呢？可以不是全部，热门的，挑那些所属的动作多的应用也行。
点击一下安装全部软件，quicker自动采集
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
只需要安装一个quicker之后再不用安装其他的东西了，点击云备份桌面-恢复，提取出设置里面的软件名，数据库里面存着一些软件的下载网址链接，提前规划好文件夹结构，安装到指定的地方。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
假如电脑出现了问题需要重新安装大量的软件，酷安有应用集功能，还有小米可以把 桌面备份到云端，重装系统之后可以使用同步自动安装软件，可能是无利可图+使用频率不是很高的缘故，windows的话国内还没有软件可以实现这个。假如quicker可以实现，可以帮助不少人节约时间，挖360软件管家的墙角。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/75556283-dedfb680-5a78-11ea-8e76-e647f8d98263.png)

**Comment by cuiliang** [comment]
这一个功能比整个Quicker可能都要复杂了。不考虑了。
