### ISSUE TITLE
如何用quicker+tinyRSS来看小说，随缘 提一下这个。

### ISSUE THREAD

**Issue by 222YEDONG** [cuiliang/Quicker#764]
**需求描述**

对需求的描述。如需求的场景、解决的问题等。
这个任务在滴答清单里面放着好久了，但是一直没有一个方向。虽然有下面的这个动作，或者其他类似的动作可供参考：
https://getquicker.net/sharedaction?code=f62dcd82-051d-438a-20e9-08d742f11f76
突然想到一个问题：目前好像quicker都得是自己手动添加，添加了多少引擎才能用多少，能不能做一些改进，类似于小说阅读软件那样可以导入txt 或者其他格式的其他人的书源那样，类似于这个阅读软件下面https://www.coolapk.com/apk/com.gedoor.monkeybook，评论里面有很多人互换书源，   点击切换订阅源太方便了，但是电脑上却不是这样 切换搜索不是那么方便，而且种类也不多，不知道是阅读软件怎么检测哪些源可用，哪些不可用的。导入之后不太清楚有多少书源，软件可以自动找出质量不好的，批量删除
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
奶酪书签里面有很多的网页，还有搜索引擎，之前还在知乎刷过不短的时间去了解工具啊，思维这些乱七八糟的，这个书签可以说的是非常全面了，可以不用刷知乎了，但是没有办法去很好的利用，一个个手动加搜索引擎也太慢了，我百度网盘有离线版本的书签。超级讨厌百度搜索，能不用就不用。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
别问我为什么不去起点看，因为本人太穷了，偶尔会去投一下推荐票。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/75561734-7695d280-5a82-11ea-95ee-5d992982cb16.png)
---
![image](https://user-images.githubusercontent.com/44609485/75561780-844b5800-5a82-11ea-8c65-b9249e9ced3a.png)
---
![image](https://user-images.githubusercontent.com/44609485/75562286-4864c280-5a83-11ea-8d7b-1bdf52baa464.png)
---
![image](https://user-images.githubusercontent.com/44609485/75562772-1869ef00-5a84-11ea-8b69-aee63c2abd21.png)
---
![image](https://user-images.githubusercontent.com/44609485/75563111-c07fb800-5a84-11ea-8f23-d68ed2dfd556.png)
---
我没有去加粗啊，为什么预览是这样的，感觉好难看
![image](https://user-images.githubusercontent.com/44609485/75563260-0b99cb00-5a85-11ea-8d7d-cc01f8701eeb.png)

**Comment by cuiliang** [comment]
专业的事情还是专业的软件做比较好，暂不考虑了
