### ISSUE TITLE
绑定主机有严重bug，识别主机名错误

### ISSUE THREAD

**Issue by elmagnificogi** [cuiliang/Quicker#765]
**描述BUG**
我有两个机器，
主机名1 ELMAGNIFICO
主机名2 ELMAGNIFICO-COM
然后在主机ELMAGNIFICO上可以加载到所有分页，包括ELMAGNIFICO-COM的分页
但是只要我把ELMAGNIFICO-COM不全拼或者换成什么11122之类的东西就加载不出来了
明显时判名字的地方有误，正则写错了或者字符串比较有问题

还有可能是你们程序这里分解字符串用的是符号？？？我主机名里刚好有个符号，split以后可能刚好分成了两个主机？？？？
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by elmagnificogi** [comment]
主机名1 ELMAGNIFICO
主机名2 ELMAGNIFICO-COM
主机名2 ELMAGNIFICO-C
主机名2 ELMAGNIFICO-CO
他们在不同分页上，同时都会加载出来

**Comment by elmagnificogi** [comment]
主机名 ELMAGNIFICO1 这个也能加载出来，这也太奇怪了吧 使用的主机名是ELMAGNIFICO

**Comment by cuiliang** [comment]
之前是通过contains检查。
已解决，等下个版本更新。
