### ISSUE TITLE
同步时，不同电脑软件配置位置不同的问题

### ISSUE THREAD

**Issue by jkyzwh** [cuiliang/Quicker#766]
算不上软件bug，是功能设置的问题，或许也可能是我使用方式不正确。

当在A电脑面板中设置了X程序启动的快捷方式后，会同步至B电脑，而B电脑中X程序的路径与A电脑并不相同，十分令人捉急。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/75639331-48271b80-5c6b-11ea-869d-12292517469d.png)
可以使用备用路径设置其他电脑上的软件位置。

**Comment by cuiliang** [comment]
已发布1.5.1到快速通道，请更新测试。
