### ISSUE TITLE
1.5.1.0版本，上下边缘滚轮调节音量功能失效

### ISSUE THREAD

**Issue by lovemybabyxuan** [cuiliang/Quicker#772]
1.5.1.0版本，上下边缘滚轮调节音量功能失效

**Comment by cuiliang** [comment]
本地测试无问题。 请检查配置中是否启用了相应的选项。 另外可以试试重启quicker、重启电脑、关闭运行中的其他可能用到鼠标的软件测试。
![image](https://user-images.githubusercontent.com/1972649/75830009-a29ab600-5dea-11ea-8c20-5f341f4784ad.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
