### ISSUE TITLE
某些情况下无法输入文本

### ISSUE THREAD

**Issue by NP-Prob** [cuiliang/Quicker#776]
**描述BUG**
问题有二：
1. 在向日葵远控客户端上输入账户、密码时，有时无法输入文本
2. “复制到剪贴板后粘贴（ctrl+V）”的方式输入一定无法输入文本

**重现步骤**
1. 我在刚登出的界面下测试是否能顺利选定账户、密码输入框，并输入文本，发现可以成功用“模拟输入”的方式输入账户&密码，但“复制到剪贴板后粘贴（ctrl+V）”的方式无效；
2. 登录账户后，我将前面写好用来“注销当前账号”的步骤组启用，发现可以正确退出当前账号并正确选定登录界面的账户、密码输入框，但是无论用“模拟输入”的方式还是“复制到剪贴板后粘贴（ctrl+V）”的方式，均无法输入内容

**相关截图**
截图不能很好地反映问题，录屏比较好。

**环境信息:**
 - 操作系统版本：Windows 10 家庭版
 - Quicker版本：1.5.1.0

**Comment by cuiliang** [comment]
密码框很多不允许粘贴的。模拟输入有的也会有问题，是密码框的限制。 QQ的密码框还会更改键盘状态。

**Comment by NP-Prob** [comment]
> 密码框很多不允许粘贴的。模拟输入有的也会有问题，是密码框的限制。 QQ的密码框还会更改键盘状态。

现在的问题是，在未登录状态下，每次都可以准确找到并输入，但是如果有“先注销再登录”这个过程的话，就无法输入了，虽然其他步骤都完全可以准确做到，不明白为什么。

**Comment by cuiliang** [comment]
是不是延时加的不够，可以在输入内容之前多加点延时等待界面准备好。
