### ISSUE TITLE
什么时候更新quicker手机版

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#777]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
感觉好久没有更新quicker手机版本了，家里宽带坏了，电脑一直连的手机热点，为什么这种都链接不上，条件是不是苛刻了一点。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
改进手机版。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
最近一个程序员推荐我的软件，anywhere 类似于苹果的捷径，他说有andorid基础最好，或许群主可以看一下这个软件，用来改进quicker app.这个在酷安就可以下载。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by 222YEDONG** [comment]
出于控制学习边界，不能摊大饼的考虑所以保持了克制，没有学习了解这个，群主可以了解学习一下这个

**Comment by cuiliang** [comment]
整理issues
