### ISSUE TITLE
关于轮盘功能和选择模块

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#779]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
轮盘里的一个动作包含选择模块，生效时候，是否自动可以将选择的选项 放到轮盘动作里面，
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
此时不显示以往设置的动作，按照顺序或者点击的次数自动排序，由里到外，安放选项。鼠标激活轮盘再滑动一次，不弹出选择窗口，用轮盘的那个滑动停止的时候 点击之前激活的某个选项。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
最好可以多次滑动，目前只能滑动一次，激活一次动作。能否支持多层轮盘显示呢，动作页可以通过加载动作页来快速切换动作页，轮盘为什么不行呢？不能跳转。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/76161548-64e1b880-616f-11ea-88b8-1a755f681852.png)

**Comment by cuiliang** [comment]
无法实现哦，选项很多，显示不下。而且触发前也不适合检查动作内容的。
