### ISSUE TITLE
Quicker的“添加应用”中缺少部分UWP应用

### ISSUE THREAD

**Issue by WitherZuo** [cuiliang/Quicker#78]
### 问题
使用Quicker的“添加已安装应用程序”窗口选择程序，里面缺少了部分UWP应用，但电脑上已经安装了这个应用，窗口里则没有出现。  
  
**示例：Img Share**    

### 微软商店截图：
![2018-12-17_16-06-02](https://user-images.githubusercontent.com/25317916/50074215-27b1a380-0216-11e9-9490-144a29559a16.png)

### 表明设备上已经安装了这个应用：  
![2018-12-17_15-59-45](https://user-images.githubusercontent.com/25317916/50074246-3dbf6400-0216-11e9-85df-44516768ad8d.png)

### Quicker里没有出现这个应用，无法搜索到：
![2018-12-17_16-02-27](https://user-images.githubusercontent.com/25317916/50074273-57f94200-0216-11e9-95d3-45c5a95b9b52.png)

**Comment by cuiliang** [comment]
收到

**Comment by cuiliang** [comment]
@WitherZuo 我在MSStore里似乎找不到这个应用

![image](https://user-images.githubusercontent.com/1972649/50134713-4f634300-02cc-11e9-9713-665030c38c66.png)

**Comment by WitherZuo** [comment]
@cuiliang 试一下这个开源的代码看看，也许也可以。。

**Comment by cuiliang** [comment]
@WitherZuo 好的。 还有别的软件有这个现象么？ 我试试看

**Comment by WitherZuo** [comment]
@cuiliang 目前我电脑上只有它无法被搜索到，其它的正常

**Comment by WitherZuo** [comment]
@cuiliang  作者把这个应用更名重新上架了，名字叫picture share。
https://www.microsoft.com/zh-cn/p/picture-share/9phwz3ql0hn3?activetab=pivot:overviewtab

**Comment by cuiliang** [comment]
fixed in 0.9.27
