### ISSUE TITLE
使用“运行脚本”中的“CMD命令（完成后保留窗口）”模式不显示窗口

### ISSUE THREAD

**Issue by NP-Prob** [cuiliang/Quicker#781]
**描述BUG**
使用“运行脚本”中的“CMD命令（完成后保留窗口）”模式不显示窗口

**重现步骤**
1. 用Python写了个脚本，使用“运行脚本”模块运行，获取结果以进一步使用
2. 无论选择“CMD命令（完成后保留窗口）”还是“CMD命令（完成后关闭窗口）”还是“CMD命令（隐藏命令行窗口）”，在执行脚本过程中均未发现弹出命令行窗口
3. 且在修改Python脚本之后（功能不变，仅改为多进程运行），无法正常运行，无法获取结果，而自己打开CMD运行的时候均是有效的
4. 在Windows“运行”对话框中无论是使用cmd /K还是cmd /C方式运行自写脚本也是正常的

**相关截图**
![1](https://user-images.githubusercontent.com/9911456/76251522-1709a500-6282-11ea-9ab3-a5d056038ad0.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭版
 - Quicker版本：1.5.1.0

**Comment by cuiliang** [comment]
所有情况下，如果选择“控制台输出”到变量里，都不会再显示窗口。
脚本模块是把脚本文件的内容直接放在“脚本内容”里，在执行动作的时候动态创建文件并用Process.Start执行这个文件。如果已经存好文件，可以用“运行或打开”模块分别指定python.exe的路径和参数。

**Comment by NP-Prob** [comment]
谢谢您的回复，我后来自己也摸索出来了，而且发现如果Python开了多进程的话，quicker跟踪的是主进程的输出，这一点可能用Python的同学要注意一下了。

**Comment by NP-Prob** [comment]
谢谢您的回复，我后来自己也摸索出来了，而且发现如果Python开了多进程的话，quicker跟踪的是主进程的输出，这一点可能用Python的同学要注意一下了。
