### ISSUE TITLE
打开quicker后，影响word移动流畅度。

### ISSUE THREAD

**Issue by hw-fun** [cuiliang/Quicker#782]
**描述BUG**
对bug的清晰简洁描述。
打开quicker后，影响word移动流畅度。打开quicker后，使用鼠标按住word移动，感觉有粘滞感，不流畅。
**重现步骤**
1.打开word Microsoft Word 2019 MSo (16.0.12527.20170)32位
2.在word不全屏的窗口模式下按住顶部移动，有鼠标不灵、粘滞感。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 家庭中文版
 - Quicker版本：1.4.9.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
嗯，是有这个现象。但是另一些软件的窗口似乎就没有影响。 还没有时间详细研究具体原因。

**Comment by cuiliang** [comment]
重新测试了一下，可能是受到了系统性能的影响，毕竟增加了一层鼠标hook。
测试：打开Quicker，在桌面上移动word窗口，速度很快；但是如果后面开了谷歌浏览器，这时候再移动word就会略慢。
看起来似乎没有可以优化的地方了，暂不处理。
