### ISSUE TITLE
希望Quicker加入云剪贴板功能+QQ群信息

### ISSUE THREAD

**Issue by BlurDelphin** [cuiliang/Quicker#783]
1. 目前在国内环境中，还没有一个很好的云剪贴板工具。国内比较出众的就是快贴了，但快贴并没有后台检测剪贴板变动后自动同步的设定，相比于传统的发送到QQ的方式并没有太大的改变。希望Quicker能够帮助并改善这种局面，也可以让手机端的功能变得更加强大。
2. 在官网上看到了官方QQ群，入群信息是Quicker的网址，但我填写https://getquicker.net，并不对，请知道的人回复一下。
最后祝Quicker越来越好！

**Comment by cuiliang** [comment]
后来加入到群里了么？验证方法已改变，可以明天再试试。 剪贴板在后台会被系统限制，否则就会 是一个安全隐患了。所以这方面会越来越严。

**Comment by BlurDelphin** [comment]
> 后来加入到群里了么？验证方法已改变，可以明天再试试。 剪贴板在后台会被系统限制，否则就会 是一个安全隐患了。所以这方面会越来越严。

已顺利加入QQ群，多谢。
再次提一次，真心希望quicker能够解决多终端剪贴板同步问题，这样才能最大化移动端quicker的优势

**Comment by cuiliang** [comment]
整理issues
