### ISSUE TITLE
悬浮窗按钮建议加上鼠标滑动事件触发

### ISSUE THREAD

**Issue by yancheng199287** [cuiliang/Quicker#786]
我是VIP用户，最近在使用悬浮按钮发现每次需要点击才能触发事件，如果增加鼠标滑动就可以触发事件的选项就非常完美，而不是每次去点击。谢谢

**Comment by yancheng199287** [comment]
鼠标滑动，是指光标经过或者停在悬浮按钮上就能自动触发事件

**Comment by cuiliang** [comment]
比较容易误触发，而且会有点玄学，放上去等待的话，不如直接点击更快速的触发了。

**Comment by yancheng199287** [comment]
可以做成选项开关，我觉得比较实用的，像我每次用翻译的时候，固定在一个点，经常使用，避免每次点击，还是非常实用。这个使用交互，也是我用了chrome浏览器部分插件看到的，在选中内容的时候，自动浮窗，鼠标贴上就可以触发查询。 因为是用户主动贴上去的，自己当然会明白把悬浮按钮放在合适位置的。请再三考虑下哦。



---原始邮件---
发件人: "CuiLiang"<notifications@github.com&gt;
发送时间: 2020年3月14日(周六) 下午3:37
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"WangZiHe"<648830605@qq.com&gt;;
主题: Re: [cuiliang/Quicker] 悬浮窗按钮建议加上鼠标滑动事件触发 (#786)




 
比较容易误触发，而且会有点玄学，放上去等待的话，不如直接点击更快速的触发了。

**Comment by cuiliang** [comment]
整理issues：暂不考虑了哦。
