### ISSUE TITLE
轮盘菜单bug

### ISSUE THREAD

**Issue by slmlms** [cuiliang/Quicker#789]
**描述BUG**
Chrome窗口和微信电脑版（其他软件差不多）同时显示时（微信在Chrome上方），使用轮盘菜单关闭微信窗口，然后点击Chrome中的网页链接，会自动下载该网页

**重现步骤**
1.开启Chrome
2.开启微信，使得微信显示于Chrome上方
3.使用轮盘菜单关闭微信窗口
4.点击Chrome中的任意网页链接
5.会自动下载该网页，而不是打开链接

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
win10家庭中文版  18362.239
 - Quicker版本：
1.5.4.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
本地测试没有出现这个问题。 不过这个问题可能和某些情况下alt变成按下状态有关。https://github.com/cuiliang/Quicker/issues/757
目前还不清楚这个是什么原因，有可能是windows的一个bug。

**Comment by slmlms** [comment]
> 本地测试没有出现这个问题。 不过这个问题可能和某些情况下alt变成按下状态有关。#757
> 目前还不清楚这个是什么原因，有可能是windows的一个bug。

微信也是通过轮盘菜单启动，直接启动没有出现此问题

**Comment by cuiliang** [comment]
快速通道已更新1.6.6版本，对alt处理了一下，方便的时候请测试看看是否还有问题。

**Comment by cuiliang** [comment]
https://getquicker.net/QA/Question/1944
