### ISSUE TITLE
多选的另外一种操作方式

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#790]
兼容单选的操作模式，单击返回。
按ctrl可以多选、右键可以多选。

**Comment by kanglade** [comment]
这个暂时还是不改了吧。
如果以后要改的话，有两点冲突需要考虑（写在这里备忘）：
① Ctrl有可能被动作开发者通过「按键操作」来实现了某些特殊功能；
② 右键以后有可能实现快捷菜单的功能。

**Comment by cuiliang** [comment]
整理issues
