### ISSUE TITLE
upupoo会使quicker不能通过鼠标弹出面板

### ISSUE THREAD

**Issue by dtxdtx** [cuiliang/Quicker#792]
**描述BUG**
upupoo打开后，会使得在任何应用中都无法通过鼠标弹出面板，只能手动选择重新加载鼠标挂钩后才能恢复正常。

**重现步骤**
1. 打开quicker
2. 打开upupoo

**环境信息:**
 - 操作系统版本：win10专业版
 - Quicker版本：1.4.25.0

**附加信息**
upupoo这个东西是好几个程序组成的

**Comment by dtxdtx** [comment]
> **描述BUG**
> 在打开桌面美化软件upupoo的开机自启后，开机后在显示了Quicker已启动后，在所有应用中，都无法通过鼠标弹出面板，需要手动选择重新加载鼠标挂钩。
> 
> **重现步骤**
> Steps to reproduce the behavior:
> 
> 1. 安装upupoo，打开其开机自启（默认打开）。
> 2. 电脑开机后就出现bug了
> 
> **环境信息:**
> 
> * 操作系统版本：win10专业版
> * Quicker版本：1.4.25.0
> 
> **附加信息**
> 建议开机一段时间后自动重新加载鼠标挂钩

**Comment by cuiliang** [comment]
桌面软件为什么要使用鼠标挂钩呢，建议向upupoo反馈解决一下。 qk自身没法判断什么时候挂钩不正常了，无法自动的重新挂钩。
