### ISSUE TITLE
分享动作窗口的备注会撑宽窗口

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#793]
享动作窗口的备注栏，有没有可能设置自动换行？一旦备注内容过长，窗口就会很宽，并且超过一定字数就被吞掉显示不出来，不会自动换行。同样的情况也会出现在动作库，悬停在有很长备注内容的动作上面时，临时显示的详情页页也很长很长不会自断行。

**Comment by NewbieToEverything** [comment]
您在工具箱里搜索 [Export Reference](https://getquicker.net/Sharedaction?code=277357c6-4f9d-438b-52a3-08d7ccaa0ea8)，然后鼠标悬浮到图标上让含有备注信息的临时弹出窗口浮现，就可以复现这个撑宽窗口的问题。不排除和我使用的设备分辨率较低（1366*768）导致屏幕显示有限有关系，但是如果能改为限制单行字符数并自动断行，窗口向下方自适应加宽，可能会比更好一些。
Quicker version: 1.5.5.0

**Comment by cuiliang** [comment]
> 您在工具箱里搜索 [Export Reference](https://getquicker.net/Sharedaction?code=277357c6-4f9d-438b-52a3-08d7ccaa0ea8)，然后鼠标悬浮到图标上让含有备注信息的临时弹出窗口浮现，就可以复现这个撑宽窗口的问题。不排除和我使用的设备分辨率较低（1366*768）导致屏幕显示有限有关系，但是如果能改为限制单行字符数并自动断行，窗口向下方自适应加宽，可能会比更好一些。
> Quicker version: 1.5.5.0

方便截图一下么？没太搞明白是哪个地方。分享窗口已经处理好等下个版本更新。

**Comment by NewbieToEverything** [comment]
> > 您在工具箱里搜索 [Export Reference](https://getquicker.net/Sharedaction?code=277357c6-4f9d-438b-52a3-08d7ccaa0ea8)，然后鼠标悬浮到图标上让含有备注信息的临时弹出窗口浮现，就可以复现这个撑宽窗口的问题。不排除和我使用的设备分辨率较低（1366*768）导致屏幕显示有限有关系，但是如果能改为限制单行字符数并自动断行，窗口向下方自适应加宽，可能会比更好一些。
> > Quicker version: 1.5.5.0
> 
> 方便截图一下么？没太搞明白是哪个地方。分享窗口已经处理好等下个版本更新。

![image](https://user-images.githubusercontent.com/36309469/77329184-95714700-6d58-11ea-9079-efedac241acd.png)
您说的是这个么？重现步骤：鼠标中键->（腰栏）工具窗口->搜索 Export Reference -> 鼠标悬浮
另外我在截图的时候发现，当鼠标中键呼出 Quciker 时，Quicker 的窗口是在最顶端的，截图软件如 Snipaste 无法截取到，这是功能需要还是 bug？

**Comment by cuiliang** [comment]
> > > 您在工具箱里搜索 [Export Reference](https://getquicker.net/Sharedaction?code=277357c6-4f9d-438b-52a3-08d7ccaa0ea8)，然后鼠标悬浮到图标上让含有备注信息的临时弹出窗口浮现，就可以复现这个撑宽窗口的问题。不排除和我使用的设备分辨率较低（1366*768）导致屏幕显示有限有关系，但是如果能改为限制单行字符数并自动断行，窗口向下方自适应加宽，可能会比更好一些。
> > > Quicker version: 1.5.5.0
> > 
> > 
> > 方便截图一下么？没太搞明白是哪个地方。分享窗口已经处理好等下个版本更新。
> 
> ![image](https://user-images.githubusercontent.com/36309469/77329184-95714700-6d58-11ea-9079-efedac241acd.png)
> 您说的是这个么？重现步骤：鼠标中键->（腰栏）工具窗口->搜索 Export Reference -> 鼠标悬浮
> 另外我在截图的时候发现，当鼠标中键呼出 Quciker 时，Quicker 的窗口是在最顶端的，截图软件如 Snipaste 无法截取到，这是功能需要还是 bug？

哦，这个提示是.Net系统的，在内容比较多的时候可能确实对低分屏不太友好。我试试能不能限制一下。

最顶端是正常的，因为Quicker要和别的软件交互，必须使用topmost才能看到。再加上quicker窗口权限比较高，截图软件有时候会处理不好。可以用管理员身份启动截图软件试试。或者从quicker窗口外开始截图。

**Comment by cuiliang** [comment]
@NewbieToEverything 
宽度限制了一下，现在应该好多了。等下个版本加进去。
![image](https://user-images.githubusercontent.com/1972649/77372887-c033bd80-6da1-11ea-8432-ce7b100c3731.png)

**Comment by NewbieToEverything** [comment]
@cuiliang 棒，这样看起来效果好多了。
