### ISSUE TITLE
文本悬浮窗无法显示？？？

### ISSUE THREAD

**Issue by hzm5666** [cuiliang/Quicker#798]
**描述BUG**
我尝试     选中文本/输入文本/单击   ， 文本悬浮窗均未显示（已打开文本悬浮窗功能）
  - 未安装任何安全软件
  - 除了“Realtek高清晰音频管理器”（系统自带，不让关）未运行任何非系统程序
  - 未运行任何动作
  - 多次重启均无效

**环境信息:**
 - 操作系统版本：Windows10 x64---1903版（os内部版本18362.720）
 - Quicker版本：1.5.5.0

**Comment by cuiliang** [comment]
记事本里试试？
不行的话退出帐号重新登录再试试。
![image](https://user-images.githubusercontent.com/1972649/77248845-abf3a180-6c77-11ea-9845-9b401ede04fd.png)

**Comment by cuiliang** [comment]
整理issues
