### ISSUE TITLE
希望手机端能够切换动作页

### ISSUE THREAD

**Issue by bieniudeiRh** [cuiliang/Quicker#799]

**Comment by cuiliang** [comment]
已经有一个版本可以了
[quicker_cn1.0-1-debug.apk.zip](https://github.com/cuiliang/Quicker/files/4365433/quicker_cn1.0-1-debug.apk.zip)

**Comment by bieniudeiRh** [comment]
好的，谢谢

**Comment by bieniudeiRh** [comment]
好的，谢谢
