### ISSUE TITLE
自定义子程序？

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#8]
请问能否以类似于Wox的插件的形式自定义子程序？类似地，如果能提供多编程语言支持就更好了！

**Comment by cuiliang** [comment]
目前的话，可以通过组合动作，把第三方的应用作为一个步骤执行（选中“等待进程结束”选项，这个进程退出后再执行后续的操作）。可以通过剪贴板作为数据传递的中介。未来会考虑支持自定义插件系统，这样可以实现共享。 您主要是希望通过插件实现什么样的功能？

**Comment by LonelySteve** [comment]
比如词典查询/中英互译，现在的方法是打开浏览器查询。但是每次都得手动关闭搜索结果页，用户也不总是查询网页上的字词翻译，因此对于文档或者代码的某一处字词进行翻译查询，都为此浏览器新开一个标签页的行为既麻烦又慢。
我期望能够直接弹窗显示所选文本的翻译结果，目前这受限于子程序种类过少而无法做到（木有和网络交互的子程序），但开发者显然不可能编写一整套完整的标准库，因此插件系统/自定义子程序是必要的。

**Comment by cuiliang** [comment]
是的，这个会考虑一下。目前正在重新设计组合动作功能，应该会增加一些通用的网络调用支持。插件系统也在考虑之中。
当前的版本可以这样实现：先通过子程序发送ctrl+c，把选中的内容放入剪贴板，然后增加一个步骤启动写好的翻译程序，在这个程序中读取剪贴板内容，做处理（比如调用第三方翻译接口）后显示。

**Comment by cuiliang** [comment]
整理issues
