### ISSUE TITLE
运行子程序的参数设置窗口中长变量名显示不全

### ISSUE THREAD

**Issue by NewbieToEverything** [cuiliang/Quicker#803]
**描述BUG**
如截图所示，当变量名较长时，处在页面上半部分的参数区域的长变量会被截断不显示，下半部分的输出区域的长变量会被自动断行全部显示。
这个问题很有可能和我的电脑的低分辨率有关系，但是我没有其他设备可以检测。

**重现步骤**
可以通过下载并编辑“快速添加多个类别”动作来复现
1. 编辑动作
2.在主程序步骤区域，编辑运行子程序：增加类别或子类别

**相关截图**
![image](https://user-images.githubusercontent.com/36309469/77383456-ebc4a100-6dbd-11ea-8e38-3d15ff824867.png)

**环境信息:**
 - 操作系统版本：win 10
 - Quicker版本：1.5.6.0

**附加信息**
附带一点想法，也一并写在了截图里

**Comment by cuiliang** [comment]
1.10.6 改成和下面一样了。
