### ISSUE TITLE
使用clover后无法使用获取资源管理器当前路径的动作

### ISSUE THREAD

**Issue by linszx** [cuiliang/Quicker#806]
**描述BUG**
在clover下使用获取资源管理器当前路径的操作后，系统提示“无法获取当前路径，请在资源管理器中执行本操作”，希望能够兼容该软件

**重现步骤**
1.安装clover
2.调用获取资源管理器当前路径的操作

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win7
 - Quicker版本：1.4.25.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个问题无解哦，原来就有。
可以使用其他tab插件试试，qttabbar

**Comment by zj1123581321** [comment]
https://www.cnblogs.com/zhiyin1209/p/12150113.html

按照这个操作，我在 Clover 里面可用 Quicker
