### ISSUE TITLE
快速定位（某个/多个）步骤

### ISSUE THREAD

**Issue by NewbieToEverything** [cuiliang/Quicker#812]
**需求描述**
动作一旦写复杂了以后，后续如果需要反复微调某一步骤，比如等待时间，定位起来很痛苦，要凭记忆去定位，多几次这样的操作会很容易眼花。

**描述你想要的解决方案**
1. 主程序步骤 旁的搜索框内可以支持搜索动作名称，然后高亮结果
或2. 可以将步骤“收藏”（大概意思）至一个类似快捷定位栏的地方，点击就跳转到该位置，方便修改
或3. 在编辑窗口的某一位置提供一个树状大纲/或者整个动作所有步骤的缩略图（框出屏幕中正在显示的区域，并随着上下滚动实时更新）

表达方式很不专业，请理解。

**Comment by cuiliang** [comment]
可以ctrl+点击保存，仅保存动作，不关闭窗口。
另外，也可以在编辑器中直接调试或运行动作，请参考：
https://www.yuque.com/quicker/help/xaction-editor#sxKsx

关键词高亮目前也是有的。
