### ISSUE TITLE
根据不同按键呼出不同的轮盘

### ISSUE THREAD

**Issue by PotoTan** [cuiliang/Quicker#813]
**需求描述**
根据鼠标不同的侧键呼出不同的轮盘

换句话说：特定按键呼出特定的轮盘，提供多轮盘设置，而不是现在的单轮盘

**描述你想要的解决方案**
用户可以设置不同鼠标侧键呼出不同的轮盘，从而获得更多的功能

**描述您考虑过的替代方案**

 **其他上下文**
单轮盘可能不能够满足鼠标侧键多的用户需求

**Comment by cuiliang** [comment]
轮盘的设计目的是快速触发最常用操作。轮盘多了会产生选择成本。所以暂不考虑增加类似功能。

更多的动作应该通过面板窗口选择或搜索查找。
