### ISSUE TITLE
Quicker内建桌面端移动端文件传输

### ISSUE THREAD

**Issue by isPoto** [cuiliang/Quicker#814]
**需求描述**
现在quicker app和desktop可以传输图片。

如果可以传输文件的话会不会更好呢？

我苦于电脑手机之间的无线传输，希望quicker能够实现电脑手机之间的文件双向传输

**描述你想要的解决方案**
像图片可以在电脑手机上无缝传输一样，希望quicker也能在电脑手机之间传输文件，文件默认保存在download文件夹下

**描述您考虑过的替代方案**
在图片传输icon旁边添加文件传输按钮

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
后来有了http服务器模块。
