### ISSUE TITLE
能有唤出窗口的悬浮球

### ISSUE THREAD

**Issue by BigTear** [cuiliang/Quicker#821]
**需求描述**
希望能有唤出窗口的悬浮球，surface平板挺依赖quicker的，如果quicker有iPhone小圆点那种悬浮球会非常方便

**Comment by cuiliang** [comment]
surface 可以用GestureSign模拟快捷键触发仪表盘视图，感觉会更省力一点。

**Comment by cuiliang** [comment]
另外，有悬浮动作页的功能，可以将某些动作页悬浮出来。
