### ISSUE TITLE
启动软件多个电脑间不适配

### ISSUE THREAD

**Issue by Utobehabe** [cuiliang/Quicker#822]
**需求描述**
现在Quicker软件，我现在主要是运用在主机电脑和笔记本电脑，现在在主机电脑配置了，在笔记本启动软件基本都要重新配置一次才可以用。而且主机电脑和笔记本存放软件的位置是有差异也无法统一。

**描述你想要的解决方案**
一个启动软件命令可以存放不同电脑的启动位置，用电脑的MAC地址或者电脑名称来保存。

如果能解决这个问题，真的是太感谢了

**Comment by cuiliang** [comment]
”运行或打开“ 支持备用路径参数。可以用于填写不同电脑上的路径。
你也可以在动作里通过“获取系统信息”得到主机名来做判断。
