### ISSUE TITLE
电脑自动启动时候，鼠标挂钩有时候没启动作用

### ISSUE THREAD

**Issue by yancheng199287** [cuiliang/Quicker#823]
有时候有用，有时候没用，没用的时候要重新加载鼠标挂钩。
挺麻烦的，建议优化下。

我是windows10

**Comment by cuiliang** [comment]
可能是其他软件影响了挂钩。
包含手势软件、鼠标增强软件、桌面增强软件等。请测试排除影响。
也有可能电脑性能差导致挂钩超时。

**Comment by yancheng199287** [comment]
不会吧，我也不懂啊，你就不能用其他办法解决下吗，很影响用户体验



---原始邮件---
发件人: "CuiLiang"<notifications@github.com&gt;
发送时间: 2020年3月31日(周二) 下午4:42
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"WangZiHe"<648830605@qq.com&gt;;
主题: Re: [cuiliang/Quicker] 电脑自动启动时候，鼠标挂钩有时候没启动作用 (#823)




 
可能是其他软件影响了挂钩。
 包含手势软件、鼠标增强软件、桌面增强软件等。请测试排除影响。
 也有可能电脑性能差导致挂钩超时。

**Comment by Clemon-afk** [comment]
我也经常出现这个情况，建议优化一下

**Comment by cuiliang** [comment]
@Clemon-afk @yancheng199287 快速通道1.6.4 已增加自动检测挂钩功能，可以测试下看看。
