### ISSUE TITLE
发送文本的时候可不可以设计智能点

### ISSUE THREAD

**Issue by yancheng199287** [cuiliang/Quicker#824]
有时候自己写代码，或者写文章，需要对特定的一个字符串进行加工后处理。

比如 我自己写了一个变量名 name

自动根据变量名，生成一个方法

public void getName(){
}

相当于可以对指定的字符串进行加工处理输出。  这边建议加入下脚本吧。 或者看有没有其他办法

**Comment by cuiliang** [comment]
这个可以通过组合动作实现。
先获取选中的文本，然后拼接更多的内容，再发送到当前窗口就可以了。
