### ISSUE TITLE
无法选中主面板二级菜单

### ISSUE THREAD

**Issue by isdoge** [cuiliang/Quicker#826]
**描述BUG**
无法选择到主面板二级菜单，移动到'数据同步'与'工具'菜单的二级菜单过去后，二级菜单自动隐藏

**重现步骤**
1.打开主面板菜单“···”
2.移动到“数据同步”项，左侧会显示二级菜单“立即同步 与 同步历史”
3.鼠标移动过去，到交界处，二级菜单自动消失，选择不到。

**相关截图**
![图片](https://user-images.githubusercontent.com/19979176/78040831-903c7980-73a2-11ea-9dbc-a59a394bad9f.png)

**环境信息:**
 - 操作系统版本：Windows10企业版LTSC
 - Quicker版本：1.5.6.0

**附加信息**
只有把主窗口移到屏幕最左侧，二级菜单才会显示在一级菜单右侧。此情况下二级菜单才可被选中

**Comment by cuiliang** [comment]
可以试试这里的方法是否有效：https://getquicker.net/kc/help/doc/menu-left-problem
这个应该是windows本身的某个设置导致的，在软件里没法控制。但是还不是十分确定是哪里的原因。

**Comment by isdoge** [comment]
> 
> 
> 可以试试这里的方法是否有效：https://getquicker.net/kc/help/doc/menu-left-problem
> 这个应该是windows本身的某个设置导致的，在软件里没法控制。但是还不是十分确定是哪里的原因。

此方法有效~
另一台win7电脑上并不会出现此问题。可能是win10的问题
