### ISSUE TITLE
激活窗口的鼠标中键，与其他功能冲突

### ISSUE THREAD

**Issue by DavidHJong** [cuiliang/Quicker#827]
**需求描述**
一些软件需要用到鼠标中键，比如网页浏览器用鼠标中键关闭标签页，在windows 10任务栏上点中键新建窗口，三维模型软件用鼠标中键转换视角。现在鼠标中键被占用，无法实现以上的原始功能。

**描述你想要的解决方案**
最好是能够根据当前窗口类别和鼠标位置，决定是否让鼠标中键激活窗口。比如，

- 当前窗口为Edge时，如果判定鼠标在标签页位置点击中键，则不激活Quicker，而是保留其原始功能：关闭标签页。

- 当鼠标在任务栏Windows 10 的任务栏范围内点击鼠标中键，则不激活Quicker，而是打开新窗口。

- 如果在Sketchup中按下中间，也不激活Quicker，而是保留其原始功能：旋转视角。

**描述您考虑过的替代方案**
如果以上难以做到，可以考虑让用户自定义激活按键。比如设施ctrl+中键，或者中键+右键，等等。

**Comment by cuiliang** [comment]
本来就可以自定义的哦。 还可以加黑名单的。
https://www.yuque.com/quicker/help/activate

**Comment by DavidHJong** [comment]
哦哦，多谢
