### ISSUE TITLE
能否搜索动作的时候 右键增加一个跳转到

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#830]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
希望搜索到的动作，右键之后增加一个 跳转到显示的面板的选项
![image](https://user-images.githubusercontent.com/44609485/78325299-d31c6e00-75a9-11ea-98f4-eb9b32ba5174.png)
例如此图片的，右键然后点击跳转到，就自动弹出动作所在的面板
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
1.6.4
