### ISSUE TITLE
用户输入模块窗口会遮挡微软拼音输入法候选窗口

### ISSUE THREAD

**Issue by XHZMC** [cuiliang/Quicker#831]
**描述BUG**
rt

**重现步骤**
使用微软拼音输入法在用户输入模块窗口输入信息

**相关截图**
![批注 2020-03-30 160422](https://user-images.githubusercontent.com/45710247/78328032-be8fa400-75b0-11ea-845c-c40eb35c4606.png)

**环境信息:**
 - 操作系统版本：10.0.19041
 - Quicker版本：1.5.8.0

**附加信息**
无

**Comment by cuiliang** [comment]
每次都这样还是偶尔这样？ 我在win10 1909上是正常的。
![image](https://user-images.githubusercontent.com/1972649/78415156-880a6580-7652-11ea-9b6c-0bb4dfc19f99.png)

**Comment by XHZMC** [comment]
每次都这样

**Comment by XHZMC** [comment]
1.6.4

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/80793598-247c4500-8bca-11ea-942d-b8f8419cae70.png)
额，这个我也不清楚具体是什么原因，本地测试没问题。

**Comment by XHZMC** [comment]
win10 2004有此问题

**Comment by cuiliang** [comment]
用户输入已修改为非topmost，应该不再遮挡了。
先关了，如果还有问题，请再reopen
