### ISSUE TITLE
扩展热键 Capslock 太容易误触发了

### ISSUE THREAD

**Issue by mgdreamingstar** [cuiliang/Quicker#832]
使用 Capslock 为 Hyper 键，虽然设置了单击不触发 Capslock，但还是因为热键机制会开启大写状态。

1. 按住 Capslock 和其他键时，偶尔会开启大写
2. Shift/Ctrl + Capslock 会开启大写 

可否提供将 Capslock 映射为一个不存在的按键，比如 F13，然后再将 F13 + 其他键 映射为其他的功能。

**Comment by mgdreamingstar** [comment]
另外，可否添加扩展热键中，单个条目的单独开关（禁用/启用）

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
