### ISSUE TITLE
圆盘显示软件问题

### ISSUE THREAD

**Issue by Drchen-AI** [cuiliang/Quicker#839]
**描述BUG**
圆盘图标在桌面显示没有问题，但到浏览器中显示就会缺少不少

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://getquicker.net/kc/help/doc/circle-menu
如果某个位置不显示，可以在位置上添加一个操作后再删掉，一般就可以解决了。
