### ISSUE TITLE
官网文档【快速为动作设置图标】的图片挂了

### ISSUE THREAD

**Issue by mifenfeifen** [cuiliang/Quicker#84]
显示【此图片来自微信公众平台，未经允许不可引用】

建议：把图片地址后面那串参数删除
https://mmbiz.qpic.cn/mmbiz_gif/lKM237bcQSCy3E1ZmS4fGXlzc2sCACUFTvxI3emoV1uErsicgia1c91jJHoN9EKobFyWUkU207icSO0oic4r9x3fAw/640?wx_fmt=gif&tp=webp&wxfrom=5&wx_lazy=1
↓
https://mmbiz.qpic.cn/mmbiz_gif/lKM237bcQSCy3E1ZmS4fGXlzc2sCACUFTvxI3emoV1uErsicgia1c91jJHoN9EKobFyWUkU207icSO0oic4r9x3fAw/640

**Comment by cuiliang** [comment]
好的，谢谢，我重新传一下

**Comment by cuiliang** [comment]
更新成本地图片了
