### ISSUE TITLE
删除动作轮盘动作后无法添加同一个动作到动作轮盘

### ISSUE THREAD

**Issue by xccy** [cuiliang/Quicker#840]
将动作轮盘的动作删除后，在设置面板将动作重新添加到动作轮盘，此时设置窗口明明已经显示添加动作成功，但到真正使用的时候轮盘上那个位置还是空的，无法使用

**Comment by cuiliang** [comment]
不是很明白，简单测试也没复现。
方便录屏一下么？

**Comment by xccy** [comment]
抱歉我这边也是偶尔才会出现（捂脸），现在没法录屏。如果下次再出现我再录屏发给你吧。如果你没收到过其他人反应同一个问题的话，也可能是我电脑上有什么东西导致了冲突




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CuiLiang"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 晚上10:09
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com&gt;; 
抄送: "星尘草"<2232198572@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cuiliang/Quicker] 删除动作轮盘动作后无法添加同一个动作到动作轮盘 (#840)





 
不是很明白，简单测试也没复现。
 方便录屏一下么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
