### ISSUE TITLE
增加User Installer

### ISSUE THREAD

**Issue by u3IFw2wfJ** [cuiliang/Quicker#847]
现在的安装包默认为System Installer, 在安装的时候需要申请管理员权限。但是很多人（比如我），在公司里用的时候公司的电脑一般是没有管理员权限的，就很麻烦。有没有可能弄一个User Installer，安装在用户文件夹，不需要管理员权限的那种？
比如VS Code就提供了一个User Installer：
![image](https://user-images.githubusercontent.com/32400590/78729307-94125380-78ee-11ea-8c7b-0efab9bea693.png)

https://code.visualstudio.com/insiders/

**Comment by cuiliang** [comment]
Quicker软件因为其本身的特点，需要和其他进程协作交互，需要高级别的权限级别，需要使用Windows的自动提权机制。这个机制要求把软件安装到指定的几个位置之一。
可以参考：https://getquicker.net/KC/Help/Doc/install#59TP4
