### ISSUE TITLE
多屏幕下截图偏移故障

### ISSUE THREAD

**Issue by yuu011** [cuiliang/Quicker#848]
**描述BUG**
单屏幕下一切正常，一旦外接显示器，设置为扩展显示器之后，所有涉及截图功能都出现偏移问题。

具体表现为：
1.截图时，屏幕最右侧出现空白位移。因为被空白矩形挤占，最左侧画面缺失
2.实际得到的截图，并没有出现空白位移。
3.也就是说，实际截图的位置比显示的画面更靠右。空白矩形相当于一个“障眼法”，截图的时候出现，截图后却消失，造成了实际截图偏移。

但是截图后，呈现的截图，却出现的是

**重现步骤**
1.插入扩展显示器
2.截图
3.得到一张偏移的截图

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
https://wx2.sinaimg.cn/large/4d741d52gy1gdnbim9c50j21ys0u01dp.jpg

**环境信息:**
 - 操作系统版本：WIN10 专业工作站版 64位 （10.0，版本18363）
 - Quicker版本：1.5.12.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果两个显示器有不同的dpi设置就会出现这个情况。这个问题需要重写截图模块才能解决，
目前的话如果经常这样用，可以在配置里设置第三方截图的快捷键，改为使用其他截图软件截图。
![image](https://user-images.githubusercontent.com/1972649/78849269-925ba380-7a46-11ea-956e-d48d6495bd91.png)

**Comment by cuiliang** [comment]
你好， 1.11.1 增加了dpi感知，方便的话请测试一下看看 现在内置截图模块是否能正常工作了。 https://getquicker.net/Help/Versions/Version?version=1.11.1.0

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
