### ISSUE TITLE
希望在设置“禁止在此软件下使用轮盘菜单”改为“在此软件下使用轮盘菜单”

### ISSUE THREAD

**Issue by cdaotgriver** [cuiliang/Quicker#850]
希望在设置“禁止在此软件下使用轮盘”改为“在此软件下使用轮盘”

因为某些软件quicker无法添加到应用程序设置里面，这就导致该软件的热键与调出轮盘菜单的热键冲突，影响使用

**Comment by cuiliang** [comment]
不太明白。
这种情况不正是应该禁用轮盘的情况么？

**Comment by cdaotgriver** [comment]
> 不太明白。
> 这种情况不正是应该补充轮盘的情况么？

我之前的语序有问题，应该这样说“因为某些软件的热键与调出轮盘菜单的热键冲突，而quicker无法将该软件添加到应用程序设置里面，因此无法设置’在此软件下禁止使用轮盘’。”

**Comment by cuiliang** [comment]
轮盘菜单的设计初衷是提供一个全局快捷操作工具，类似于全局手势软件一样。 所以扩展圈的操作默认和建议都是一些通用操作，如关闭窗口之类的。
如果不是全局使用，建议禁用轮盘功能直接使用面板窗口即可。

**Comment by cdaotgriver** [comment]
> 轮盘菜单的设计初衷是提供一个全局快捷操作工具，类似于全局手势软件一样。 所以扩展圈的操作默认和建议都是一些通用操作，如关闭窗口之类的。
> 如果不是全局使用，建议禁用轮盘功能直接使用面板窗口即可。

我直接以某些软件举例吧，我在Chrome里面利用中键调用轮盘菜单进行快捷操作非常方便，但是我在solidworks三维制图软件里不需要轮盘甚至quicker的面板窗口都不需要调出，可如果不关闭quicker我只要一使用中键（在SW里中键的功能很重要），轮盘菜单就会出现影响我的操作，可是我在quicker的软件设置里面找不到SW，那也就无法设置“在此软件下禁用轮盘菜单”，所以一旦我需要使用SW，那就必须关闭quicker，同理在其他软件上也可能会出现这个问题。

**Comment by cuiliang** [comment]
> 在应用程序设置里面找不到该软件

应用程序设置是根据需要添加的哦。https://www.yuque.com/quicker/help/profiles
