### ISSUE TITLE
希望增加弹出面板的键盘黑名单。在弹出面板黑名单里只能设置鼠标激活的黑名单，不能设置键盘激活的黑名单，我用的ctrl弹出面板，但在另一个软件里ctrl有单独的用处

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/Quicker#851]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
无法实现此功能，目前键盘是全局的和鼠标有明确指向是不同的。
可以设置使用快捷键，取消单击ctrl。在必要的时候可以使用快捷键暂停quicker。
