### ISSUE TITLE
文本参数输入框可选支持的扩展菜单

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#855]
根据参数的用途显示扩展菜单而不是全部显示
如填写进程名的，只显示选择进程的即可。
另外可选是添加到末尾还是替换模式。

**Comment by kanglade** [comment]
看到这个提醒我了，对于模块我一直有个想法，许多模块的选项太多，很多只有在少数情况下才会用到，所以我想对于那些不常用的选项是不是可以折叠起来，点击后才展开呢？这个想法在我脑中存了很久，如果能实现的话，还是非常希望实现的。
![image](https://user-images.githubusercontent.com/24608004/79064443-9c4a0480-7cdb-11ea-9465-d07b384063b5.png)

**Comment by kanglade** [comment]
还有「多字段表单」，可不可以选择性的折叠呢？

**Comment by cuiliang** [comment]
后来有了文本选择工具。
