### ISSUE TITLE
触摸点击面板以外区域关闭面板

### ISSUE THREAD

**Issue by WangYH195** [cuiliang/Quicker#857]
**需求描述**
弹出面板后，点击面板以外区域时自动关闭面板。因为有时候会误触发面板弹出，但是必须点右上角的×才能关，很不方便。

**Comment by cuiliang** [comment]
正常都是点外面自动关闭的啊。
是不是“钉住”了，或者挂钩丢失了。
https://www.yuque.com/quicker/help/pin
https://getquicker.net/QA/Question/1833

**Comment by WangYH195** [comment]
哦……鼠标没问题，触摸不行用gesture模拟按键弹出面板后，触摸面板以外的地方不能关面板












王宇航
mr.wangyuhang@qq.com

哈工大（威海）
+8615225180462

---原始邮件---
发件人: "CuiLiang"<notifications@github.com&gt;
发送时间: 2020年4月12日(周日) 晚上8:03
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Wang Y.H."<1950727614@qq.com&gt;;
主题: Re: [cuiliang/Quicker] 点击面板以外区域关闭面板 (#857)




 
正常都是点外面自动关闭的啊。
 是不是“钉住”了，或者挂钩丢失了。
 https://www.yuque.com/quicker/help/pin
 https://getquicker.net/QA/Question/1833

**Comment by cuiliang** [comment]
录屏看看。
 另外你的私人信息留在评论里了，请编辑删除。

**Comment by WangYH195** [comment]
从QQ邮箱发来的超大附件 		 	
 	 		  	 	 		 			 		
 		 			 VID_20200413_104958.mp4 (68.31M, 2020年5月13日 10:51 到期) 			 			 				进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=cf9b5f668b8a7310fde81966373736644c86736235373664154b0e525604045454521a05505552490455015e180e05015249040701060e5d525c515f07022164662d733907070454005006556a06065009510f48584702704c3535b28ded2786d3d2dc2c1f75997567a36f9a&t=exs_ftn_download&code=0d7f576d

**Comment by cuiliang** [comment]
哦，触摸关闭不了的，目前还没法监听到触摸事件。

**Comment by cuiliang** [comment]
快速通道已更新1.6.6版本，对此问题进行了处理，请测试看看是否还有问题。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
