### ISSUE TITLE
插件面板输入文字时，输入法不在最上面

### ISSUE THREAD

**Issue by pzcn** [cuiliang/Quicker#858]
**描述BUG**
打开quicker插件的窗口时，输入文字时输入法在窗口下面

**重现步骤**
1.打开一个插件，例如 翻译
2.输入文字，此时输入法不被置顶

**相关截图**
![image.png](https://ae05.alicdn.com/kf/H3e42f5842a7c40ea875c4573a4145c81Z.png)

**环境信息:**
 - 操作系统版本：Windows10 20H1
 - Quicker版本：1.5.15.0

**附加信息**
无

**Comment by cuiliang** [comment]
程序里没有可以控制的地方，这个大概率是输入法或windows的bug了。
![image](https://user-images.githubusercontent.com/1972649/79093155-f43d4580-7d85-11ea-850b-1700ac2957cd.png)

**Comment by PedroZhang** [comment]
发现是和其他软件的冲突

**Comment by cuiliang** [comment]
> 发现是和其他软件的冲突

o ? 是啥软件呀？

**Comment by PedroZhang** [comment]
> > 发现是和其他软件的冲突
> 
> o ? 是啥软件呀？

mouseinc
刚才又试了试，只是解决了置于开始菜单顶部的bug，输入法和状态栏还是在下面：(

**Comment by mengfanShi** [comment]
现在我也是这样  就不知道是软件BUG还是输入法的问题 
windows2004
quicker 1.7.5.0

**Comment by cuiliang** [comment]
文本输入窗口后来去掉topmost标记了，现在应该没有这个问题了。
先关了，如果还有问题，请再reopen
