### ISSUE TITLE
唤起界面在鼠标指针处,而非屏幕正中央

### ISSUE THREAD

**Issue by sycophant-stone** [cuiliang/Quicker#860]
**需求描述**
唤起界面在鼠标指针处,而非屏幕正中央.
这样可以节省鼠标滑动的多余操作. 唤起后, 直接在指针附近出现.

**描述你想要的解决方案**
 唤起后, 直接在指针附近出现.

**描述您考虑过的替代方案**
检查指针位置,然后更改出现位置.

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
估计是使用手势软件模拟快捷键激活的面板吧，直接用鼠标是自动在鼠标中间的。
开启这个选项。
![image](https://user-images.githubusercontent.com/1972649/79108712-7d19a880-7da9-11ea-806e-9b51b611b39f.png)

**Comment by sycophant-stone** [comment]
thanks
