### ISSUE TITLE
个人中心

### ISSUE THREAD

**Issue by AprilHello** [cuiliang/Quicker#868]
无法修改个人信息的邮箱吗，之前绑定的QQ邮箱不用了，现在换不了啊

**Comment by cuiliang** [comment]
专业版将会开发修改email功能。近几天上线。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/79628374-fe3eba00-8172-11ea-94f4-0cc7ad10517b.png)
专业版已可更改email。
