### ISSUE TITLE
外部启动增强参数传递

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/Quicker#879]
支持:
quicker:runaction:1c201781-6004-4146-a41c-8f80d35e239d?pram=value&....

**Comment by kanglade** [comment]
~~动作中使用的话，是一个词典变量Params吗？如果是文本的话，现在就可以是任何内容，即使包含参数，像「pram=value&....」这样，动作中也能自行写步骤来解析，并不存在问题。~~

**Comment by kanglade** [comment]
实践过程中，发现
quicker:runaction:1c201781-6004-4146-a41c-8f80d35e239d?pram=value&....
这种形式还是更好一些，
quicker_in_param作为词典传入到动作，使用起来会更方便。

像「文本窗口」的参数传递那样就挺好。

虽然纯文本可以自行解析，但解析起来有点麻烦，现在挺希望内置的~

**Comment by cuiliang** [comment]
1.9.5 词典操作增加了查询字符串和词典的转换。  @kanglade 
![image](https://user-images.githubusercontent.com/1972649/92318365-e7273880-f03d-11ea-8fc2-f42700f6c3c0.png)
