### ISSUE TITLE
Quicker程序快捷启动Bug

### ISSUE THREAD

**Issue by rychong** [cuiliang/Quicker#88]
Quicker在启动某些exe程序时会出现各种奇怪的Bug，而这些程序如果双击启动或快捷方式启动，均无Bug，经过测试，发现原因如下：

如Quicker启动C:\GAME\BFV\BFV.exe时，似乎是直接从命令行运行BFV.exe，而此时cmd的当前目录却很可能是用户目录或System32目录，如果BFV.exe需要BFV目录下的部分文件才能启动并读取设置等，那么你从System32目录直接启动BFV.exe，程序就找不到相应的文件或者设置就会报错！

解决方法——先进入程序所在的目录，然后exe启动程序！

希望能尽快修正此Bug！另外还有一个建议——希望能让用户自定义动作的数量；

**Comment by cuiliang** [comment]
收到

**Comment by FreeCodeCampXYG** [comment]
Quicker最小化的时候，有快捷键显示吗？我鼠标右键双击偶尔会触发显示出来，有时右键单击也会显示出来时灵时不灵的。

**Comment by cuiliang** [comment]
组合动作中的运行模块已增加设置工作目录参数。
