### ISSUE TITLE
不知道是否能实现呢，希望能有便携版

### ISSUE THREAD

**Issue by 976269148** [cuiliang/Quicker#883]
有时候在外面帮别人弄电脑，没有了quicker突然用不习惯了，老想着按快捷键把quicker调出来，如果能有便携版就好了

**Comment by cuiliang** [comment]
quicker必须安装到那个目录才能正常实现功能，所以目前没有考虑开发便携版的。

**Comment by 976269148** [comment]
好的，谢谢
