### ISSUE TITLE
未联网计算机如何使用

### ISSUE THREAD

**Issue by honestgrubby** [cuiliang/Quicker#890]
**描述BUG**
我的工作机无法联网，安装QUCKER后，一定要登录才能使用。但在禁止联网的情况下，这一点做不到，也就无法使用，恳请解决。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/install#O3Rpu
Quicker自设计之初就是一个网络版的软件，所以最多也只能做到这样了。

**Comment by honestgrubby** [comment]
谢谢。特别能适配一个离线版本，哪怕功能阉割一些。
| |
sinchance
|
|
sinchance@163.com
|
签名由网易邮箱大师定制
在2020年4月22日 09:45，CuiLiang<notifications@github.com> 写道：

Closed #890.
