### ISSUE TITLE
使用自定义热键暂停quicker后点恢复没有用

### ISSUE THREAD

**Issue by Oxygenym** [cuiliang/Quicker#892]
**描述BUG**
用热键空格加T暂停quicker后鼠标点恢复无任何反应，重新加载鼠标挂钩也没用，只有彻底退出quicker再启动才可以使用。

**重现步骤**
1.热键暂停quicker
2.恢复quicker

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：版本 Windows 10专业版  18362.778
 - Quicker版本：1.5.24.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
快速通道1.5.27版本已修复此问题，更新试试。
