### ISSUE TITLE
网站现在注册不了

### ISSUE THREAD

**Issue by ivernaloo** [cuiliang/Quicker#899]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1. 没有注册按钮
2. 用微信登陆跳转到绑定账号上，跳不过去

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
需要在软件里注册。 如果没有帐号，微信登录后需要创建新帐号。
