### ISSUE TITLE
美化弹窗效果

### ISSUE THREAD

**Issue by LonelySteve** [cuiliang/Quicker#9]
目前使用子程序弹窗的效果过于简陋，但是报错/提醒用的弹窗（从任务栏上方弹出的）设计很新颖，我很喜欢，如果重新设计的话，我希望能够使用这种风格的弹窗。

**Comment by LonelySteve** [comment]
另外如果能够使用自定义子程序/插件系统 （详见#8） 的话 ，那么我期望弹窗能够指定图标，内容，按钮（类似MessageBox）

**Comment by cuiliang** [comment]
收到：）

**Comment by cuiliang** [comment]
done
