### ISSUE TITLE
远程桌面中无法获取选中的文本

### ISSUE THREAD

**Issue by shilei-exists** [cuiliang/Quicker#90]
在远程桌面中长按鼠标右键可以呼出主面板，但是无法获取选中的文本，在编辑区输入三个字符c之后提示获取选中的文本失败。

推测是不是和远程桌面的剪贴板共享功能冲突？

win10 64 1809 17763.194
远程桌面连接的目标系统是windows server 2008 r2 64

远程桌面中打开的软件是navicat premium 11.0.8 x86版本

**Comment by cuiliang** [comment]
是用的mstsc 远程桌面程序么？

**Comment by shilei-exists** [comment]
>           是用的mstsc 远程桌面程序么？

是的，mstsc。

补充一下，我在问题发生的时候打开任务管理器，貌似没有找打rclip.exe还是rdpclip.exe这个程序来着。

**Comment by cuiliang** [comment]
后来测试可以复制，忘了更新了。 获取选中文本的原理是模拟发送Ctrl+C，然后等待剪贴板内容改变后读取剪贴板。所以如果软件不能正常响应这个操作并把远程主机的内容复制到本机剪贴板，会有失败的可能。
