### ISSUE TITLE
“获取选中文本”为何会自动将获取内容写入剪贴板

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/Quicker#901]
问题：“获取选中文本”为何会自动将获取内容写入剪贴板
[相关截图.docx](https://github.com/cuiliang/Quicker/files/4533580/default.docx)
[创建的动作](https://getquicker.net/Sharedaction?code=4206e28b-e124-41eb-c794-08d7e902341a)
执行后的结果：
         选中前剪贴板内容：00000000000000
                       选中内容：1111111111111
        选中后剪贴板内容：1111111111111
                      系统版本：10.0.18363.0
                  ------Win10：true
                 Quicker版本：1005027
                  -----专业版：true

**Comment by cuiliang** [comment]
这个功能就是通过模拟ctrl+c后读取剪贴板实现的。
 quicker没法直接获取其他进程内的信息的，只能通过剪贴板作为桥梁。
