### ISSUE TITLE
关于主面板功能增加快捷选择编号的建议

### ISSUE THREAD

**Issue by shilei-exists** [cuiliang/Quicker#91]
当使用键盘快捷键激活主面板时，建议在主面板上为每个功能增加编号，以方便通过键盘直接触发需要的功能，而不是再通过鼠标操作，提升操作便利性。

**Comment by cuiliang** [comment]
嗯，后期会增加此功能 #21 。 这个可能还需要允许每个人设置不同的按键。

**Comment by cuiliang** [comment]
0.7.28 加入
