### ISSUE TITLE
截图多了后，quicker会卡死

### ISSUE THREAD

**Issue by YZz-S** [cuiliang/Quicker#913]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.截了30张以上的图时quicker会经常性卡死
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：1909
 - Quicker版本：1.5.24.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
在同一个动作里截图还是不同动作？ 新截图的时候旧截图关掉了么？ 
不能同时有2个截图在进行，会卡窗口。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
