### ISSUE TITLE
网页动作库页面点赞没反映

### ISSUE THREAD

**Issue by BenjaminGao** [cuiliang/Quicker#914]
**描述BUG**
官网动作库页面，给这个[动作](https://getquicker.net/Sharedaction?code=ba82e11a-f845-4ca3-44ee-08d690b5076c)点赞，页面此时自动刷新，但好久也不刷新不出来，手动刷新后显示没有点赞。软件内点赞功能是正常的。

**重现步骤**
...

**相关截图**
![image](https://user-images.githubusercontent.com/16028320/80582034-9fb1ef80-8a40-11ea-986a-c55f02f0e0ca.png)

**环境信息:**
 - 操作系统版本：Windows10 1909
 - Quicker版本：...

**附加**
此后我又对这个[动作](https://getquicker.net/Sharedaction?code=4f8b0df2-d031-4309-173c-08d7079ea819)进行点赞操作，发现并没有一直刷新不出来的情况， 在上面出现问题的链接中，点赞有800+，而上面的链接只有200+，我怀疑是不是 _JS_ 算法哪里出现了小问题，导致在 __已经点赞太多__ 的情况下，不能刷新出来，卡在那里的情况。

![image](https://user-images.githubusercontent.com/16028320/80583162-72664100-8a42-11ea-916e-76d565322dc8.png)

**Comment by cuiliang** [comment]
感谢反馈，似乎似乎是特别慢，我查一下。

**Comment by cuiliang** [comment]
现在应该快了很多了，如果还有什么页面比较慢欢迎反馈！谢谢
