### ISSUE TITLE
由动作ID打开动作

### ISSUE THREAD

**Issue by who0am0i** [cuiliang/Quicker#916]
将动作ID作为变量，（由表单填写变量值），当此变量值为空白的时候会随机打开一个动作
比如这个动作，https://getquicker.net/sharedaction?code=6bd460bf-6fbf-4a7a-f7cd-08d7b41fb3e2
不填写动作ID时就会出现问题，此问题为更新之后才有的 ，以前并未出现

**Comment by cuiliang** [comment]
报什么错么？可以调试运行一下看看。

**Comment by cuiliang** [comment]
整理issues
