### ISSUE TITLE
动作页里的软件无法启动

### ISSUE THREAD

**Issue by GYZSSDH** [cuiliang/Quicker#917]
**描述BUG**
在动作页里添加了怪物猎人世界游戏，在动作页里点击无法启动。

**重现步骤**
1.点击动作页里的怪物猎人游戏
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![怪物猎人状态](https://user-images.githubusercontent.com/30552759/80619978-ff77bd00-8a77-11ea-8897-4e367b8ff3e5.png)
![系统版本](https://user-images.githubusercontent.com/30552759/80619988-0272ad80-8a78-11ea-8243-930f796e5459.png)

**环境信息:**
 - 操作系统版本：win10 1909
 - Quicker版本：1.5.24.0

**附加信息**
1.游戏是正常的，本地文件可以打开，快捷方式可以打开，同样操作添加的steam应用等，都可以正常打开。
2.发现使用quicker打开的怪物猎人游戏在任务管理器里间隔几秒状态会显示为已挂起。如上面截图。
3.关机重启无法解决此问题。重新添加也无用。添加方式以exe文件和快捷方式两种都无用。

**Comment by cuiliang** [comment]
试试设定一下工作目录到exe所在的文件夹路径。

**Comment by GYZSSDH** [comment]
非常感谢，问题已解决

> 请尝试设定一下工作目录到exe所在的文件夹路径。另外
> 看看是不是选里管理员身份启动，取消掉。
