### ISSUE TITLE
希望可以当光标在屏幕顶端或底端时滚动滚轮就可以调节亮度，不用按ctrl

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/Quicker#922]
**需求描述**
希望可以增加设置——当光标在屏幕顶端或底端时直接滚动滚轮就可以调节亮度，不用按ctrl

**描述你想要的解决方案**
既然调节音量都可以实现当光标在屏幕顶端或底端时直接滚动滚轮调节音量，为什么调节亮度不可以这样呢？还要按住ctrl

**Comment by cuiliang** [comment]
这个操作用来调节音量了。操作方式就那么多，更简单的留给更常用的操作。
