### ISSUE TITLE
quicker后台运行时会莫名触发按键

### ISSUE THREAD

**Issue by Oxygenym** [cuiliang/Quicker#923]
**描述BUG**
quicker在后台运行，但无任何其他脚本或动作在运行，在英雄联盟游戏中经常会自动触发D按键，无数次忘了关quicker导致D键闪现被用掉。频率挺高的，基本每次只要没暂停都会。暂停quicker后此问题消失

**重现步骤**
1.开启quicker，后台运行
2.进入英雄联盟游戏后不确定时间自动触发D键。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本：1.6.4.0

**附加信息**
在非英雄联盟环境中未发现自动触发D键

**Comment by cuiliang** [comment]
关掉滚轮调节音量功能测试一下。另外有没有扩展热键？游戏有没有加入黑名单？

**Comment by Oxygenym** [comment]
没用，还是一样的，关闭音量调节，设置全屏禁用软件，扩展热键也没有

**Comment by cuiliang** [comment]
有设置动作快捷键么？ 加黑名单管用么？
我目前没有什么思路，如果没有触发动作，应该不会有按键发送出来才对。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
