### ISSUE TITLE
不能添加动作，一添加就错误卡死！

### ISSUE THREAD

**Issue by su316** [cuiliang/Quicker#927]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by su316** [comment]
![image](https://user-images.githubusercontent.com/59133203/81048914-ca43f280-8eef-11ea-8186-d23f9852d155.png)
[](url)

**Comment by cuiliang** [comment]
点击发送报告会有一份邮件发送到帐号信箱，请参考里面的说明解决。
