### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by xccy** [cuiliang/Quicker#933]
**描述BUG**
动作编辑时设置了窗口以最大化形式打开，但依然无效。

**重现步骤**
打开的软件为chormium内核的edge浏览器

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 1903
 - Quicker版本：1.6.4

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
截图看下配置。
路径要指定exe文件路径，不能使用快捷方式。
另外这个是不是生效时依赖于软件自身的。
