### ISSUE TITLE
希望鼠标输入可以支持更多的内容，比如鼠标滚轮。

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/Quicker#935]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
之前在用potplayer，制作动作并且分享的时候，发现potplayer支持这个，以前都没咋用过，因为支持这个的软件比较少，所以我还以为我的罗技滚轮那个左右移动没有用呢，试了之后发现这个还是有用的，希望quicker 输入模块也可以支持鼠标滚轮操作，上下滑动，左右移动。罗技还有另外6个键没说，主要打游戏时候用的比较多，感觉其他人使用频率不高，所以就不说了。
![image](https://user-images.githubusercontent.com/44609485/81205374-2ea0a800-8ffd-11ea-9c88-71c2bb010a39.png)
用的是这个鼠标 罗技G502，https://www.logitechg.com.cn/zh-cn/products/gaming-mice/g502-hero-gaming-mouse.html。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
![image](https://user-images.githubusercontent.com/44609485/81205262-0a44cb80-8ffd-11ea-8e51-dcb533757c41.png)
这个的支持感觉还是不够
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
有的啊，“滚动”
