### ISSUE TITLE
建议：显示文本的窗口尺寸增加调整参数

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/Quicker#939]
不得不说，这个模块近期的更新和原来相比功能强大了很多（语法高亮、显示行号、调用子程序等），但是还是存在一些细节上的小瑕疵。
本人最近主要运用显示文本模块写了一个运行代码的动作，但是这个显示窗口经常需要手动调整窗口大小。通常运行的代码单行文本内容不会很多，但是默认的窗口宽度比较长，这样会造成窗口右部分存在大量的空白，造成空间的浪费；而窗口默认的高度却刚好相反，无法整体显示代码运行的结果，也需要频繁手动调整，十分不方便。
所以，我建议显示文本模块可以考虑增加一个调整参数，增加程序的灵活性，新的用户选择模块目前就已经采用这种方案了，个人也是受到这一点启发而提出这个建议，希望这个建议对老大有所帮助。

**Comment by guoranjun2** [comment]
<img src='https://i.loli.net/2020/05/07/Z7mNATc8HLi2WwU.png' title='quicker_c8dd2594-2e0b-447b-805c-e368bdbb6fbc.png' />

**Comment by cuiliang** [comment]
改一下issue的摘要哦😂  
![image](https://user-images.githubusercontent.com/1972649/81274117-7584b100-9082-11ea-86db-806a2c04b2d9.png)

**Comment by cuiliang** [comment]
1.7.2

**Comment by guoranjun2** [comment]
> 1.7.2

😀 nice job!
