### ISSUE TITLE
无法中止全部动作

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/Quicker#940]
动作出了bug，用托盘或快捷键点击全部停止无效，只能一个一个中止。
![20200507_182812](https://user-images.githubusercontent.com/50692082/81284304-85a38d00-9090-11ea-96ba-851e6e411766.png)

**Comment by guoranjun2** [comment]
![20200507_183523](https://user-images.githubusercontent.com/50692082/81285051-8557c180-9091-11ea-9bf8-f972c56eaea7.png)

发现原来中止的实例还在

**Comment by guoranjun2** [comment]
![20200507_183523](https://user-images.githubusercontent.com/50692082/81285051-8557c180-9091-11ea-9bf8-f972c56eaea7.png)

发现原来中止的实例还在

**Comment by guoranjun2** [comment]
有点怀疑是不是自己动作的原因，我还是暂时关闭吧

**Comment by cuiliang** [comment]
动作需要在一个模块运行结束的时候才能检查是不是停止。 如果模块里使用了脚本这类，quicker是没法停止它的，需要它结束之后才能停止。

**Comment by guoranjun2** [comment]
好的，我再检查一下是哪个环节的问题
