### ISSUE TITLE
显示图片用于显示或编辑文本窗口的扩展按钮时能提供执行失败的反馈信息

### ISSUE THREAD

**Issue by NewbieToEverything** [cuiliang/Quicker#941]
**需求描述**
当把显示图片模块用于显示或编辑文本窗口的扩展按钮时，如果本地图片的路径信息不正确，给予执行失败的提示信息。否则用户可能会一直等待图片弹窗的出现，完全不知道是出了什么问题。网络图片如果网址不正确，会有提示信息。详情见动态图
![test](https://user-images.githubusercontent.com/36309469/81883945-2500dc80-95c9-11ea-859b-ad04b1bb17a4.gif)

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
当时可能忽略了这条，如果仍然需要，请reopen或创建一条新的。
