### ISSUE TITLE
quciker的二级菜单在左边显示的时候很难选中

### ISSUE THREAD

**Issue by liangxyz** [cuiliang/Quicker#943]
**描述BUG**
对bug的清晰简洁描述。
quciker的二级菜单在左边显示的时候很难选中

**重现步骤**
1.动作上右键
2.鼠标移动到信息
3.弹出二级菜单，鼠标移向二级菜单
4.二级菜单消失，无法选中

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![snipaste_20200508_215918](https://user-images.githubusercontent.com/8108927/81413221-a5fa4700-9177-11ea-895e-4d70c91ef829.png)
![snipaste_20200508_215959](https://user-images.githubusercontent.com/8108927/81413229-a98dce00-9177-11ea-9f02-2ef778381f8b.png)

**环境信息:**
 - 操作系统版本：win10 19041.208
 - Quicker版本：1.6.7

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能是.net底层的bug，显示在哪边qk里没法控制。
可以试试这里的方法。
https://getquicker.net/kc/help/doc/menu-left-problem

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/81413716-7992fa80-9178-11ea-8256-33e5ed419951.png)
如果你有绘图板，这里可能 也会有选项，可以调整一下试试。

**Comment by liangxyz** [comment]
好的，谢谢

**Comment by cuiliang** [comment]
除了调整设置，将在1.7.2中自动强制更新一下菜单显示在右侧。
