### ISSUE TITLE
对 Infinite progress bar 的支持

### ISSUE THREAD

**Issue by spencerwooo** [cuiliang/Quicker#946]
**需求描述**

在不能直接获取进展情况的环境下（比如 SM.MS 上传过程），如果可以支持一个 infinite progress bar（无穷进度条？不知道中文具体叫什么 😓），就比较人性化了。

**描述你想要的解决方案**

![infinite](https://user-images.githubusercontent.com/32114380/81465352-18146f80-91fc-11ea-9710-ae98e9b61b8b.gif)

> 来自：[CodePen - Infinite Progress Bar](https://codepen.io/tequilahifi/pen/xwmbVW)

**描述您考虑过的替代方案**

目前就是通过多次更新「等待窗口」来实现不平滑进度，比较尴尬。

![image](https://user-images.githubusercontent.com/32114380/81465373-5c077480-91fc-11ea-8306-97bf7b599525.png)

这种方案的效果：

![demo](https://user-images.githubusercontent.com/32114380/81465422-b99bc100-91fc-11ea-8819-dca6ca51a236.gif)

**Comment by cuiliang** [comment]
1.10.8 版本增加了进度显示支持。
