### ISSUE TITLE
建议移除”Quicker已启动”通知

### ISSUE THREAD

**Issue by aesthetic-archaeopteryx** [cuiliang/Quicker#947]
**需求描述**
每次启动Quicker都会在屏幕底部显示示蓝色方框通知“Quicker已启动“。尤其是作为开机启动项，这个通知十分的冗余。而且这个蓝色通知框是真的丑。

**描述你想要的解决方案**
1.移除每次启动Quicker时的”Quicker已启动“通知消息
2.对于蓝色边框的通知消息，可能有用于其他场景的通知（这个我不确定的），建议对通知框进行一下显示优化，用其他显示效果进行替换。

附：屏幕截图
![image](https://user-images.githubusercontent.com/45968773/81465912-3aa88780-9200-11ea-91fa-7902eea3371d.png)

**Comment by cuiliang** [comment]
配置第一页关掉“启动完成通知”即可。
![image](https://user-images.githubusercontent.com/1972649/81465961-8ce9a880-9200-11ea-9f25-4cf848d20f92.png)
