### ISSUE TITLE
全局菜单

### ISSUE THREAD

**Issue by demosu** [cuiliang/Quicker#948]
老大，我一直想提的：对用户选择做这么个全局的菜单怎么样？就是用户选择的下面的按钮改为全局菜单和右键菜单不一样。右键菜单应该是仅对选择项进行操作，而有些操作不是针对选择项的，这时不适合用右键菜单，比如：添加加条目、设置等等啥的比如，用户选择下面的这个就可以改成全局菜单，作为右键菜单挺別扭的。具体可以参考，快启动：https://getquicker.net/sharedaction?code=f71f82c1-e2a2-4a6a-4ec5-08d7d3392c8c
![33](https://user-images.githubusercontent.com/31314917/81467136-303ebb80-9209-11ea-8f39-80ccaec6d1db.jpg)

**Comment by cuiliang** [comment]
1.7.1  菜单定义中，使用[=]开始的菜单作为全局菜单。例子：[=][fa:Solid_Pen:#FF0000]按钮标题(提示文字第一行\r\n提示文字第二行)|operation
