### ISSUE TITLE
与欧陆词典的“按两次CTRL+C剪切板取词”冲突

### ISSUE THREAD

**Issue by soulless-c** [cuiliang/Quicker#96]
![screenshot_2018-12-21_21-04-09](https://user-images.githubusercontent.com/45476582/50343981-180ec380-0564-11e9-8843-acdc9c7c4b78.png)

同时开启两个软件会导致Quicker提示无法获取选中的文本，托盘退出欧陆词典即可正常使用Quicker的选中功能

**Comment by cuiliang** [comment]
下个版本更改了ctrl+c的发送方式，可能能解决这个问题。到时候请试下。

**Comment by cuiliang** [comment]
done
