### ISSUE TITLE
建议：动作面板增加快捷切换功能

### ISSUE THREAD

**Issue by 023Sparrow** [cuiliang/Quicker#98]
若我在Chrome界面想要执行默认动作面板的一些功能，必须手动打开面板管理切到默认再点击，或者激活非Chrome窗口再打开Quicker，这样不太方便。最上方的通用面板格子不一定够用。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/avoid-manual-switch

1. 将最常用的动作放入全局面板。
2. 使用任务栏面板。把不需要根据选中文字执行的常用动作放入任务栏面板中，在任务栏上弹开面板即可快速使用这些动作。任务栏面板上适合放置的动作类型：启动/截图/OCR等。
3. 为软件设置专用的面板。每个软件都是一个场景，在使用软件时自动切换到为此软件特别设置的面板上。
4. 【收费功能】使用面板分页扩展。
